/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerter.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Allerta service. Represents a row in the &quot;ALLERTER_Allerta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.allerter.model.impl.AllertaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.allerter.model.impl.AllertaImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see Allerta
 * @generated
 */
@ProviderType
public interface AllertaModel
	extends BaseModel<Allerta>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a allerta model instance should use the {@link Allerta} interface instead.
	 */

	/**
	 * Returns the primary key of this allerta.
	 *
	 * @return the primary key of this allerta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this allerta.
	 *
	 * @param primaryKey the primary key of this allerta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this allerta.
	 *
	 * @return the uuid of this allerta
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this allerta.
	 *
	 * @param uuid the uuid of this allerta
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the allerta ID of this allerta.
	 *
	 * @return the allerta ID of this allerta
	 */
	public long getAllertaId();

	/**
	 * Sets the allerta ID of this allerta.
	 *
	 * @param allertaId the allerta ID of this allerta
	 */
	public void setAllertaId(long allertaId);

	/**
	 * Returns the group ID of this allerta.
	 *
	 * @return the group ID of this allerta
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this allerta.
	 *
	 * @param groupId the group ID of this allerta
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this allerta.
	 *
	 * @return the company ID of this allerta
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this allerta.
	 *
	 * @param companyId the company ID of this allerta
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this allerta.
	 *
	 * @return the user ID of this allerta
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this allerta.
	 *
	 * @param userId the user ID of this allerta
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this allerta.
	 *
	 * @return the user uuid of this allerta
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this allerta.
	 *
	 * @param userUuid the user uuid of this allerta
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this allerta.
	 *
	 * @return the user name of this allerta
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this allerta.
	 *
	 * @param userName the user name of this allerta
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the creator name of this allerta.
	 *
	 * @return the creator name of this allerta
	 */
	@AutoEscape
	public String getCreatorName();

	/**
	 * Sets the creator name of this allerta.
	 *
	 * @param creatorName the creator name of this allerta
	 */
	public void setCreatorName(String creatorName);

	/**
	 * Returns the create date of this allerta.
	 *
	 * @return the create date of this allerta
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this allerta.
	 *
	 * @param createDate the create date of this allerta
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this allerta.
	 *
	 * @return the modified date of this allerta
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this allerta.
	 *
	 * @param modifiedDate the modified date of this allerta
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the stato of this allerta.
	 *
	 * @return the stato of this allerta
	 */
	public int getStato();

	/**
	 * Sets the stato of this allerta.
	 *
	 * @param stato the stato of this allerta
	 */
	public void setStato(int stato);

	/**
	 * Returns the numero of this allerta.
	 *
	 * @return the numero of this allerta
	 */
	@AutoEscape
	public String getNumero();

	/**
	 * Sets the numero of this allerta.
	 *
	 * @param numero the numero of this allerta
	 */
	public void setNumero(String numero);

	/**
	 * Returns the progressivo of this allerta.
	 *
	 * @return the progressivo of this allerta
	 */
	public int getProgressivo();

	/**
	 * Sets the progressivo of this allerta.
	 *
	 * @param progressivo the progressivo of this allerta
	 */
	public void setProgressivo(int progressivo);

	/**
	 * Returns the anno of this allerta.
	 *
	 * @return the anno of this allerta
	 */
	public int getAnno();

	/**
	 * Sets the anno of this allerta.
	 *
	 * @param anno the anno of this allerta
	 */
	public void setAnno(int anno);

	/**
	 * Returns the data emissione of this allerta.
	 *
	 * @return the data emissione of this allerta
	 */
	public Date getDataEmissione();

	/**
	 * Sets the data emissione of this allerta.
	 *
	 * @param dataEmissione the data emissione of this allerta
	 */
	public void setDataEmissione(Date dataEmissione);

	/**
	 * Returns the data inizio of this allerta.
	 *
	 * @return the data inizio of this allerta
	 */
	public Date getDataInizio();

	/**
	 * Sets the data inizio of this allerta.
	 *
	 * @param dataInizio the data inizio of this allerta
	 */
	public void setDataInizio(Date dataInizio);

	/**
	 * Returns the data fine of this allerta.
	 *
	 * @return the data fine of this allerta
	 */
	public Date getDataFine();

	/**
	 * Sets the data fine of this allerta.
	 *
	 * @param dataFine the data fine of this allerta
	 */
	public void setDataFine(Date dataFine);

	/**
	 * Returns the descrizione meteo of this allerta.
	 *
	 * @return the descrizione meteo of this allerta
	 */
	@AutoEscape
	public String getDescrizioneMeteo();

	/**
	 * Sets the descrizione meteo of this allerta.
	 *
	 * @param descrizioneMeteo the descrizione meteo of this allerta
	 */
	public void setDescrizioneMeteo(String descrizioneMeteo);

	/**
	 * Returns the tendenza of this allerta.
	 *
	 * @return the tendenza of this allerta
	 */
	public int getTendenza();

	/**
	 * Sets the tendenza of this allerta.
	 *
	 * @param tendenza the tendenza of this allerta
	 */
	public void setTendenza(int tendenza);

	/**
	 * Returns the note of this allerta.
	 *
	 * @return the note of this allerta
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this allerta.
	 *
	 * @param note the note of this allerta
	 */
	public void setNote(String note);

	/**
	 * Returns the riferimenti of this allerta.
	 *
	 * @return the riferimenti of this allerta
	 */
	@AutoEscape
	public String getRiferimenti();

	/**
	 * Sets the riferimenti of this allerta.
	 *
	 * @param riferimenti the riferimenti of this allerta
	 */
	public void setRiferimenti(String riferimenti);

	/**
	 * Returns the utente firma arpa ID of this allerta.
	 *
	 * @return the utente firma arpa ID of this allerta
	 */
	public long getUtenteFirmaArpaId();

	/**
	 * Sets the utente firma arpa ID of this allerta.
	 *
	 * @param utenteFirmaArpaId the utente firma arpa ID of this allerta
	 */
	public void setUtenteFirmaArpaId(long utenteFirmaArpaId);

	/**
	 * Returns the data firma arpa of this allerta.
	 *
	 * @return the data firma arpa of this allerta
	 */
	public Date getDataFirmaArpa();

	/**
	 * Sets the data firma arpa of this allerta.
	 *
	 * @param dataFirmaArpa the data firma arpa of this allerta
	 */
	public void setDataFirmaArpa(Date dataFirmaArpa);

	/**
	 * Returns the utente firma prot ID of this allerta.
	 *
	 * @return the utente firma prot ID of this allerta
	 */
	public long getUtenteFirmaProtId();

	/**
	 * Sets the utente firma prot ID of this allerta.
	 *
	 * @param utenteFirmaProtId the utente firma prot ID of this allerta
	 */
	public void setUtenteFirmaProtId(long utenteFirmaProtId);

	/**
	 * Returns the data firma prot of this allerta.
	 *
	 * @return the data firma prot of this allerta
	 */
	public Date getDataFirmaProt();

	/**
	 * Sets the data firma prot of this allerta.
	 *
	 * @param dataFirmaProt the data firma prot of this allerta
	 */
	public void setDataFirmaProt(Date dataFirmaProt);

	/**
	 * Returns the parent ID of this allerta.
	 *
	 * @return the parent ID of this allerta
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this allerta.
	 *
	 * @param parentId the parent ID of this allerta
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the sintesi of this allerta.
	 *
	 * @return the sintesi of this allerta
	 */
	@AutoEscape
	public String getSintesi();

	/**
	 * Sets the sintesi of this allerta.
	 *
	 * @param sintesi the sintesi of this allerta
	 */
	public void setSintesi(String sintesi);

	/**
	 * Returns the link of this allerta.
	 *
	 * @return the link of this allerta
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this allerta.
	 *
	 * @param link the link of this allerta
	 */
	public void setLink(String link);

	/**
	 * Returns the titolo of this allerta.
	 *
	 * @return the titolo of this allerta
	 */
	@AutoEscape
	public String getTitolo();

	/**
	 * Sets the titolo of this allerta.
	 *
	 * @param titolo the titolo of this allerta
	 */
	public void setTitolo(String titolo);

	/**
	 * Returns the tipo allerta of this allerta.
	 *
	 * @return the tipo allerta of this allerta
	 */
	public boolean getTipoAllerta();

	/**
	 * Returns <code>true</code> if this allerta is tipo allerta.
	 *
	 * @return <code>true</code> if this allerta is tipo allerta; <code>false</code> otherwise
	 */
	public boolean isTipoAllerta();

	/**
	 * Sets whether this allerta is tipo allerta.
	 *
	 * @param tipoAllerta the tipo allerta of this allerta
	 */
	public void setTipoAllerta(boolean tipoAllerta);

	/**
	 * Returns the hash of this allerta.
	 *
	 * @return the hash of this allerta
	 */
	@AutoEscape
	public String getHash();

	/**
	 * Sets the hash of this allerta.
	 *
	 * @param hash the hash of this allerta
	 */
	public void setHash(String hash);

	/**
	 * Returns the sintesi briefing of this allerta.
	 *
	 * @return the sintesi briefing of this allerta
	 */
	@AutoEscape
	public String getSintesiBriefing();

	/**
	 * Sets the sintesi briefing of this allerta.
	 *
	 * @param sintesiBriefing the sintesi briefing of this allerta
	 */
	public void setSintesiBriefing(String sintesiBriefing);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.allerter.model.Allerta allerta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.allerter.model.Allerta> toCacheModel();

	@Override
	public it.eng.allerter.model.Allerta toEscapedModel();

	@Override
	public it.eng.allerter.model.Allerta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}