/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LogInterno service. Represents a row in the &quot;ALLERTER_LogInterno&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.allerter.model.impl.LogInternoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.allerter.model.impl.LogInternoImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see LogInterno
 * @generated
 */
@ProviderType
public interface LogInternoModel extends BaseModel<LogInterno> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a log interno model instance should use the {@link LogInterno} interface instead.
	 */

	/**
	 * Returns the primary key of this log interno.
	 *
	 * @return the primary key of this log interno
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this log interno.
	 *
	 * @param primaryKey the primary key of this log interno
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the log ID of this log interno.
	 *
	 * @return the log ID of this log interno
	 */
	public long getLogId();

	/**
	 * Sets the log ID of this log interno.
	 *
	 * @param logId the log ID of this log interno
	 */
	public void setLogId(long logId);

	/**
	 * Returns the timestamp of this log interno.
	 *
	 * @return the timestamp of this log interno
	 */
	public Date getTimestamp();

	/**
	 * Sets the timestamp of this log interno.
	 *
	 * @param timestamp the timestamp of this log interno
	 */
	public void setTimestamp(Date timestamp);

	/**
	 * Returns the thread of this log interno.
	 *
	 * @return the thread of this log interno
	 */
	@AutoEscape
	public String getThread();

	/**
	 * Sets the thread of this log interno.
	 *
	 * @param thread the thread of this log interno
	 */
	public void setThread(String thread);

	/**
	 * Returns the cosa of this log interno.
	 *
	 * @return the cosa of this log interno
	 */
	@AutoEscape
	public String getCosa();

	/**
	 * Sets the cosa of this log interno.
	 *
	 * @param cosa the cosa of this log interno
	 */
	public void setCosa(String cosa);

	/**
	 * Returns the dettaglio of this log interno.
	 *
	 * @return the dettaglio of this log interno
	 */
	@AutoEscape
	public String getDettaglio();

	/**
	 * Sets the dettaglio of this log interno.
	 *
	 * @param dettaglio the dettaglio of this log interno
	 */
	public void setDettaglio(String dettaglio);

	/**
	 * Returns the utente of this log interno.
	 *
	 * @return the utente of this log interno
	 */
	@AutoEscape
	public String getUtente();

	/**
	 * Sets the utente of this log interno.
	 *
	 * @param utente the utente of this log interno
	 */
	public void setUtente(String utente);

	/**
	 * Returns the risultato of this log interno.
	 *
	 * @return the risultato of this log interno
	 */
	@AutoEscape
	public String getRisultato();

	/**
	 * Sets the risultato of this log interno.
	 *
	 * @param risultato the risultato of this log interno
	 */
	public void setRisultato(String risultato);

	/**
	 * Returns the eccezione of this log interno.
	 *
	 * @return the eccezione of this log interno
	 */
	@AutoEscape
	public String getEccezione();

	/**
	 * Sets the eccezione of this log interno.
	 *
	 * @param eccezione the eccezione of this log interno
	 */
	public void setEccezione(String eccezione);

	@Override
	public LogInterno cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}