/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerter.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TipoEvento service. Represents a row in the &quot;ALLERTER_TipoEvento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.allerter.model.impl.TipoEventoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.allerter.model.impl.TipoEventoImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see TipoEvento
 * @generated
 */
@ProviderType
public interface TipoEventoModel
	extends BaseModel<TipoEvento>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipo evento model instance should use the {@link TipoEvento} interface instead.
	 */

	/**
	 * Returns the primary key of this tipo evento.
	 *
	 * @return the primary key of this tipo evento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipo evento.
	 *
	 * @param primaryKey the primary key of this tipo evento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this tipo evento.
	 *
	 * @return the uuid of this tipo evento
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this tipo evento.
	 *
	 * @param uuid the uuid of this tipo evento
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the evento ID of this tipo evento.
	 *
	 * @return the evento ID of this tipo evento
	 */
	public long getEventoId();

	/**
	 * Sets the evento ID of this tipo evento.
	 *
	 * @param eventoId the evento ID of this tipo evento
	 */
	public void setEventoId(long eventoId);

	/**
	 * Returns the group ID of this tipo evento.
	 *
	 * @return the group ID of this tipo evento
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tipo evento.
	 *
	 * @param groupId the group ID of this tipo evento
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tipo evento.
	 *
	 * @return the company ID of this tipo evento
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tipo evento.
	 *
	 * @param companyId the company ID of this tipo evento
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tipo evento.
	 *
	 * @return the user ID of this tipo evento
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tipo evento.
	 *
	 * @param userId the user ID of this tipo evento
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tipo evento.
	 *
	 * @return the user uuid of this tipo evento
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tipo evento.
	 *
	 * @param userUuid the user uuid of this tipo evento
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tipo evento.
	 *
	 * @return the user name of this tipo evento
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tipo evento.
	 *
	 * @param userName the user name of this tipo evento
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tipo evento.
	 *
	 * @return the create date of this tipo evento
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tipo evento.
	 *
	 * @param createDate the create date of this tipo evento
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tipo evento.
	 *
	 * @return the modified date of this tipo evento
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tipo evento.
	 *
	 * @param modifiedDate the modified date of this tipo evento
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nome of this tipo evento.
	 *
	 * @return the nome of this tipo evento
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this tipo evento.
	 *
	 * @param nome the nome of this tipo evento
	 */
	public void setNome(String nome);

	/**
	 * Returns the indice of this tipo evento.
	 *
	 * @return the indice of this tipo evento
	 */
	public int getIndice();

	/**
	 * Sets the indice of this tipo evento.
	 *
	 * @param indice the indice of this tipo evento
	 */
	public void setIndice(int indice);

	/**
	 * Returns the tabella of this tipo evento.
	 *
	 * @return the tabella of this tipo evento
	 */
	public int getTabella();

	/**
	 * Sets the tabella of this tipo evento.
	 *
	 * @param tabella the tabella of this tipo evento
	 */
	public void setTabella(int tabella);

	/**
	 * Returns the split of this tipo evento.
	 *
	 * @return the split of this tipo evento
	 */
	public boolean getSplit();

	/**
	 * Returns <code>true</code> if this tipo evento is split.
	 *
	 * @return <code>true</code> if this tipo evento is split; <code>false</code> otherwise
	 */
	public boolean isSplit();

	/**
	 * Sets whether this tipo evento is split.
	 *
	 * @param split the split of this tipo evento
	 */
	public void setSplit(boolean split);

	/**
	 * Returns the costiero of this tipo evento.
	 *
	 * @return the costiero of this tipo evento
	 */
	public boolean getCostiero();

	/**
	 * Returns <code>true</code> if this tipo evento is costiero.
	 *
	 * @return <code>true</code> if this tipo evento is costiero; <code>false</code> otherwise
	 */
	public boolean isCostiero();

	/**
	 * Sets whether this tipo evento is costiero.
	 *
	 * @param costiero the costiero of this tipo evento
	 */
	public void setCostiero(boolean costiero);

	/**
	 * Returns the data inizio of this tipo evento.
	 *
	 * @return the data inizio of this tipo evento
	 */
	public Date getDataInizio();

	/**
	 * Sets the data inizio of this tipo evento.
	 *
	 * @param dataInizio the data inizio of this tipo evento
	 */
	public void setDataInizio(Date dataInizio);

	/**
	 * Returns the data fine of this tipo evento.
	 *
	 * @return the data fine of this tipo evento
	 */
	public Date getDataFine();

	/**
	 * Sets the data fine of this tipo evento.
	 *
	 * @param dataFine the data fine of this tipo evento
	 */
	public void setDataFine(Date dataFine);

	/**
	 * Returns the parent ID of this tipo evento.
	 *
	 * @return the parent ID of this tipo evento
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this tipo evento.
	 *
	 * @param parentId the parent ID of this tipo evento
	 */
	public void setParentId(long parentId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.allerter.model.TipoEvento tipoEvento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.allerter.model.TipoEvento> toCacheModel();

	@Override
	public it.eng.allerter.model.TipoEvento toEscapedModel();

	@Override
	public it.eng.allerter.model.TipoEvento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}