/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import it.eng.bollettino.model.RegolaAllarme;
import it.eng.bollettino.service.RegolaAllarmeService;
import it.eng.bollettino.service.persistence.AllarmePersistence;
import it.eng.bollettino.service.persistence.AttivazioneFiumePersistence;
import it.eng.bollettino.service.persistence.BacinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoBacinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoFinder;
import it.eng.bollettino.service.persistence.BollettinoIconaPersistence;
import it.eng.bollettino.service.persistence.BollettinoParametroPersistence;
import it.eng.bollettino.service.persistence.BollettinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoSensorePersistence;
import it.eng.bollettino.service.persistence.IconaPersistence;
import it.eng.bollettino.service.persistence.IdrometroPersistence;
import it.eng.bollettino.service.persistence.PluviometroPersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmeComunePersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmeCondizionePersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmePersistence;
import it.eng.bollettino.service.persistence.StazionePersistence;
import it.eng.bollettino.service.persistence.StazioneVariabilePersistence;
import it.eng.bollettino.service.persistence.ValoreSensorePersistence;
import it.eng.bollettino.service.persistence.VariabilePersistence;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the regola allarme remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.bollettino.service.impl.RegolaAllarmeServiceImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see it.eng.bollettino.service.impl.RegolaAllarmeServiceImpl
 * @generated
 */
public abstract class RegolaAllarmeServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, RegolaAllarmeService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RegolaAllarmeService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.bollettino.service.RegolaAllarmeServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RegolaAllarmeService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		regolaAllarmeService = (RegolaAllarmeService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RegolaAllarmeService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RegolaAllarme.class;
	}

	protected String getModelClassName() {
		return RegolaAllarme.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = regolaAllarmePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AllarmePersistence allarmePersistence;

	@Reference
	protected AttivazioneFiumePersistence attivazioneFiumePersistence;

	@Reference
	protected BacinoPersistence bacinoPersistence;

	@Reference
	protected BollettinoPersistence bollettinoPersistence;

	@Reference
	protected BollettinoFinder bollettinoFinder;

	@Reference
	protected BollettinoBacinoPersistence bollettinoBacinoPersistence;

	@Reference
	protected BollettinoIconaPersistence bollettinoIconaPersistence;

	@Reference
	protected BollettinoParametroPersistence bollettinoParametroPersistence;

	@Reference
	protected BollettinoSensorePersistence bollettinoSensorePersistence;

	@Reference
	protected IconaPersistence iconaPersistence;

	@Reference
	protected IdrometroPersistence idrometroPersistence;

	@Reference
	protected PluviometroPersistence pluviometroPersistence;

	@Reference
	protected it.eng.bollettino.service.RegolaAllarmeLocalService
		regolaAllarmeLocalService;

	protected RegolaAllarmeService regolaAllarmeService;

	@Reference
	protected RegolaAllarmePersistence regolaAllarmePersistence;

	@Reference
	protected RegolaAllarmeComunePersistence regolaAllarmeComunePersistence;

	@Reference
	protected RegolaAllarmeCondizionePersistence
		regolaAllarmeCondizionePersistence;

	@Reference
	protected StazionePersistence stazionePersistence;

	@Reference
	protected StazioneVariabilePersistence stazioneVariabilePersistence;

	@Reference
	protected ValoreSensorePersistence valoreSensorePersistence;

	@Reference
	protected VariabilePersistence variabilePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		RegolaAllarmeServiceBaseImpl.class);

}