/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import it.eng.bollettino.model.StazioneVariabile;
import it.eng.bollettino.service.StazioneVariabileLocalService;
import it.eng.bollettino.service.persistence.AllarmePersistence;
import it.eng.bollettino.service.persistence.AttivazioneFiumePersistence;
import it.eng.bollettino.service.persistence.BacinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoBacinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoFinder;
import it.eng.bollettino.service.persistence.BollettinoIconaPersistence;
import it.eng.bollettino.service.persistence.BollettinoParametroPersistence;
import it.eng.bollettino.service.persistence.BollettinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoSensorePersistence;
import it.eng.bollettino.service.persistence.IconaPersistence;
import it.eng.bollettino.service.persistence.IdrometroPersistence;
import it.eng.bollettino.service.persistence.PluviometroPersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmeComunePersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmeCondizionePersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmePersistence;
import it.eng.bollettino.service.persistence.StazionePersistence;
import it.eng.bollettino.service.persistence.StazioneVariabilePersistence;
import it.eng.bollettino.service.persistence.ValoreSensorePersistence;
import it.eng.bollettino.service.persistence.VariabilePersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the stazione variabile local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.bollettino.service.impl.StazioneVariabileLocalServiceImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see it.eng.bollettino.service.impl.StazioneVariabileLocalServiceImpl
 * @generated
 */
public abstract class StazioneVariabileLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   StazioneVariabileLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>StazioneVariabileLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.bollettino.service.StazioneVariabileLocalServiceUtil</code>.
	 */

	/**
	 * Adds the stazione variabile to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StazioneVariabileLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param stazioneVariabile the stazione variabile
	 * @return the stazione variabile that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StazioneVariabile addStazioneVariabile(
		StazioneVariabile stazioneVariabile) {

		stazioneVariabile.setNew(true);

		return stazioneVariabilePersistence.update(stazioneVariabile);
	}

	/**
	 * Creates a new stazione variabile with the primary key. Does not add the stazione variabile to the database.
	 *
	 * @param id the primary key for the new stazione variabile
	 * @return the new stazione variabile
	 */
	@Override
	@Transactional(enabled = false)
	public StazioneVariabile createStazioneVariabile(long id) {
		return stazioneVariabilePersistence.create(id);
	}

	/**
	 * Deletes the stazione variabile with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StazioneVariabileLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param id the primary key of the stazione variabile
	 * @return the stazione variabile that was removed
	 * @throws PortalException if a stazione variabile with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StazioneVariabile deleteStazioneVariabile(long id)
		throws PortalException {

		return stazioneVariabilePersistence.remove(id);
	}

	/**
	 * Deletes the stazione variabile from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StazioneVariabileLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param stazioneVariabile the stazione variabile
	 * @return the stazione variabile that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StazioneVariabile deleteStazioneVariabile(
		StazioneVariabile stazioneVariabile) {

		return stazioneVariabilePersistence.remove(stazioneVariabile);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return stazioneVariabilePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			StazioneVariabile.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return stazioneVariabilePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.bollettino.model.impl.StazioneVariabileModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return stazioneVariabilePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.bollettino.model.impl.StazioneVariabileModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return stazioneVariabilePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return stazioneVariabilePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return stazioneVariabilePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public StazioneVariabile fetchStazioneVariabile(long id) {
		return stazioneVariabilePersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the stazione variabile with the primary key.
	 *
	 * @param id the primary key of the stazione variabile
	 * @return the stazione variabile
	 * @throws PortalException if a stazione variabile with the primary key could not be found
	 */
	@Override
	public StazioneVariabile getStazioneVariabile(long id)
		throws PortalException {

		return stazioneVariabilePersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			stazioneVariabileLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StazioneVariabile.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			stazioneVariabileLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(StazioneVariabile.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			stazioneVariabileLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StazioneVariabile.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return stazioneVariabilePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement StazioneVariabileLocalServiceImpl#deleteStazioneVariabile(StazioneVariabile) to avoid orphaned data");
		}

		return stazioneVariabileLocalService.deleteStazioneVariabile(
			(StazioneVariabile)persistedModel);
	}

	@Override
	public BasePersistence<StazioneVariabile> getBasePersistence() {
		return stazioneVariabilePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return stazioneVariabilePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the stazione variabiles.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.bollettino.model.impl.StazioneVariabileModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of stazione variabiles
	 * @param end the upper bound of the range of stazione variabiles (not inclusive)
	 * @return the range of stazione variabiles
	 */
	@Override
	public List<StazioneVariabile> getStazioneVariabiles(int start, int end) {
		return stazioneVariabilePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of stazione variabiles.
	 *
	 * @return the number of stazione variabiles
	 */
	@Override
	public int getStazioneVariabilesCount() {
		return stazioneVariabilePersistence.countAll();
	}

	/**
	 * Updates the stazione variabile in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect StazioneVariabileLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param stazioneVariabile the stazione variabile
	 * @return the stazione variabile that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StazioneVariabile updateStazioneVariabile(
		StazioneVariabile stazioneVariabile) {

		return stazioneVariabilePersistence.update(stazioneVariabile);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			StazioneVariabileLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		stazioneVariabileLocalService = (StazioneVariabileLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return StazioneVariabileLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return StazioneVariabile.class;
	}

	protected String getModelClassName() {
		return StazioneVariabile.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = stazioneVariabilePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AllarmePersistence allarmePersistence;

	@Reference
	protected AttivazioneFiumePersistence attivazioneFiumePersistence;

	@Reference
	protected BacinoPersistence bacinoPersistence;

	@Reference
	protected BollettinoPersistence bollettinoPersistence;

	@Reference
	protected BollettinoFinder bollettinoFinder;

	@Reference
	protected BollettinoBacinoPersistence bollettinoBacinoPersistence;

	@Reference
	protected BollettinoIconaPersistence bollettinoIconaPersistence;

	@Reference
	protected BollettinoParametroPersistence bollettinoParametroPersistence;

	@Reference
	protected BollettinoSensorePersistence bollettinoSensorePersistence;

	@Reference
	protected IconaPersistence iconaPersistence;

	@Reference
	protected IdrometroPersistence idrometroPersistence;

	@Reference
	protected PluviometroPersistence pluviometroPersistence;

	@Reference
	protected RegolaAllarmePersistence regolaAllarmePersistence;

	@Reference
	protected RegolaAllarmeComunePersistence regolaAllarmeComunePersistence;

	@Reference
	protected RegolaAllarmeCondizionePersistence
		regolaAllarmeCondizionePersistence;

	@Reference
	protected StazionePersistence stazionePersistence;

	protected StazioneVariabileLocalService stazioneVariabileLocalService;

	@Reference
	protected StazioneVariabilePersistence stazioneVariabilePersistence;

	@Reference
	protected ValoreSensorePersistence valoreSensorePersistence;

	@Reference
	protected VariabilePersistence variabilePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		StazioneVariabileLocalServiceBaseImpl.class);

}