/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import it.eng.bollettino.model.StazioneVariabile;
import it.eng.bollettino.service.StazioneVariabileService;
import it.eng.bollettino.service.persistence.AllarmePersistence;
import it.eng.bollettino.service.persistence.AttivazioneFiumePersistence;
import it.eng.bollettino.service.persistence.BacinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoBacinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoFinder;
import it.eng.bollettino.service.persistence.BollettinoIconaPersistence;
import it.eng.bollettino.service.persistence.BollettinoParametroPersistence;
import it.eng.bollettino.service.persistence.BollettinoPersistence;
import it.eng.bollettino.service.persistence.BollettinoSensorePersistence;
import it.eng.bollettino.service.persistence.IconaPersistence;
import it.eng.bollettino.service.persistence.IdrometroPersistence;
import it.eng.bollettino.service.persistence.PluviometroPersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmeComunePersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmeCondizionePersistence;
import it.eng.bollettino.service.persistence.RegolaAllarmePersistence;
import it.eng.bollettino.service.persistence.StazionePersistence;
import it.eng.bollettino.service.persistence.StazioneVariabilePersistence;
import it.eng.bollettino.service.persistence.ValoreSensorePersistence;
import it.eng.bollettino.service.persistence.VariabilePersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the stazione variabile remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.bollettino.service.impl.StazioneVariabileServiceImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see it.eng.bollettino.service.impl.StazioneVariabileServiceImpl
 * @generated
 */
public abstract class StazioneVariabileServiceBaseImpl
	extends BaseServiceImpl
	implements StazioneVariabileService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>StazioneVariabileService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.bollettino.service.StazioneVariabileServiceUtil</code>.
	 */

	/**
	 * Returns the allarme local service.
	 *
	 * @return the allarme local service
	 */
	public it.eng.bollettino.service.AllarmeLocalService
		getAllarmeLocalService() {

		return allarmeLocalService;
	}

	/**
	 * Sets the allarme local service.
	 *
	 * @param allarmeLocalService the allarme local service
	 */
	public void setAllarmeLocalService(
		it.eng.bollettino.service.AllarmeLocalService allarmeLocalService) {

		this.allarmeLocalService = allarmeLocalService;
	}

	/**
	 * Returns the allarme remote service.
	 *
	 * @return the allarme remote service
	 */
	public it.eng.bollettino.service.AllarmeService getAllarmeService() {
		return allarmeService;
	}

	/**
	 * Sets the allarme remote service.
	 *
	 * @param allarmeService the allarme remote service
	 */
	public void setAllarmeService(
		it.eng.bollettino.service.AllarmeService allarmeService) {

		this.allarmeService = allarmeService;
	}

	/**
	 * Returns the allarme persistence.
	 *
	 * @return the allarme persistence
	 */
	public AllarmePersistence getAllarmePersistence() {
		return allarmePersistence;
	}

	/**
	 * Sets the allarme persistence.
	 *
	 * @param allarmePersistence the allarme persistence
	 */
	public void setAllarmePersistence(AllarmePersistence allarmePersistence) {
		this.allarmePersistence = allarmePersistence;
	}

	/**
	 * Returns the attivazione fiume local service.
	 *
	 * @return the attivazione fiume local service
	 */
	public it.eng.bollettino.service.AttivazioneFiumeLocalService
		getAttivazioneFiumeLocalService() {

		return attivazioneFiumeLocalService;
	}

	/**
	 * Sets the attivazione fiume local service.
	 *
	 * @param attivazioneFiumeLocalService the attivazione fiume local service
	 */
	public void setAttivazioneFiumeLocalService(
		it.eng.bollettino.service.AttivazioneFiumeLocalService
			attivazioneFiumeLocalService) {

		this.attivazioneFiumeLocalService = attivazioneFiumeLocalService;
	}

	/**
	 * Returns the attivazione fiume remote service.
	 *
	 * @return the attivazione fiume remote service
	 */
	public it.eng.bollettino.service.AttivazioneFiumeService
		getAttivazioneFiumeService() {

		return attivazioneFiumeService;
	}

	/**
	 * Sets the attivazione fiume remote service.
	 *
	 * @param attivazioneFiumeService the attivazione fiume remote service
	 */
	public void setAttivazioneFiumeService(
		it.eng.bollettino.service.AttivazioneFiumeService
			attivazioneFiumeService) {

		this.attivazioneFiumeService = attivazioneFiumeService;
	}

	/**
	 * Returns the attivazione fiume persistence.
	 *
	 * @return the attivazione fiume persistence
	 */
	public AttivazioneFiumePersistence getAttivazioneFiumePersistence() {
		return attivazioneFiumePersistence;
	}

	/**
	 * Sets the attivazione fiume persistence.
	 *
	 * @param attivazioneFiumePersistence the attivazione fiume persistence
	 */
	public void setAttivazioneFiumePersistence(
		AttivazioneFiumePersistence attivazioneFiumePersistence) {

		this.attivazioneFiumePersistence = attivazioneFiumePersistence;
	}

	/**
	 * Returns the bacino local service.
	 *
	 * @return the bacino local service
	 */
	public it.eng.bollettino.service.BacinoLocalService
		getBacinoLocalService() {

		return bacinoLocalService;
	}

	/**
	 * Sets the bacino local service.
	 *
	 * @param bacinoLocalService the bacino local service
	 */
	public void setBacinoLocalService(
		it.eng.bollettino.service.BacinoLocalService bacinoLocalService) {

		this.bacinoLocalService = bacinoLocalService;
	}

	/**
	 * Returns the bacino remote service.
	 *
	 * @return the bacino remote service
	 */
	public it.eng.bollettino.service.BacinoService getBacinoService() {
		return bacinoService;
	}

	/**
	 * Sets the bacino remote service.
	 *
	 * @param bacinoService the bacino remote service
	 */
	public void setBacinoService(
		it.eng.bollettino.service.BacinoService bacinoService) {

		this.bacinoService = bacinoService;
	}

	/**
	 * Returns the bacino persistence.
	 *
	 * @return the bacino persistence
	 */
	public BacinoPersistence getBacinoPersistence() {
		return bacinoPersistence;
	}

	/**
	 * Sets the bacino persistence.
	 *
	 * @param bacinoPersistence the bacino persistence
	 */
	public void setBacinoPersistence(BacinoPersistence bacinoPersistence) {
		this.bacinoPersistence = bacinoPersistence;
	}

	/**
	 * Returns the bollettino local service.
	 *
	 * @return the bollettino local service
	 */
	public it.eng.bollettino.service.BollettinoLocalService
		getBollettinoLocalService() {

		return bollettinoLocalService;
	}

	/**
	 * Sets the bollettino local service.
	 *
	 * @param bollettinoLocalService the bollettino local service
	 */
	public void setBollettinoLocalService(
		it.eng.bollettino.service.BollettinoLocalService
			bollettinoLocalService) {

		this.bollettinoLocalService = bollettinoLocalService;
	}

	/**
	 * Returns the bollettino remote service.
	 *
	 * @return the bollettino remote service
	 */
	public it.eng.bollettino.service.BollettinoService getBollettinoService() {
		return bollettinoService;
	}

	/**
	 * Sets the bollettino remote service.
	 *
	 * @param bollettinoService the bollettino remote service
	 */
	public void setBollettinoService(
		it.eng.bollettino.service.BollettinoService bollettinoService) {

		this.bollettinoService = bollettinoService;
	}

	/**
	 * Returns the bollettino persistence.
	 *
	 * @return the bollettino persistence
	 */
	public BollettinoPersistence getBollettinoPersistence() {
		return bollettinoPersistence;
	}

	/**
	 * Sets the bollettino persistence.
	 *
	 * @param bollettinoPersistence the bollettino persistence
	 */
	public void setBollettinoPersistence(
		BollettinoPersistence bollettinoPersistence) {

		this.bollettinoPersistence = bollettinoPersistence;
	}

	/**
	 * Returns the bollettino finder.
	 *
	 * @return the bollettino finder
	 */
	public BollettinoFinder getBollettinoFinder() {
		return bollettinoFinder;
	}

	/**
	 * Sets the bollettino finder.
	 *
	 * @param bollettinoFinder the bollettino finder
	 */
	public void setBollettinoFinder(BollettinoFinder bollettinoFinder) {
		this.bollettinoFinder = bollettinoFinder;
	}

	/**
	 * Returns the bollettino bacino local service.
	 *
	 * @return the bollettino bacino local service
	 */
	public it.eng.bollettino.service.BollettinoBacinoLocalService
		getBollettinoBacinoLocalService() {

		return bollettinoBacinoLocalService;
	}

	/**
	 * Sets the bollettino bacino local service.
	 *
	 * @param bollettinoBacinoLocalService the bollettino bacino local service
	 */
	public void setBollettinoBacinoLocalService(
		it.eng.bollettino.service.BollettinoBacinoLocalService
			bollettinoBacinoLocalService) {

		this.bollettinoBacinoLocalService = bollettinoBacinoLocalService;
	}

	/**
	 * Returns the bollettino bacino remote service.
	 *
	 * @return the bollettino bacino remote service
	 */
	public it.eng.bollettino.service.BollettinoBacinoService
		getBollettinoBacinoService() {

		return bollettinoBacinoService;
	}

	/**
	 * Sets the bollettino bacino remote service.
	 *
	 * @param bollettinoBacinoService the bollettino bacino remote service
	 */
	public void setBollettinoBacinoService(
		it.eng.bollettino.service.BollettinoBacinoService
			bollettinoBacinoService) {

		this.bollettinoBacinoService = bollettinoBacinoService;
	}

	/**
	 * Returns the bollettino bacino persistence.
	 *
	 * @return the bollettino bacino persistence
	 */
	public BollettinoBacinoPersistence getBollettinoBacinoPersistence() {
		return bollettinoBacinoPersistence;
	}

	/**
	 * Sets the bollettino bacino persistence.
	 *
	 * @param bollettinoBacinoPersistence the bollettino bacino persistence
	 */
	public void setBollettinoBacinoPersistence(
		BollettinoBacinoPersistence bollettinoBacinoPersistence) {

		this.bollettinoBacinoPersistence = bollettinoBacinoPersistence;
	}

	/**
	 * Returns the bollettino icona local service.
	 *
	 * @return the bollettino icona local service
	 */
	public it.eng.bollettino.service.BollettinoIconaLocalService
		getBollettinoIconaLocalService() {

		return bollettinoIconaLocalService;
	}

	/**
	 * Sets the bollettino icona local service.
	 *
	 * @param bollettinoIconaLocalService the bollettino icona local service
	 */
	public void setBollettinoIconaLocalService(
		it.eng.bollettino.service.BollettinoIconaLocalService
			bollettinoIconaLocalService) {

		this.bollettinoIconaLocalService = bollettinoIconaLocalService;
	}

	/**
	 * Returns the bollettino icona remote service.
	 *
	 * @return the bollettino icona remote service
	 */
	public it.eng.bollettino.service.BollettinoIconaService
		getBollettinoIconaService() {

		return bollettinoIconaService;
	}

	/**
	 * Sets the bollettino icona remote service.
	 *
	 * @param bollettinoIconaService the bollettino icona remote service
	 */
	public void setBollettinoIconaService(
		it.eng.bollettino.service.BollettinoIconaService
			bollettinoIconaService) {

		this.bollettinoIconaService = bollettinoIconaService;
	}

	/**
	 * Returns the bollettino icona persistence.
	 *
	 * @return the bollettino icona persistence
	 */
	public BollettinoIconaPersistence getBollettinoIconaPersistence() {
		return bollettinoIconaPersistence;
	}

	/**
	 * Sets the bollettino icona persistence.
	 *
	 * @param bollettinoIconaPersistence the bollettino icona persistence
	 */
	public void setBollettinoIconaPersistence(
		BollettinoIconaPersistence bollettinoIconaPersistence) {

		this.bollettinoIconaPersistence = bollettinoIconaPersistence;
	}

	/**
	 * Returns the bollettino parametro local service.
	 *
	 * @return the bollettino parametro local service
	 */
	public it.eng.bollettino.service.BollettinoParametroLocalService
		getBollettinoParametroLocalService() {

		return bollettinoParametroLocalService;
	}

	/**
	 * Sets the bollettino parametro local service.
	 *
	 * @param bollettinoParametroLocalService the bollettino parametro local service
	 */
	public void setBollettinoParametroLocalService(
		it.eng.bollettino.service.BollettinoParametroLocalService
			bollettinoParametroLocalService) {

		this.bollettinoParametroLocalService = bollettinoParametroLocalService;
	}

	/**
	 * Returns the bollettino parametro remote service.
	 *
	 * @return the bollettino parametro remote service
	 */
	public it.eng.bollettino.service.BollettinoParametroService
		getBollettinoParametroService() {

		return bollettinoParametroService;
	}

	/**
	 * Sets the bollettino parametro remote service.
	 *
	 * @param bollettinoParametroService the bollettino parametro remote service
	 */
	public void setBollettinoParametroService(
		it.eng.bollettino.service.BollettinoParametroService
			bollettinoParametroService) {

		this.bollettinoParametroService = bollettinoParametroService;
	}

	/**
	 * Returns the bollettino parametro persistence.
	 *
	 * @return the bollettino parametro persistence
	 */
	public BollettinoParametroPersistence getBollettinoParametroPersistence() {
		return bollettinoParametroPersistence;
	}

	/**
	 * Sets the bollettino parametro persistence.
	 *
	 * @param bollettinoParametroPersistence the bollettino parametro persistence
	 */
	public void setBollettinoParametroPersistence(
		BollettinoParametroPersistence bollettinoParametroPersistence) {

		this.bollettinoParametroPersistence = bollettinoParametroPersistence;
	}

	/**
	 * Returns the bollettino sensore local service.
	 *
	 * @return the bollettino sensore local service
	 */
	public it.eng.bollettino.service.BollettinoSensoreLocalService
		getBollettinoSensoreLocalService() {

		return bollettinoSensoreLocalService;
	}

	/**
	 * Sets the bollettino sensore local service.
	 *
	 * @param bollettinoSensoreLocalService the bollettino sensore local service
	 */
	public void setBollettinoSensoreLocalService(
		it.eng.bollettino.service.BollettinoSensoreLocalService
			bollettinoSensoreLocalService) {

		this.bollettinoSensoreLocalService = bollettinoSensoreLocalService;
	}

	/**
	 * Returns the bollettino sensore remote service.
	 *
	 * @return the bollettino sensore remote service
	 */
	public it.eng.bollettino.service.BollettinoSensoreService
		getBollettinoSensoreService() {

		return bollettinoSensoreService;
	}

	/**
	 * Sets the bollettino sensore remote service.
	 *
	 * @param bollettinoSensoreService the bollettino sensore remote service
	 */
	public void setBollettinoSensoreService(
		it.eng.bollettino.service.BollettinoSensoreService
			bollettinoSensoreService) {

		this.bollettinoSensoreService = bollettinoSensoreService;
	}

	/**
	 * Returns the bollettino sensore persistence.
	 *
	 * @return the bollettino sensore persistence
	 */
	public BollettinoSensorePersistence getBollettinoSensorePersistence() {
		return bollettinoSensorePersistence;
	}

	/**
	 * Sets the bollettino sensore persistence.
	 *
	 * @param bollettinoSensorePersistence the bollettino sensore persistence
	 */
	public void setBollettinoSensorePersistence(
		BollettinoSensorePersistence bollettinoSensorePersistence) {

		this.bollettinoSensorePersistence = bollettinoSensorePersistence;
	}

	/**
	 * Returns the icona local service.
	 *
	 * @return the icona local service
	 */
	public it.eng.bollettino.service.IconaLocalService getIconaLocalService() {
		return iconaLocalService;
	}

	/**
	 * Sets the icona local service.
	 *
	 * @param iconaLocalService the icona local service
	 */
	public void setIconaLocalService(
		it.eng.bollettino.service.IconaLocalService iconaLocalService) {

		this.iconaLocalService = iconaLocalService;
	}

	/**
	 * Returns the icona remote service.
	 *
	 * @return the icona remote service
	 */
	public it.eng.bollettino.service.IconaService getIconaService() {
		return iconaService;
	}

	/**
	 * Sets the icona remote service.
	 *
	 * @param iconaService the icona remote service
	 */
	public void setIconaService(
		it.eng.bollettino.service.IconaService iconaService) {

		this.iconaService = iconaService;
	}

	/**
	 * Returns the icona persistence.
	 *
	 * @return the icona persistence
	 */
	public IconaPersistence getIconaPersistence() {
		return iconaPersistence;
	}

	/**
	 * Sets the icona persistence.
	 *
	 * @param iconaPersistence the icona persistence
	 */
	public void setIconaPersistence(IconaPersistence iconaPersistence) {
		this.iconaPersistence = iconaPersistence;
	}

	/**
	 * Returns the idrometro local service.
	 *
	 * @return the idrometro local service
	 */
	public it.eng.bollettino.service.IdrometroLocalService
		getIdrometroLocalService() {

		return idrometroLocalService;
	}

	/**
	 * Sets the idrometro local service.
	 *
	 * @param idrometroLocalService the idrometro local service
	 */
	public void setIdrometroLocalService(
		it.eng.bollettino.service.IdrometroLocalService idrometroLocalService) {

		this.idrometroLocalService = idrometroLocalService;
	}

	/**
	 * Returns the idrometro remote service.
	 *
	 * @return the idrometro remote service
	 */
	public it.eng.bollettino.service.IdrometroService getIdrometroService() {
		return idrometroService;
	}

	/**
	 * Sets the idrometro remote service.
	 *
	 * @param idrometroService the idrometro remote service
	 */
	public void setIdrometroService(
		it.eng.bollettino.service.IdrometroService idrometroService) {

		this.idrometroService = idrometroService;
	}

	/**
	 * Returns the idrometro persistence.
	 *
	 * @return the idrometro persistence
	 */
	public IdrometroPersistence getIdrometroPersistence() {
		return idrometroPersistence;
	}

	/**
	 * Sets the idrometro persistence.
	 *
	 * @param idrometroPersistence the idrometro persistence
	 */
	public void setIdrometroPersistence(
		IdrometroPersistence idrometroPersistence) {

		this.idrometroPersistence = idrometroPersistence;
	}

	/**
	 * Returns the pluviometro local service.
	 *
	 * @return the pluviometro local service
	 */
	public it.eng.bollettino.service.PluviometroLocalService
		getPluviometroLocalService() {

		return pluviometroLocalService;
	}

	/**
	 * Sets the pluviometro local service.
	 *
	 * @param pluviometroLocalService the pluviometro local service
	 */
	public void setPluviometroLocalService(
		it.eng.bollettino.service.PluviometroLocalService
			pluviometroLocalService) {

		this.pluviometroLocalService = pluviometroLocalService;
	}

	/**
	 * Returns the pluviometro remote service.
	 *
	 * @return the pluviometro remote service
	 */
	public it.eng.bollettino.service.PluviometroService
		getPluviometroService() {

		return pluviometroService;
	}

	/**
	 * Sets the pluviometro remote service.
	 *
	 * @param pluviometroService the pluviometro remote service
	 */
	public void setPluviometroService(
		it.eng.bollettino.service.PluviometroService pluviometroService) {

		this.pluviometroService = pluviometroService;
	}

	/**
	 * Returns the pluviometro persistence.
	 *
	 * @return the pluviometro persistence
	 */
	public PluviometroPersistence getPluviometroPersistence() {
		return pluviometroPersistence;
	}

	/**
	 * Sets the pluviometro persistence.
	 *
	 * @param pluviometroPersistence the pluviometro persistence
	 */
	public void setPluviometroPersistence(
		PluviometroPersistence pluviometroPersistence) {

		this.pluviometroPersistence = pluviometroPersistence;
	}

	/**
	 * Returns the regola allarme local service.
	 *
	 * @return the regola allarme local service
	 */
	public it.eng.bollettino.service.RegolaAllarmeLocalService
		getRegolaAllarmeLocalService() {

		return regolaAllarmeLocalService;
	}

	/**
	 * Sets the regola allarme local service.
	 *
	 * @param regolaAllarmeLocalService the regola allarme local service
	 */
	public void setRegolaAllarmeLocalService(
		it.eng.bollettino.service.RegolaAllarmeLocalService
			regolaAllarmeLocalService) {

		this.regolaAllarmeLocalService = regolaAllarmeLocalService;
	}

	/**
	 * Returns the regola allarme remote service.
	 *
	 * @return the regola allarme remote service
	 */
	public it.eng.bollettino.service.RegolaAllarmeService
		getRegolaAllarmeService() {

		return regolaAllarmeService;
	}

	/**
	 * Sets the regola allarme remote service.
	 *
	 * @param regolaAllarmeService the regola allarme remote service
	 */
	public void setRegolaAllarmeService(
		it.eng.bollettino.service.RegolaAllarmeService regolaAllarmeService) {

		this.regolaAllarmeService = regolaAllarmeService;
	}

	/**
	 * Returns the regola allarme persistence.
	 *
	 * @return the regola allarme persistence
	 */
	public RegolaAllarmePersistence getRegolaAllarmePersistence() {
		return regolaAllarmePersistence;
	}

	/**
	 * Sets the regola allarme persistence.
	 *
	 * @param regolaAllarmePersistence the regola allarme persistence
	 */
	public void setRegolaAllarmePersistence(
		RegolaAllarmePersistence regolaAllarmePersistence) {

		this.regolaAllarmePersistence = regolaAllarmePersistence;
	}

	/**
	 * Returns the regola allarme comune local service.
	 *
	 * @return the regola allarme comune local service
	 */
	public it.eng.bollettino.service.RegolaAllarmeComuneLocalService
		getRegolaAllarmeComuneLocalService() {

		return regolaAllarmeComuneLocalService;
	}

	/**
	 * Sets the regola allarme comune local service.
	 *
	 * @param regolaAllarmeComuneLocalService the regola allarme comune local service
	 */
	public void setRegolaAllarmeComuneLocalService(
		it.eng.bollettino.service.RegolaAllarmeComuneLocalService
			regolaAllarmeComuneLocalService) {

		this.regolaAllarmeComuneLocalService = regolaAllarmeComuneLocalService;
	}

	/**
	 * Returns the regola allarme comune remote service.
	 *
	 * @return the regola allarme comune remote service
	 */
	public it.eng.bollettino.service.RegolaAllarmeComuneService
		getRegolaAllarmeComuneService() {

		return regolaAllarmeComuneService;
	}

	/**
	 * Sets the regola allarme comune remote service.
	 *
	 * @param regolaAllarmeComuneService the regola allarme comune remote service
	 */
	public void setRegolaAllarmeComuneService(
		it.eng.bollettino.service.RegolaAllarmeComuneService
			regolaAllarmeComuneService) {

		this.regolaAllarmeComuneService = regolaAllarmeComuneService;
	}

	/**
	 * Returns the regola allarme comune persistence.
	 *
	 * @return the regola allarme comune persistence
	 */
	public RegolaAllarmeComunePersistence getRegolaAllarmeComunePersistence() {
		return regolaAllarmeComunePersistence;
	}

	/**
	 * Sets the regola allarme comune persistence.
	 *
	 * @param regolaAllarmeComunePersistence the regola allarme comune persistence
	 */
	public void setRegolaAllarmeComunePersistence(
		RegolaAllarmeComunePersistence regolaAllarmeComunePersistence) {

		this.regolaAllarmeComunePersistence = regolaAllarmeComunePersistence;
	}

	/**
	 * Returns the regola allarme condizione local service.
	 *
	 * @return the regola allarme condizione local service
	 */
	public it.eng.bollettino.service.RegolaAllarmeCondizioneLocalService
		getRegolaAllarmeCondizioneLocalService() {

		return regolaAllarmeCondizioneLocalService;
	}

	/**
	 * Sets the regola allarme condizione local service.
	 *
	 * @param regolaAllarmeCondizioneLocalService the regola allarme condizione local service
	 */
	public void setRegolaAllarmeCondizioneLocalService(
		it.eng.bollettino.service.RegolaAllarmeCondizioneLocalService
			regolaAllarmeCondizioneLocalService) {

		this.regolaAllarmeCondizioneLocalService =
			regolaAllarmeCondizioneLocalService;
	}

	/**
	 * Returns the regola allarme condizione remote service.
	 *
	 * @return the regola allarme condizione remote service
	 */
	public it.eng.bollettino.service.RegolaAllarmeCondizioneService
		getRegolaAllarmeCondizioneService() {

		return regolaAllarmeCondizioneService;
	}

	/**
	 * Sets the regola allarme condizione remote service.
	 *
	 * @param regolaAllarmeCondizioneService the regola allarme condizione remote service
	 */
	public void setRegolaAllarmeCondizioneService(
		it.eng.bollettino.service.RegolaAllarmeCondizioneService
			regolaAllarmeCondizioneService) {

		this.regolaAllarmeCondizioneService = regolaAllarmeCondizioneService;
	}

	/**
	 * Returns the regola allarme condizione persistence.
	 *
	 * @return the regola allarme condizione persistence
	 */
	public RegolaAllarmeCondizionePersistence
		getRegolaAllarmeCondizionePersistence() {

		return regolaAllarmeCondizionePersistence;
	}

	/**
	 * Sets the regola allarme condizione persistence.
	 *
	 * @param regolaAllarmeCondizionePersistence the regola allarme condizione persistence
	 */
	public void setRegolaAllarmeCondizionePersistence(
		RegolaAllarmeCondizionePersistence regolaAllarmeCondizionePersistence) {

		this.regolaAllarmeCondizionePersistence =
			regolaAllarmeCondizionePersistence;
	}

	/**
	 * Returns the stazione local service.
	 *
	 * @return the stazione local service
	 */
	public it.eng.bollettino.service.StazioneLocalService
		getStazioneLocalService() {

		return stazioneLocalService;
	}

	/**
	 * Sets the stazione local service.
	 *
	 * @param stazioneLocalService the stazione local service
	 */
	public void setStazioneLocalService(
		it.eng.bollettino.service.StazioneLocalService stazioneLocalService) {

		this.stazioneLocalService = stazioneLocalService;
	}

	/**
	 * Returns the stazione remote service.
	 *
	 * @return the stazione remote service
	 */
	public it.eng.bollettino.service.StazioneService getStazioneService() {
		return stazioneService;
	}

	/**
	 * Sets the stazione remote service.
	 *
	 * @param stazioneService the stazione remote service
	 */
	public void setStazioneService(
		it.eng.bollettino.service.StazioneService stazioneService) {

		this.stazioneService = stazioneService;
	}

	/**
	 * Returns the stazione persistence.
	 *
	 * @return the stazione persistence
	 */
	public StazionePersistence getStazionePersistence() {
		return stazionePersistence;
	}

	/**
	 * Sets the stazione persistence.
	 *
	 * @param stazionePersistence the stazione persistence
	 */
	public void setStazionePersistence(
		StazionePersistence stazionePersistence) {

		this.stazionePersistence = stazionePersistence;
	}

	/**
	 * Returns the stazione variabile local service.
	 *
	 * @return the stazione variabile local service
	 */
	public it.eng.bollettino.service.StazioneVariabileLocalService
		getStazioneVariabileLocalService() {

		return stazioneVariabileLocalService;
	}

	/**
	 * Sets the stazione variabile local service.
	 *
	 * @param stazioneVariabileLocalService the stazione variabile local service
	 */
	public void setStazioneVariabileLocalService(
		it.eng.bollettino.service.StazioneVariabileLocalService
			stazioneVariabileLocalService) {

		this.stazioneVariabileLocalService = stazioneVariabileLocalService;
	}

	/**
	 * Returns the stazione variabile remote service.
	 *
	 * @return the stazione variabile remote service
	 */
	public StazioneVariabileService getStazioneVariabileService() {
		return stazioneVariabileService;
	}

	/**
	 * Sets the stazione variabile remote service.
	 *
	 * @param stazioneVariabileService the stazione variabile remote service
	 */
	public void setStazioneVariabileService(
		StazioneVariabileService stazioneVariabileService) {

		this.stazioneVariabileService = stazioneVariabileService;
	}

	/**
	 * Returns the stazione variabile persistence.
	 *
	 * @return the stazione variabile persistence
	 */
	public StazioneVariabilePersistence getStazioneVariabilePersistence() {
		return stazioneVariabilePersistence;
	}

	/**
	 * Sets the stazione variabile persistence.
	 *
	 * @param stazioneVariabilePersistence the stazione variabile persistence
	 */
	public void setStazioneVariabilePersistence(
		StazioneVariabilePersistence stazioneVariabilePersistence) {

		this.stazioneVariabilePersistence = stazioneVariabilePersistence;
	}

	/**
	 * Returns the valore sensore local service.
	 *
	 * @return the valore sensore local service
	 */
	public it.eng.bollettino.service.ValoreSensoreLocalService
		getValoreSensoreLocalService() {

		return valoreSensoreLocalService;
	}

	/**
	 * Sets the valore sensore local service.
	 *
	 * @param valoreSensoreLocalService the valore sensore local service
	 */
	public void setValoreSensoreLocalService(
		it.eng.bollettino.service.ValoreSensoreLocalService
			valoreSensoreLocalService) {

		this.valoreSensoreLocalService = valoreSensoreLocalService;
	}

	/**
	 * Returns the valore sensore remote service.
	 *
	 * @return the valore sensore remote service
	 */
	public it.eng.bollettino.service.ValoreSensoreService
		getValoreSensoreService() {

		return valoreSensoreService;
	}

	/**
	 * Sets the valore sensore remote service.
	 *
	 * @param valoreSensoreService the valore sensore remote service
	 */
	public void setValoreSensoreService(
		it.eng.bollettino.service.ValoreSensoreService valoreSensoreService) {

		this.valoreSensoreService = valoreSensoreService;
	}

	/**
	 * Returns the valore sensore persistence.
	 *
	 * @return the valore sensore persistence
	 */
	public ValoreSensorePersistence getValoreSensorePersistence() {
		return valoreSensorePersistence;
	}

	/**
	 * Sets the valore sensore persistence.
	 *
	 * @param valoreSensorePersistence the valore sensore persistence
	 */
	public void setValoreSensorePersistence(
		ValoreSensorePersistence valoreSensorePersistence) {

		this.valoreSensorePersistence = valoreSensorePersistence;
	}

	/**
	 * Returns the variabile local service.
	 *
	 * @return the variabile local service
	 */
	public it.eng.bollettino.service.VariabileLocalService
		getVariabileLocalService() {

		return variabileLocalService;
	}

	/**
	 * Sets the variabile local service.
	 *
	 * @param variabileLocalService the variabile local service
	 */
	public void setVariabileLocalService(
		it.eng.bollettino.service.VariabileLocalService variabileLocalService) {

		this.variabileLocalService = variabileLocalService;
	}

	/**
	 * Returns the variabile remote service.
	 *
	 * @return the variabile remote service
	 */
	public it.eng.bollettino.service.VariabileService getVariabileService() {
		return variabileService;
	}

	/**
	 * Sets the variabile remote service.
	 *
	 * @param variabileService the variabile remote service
	 */
	public void setVariabileService(
		it.eng.bollettino.service.VariabileService variabileService) {

		this.variabileService = variabileService;
	}

	/**
	 * Returns the variabile persistence.
	 *
	 * @return the variabile persistence
	 */
	public VariabilePersistence getVariabilePersistence() {
		return variabilePersistence;
	}

	/**
	 * Sets the variabile persistence.
	 *
	 * @param variabilePersistence the variabile persistence
	 */
	public void setVariabilePersistence(
		VariabilePersistence variabilePersistence) {

		this.variabilePersistence = variabilePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return StazioneVariabileService.class.getName();
	}

	protected Class<?> getModelClass() {
		return StazioneVariabile.class;
	}

	protected String getModelClassName() {
		return StazioneVariabile.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				stazioneVariabilePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = it.eng.bollettino.service.AllarmeLocalService.class)
	protected it.eng.bollettino.service.AllarmeLocalService allarmeLocalService;

	@BeanReference(type = it.eng.bollettino.service.AllarmeService.class)
	protected it.eng.bollettino.service.AllarmeService allarmeService;

	@BeanReference(type = AllarmePersistence.class)
	protected AllarmePersistence allarmePersistence;

	@BeanReference(
		type = it.eng.bollettino.service.AttivazioneFiumeLocalService.class
	)
	protected it.eng.bollettino.service.AttivazioneFiumeLocalService
		attivazioneFiumeLocalService;

	@BeanReference(
		type = it.eng.bollettino.service.AttivazioneFiumeService.class
	)
	protected it.eng.bollettino.service.AttivazioneFiumeService
		attivazioneFiumeService;

	@BeanReference(type = AttivazioneFiumePersistence.class)
	protected AttivazioneFiumePersistence attivazioneFiumePersistence;

	@BeanReference(type = it.eng.bollettino.service.BacinoLocalService.class)
	protected it.eng.bollettino.service.BacinoLocalService bacinoLocalService;

	@BeanReference(type = it.eng.bollettino.service.BacinoService.class)
	protected it.eng.bollettino.service.BacinoService bacinoService;

	@BeanReference(type = BacinoPersistence.class)
	protected BacinoPersistence bacinoPersistence;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoLocalService.class
	)
	protected it.eng.bollettino.service.BollettinoLocalService
		bollettinoLocalService;

	@BeanReference(type = it.eng.bollettino.service.BollettinoService.class)
	protected it.eng.bollettino.service.BollettinoService bollettinoService;

	@BeanReference(type = BollettinoPersistence.class)
	protected BollettinoPersistence bollettinoPersistence;

	@BeanReference(type = BollettinoFinder.class)
	protected BollettinoFinder bollettinoFinder;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoBacinoLocalService.class
	)
	protected it.eng.bollettino.service.BollettinoBacinoLocalService
		bollettinoBacinoLocalService;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoBacinoService.class
	)
	protected it.eng.bollettino.service.BollettinoBacinoService
		bollettinoBacinoService;

	@BeanReference(type = BollettinoBacinoPersistence.class)
	protected BollettinoBacinoPersistence bollettinoBacinoPersistence;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoIconaLocalService.class
	)
	protected it.eng.bollettino.service.BollettinoIconaLocalService
		bollettinoIconaLocalService;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoIconaService.class
	)
	protected it.eng.bollettino.service.BollettinoIconaService
		bollettinoIconaService;

	@BeanReference(type = BollettinoIconaPersistence.class)
	protected BollettinoIconaPersistence bollettinoIconaPersistence;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoParametroLocalService.class
	)
	protected it.eng.bollettino.service.BollettinoParametroLocalService
		bollettinoParametroLocalService;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoParametroService.class
	)
	protected it.eng.bollettino.service.BollettinoParametroService
		bollettinoParametroService;

	@BeanReference(type = BollettinoParametroPersistence.class)
	protected BollettinoParametroPersistence bollettinoParametroPersistence;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoSensoreLocalService.class
	)
	protected it.eng.bollettino.service.BollettinoSensoreLocalService
		bollettinoSensoreLocalService;

	@BeanReference(
		type = it.eng.bollettino.service.BollettinoSensoreService.class
	)
	protected it.eng.bollettino.service.BollettinoSensoreService
		bollettinoSensoreService;

	@BeanReference(type = BollettinoSensorePersistence.class)
	protected BollettinoSensorePersistence bollettinoSensorePersistence;

	@BeanReference(type = it.eng.bollettino.service.IconaLocalService.class)
	protected it.eng.bollettino.service.IconaLocalService iconaLocalService;

	@BeanReference(type = it.eng.bollettino.service.IconaService.class)
	protected it.eng.bollettino.service.IconaService iconaService;

	@BeanReference(type = IconaPersistence.class)
	protected IconaPersistence iconaPersistence;

	@BeanReference(type = it.eng.bollettino.service.IdrometroLocalService.class)
	protected it.eng.bollettino.service.IdrometroLocalService
		idrometroLocalService;

	@BeanReference(type = it.eng.bollettino.service.IdrometroService.class)
	protected it.eng.bollettino.service.IdrometroService idrometroService;

	@BeanReference(type = IdrometroPersistence.class)
	protected IdrometroPersistence idrometroPersistence;

	@BeanReference(
		type = it.eng.bollettino.service.PluviometroLocalService.class
	)
	protected it.eng.bollettino.service.PluviometroLocalService
		pluviometroLocalService;

	@BeanReference(type = it.eng.bollettino.service.PluviometroService.class)
	protected it.eng.bollettino.service.PluviometroService pluviometroService;

	@BeanReference(type = PluviometroPersistence.class)
	protected PluviometroPersistence pluviometroPersistence;

	@BeanReference(
		type = it.eng.bollettino.service.RegolaAllarmeLocalService.class
	)
	protected it.eng.bollettino.service.RegolaAllarmeLocalService
		regolaAllarmeLocalService;

	@BeanReference(type = it.eng.bollettino.service.RegolaAllarmeService.class)
	protected it.eng.bollettino.service.RegolaAllarmeService
		regolaAllarmeService;

	@BeanReference(type = RegolaAllarmePersistence.class)
	protected RegolaAllarmePersistence regolaAllarmePersistence;

	@BeanReference(
		type = it.eng.bollettino.service.RegolaAllarmeComuneLocalService.class
	)
	protected it.eng.bollettino.service.RegolaAllarmeComuneLocalService
		regolaAllarmeComuneLocalService;

	@BeanReference(
		type = it.eng.bollettino.service.RegolaAllarmeComuneService.class
	)
	protected it.eng.bollettino.service.RegolaAllarmeComuneService
		regolaAllarmeComuneService;

	@BeanReference(type = RegolaAllarmeComunePersistence.class)
	protected RegolaAllarmeComunePersistence regolaAllarmeComunePersistence;

	@BeanReference(
		type = it.eng.bollettino.service.RegolaAllarmeCondizioneLocalService.class
	)
	protected it.eng.bollettino.service.RegolaAllarmeCondizioneLocalService
		regolaAllarmeCondizioneLocalService;

	@BeanReference(
		type = it.eng.bollettino.service.RegolaAllarmeCondizioneService.class
	)
	protected it.eng.bollettino.service.RegolaAllarmeCondizioneService
		regolaAllarmeCondizioneService;

	@BeanReference(type = RegolaAllarmeCondizionePersistence.class)
	protected RegolaAllarmeCondizionePersistence
		regolaAllarmeCondizionePersistence;

	@BeanReference(type = it.eng.bollettino.service.StazioneLocalService.class)
	protected it.eng.bollettino.service.StazioneLocalService
		stazioneLocalService;

	@BeanReference(type = it.eng.bollettino.service.StazioneService.class)
	protected it.eng.bollettino.service.StazioneService stazioneService;

	@BeanReference(type = StazionePersistence.class)
	protected StazionePersistence stazionePersistence;

	@BeanReference(
		type = it.eng.bollettino.service.StazioneVariabileLocalService.class
	)
	protected it.eng.bollettino.service.StazioneVariabileLocalService
		stazioneVariabileLocalService;

	@BeanReference(type = StazioneVariabileService.class)
	protected StazioneVariabileService stazioneVariabileService;

	@BeanReference(type = StazioneVariabilePersistence.class)
	protected StazioneVariabilePersistence stazioneVariabilePersistence;

	@BeanReference(
		type = it.eng.bollettino.service.ValoreSensoreLocalService.class
	)
	protected it.eng.bollettino.service.ValoreSensoreLocalService
		valoreSensoreLocalService;

	@BeanReference(type = it.eng.bollettino.service.ValoreSensoreService.class)
	protected it.eng.bollettino.service.ValoreSensoreService
		valoreSensoreService;

	@BeanReference(type = ValoreSensorePersistence.class)
	protected ValoreSensorePersistence valoreSensorePersistence;

	@BeanReference(type = it.eng.bollettino.service.VariabileLocalService.class)
	protected it.eng.bollettino.service.VariabileLocalService
		variabileLocalService;

	@BeanReference(type = it.eng.bollettino.service.VariabileService.class)
	protected it.eng.bollettino.service.VariabileService variabileService;

	@BeanReference(type = VariabilePersistence.class)
	protected VariabilePersistence variabilePersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

}