/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerta.messages.services.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.allerta.messages.services.model.Parametro;
import it.eng.allerta.messages.services.model.ParametroModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Parametro service. Represents a row in the &quot;smsService_Parametro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParametroModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParametroImpl}.
 * </p>
 *
 * @author Giorgianni_F
 * @see ParametroImpl
 * @generated
 */
@JSON(strict = true)
public class ParametroModelImpl
	extends BaseModelImpl<Parametro> implements ParametroModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parametro model instance should use the <code>Parametro</code> interface instead.
	 */
	public static final String TABLE_NAME = "smsService_Parametro";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.BIGINT}, {"ip", Types.VARCHAR}, {"porta", Types.INTEGER},
		{"username", Types.VARCHAR}, {"password_", Types.VARCHAR},
		{"mittente", Types.VARCHAR}, {"nodo", Types.VARCHAR},
		{"dataConnessione", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("porta", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("username", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("password_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mittente", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nodo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataConnessione", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table smsService_Parametro (Id LONG not null primary key,ip VARCHAR(75) null,porta INTEGER,username VARCHAR(75) null,password_ VARCHAR(75) null,mittente VARCHAR(75) null,nodo VARCHAR(75) null,dataConnessione DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table smsService_Parametro";

	public static final String ORDER_BY_JPQL = " ORDER BY parametro.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY smsService_Parametro.Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NODO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ParametroModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Parametro.class;
	}

	@Override
	public String getModelClassName() {
		return Parametro.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Parametro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Parametro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parametro, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Parametro)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Parametro, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Parametro, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Parametro)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Parametro, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Parametro, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Parametro, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Parametro, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Parametro, Object>>();

			attributeGetterFunctions.put("Id", Parametro::getId);
			attributeGetterFunctions.put("ip", Parametro::getIp);
			attributeGetterFunctions.put("porta", Parametro::getPorta);
			attributeGetterFunctions.put("username", Parametro::getUsername);
			attributeGetterFunctions.put("password", Parametro::getPassword);
			attributeGetterFunctions.put("mittente", Parametro::getMittente);
			attributeGetterFunctions.put("nodo", Parametro::getNodo);
			attributeGetterFunctions.put(
				"dataConnessione", Parametro::getDataConnessione);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Parametro, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Parametro, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Parametro, ?>>();

			attributeSetterBiConsumers.put(
				"Id", (BiConsumer<Parametro, Long>)Parametro::setId);
			attributeSetterBiConsumers.put(
				"ip", (BiConsumer<Parametro, String>)Parametro::setIp);
			attributeSetterBiConsumers.put(
				"porta", (BiConsumer<Parametro, Integer>)Parametro::setPorta);
			attributeSetterBiConsumers.put(
				"username",
				(BiConsumer<Parametro, String>)Parametro::setUsername);
			attributeSetterBiConsumers.put(
				"password",
				(BiConsumer<Parametro, String>)Parametro::setPassword);
			attributeSetterBiConsumers.put(
				"mittente",
				(BiConsumer<Parametro, String>)Parametro::setMittente);
			attributeSetterBiConsumers.put(
				"nodo", (BiConsumer<Parametro, String>)Parametro::setNodo);
			attributeSetterBiConsumers.put(
				"dataConnessione",
				(BiConsumer<Parametro, Date>)Parametro::setDataConnessione);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id = Id;
	}

	@JSON
	@Override
	public String getIp() {
		if (_ip == null) {
			return "";
		}
		else {
			return _ip;
		}
	}

	@Override
	public void setIp(String ip) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ip = ip;
	}

	@JSON
	@Override
	public int getPorta() {
		return _porta;
	}

	@Override
	public void setPorta(int porta) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_porta = porta;
	}

	@JSON
	@Override
	public String getUsername() {
		if (_username == null) {
			return "";
		}
		else {
			return _username;
		}
	}

	@Override
	public void setUsername(String username) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_username = username;
	}

	@JSON
	@Override
	public String getPassword() {
		if (_password == null) {
			return "";
		}
		else {
			return _password;
		}
	}

	@Override
	public void setPassword(String password) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_password = password;
	}

	@JSON
	@Override
	public String getMittente() {
		if (_mittente == null) {
			return "";
		}
		else {
			return _mittente;
		}
	}

	@Override
	public void setMittente(String mittente) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mittente = mittente;
	}

	@JSON
	@Override
	public String getNodo() {
		if (_nodo == null) {
			return "";
		}
		else {
			return _nodo;
		}
	}

	@Override
	public void setNodo(String nodo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nodo = nodo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNodo() {
		return getColumnOriginalValue("nodo");
	}

	@JSON
	@Override
	public Date getDataConnessione() {
		return _dataConnessione;
	}

	@Override
	public void setDataConnessione(Date dataConnessione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataConnessione = dataConnessione;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Parametro.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Parametro toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Parametro>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParametroImpl parametroImpl = new ParametroImpl();

		parametroImpl.setId(getId());
		parametroImpl.setIp(getIp());
		parametroImpl.setPorta(getPorta());
		parametroImpl.setUsername(getUsername());
		parametroImpl.setPassword(getPassword());
		parametroImpl.setMittente(getMittente());
		parametroImpl.setNodo(getNodo());
		parametroImpl.setDataConnessione(getDataConnessione());

		parametroImpl.resetOriginalValues();

		return parametroImpl;
	}

	@Override
	public Parametro cloneWithOriginalValues() {
		ParametroImpl parametroImpl = new ParametroImpl();

		parametroImpl.setId(this.<Long>getColumnOriginalValue("Id"));
		parametroImpl.setIp(this.<String>getColumnOriginalValue("ip"));
		parametroImpl.setPorta(this.<Integer>getColumnOriginalValue("porta"));
		parametroImpl.setUsername(
			this.<String>getColumnOriginalValue("username"));
		parametroImpl.setPassword(
			this.<String>getColumnOriginalValue("password_"));
		parametroImpl.setMittente(
			this.<String>getColumnOriginalValue("mittente"));
		parametroImpl.setNodo(this.<String>getColumnOriginalValue("nodo"));
		parametroImpl.setDataConnessione(
			this.<Date>getColumnOriginalValue("dataConnessione"));

		return parametroImpl;
	}

	@Override
	public int compareTo(Parametro parametro) {
		long primaryKey = parametro.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Parametro)) {
			return false;
		}

		Parametro parametro = (Parametro)object;

		long primaryKey = parametro.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Parametro> toCacheModel() {
		ParametroCacheModel parametroCacheModel = new ParametroCacheModel();

		parametroCacheModel.Id = getId();

		parametroCacheModel.ip = getIp();

		String ip = parametroCacheModel.ip;

		if ((ip != null) && (ip.length() == 0)) {
			parametroCacheModel.ip = null;
		}

		parametroCacheModel.porta = getPorta();

		parametroCacheModel.username = getUsername();

		String username = parametroCacheModel.username;

		if ((username != null) && (username.length() == 0)) {
			parametroCacheModel.username = null;
		}

		parametroCacheModel.password = getPassword();

		String password = parametroCacheModel.password;

		if ((password != null) && (password.length() == 0)) {
			parametroCacheModel.password = null;
		}

		parametroCacheModel.mittente = getMittente();

		String mittente = parametroCacheModel.mittente;

		if ((mittente != null) && (mittente.length() == 0)) {
			parametroCacheModel.mittente = null;
		}

		parametroCacheModel.nodo = getNodo();

		String nodo = parametroCacheModel.nodo;

		if ((nodo != null) && (nodo.length() == 0)) {
			parametroCacheModel.nodo = null;
		}

		Date dataConnessione = getDataConnessione();

		if (dataConnessione != null) {
			parametroCacheModel.dataConnessione = dataConnessione.getTime();
		}
		else {
			parametroCacheModel.dataConnessione = Long.MIN_VALUE;
		}

		return parametroCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Parametro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Parametro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parametro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Parametro)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Parametro>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Parametro.class, ModelWrapper.class);

	}

	private long _Id;
	private String _ip;
	private int _porta;
	private String _username;
	private String _password;
	private String _mittente;
	private String _nodo;
	private Date _dataConnessione;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Parametro, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Parametro)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id", _Id);
		_columnOriginalValues.put("ip", _ip);
		_columnOriginalValues.put("porta", _porta);
		_columnOriginalValues.put("username", _username);
		_columnOriginalValues.put("password_", _password);
		_columnOriginalValues.put("mittente", _mittente);
		_columnOriginalValues.put("nodo", _nodo);
		_columnOriginalValues.put("dataConnessione", _dataConnessione);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("password_", "password");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id", 1L);

		columnBitmasks.put("ip", 2L);

		columnBitmasks.put("porta", 4L);

		columnBitmasks.put("username", 8L);

		columnBitmasks.put("password_", 16L);

		columnBitmasks.put("mittente", 32L);

		columnBitmasks.put("nodo", 64L);

		columnBitmasks.put("dataConnessione", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Parametro _escapedModel;

}