/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerte.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import it.eng.allerte.model.RubricaContatto;
import it.eng.allerte.service.RubricaContattoService;
import it.eng.allerte.service.persistence.RubricaCanalePersistence;
import it.eng.allerte.service.persistence.RubricaCategoriaPersistence;
import it.eng.allerte.service.persistence.RubricaContattoFinder;
import it.eng.allerte.service.persistence.RubricaContattoPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoFinder;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiFinder;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoNominativiFinder;
import it.eng.allerte.service.persistence.RubricaGruppoNominativiPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoPersistence;
import it.eng.allerte.service.persistence.RubricaLogFinder;
import it.eng.allerte.service.persistence.RubricaLogPersistence;
import it.eng.allerte.service.persistence.RubricaNominativoFinder;
import it.eng.allerte.service.persistence.RubricaNominativoPersistence;
import it.eng.allerte.service.persistence.RubricaPermessiPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloPermessiPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloRubricaPersistence;
import it.eng.allerte.service.persistence.RubricaSitoPersistence;
import it.eng.allerte.service.persistence.RubricaUtenteSitoPersistence;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the rubrica contatto remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.allerte.service.impl.RubricaContattoServiceImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see it.eng.allerte.service.impl.RubricaContattoServiceImpl
 * @generated
 */
public abstract class RubricaContattoServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService, RubricaContattoService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RubricaContattoService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.allerte.service.RubricaContattoServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RubricaContattoService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		rubricaContattoService = (RubricaContattoService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RubricaContattoService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RubricaContatto.class;
	}

	protected String getModelClassName() {
		return RubricaContatto.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = rubricaContattoPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected RubricaCanalePersistence rubricaCanalePersistence;

	@Reference
	protected RubricaCategoriaPersistence rubricaCategoriaPersistence;

	@Reference
	protected it.eng.allerte.service.RubricaContattoLocalService
		rubricaContattoLocalService;

	protected RubricaContattoService rubricaContattoService;

	@Reference
	protected RubricaContattoPersistence rubricaContattoPersistence;

	@Reference
	protected RubricaContattoFinder rubricaContattoFinder;

	@Reference
	protected RubricaGruppoPersistence rubricaGruppoPersistence;

	@Reference
	protected RubricaGruppoFinder rubricaGruppoFinder;

	@Reference
	protected RubricaGruppoGruppiPersistence rubricaGruppoGruppiPersistence;

	@Reference
	protected RubricaGruppoGruppiFinder rubricaGruppoGruppiFinder;

	@Reference
	protected RubricaGruppoNominativiPersistence
		rubricaGruppoNominativiPersistence;

	@Reference
	protected RubricaGruppoNominativiFinder rubricaGruppoNominativiFinder;

	@Reference
	protected RubricaLogPersistence rubricaLogPersistence;

	@Reference
	protected RubricaLogFinder rubricaLogFinder;

	@Reference
	protected RubricaNominativoPersistence rubricaNominativoPersistence;

	@Reference
	protected RubricaNominativoFinder rubricaNominativoFinder;

	@Reference
	protected RubricaPermessiPersistence rubricaPermessiPersistence;

	@Reference
	protected RubricaRuoloPersistence rubricaRuoloPersistence;

	@Reference
	protected RubricaRuoloPermessiPersistence rubricaRuoloPermessiPersistence;

	@Reference
	protected RubricaRuoloRubricaPersistence rubricaRuoloRubricaPersistence;

	@Reference
	protected RubricaSitoPersistence rubricaSitoPersistence;

	@Reference
	protected RubricaUtenteSitoPersistence rubricaUtenteSitoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		RubricaContattoServiceBaseImpl.class);

}