/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerte.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import it.eng.allerte.model.RubricaRuoloRubrica;
import it.eng.allerte.service.RubricaRuoloRubricaLocalService;
import it.eng.allerte.service.persistence.RubricaCanalePersistence;
import it.eng.allerte.service.persistence.RubricaCategoriaPersistence;
import it.eng.allerte.service.persistence.RubricaContattoFinder;
import it.eng.allerte.service.persistence.RubricaContattoPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoFinder;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiFinder;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoNominativiFinder;
import it.eng.allerte.service.persistence.RubricaGruppoNominativiPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoPersistence;
import it.eng.allerte.service.persistence.RubricaLogFinder;
import it.eng.allerte.service.persistence.RubricaLogPersistence;
import it.eng.allerte.service.persistence.RubricaNominativoFinder;
import it.eng.allerte.service.persistence.RubricaNominativoPersistence;
import it.eng.allerte.service.persistence.RubricaPermessiPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloPermessiPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloRubricaPersistence;
import it.eng.allerte.service.persistence.RubricaSitoPersistence;
import it.eng.allerte.service.persistence.RubricaUtenteSitoPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the rubrica ruolo rubrica local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.allerte.service.impl.RubricaRuoloRubricaLocalServiceImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see it.eng.allerte.service.impl.RubricaRuoloRubricaLocalServiceImpl
 * @generated
 */
public abstract class RubricaRuoloRubricaLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   RubricaRuoloRubricaLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RubricaRuoloRubricaLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.allerte.service.RubricaRuoloRubricaLocalServiceUtil</code>.
	 */

	/**
	 * Adds the rubrica ruolo rubrica to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaRuoloRubricaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaRuoloRubrica the rubrica ruolo rubrica
	 * @return the rubrica ruolo rubrica that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RubricaRuoloRubrica addRubricaRuoloRubrica(
		RubricaRuoloRubrica rubricaRuoloRubrica) {

		rubricaRuoloRubrica.setNew(true);

		return rubricaRuoloRubricaPersistence.update(rubricaRuoloRubrica);
	}

	/**
	 * Creates a new rubrica ruolo rubrica with the primary key. Does not add the rubrica ruolo rubrica to the database.
	 *
	 * @param ID_RUOLO the primary key for the new rubrica ruolo rubrica
	 * @return the new rubrica ruolo rubrica
	 */
	@Override
	@Transactional(enabled = false)
	public RubricaRuoloRubrica createRubricaRuoloRubrica(long ID_RUOLO) {
		return rubricaRuoloRubricaPersistence.create(ID_RUOLO);
	}

	/**
	 * Deletes the rubrica ruolo rubrica with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaRuoloRubricaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ID_RUOLO the primary key of the rubrica ruolo rubrica
	 * @return the rubrica ruolo rubrica that was removed
	 * @throws PortalException if a rubrica ruolo rubrica with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RubricaRuoloRubrica deleteRubricaRuoloRubrica(long ID_RUOLO)
		throws PortalException {

		return rubricaRuoloRubricaPersistence.remove(ID_RUOLO);
	}

	/**
	 * Deletes the rubrica ruolo rubrica from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaRuoloRubricaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaRuoloRubrica the rubrica ruolo rubrica
	 * @return the rubrica ruolo rubrica that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RubricaRuoloRubrica deleteRubricaRuoloRubrica(
		RubricaRuoloRubrica rubricaRuoloRubrica) {

		return rubricaRuoloRubricaPersistence.remove(rubricaRuoloRubrica);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return rubricaRuoloRubricaPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			RubricaRuoloRubrica.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return rubricaRuoloRubricaPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaRuoloRubricaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return rubricaRuoloRubricaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaRuoloRubricaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return rubricaRuoloRubricaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return rubricaRuoloRubricaPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return rubricaRuoloRubricaPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public RubricaRuoloRubrica fetchRubricaRuoloRubrica(long ID_RUOLO) {
		return rubricaRuoloRubricaPersistence.fetchByPrimaryKey(ID_RUOLO);
	}

	/**
	 * Returns the rubrica ruolo rubrica with the primary key.
	 *
	 * @param ID_RUOLO the primary key of the rubrica ruolo rubrica
	 * @return the rubrica ruolo rubrica
	 * @throws PortalException if a rubrica ruolo rubrica with the primary key could not be found
	 */
	@Override
	public RubricaRuoloRubrica getRubricaRuoloRubrica(long ID_RUOLO)
		throws PortalException {

		return rubricaRuoloRubricaPersistence.findByPrimaryKey(ID_RUOLO);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			rubricaRuoloRubricaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RubricaRuoloRubrica.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ID_RUOLO");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			rubricaRuoloRubricaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			RubricaRuoloRubrica.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("ID_RUOLO");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			rubricaRuoloRubricaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RubricaRuoloRubrica.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ID_RUOLO");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rubricaRuoloRubricaPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement RubricaRuoloRubricaLocalServiceImpl#deleteRubricaRuoloRubrica(RubricaRuoloRubrica) to avoid orphaned data");
		}

		return rubricaRuoloRubricaLocalService.deleteRubricaRuoloRubrica(
			(RubricaRuoloRubrica)persistedModel);
	}

	@Override
	public BasePersistence<RubricaRuoloRubrica> getBasePersistence() {
		return rubricaRuoloRubricaPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rubricaRuoloRubricaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rubrica ruolo rubricas.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaRuoloRubricaModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of rubrica ruolo rubricas
	 * @param end the upper bound of the range of rubrica ruolo rubricas (not inclusive)
	 * @return the range of rubrica ruolo rubricas
	 */
	@Override
	public List<RubricaRuoloRubrica> getRubricaRuoloRubricas(
		int start, int end) {

		return rubricaRuoloRubricaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rubrica ruolo rubricas.
	 *
	 * @return the number of rubrica ruolo rubricas
	 */
	@Override
	public int getRubricaRuoloRubricasCount() {
		return rubricaRuoloRubricaPersistence.countAll();
	}

	/**
	 * Updates the rubrica ruolo rubrica in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaRuoloRubricaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaRuoloRubrica the rubrica ruolo rubrica
	 * @return the rubrica ruolo rubrica that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RubricaRuoloRubrica updateRubricaRuoloRubrica(
		RubricaRuoloRubrica rubricaRuoloRubrica) {

		return rubricaRuoloRubricaPersistence.update(rubricaRuoloRubrica);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RubricaRuoloRubricaLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		rubricaRuoloRubricaLocalService =
			(RubricaRuoloRubricaLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RubricaRuoloRubricaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RubricaRuoloRubrica.class;
	}

	protected String getModelClassName() {
		return RubricaRuoloRubrica.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = rubricaRuoloRubricaPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected RubricaCanalePersistence rubricaCanalePersistence;

	@Reference
	protected RubricaCategoriaPersistence rubricaCategoriaPersistence;

	@Reference
	protected RubricaContattoPersistence rubricaContattoPersistence;

	@Reference
	protected RubricaContattoFinder rubricaContattoFinder;

	@Reference
	protected RubricaGruppoPersistence rubricaGruppoPersistence;

	@Reference
	protected RubricaGruppoFinder rubricaGruppoFinder;

	@Reference
	protected RubricaGruppoGruppiPersistence rubricaGruppoGruppiPersistence;

	@Reference
	protected RubricaGruppoGruppiFinder rubricaGruppoGruppiFinder;

	@Reference
	protected RubricaGruppoNominativiPersistence
		rubricaGruppoNominativiPersistence;

	@Reference
	protected RubricaGruppoNominativiFinder rubricaGruppoNominativiFinder;

	@Reference
	protected RubricaLogPersistence rubricaLogPersistence;

	@Reference
	protected RubricaLogFinder rubricaLogFinder;

	@Reference
	protected RubricaNominativoPersistence rubricaNominativoPersistence;

	@Reference
	protected RubricaNominativoFinder rubricaNominativoFinder;

	@Reference
	protected RubricaPermessiPersistence rubricaPermessiPersistence;

	@Reference
	protected RubricaRuoloPersistence rubricaRuoloPersistence;

	@Reference
	protected RubricaRuoloPermessiPersistence rubricaRuoloPermessiPersistence;

	protected RubricaRuoloRubricaLocalService rubricaRuoloRubricaLocalService;

	@Reference
	protected RubricaRuoloRubricaPersistence rubricaRuoloRubricaPersistence;

	@Reference
	protected RubricaSitoPersistence rubricaSitoPersistence;

	@Reference
	protected RubricaUtenteSitoPersistence rubricaUtenteSitoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		RubricaRuoloRubricaLocalServiceBaseImpl.class);

}