/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerte.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import it.eng.allerte.model.RubricaCategoria;
import it.eng.allerte.service.RubricaCategoriaLocalService;
import it.eng.allerte.service.persistence.RubricaCanalePersistence;
import it.eng.allerte.service.persistence.RubricaCategoriaPersistence;
import it.eng.allerte.service.persistence.RubricaContattoFinder;
import it.eng.allerte.service.persistence.RubricaContattoPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoFinder;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiFinder;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoNominativiFinder;
import it.eng.allerte.service.persistence.RubricaGruppoNominativiPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoPersistence;
import it.eng.allerte.service.persistence.RubricaLogFinder;
import it.eng.allerte.service.persistence.RubricaLogPersistence;
import it.eng.allerte.service.persistence.RubricaNominativoFinder;
import it.eng.allerte.service.persistence.RubricaNominativoPersistence;
import it.eng.allerte.service.persistence.RubricaPermessiPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloPermessiPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloRubricaPersistence;
import it.eng.allerte.service.persistence.RubricaSitoPersistence;
import it.eng.allerte.service.persistence.RubricaUtenteSitoPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the rubrica categoria local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.allerte.service.impl.RubricaCategoriaLocalServiceImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see it.eng.allerte.service.impl.RubricaCategoriaLocalServiceImpl
 * @generated
 */
public abstract class RubricaCategoriaLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   RubricaCategoriaLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RubricaCategoriaLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.allerte.service.RubricaCategoriaLocalServiceUtil</code>.
	 */

	/**
	 * Adds the rubrica categoria to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaCategoriaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaCategoria the rubrica categoria
	 * @return the rubrica categoria that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RubricaCategoria addRubricaCategoria(
		RubricaCategoria rubricaCategoria) {

		rubricaCategoria.setNew(true);

		return rubricaCategoriaPersistence.update(rubricaCategoria);
	}

	/**
	 * Creates a new rubrica categoria with the primary key. Does not add the rubrica categoria to the database.
	 *
	 * @param ID_CATEGORIA the primary key for the new rubrica categoria
	 * @return the new rubrica categoria
	 */
	@Override
	@Transactional(enabled = false)
	public RubricaCategoria createRubricaCategoria(long ID_CATEGORIA) {
		return rubricaCategoriaPersistence.create(ID_CATEGORIA);
	}

	/**
	 * Deletes the rubrica categoria with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaCategoriaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param ID_CATEGORIA the primary key of the rubrica categoria
	 * @return the rubrica categoria that was removed
	 * @throws PortalException if a rubrica categoria with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RubricaCategoria deleteRubricaCategoria(long ID_CATEGORIA)
		throws PortalException {

		return rubricaCategoriaPersistence.remove(ID_CATEGORIA);
	}

	/**
	 * Deletes the rubrica categoria from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaCategoriaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaCategoria the rubrica categoria
	 * @return the rubrica categoria that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RubricaCategoria deleteRubricaCategoria(
		RubricaCategoria rubricaCategoria) {

		return rubricaCategoriaPersistence.remove(rubricaCategoria);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return rubricaCategoriaPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			RubricaCategoria.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return rubricaCategoriaPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaCategoriaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return rubricaCategoriaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaCategoriaModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return rubricaCategoriaPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return rubricaCategoriaPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return rubricaCategoriaPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public RubricaCategoria fetchRubricaCategoria(long ID_CATEGORIA) {
		return rubricaCategoriaPersistence.fetchByPrimaryKey(ID_CATEGORIA);
	}

	/**
	 * Returns the rubrica categoria with the primary key.
	 *
	 * @param ID_CATEGORIA the primary key of the rubrica categoria
	 * @return the rubrica categoria
	 * @throws PortalException if a rubrica categoria with the primary key could not be found
	 */
	@Override
	public RubricaCategoria getRubricaCategoria(long ID_CATEGORIA)
		throws PortalException {

		return rubricaCategoriaPersistence.findByPrimaryKey(ID_CATEGORIA);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			rubricaCategoriaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RubricaCategoria.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ID_CATEGORIA");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			rubricaCategoriaLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(RubricaCategoria.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"ID_CATEGORIA");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			rubricaCategoriaLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RubricaCategoria.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("ID_CATEGORIA");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rubricaCategoriaPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement RubricaCategoriaLocalServiceImpl#deleteRubricaCategoria(RubricaCategoria) to avoid orphaned data");
		}

		return rubricaCategoriaLocalService.deleteRubricaCategoria(
			(RubricaCategoria)persistedModel);
	}

	@Override
	public BasePersistence<RubricaCategoria> getBasePersistence() {
		return rubricaCategoriaPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rubricaCategoriaPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rubrica categorias.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaCategoriaModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of rubrica categorias
	 * @param end the upper bound of the range of rubrica categorias (not inclusive)
	 * @return the range of rubrica categorias
	 */
	@Override
	public List<RubricaCategoria> getRubricaCategorias(int start, int end) {
		return rubricaCategoriaPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rubrica categorias.
	 *
	 * @return the number of rubrica categorias
	 */
	@Override
	public int getRubricaCategoriasCount() {
		return rubricaCategoriaPersistence.countAll();
	}

	/**
	 * Updates the rubrica categoria in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaCategoriaLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaCategoria the rubrica categoria
	 * @return the rubrica categoria that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RubricaCategoria updateRubricaCategoria(
		RubricaCategoria rubricaCategoria) {

		return rubricaCategoriaPersistence.update(rubricaCategoria);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RubricaCategoriaLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		rubricaCategoriaLocalService = (RubricaCategoriaLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RubricaCategoriaLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RubricaCategoria.class;
	}

	protected String getModelClassName() {
		return RubricaCategoria.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = rubricaCategoriaPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected RubricaCanalePersistence rubricaCanalePersistence;

	protected RubricaCategoriaLocalService rubricaCategoriaLocalService;

	@Reference
	protected RubricaCategoriaPersistence rubricaCategoriaPersistence;

	@Reference
	protected RubricaContattoPersistence rubricaContattoPersistence;

	@Reference
	protected RubricaContattoFinder rubricaContattoFinder;

	@Reference
	protected RubricaGruppoPersistence rubricaGruppoPersistence;

	@Reference
	protected RubricaGruppoFinder rubricaGruppoFinder;

	@Reference
	protected RubricaGruppoGruppiPersistence rubricaGruppoGruppiPersistence;

	@Reference
	protected RubricaGruppoGruppiFinder rubricaGruppoGruppiFinder;

	@Reference
	protected RubricaGruppoNominativiPersistence
		rubricaGruppoNominativiPersistence;

	@Reference
	protected RubricaGruppoNominativiFinder rubricaGruppoNominativiFinder;

	@Reference
	protected RubricaLogPersistence rubricaLogPersistence;

	@Reference
	protected RubricaLogFinder rubricaLogFinder;

	@Reference
	protected RubricaNominativoPersistence rubricaNominativoPersistence;

	@Reference
	protected RubricaNominativoFinder rubricaNominativoFinder;

	@Reference
	protected RubricaPermessiPersistence rubricaPermessiPersistence;

	@Reference
	protected RubricaRuoloPersistence rubricaRuoloPersistence;

	@Reference
	protected RubricaRuoloPermessiPersistence rubricaRuoloPermessiPersistence;

	@Reference
	protected RubricaRuoloRubricaPersistence rubricaRuoloRubricaPersistence;

	@Reference
	protected RubricaSitoPersistence rubricaSitoPersistence;

	@Reference
	protected RubricaUtenteSitoPersistence rubricaUtenteSitoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		RubricaCategoriaLocalServiceBaseImpl.class);

}