/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerte.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import it.eng.allerte.model.RubricaGruppoGruppi;
import it.eng.allerte.service.RubricaGruppoGruppiLocalService;
import it.eng.allerte.service.persistence.RubricaCanalePersistence;
import it.eng.allerte.service.persistence.RubricaCategoriaPersistence;
import it.eng.allerte.service.persistence.RubricaContattoFinder;
import it.eng.allerte.service.persistence.RubricaContattoPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoFinder;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiFinder;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiPK;
import it.eng.allerte.service.persistence.RubricaGruppoGruppiPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoNominativiFinder;
import it.eng.allerte.service.persistence.RubricaGruppoNominativiPersistence;
import it.eng.allerte.service.persistence.RubricaGruppoPersistence;
import it.eng.allerte.service.persistence.RubricaLogFinder;
import it.eng.allerte.service.persistence.RubricaLogPersistence;
import it.eng.allerte.service.persistence.RubricaNominativoFinder;
import it.eng.allerte.service.persistence.RubricaNominativoPersistence;
import it.eng.allerte.service.persistence.RubricaPermessiPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloPermessiPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloPersistence;
import it.eng.allerte.service.persistence.RubricaRuoloRubricaPersistence;
import it.eng.allerte.service.persistence.RubricaSitoPersistence;
import it.eng.allerte.service.persistence.RubricaUtenteSitoPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the rubrica gruppo gruppi local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.allerte.service.impl.RubricaGruppoGruppiLocalServiceImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see it.eng.allerte.service.impl.RubricaGruppoGruppiLocalServiceImpl
 * @generated
 */
public abstract class RubricaGruppoGruppiLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   RubricaGruppoGruppiLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RubricaGruppoGruppiLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.allerte.service.RubricaGruppoGruppiLocalServiceUtil</code>.
	 */

	/**
	 * Adds the rubrica gruppo gruppi to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaGruppoGruppiLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaGruppoGruppi the rubrica gruppo gruppi
	 * @return the rubrica gruppo gruppi that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RubricaGruppoGruppi addRubricaGruppoGruppi(
		RubricaGruppoGruppi rubricaGruppoGruppi) {

		rubricaGruppoGruppi.setNew(true);

		return rubricaGruppoGruppiPersistence.update(rubricaGruppoGruppi);
	}

	/**
	 * Creates a new rubrica gruppo gruppi with the primary key. Does not add the rubrica gruppo gruppi to the database.
	 *
	 * @param rubricaGruppoGruppiPK the primary key for the new rubrica gruppo gruppi
	 * @return the new rubrica gruppo gruppi
	 */
	@Override
	@Transactional(enabled = false)
	public RubricaGruppoGruppi createRubricaGruppoGruppi(
		RubricaGruppoGruppiPK rubricaGruppoGruppiPK) {

		return rubricaGruppoGruppiPersistence.create(rubricaGruppoGruppiPK);
	}

	/**
	 * Deletes the rubrica gruppo gruppi with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaGruppoGruppiLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaGruppoGruppiPK the primary key of the rubrica gruppo gruppi
	 * @return the rubrica gruppo gruppi that was removed
	 * @throws PortalException if a rubrica gruppo gruppi with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RubricaGruppoGruppi deleteRubricaGruppoGruppi(
			RubricaGruppoGruppiPK rubricaGruppoGruppiPK)
		throws PortalException {

		return rubricaGruppoGruppiPersistence.remove(rubricaGruppoGruppiPK);
	}

	/**
	 * Deletes the rubrica gruppo gruppi from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaGruppoGruppiLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaGruppoGruppi the rubrica gruppo gruppi
	 * @return the rubrica gruppo gruppi that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RubricaGruppoGruppi deleteRubricaGruppoGruppi(
		RubricaGruppoGruppi rubricaGruppoGruppi) {

		return rubricaGruppoGruppiPersistence.remove(rubricaGruppoGruppi);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return rubricaGruppoGruppiPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			RubricaGruppoGruppi.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return rubricaGruppoGruppiPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaGruppoGruppiModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return rubricaGruppoGruppiPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaGruppoGruppiModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return rubricaGruppoGruppiPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return rubricaGruppoGruppiPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return rubricaGruppoGruppiPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public RubricaGruppoGruppi fetchRubricaGruppoGruppi(
		RubricaGruppoGruppiPK rubricaGruppoGruppiPK) {

		return rubricaGruppoGruppiPersistence.fetchByPrimaryKey(
			rubricaGruppoGruppiPK);
	}

	/**
	 * Returns the rubrica gruppo gruppi with the primary key.
	 *
	 * @param rubricaGruppoGruppiPK the primary key of the rubrica gruppo gruppi
	 * @return the rubrica gruppo gruppi
	 * @throws PortalException if a rubrica gruppo gruppi with the primary key could not be found
	 */
	@Override
	public RubricaGruppoGruppi getRubricaGruppoGruppi(
			RubricaGruppoGruppiPK rubricaGruppoGruppiPK)
		throws PortalException {

		return rubricaGruppoGruppiPersistence.findByPrimaryKey(
			rubricaGruppoGruppiPK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			rubricaGruppoGruppiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RubricaGruppoGruppi.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.FK_GRUPPO_PADRE");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			rubricaGruppoGruppiLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			RubricaGruppoGruppi.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.FK_GRUPPO_PADRE");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			rubricaGruppoGruppiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RubricaGruppoGruppi.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.FK_GRUPPO_PADRE");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rubricaGruppoGruppiPersistence.create(
			(RubricaGruppoGruppiPK)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement RubricaGruppoGruppiLocalServiceImpl#deleteRubricaGruppoGruppi(RubricaGruppoGruppi) to avoid orphaned data");
		}

		return rubricaGruppoGruppiLocalService.deleteRubricaGruppoGruppi(
			(RubricaGruppoGruppi)persistedModel);
	}

	@Override
	public BasePersistence<RubricaGruppoGruppi> getBasePersistence() {
		return rubricaGruppoGruppiPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rubricaGruppoGruppiPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rubrica gruppo gruppis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerte.model.impl.RubricaGruppoGruppiModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of rubrica gruppo gruppis
	 * @param end the upper bound of the range of rubrica gruppo gruppis (not inclusive)
	 * @return the range of rubrica gruppo gruppis
	 */
	@Override
	public List<RubricaGruppoGruppi> getRubricaGruppoGruppis(
		int start, int end) {

		return rubricaGruppoGruppiPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rubrica gruppo gruppis.
	 *
	 * @return the number of rubrica gruppo gruppis
	 */
	@Override
	public int getRubricaGruppoGruppisCount() {
		return rubricaGruppoGruppiPersistence.countAll();
	}

	/**
	 * Updates the rubrica gruppo gruppi in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RubricaGruppoGruppiLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rubricaGruppoGruppi the rubrica gruppo gruppi
	 * @return the rubrica gruppo gruppi that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RubricaGruppoGruppi updateRubricaGruppoGruppi(
		RubricaGruppoGruppi rubricaGruppoGruppi) {

		return rubricaGruppoGruppiPersistence.update(rubricaGruppoGruppi);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RubricaGruppoGruppiLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		rubricaGruppoGruppiLocalService =
			(RubricaGruppoGruppiLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RubricaGruppoGruppiLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RubricaGruppoGruppi.class;
	}

	protected String getModelClassName() {
		return RubricaGruppoGruppi.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = rubricaGruppoGruppiPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected RubricaCanalePersistence rubricaCanalePersistence;

	@Reference
	protected RubricaCategoriaPersistence rubricaCategoriaPersistence;

	@Reference
	protected RubricaContattoPersistence rubricaContattoPersistence;

	@Reference
	protected RubricaContattoFinder rubricaContattoFinder;

	@Reference
	protected RubricaGruppoPersistence rubricaGruppoPersistence;

	@Reference
	protected RubricaGruppoFinder rubricaGruppoFinder;

	protected RubricaGruppoGruppiLocalService rubricaGruppoGruppiLocalService;

	@Reference
	protected RubricaGruppoGruppiPersistence rubricaGruppoGruppiPersistence;

	@Reference
	protected RubricaGruppoGruppiFinder rubricaGruppoGruppiFinder;

	@Reference
	protected RubricaGruppoNominativiPersistence
		rubricaGruppoNominativiPersistence;

	@Reference
	protected RubricaGruppoNominativiFinder rubricaGruppoNominativiFinder;

	@Reference
	protected RubricaLogPersistence rubricaLogPersistence;

	@Reference
	protected RubricaLogFinder rubricaLogFinder;

	@Reference
	protected RubricaNominativoPersistence rubricaNominativoPersistence;

	@Reference
	protected RubricaNominativoFinder rubricaNominativoFinder;

	@Reference
	protected RubricaPermessiPersistence rubricaPermessiPersistence;

	@Reference
	protected RubricaRuoloPersistence rubricaRuoloPersistence;

	@Reference
	protected RubricaRuoloPermessiPersistence rubricaRuoloPermessiPersistence;

	@Reference
	protected RubricaRuoloRubricaPersistence rubricaRuoloRubricaPersistence;

	@Reference
	protected RubricaSitoPersistence rubricaSitoPersistence;

	@Reference
	protected RubricaUtenteSitoPersistence rubricaUtenteSitoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		RubricaGruppoGruppiLocalServiceBaseImpl.class);

}