/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerta.messages.services.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CounterSms service. Represents a row in the &quot;smsService_CounterSms&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.allerta.messages.services.model.impl.CounterSmsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.allerta.messages.services.model.impl.CounterSmsImpl</code>.
 * </p>
 *
 * @author Giorgianni_F
 * @see CounterSms
 * @generated
 */
@ProviderType
public interface CounterSmsModel extends BaseModel<CounterSms> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a counter sms model instance should use the {@link CounterSms} interface instead.
	 */

	/**
	 * Returns the primary key of this counter sms.
	 *
	 * @return the primary key of this counter sms
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this counter sms.
	 *
	 * @param primaryKey the primary key of this counter sms
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the counter ID of this counter sms.
	 *
	 * @return the counter ID of this counter sms
	 */
	public long getCounterId();

	/**
	 * Sets the counter ID of this counter sms.
	 *
	 * @param counterId the counter ID of this counter sms
	 */
	public void setCounterId(long counterId);

	/**
	 * Returns the date of this counter sms.
	 *
	 * @return the date of this counter sms
	 */
	public Date getDate();

	/**
	 * Sets the date of this counter sms.
	 *
	 * @param date the date of this counter sms
	 */
	public void setDate(Date date);

	/**
	 * Returns the numerosms of this counter sms.
	 *
	 * @return the numerosms of this counter sms
	 */
	public int getNumerosms();

	/**
	 * Sets the numerosms of this counter sms.
	 *
	 * @param numerosms the numerosms of this counter sms
	 */
	public void setNumerosms(int numerosms);

	/**
	 * Returns the nodo of this counter sms.
	 *
	 * @return the nodo of this counter sms
	 */
	@AutoEscape
	public String getNodo();

	/**
	 * Sets the nodo of this counter sms.
	 *
	 * @param nodo the nodo of this counter sms
	 */
	public void setNodo(String nodo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.eng.allerta.messages.services.model.CounterSms counterSms);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.allerta.messages.services.model.CounterSms>
		toCacheModel();

	@Override
	public it.eng.allerta.messages.services.model.CounterSms toEscapedModel();

	@Override
	public it.eng.allerta.messages.services.model.CounterSms toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}