/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.radarMeteo.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import it.eng.radarMeteo.model.Json;
import it.eng.radarMeteo.service.JsonService;
import it.eng.radarMeteo.service.persistence.Comuni_bacini_wsPersistence;
import it.eng.radarMeteo.service.persistence.Comuni_wsFinder;
import it.eng.radarMeteo.service.persistence.Comuni_wsPersistence;
import it.eng.radarMeteo.service.persistence.ImgFinder;
import it.eng.radarMeteo.service.persistence.ImgPersistence;
import it.eng.radarMeteo.service.persistence.JsonFinder;
import it.eng.radarMeteo.service.persistence.JsonPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the json remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.radarMeteo.service.impl.JsonServiceImpl}.
 * </p>
 *
 * @author Francesco
 * @see it.eng.radarMeteo.service.impl.JsonServiceImpl
 * @generated
 */
public abstract class JsonServiceBaseImpl
	extends BaseServiceImpl implements JsonService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>JsonService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.radarMeteo.service.JsonServiceUtil</code>.
	 */

	/**
	 * Returns the comuni_bacini_ws local service.
	 *
	 * @return the comuni_bacini_ws local service
	 */
	public it.eng.radarMeteo.service.Comuni_bacini_wsLocalService
		getComuni_bacini_wsLocalService() {

		return comuni_bacini_wsLocalService;
	}

	/**
	 * Sets the comuni_bacini_ws local service.
	 *
	 * @param comuni_bacini_wsLocalService the comuni_bacini_ws local service
	 */
	public void setComuni_bacini_wsLocalService(
		it.eng.radarMeteo.service.Comuni_bacini_wsLocalService
			comuni_bacini_wsLocalService) {

		this.comuni_bacini_wsLocalService = comuni_bacini_wsLocalService;
	}

	/**
	 * Returns the comuni_bacini_ws remote service.
	 *
	 * @return the comuni_bacini_ws remote service
	 */
	public it.eng.radarMeteo.service.Comuni_bacini_wsService
		getComuni_bacini_wsService() {

		return comuni_bacini_wsService;
	}

	/**
	 * Sets the comuni_bacini_ws remote service.
	 *
	 * @param comuni_bacini_wsService the comuni_bacini_ws remote service
	 */
	public void setComuni_bacini_wsService(
		it.eng.radarMeteo.service.Comuni_bacini_wsService
			comuni_bacini_wsService) {

		this.comuni_bacini_wsService = comuni_bacini_wsService;
	}

	/**
	 * Returns the comuni_bacini_ws persistence.
	 *
	 * @return the comuni_bacini_ws persistence
	 */
	public Comuni_bacini_wsPersistence getComuni_bacini_wsPersistence() {
		return comuni_bacini_wsPersistence;
	}

	/**
	 * Sets the comuni_bacini_ws persistence.
	 *
	 * @param comuni_bacini_wsPersistence the comuni_bacini_ws persistence
	 */
	public void setComuni_bacini_wsPersistence(
		Comuni_bacini_wsPersistence comuni_bacini_wsPersistence) {

		this.comuni_bacini_wsPersistence = comuni_bacini_wsPersistence;
	}

	/**
	 * Returns the comuni_ws local service.
	 *
	 * @return the comuni_ws local service
	 */
	public it.eng.radarMeteo.service.Comuni_wsLocalService
		getComuni_wsLocalService() {

		return comuni_wsLocalService;
	}

	/**
	 * Sets the comuni_ws local service.
	 *
	 * @param comuni_wsLocalService the comuni_ws local service
	 */
	public void setComuni_wsLocalService(
		it.eng.radarMeteo.service.Comuni_wsLocalService comuni_wsLocalService) {

		this.comuni_wsLocalService = comuni_wsLocalService;
	}

	/**
	 * Returns the comuni_ws remote service.
	 *
	 * @return the comuni_ws remote service
	 */
	public it.eng.radarMeteo.service.Comuni_wsService getComuni_wsService() {
		return comuni_wsService;
	}

	/**
	 * Sets the comuni_ws remote service.
	 *
	 * @param comuni_wsService the comuni_ws remote service
	 */
	public void setComuni_wsService(
		it.eng.radarMeteo.service.Comuni_wsService comuni_wsService) {

		this.comuni_wsService = comuni_wsService;
	}

	/**
	 * Returns the comuni_ws persistence.
	 *
	 * @return the comuni_ws persistence
	 */
	public Comuni_wsPersistence getComuni_wsPersistence() {
		return comuni_wsPersistence;
	}

	/**
	 * Sets the comuni_ws persistence.
	 *
	 * @param comuni_wsPersistence the comuni_ws persistence
	 */
	public void setComuni_wsPersistence(
		Comuni_wsPersistence comuni_wsPersistence) {

		this.comuni_wsPersistence = comuni_wsPersistence;
	}

	/**
	 * Returns the comuni_ws finder.
	 *
	 * @return the comuni_ws finder
	 */
	public Comuni_wsFinder getComuni_wsFinder() {
		return comuni_wsFinder;
	}

	/**
	 * Sets the comuni_ws finder.
	 *
	 * @param comuni_wsFinder the comuni_ws finder
	 */
	public void setComuni_wsFinder(Comuni_wsFinder comuni_wsFinder) {
		this.comuni_wsFinder = comuni_wsFinder;
	}

	/**
	 * Returns the img local service.
	 *
	 * @return the img local service
	 */
	public it.eng.radarMeteo.service.ImgLocalService getImgLocalService() {
		return imgLocalService;
	}

	/**
	 * Sets the img local service.
	 *
	 * @param imgLocalService the img local service
	 */
	public void setImgLocalService(
		it.eng.radarMeteo.service.ImgLocalService imgLocalService) {

		this.imgLocalService = imgLocalService;
	}

	/**
	 * Returns the img remote service.
	 *
	 * @return the img remote service
	 */
	public it.eng.radarMeteo.service.ImgService getImgService() {
		return imgService;
	}

	/**
	 * Sets the img remote service.
	 *
	 * @param imgService the img remote service
	 */
	public void setImgService(it.eng.radarMeteo.service.ImgService imgService) {
		this.imgService = imgService;
	}

	/**
	 * Returns the img persistence.
	 *
	 * @return the img persistence
	 */
	public ImgPersistence getImgPersistence() {
		return imgPersistence;
	}

	/**
	 * Sets the img persistence.
	 *
	 * @param imgPersistence the img persistence
	 */
	public void setImgPersistence(ImgPersistence imgPersistence) {
		this.imgPersistence = imgPersistence;
	}

	/**
	 * Returns the img finder.
	 *
	 * @return the img finder
	 */
	public ImgFinder getImgFinder() {
		return imgFinder;
	}

	/**
	 * Sets the img finder.
	 *
	 * @param imgFinder the img finder
	 */
	public void setImgFinder(ImgFinder imgFinder) {
		this.imgFinder = imgFinder;
	}

	/**
	 * Returns the json local service.
	 *
	 * @return the json local service
	 */
	public it.eng.radarMeteo.service.JsonLocalService getJsonLocalService() {
		return jsonLocalService;
	}

	/**
	 * Sets the json local service.
	 *
	 * @param jsonLocalService the json local service
	 */
	public void setJsonLocalService(
		it.eng.radarMeteo.service.JsonLocalService jsonLocalService) {

		this.jsonLocalService = jsonLocalService;
	}

	/**
	 * Returns the json remote service.
	 *
	 * @return the json remote service
	 */
	public JsonService getJsonService() {
		return jsonService;
	}

	/**
	 * Sets the json remote service.
	 *
	 * @param jsonService the json remote service
	 */
	public void setJsonService(JsonService jsonService) {
		this.jsonService = jsonService;
	}

	/**
	 * Returns the json persistence.
	 *
	 * @return the json persistence
	 */
	public JsonPersistence getJsonPersistence() {
		return jsonPersistence;
	}

	/**
	 * Sets the json persistence.
	 *
	 * @param jsonPersistence the json persistence
	 */
	public void setJsonPersistence(JsonPersistence jsonPersistence) {
		this.jsonPersistence = jsonPersistence;
	}

	/**
	 * Returns the json finder.
	 *
	 * @return the json finder
	 */
	public JsonFinder getJsonFinder() {
		return jsonFinder;
	}

	/**
	 * Sets the json finder.
	 *
	 * @param jsonFinder the json finder
	 */
	public void setJsonFinder(JsonFinder jsonFinder) {
		this.jsonFinder = jsonFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService
		getClassNameService() {

		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {

		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {

		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return JsonService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Json.class;
	}

	protected String getModelClassName() {
		return Json.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = jsonPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(
		type = it.eng.radarMeteo.service.Comuni_bacini_wsLocalService.class
	)
	protected it.eng.radarMeteo.service.Comuni_bacini_wsLocalService
		comuni_bacini_wsLocalService;

	@BeanReference(
		type = it.eng.radarMeteo.service.Comuni_bacini_wsService.class
	)
	protected it.eng.radarMeteo.service.Comuni_bacini_wsService
		comuni_bacini_wsService;

	@BeanReference(type = Comuni_bacini_wsPersistence.class)
	protected Comuni_bacini_wsPersistence comuni_bacini_wsPersistence;

	@BeanReference(type = it.eng.radarMeteo.service.Comuni_wsLocalService.class)
	protected it.eng.radarMeteo.service.Comuni_wsLocalService
		comuni_wsLocalService;

	@BeanReference(type = it.eng.radarMeteo.service.Comuni_wsService.class)
	protected it.eng.radarMeteo.service.Comuni_wsService comuni_wsService;

	@BeanReference(type = Comuni_wsPersistence.class)
	protected Comuni_wsPersistence comuni_wsPersistence;

	@BeanReference(type = Comuni_wsFinder.class)
	protected Comuni_wsFinder comuni_wsFinder;

	@BeanReference(type = it.eng.radarMeteo.service.ImgLocalService.class)
	protected it.eng.radarMeteo.service.ImgLocalService imgLocalService;

	@BeanReference(type = it.eng.radarMeteo.service.ImgService.class)
	protected it.eng.radarMeteo.service.ImgService imgService;

	@BeanReference(type = ImgPersistence.class)
	protected ImgPersistence imgPersistence;

	@BeanReference(type = ImgFinder.class)
	protected ImgFinder imgFinder;

	@BeanReference(type = it.eng.radarMeteo.service.JsonLocalService.class)
	protected it.eng.radarMeteo.service.JsonLocalService jsonLocalService;

	@BeanReference(type = JsonService.class)
	protected JsonService jsonService;

	@BeanReference(type = JsonPersistence.class)
	protected JsonPersistence jsonPersistence;

	@BeanReference(type = JsonFinder.class)
	protected JsonFinder jsonFinder;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserService.class
	)
	protected com.liferay.portal.kernel.service.UserService userService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

}