/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package allerta.catasto.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Fonte service. Represents a row in the &quot;CATASTO_Fonte&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>allerta.catasto.model.impl.FonteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>allerta.catasto.model.impl.FonteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Fonte
 * @generated
 */
@ProviderType
public interface FonteModel extends BaseModel<Fonte> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fonte model instance should use the {@link Fonte} interface instead.
	 */

	/**
	 * Returns the primary key of this fonte.
	 *
	 * @return the primary key of this fonte
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fonte.
	 *
	 * @param primaryKey the primary key of this fonte
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this fonte.
	 *
	 * @return the ID of this fonte
	 */
	public long getId();

	/**
	 * Sets the ID of this fonte.
	 *
	 * @param id the ID of this fonte
	 */
	public void setId(long id);

	/**
	 * Returns the descrizione of this fonte.
	 *
	 * @return the descrizione of this fonte
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this fonte.
	 *
	 * @param descrizione the descrizione of this fonte
	 */
	public void setDescrizione(String descrizione);

	@Override
	public Fonte cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}