/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.animaeteo.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.animaeteo.model.AnimeteoImg;
import it.eng.animaeteo.model.AnimeteoImgModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AnimeteoImg service. Represents a row in the &quot;animeteo_AnimeteoImg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AnimeteoImgModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnimeteoImgImpl}.
 * </p>
 *
 * @author UTENTE
 * @see AnimeteoImgImpl
 * @generated
 */
@JSON(strict = true)
public class AnimeteoImgModelImpl
	extends BaseModelImpl<AnimeteoImg> implements AnimeteoImgModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a animeteo img model instance should use the <code>AnimeteoImg</code> interface instead.
	 */
	public static final String TABLE_NAME = "animeteo_AnimeteoImg";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"name", Types.VARCHAR},
		{"type_", Types.VARCHAR}, {"inserted", Types.TIMESTAMP},
		{"data_", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("inserted", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table animeteo_AnimeteoImg (id_ LONG not null primary key,name VARCHAR(75) null,type_ VARCHAR(75) null,inserted DATE null,data_ VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table animeteo_AnimeteoImg";

	public static final String ORDER_BY_JPQL = " ORDER BY animeteoImg.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY animeteo_AnimeteoImg.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TYPE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AnimeteoImgModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnimeteoImg.class;
	}

	@Override
	public String getModelClassName() {
		return AnimeteoImg.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AnimeteoImg, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AnimeteoImg, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnimeteoImg, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AnimeteoImg)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AnimeteoImg, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AnimeteoImg, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AnimeteoImg)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AnimeteoImg, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AnimeteoImg, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AnimeteoImg, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AnimeteoImg, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<AnimeteoImg, Object>>();

			attributeGetterFunctions.put("id", AnimeteoImg::getId);
			attributeGetterFunctions.put("name", AnimeteoImg::getName);
			attributeGetterFunctions.put("type", AnimeteoImg::getType);
			attributeGetterFunctions.put("inserted", AnimeteoImg::getInserted);
			attributeGetterFunctions.put("data", AnimeteoImg::getData);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AnimeteoImg, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AnimeteoImg, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AnimeteoImg, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<AnimeteoImg, Long>)AnimeteoImg::setId);
			attributeSetterBiConsumers.put(
				"name", (BiConsumer<AnimeteoImg, String>)AnimeteoImg::setName);
			attributeSetterBiConsumers.put(
				"type", (BiConsumer<AnimeteoImg, String>)AnimeteoImg::setType);
			attributeSetterBiConsumers.put(
				"inserted",
				(BiConsumer<AnimeteoImg, Date>)AnimeteoImg::setInserted);
			attributeSetterBiConsumers.put(
				"data", (BiConsumer<AnimeteoImg, String>)AnimeteoImg::setData);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalType() {
		return getColumnOriginalValue("type_");
	}

	@JSON
	@Override
	public Date getInserted() {
		return _inserted;
	}

	@Override
	public void setInserted(Date inserted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_inserted = inserted;
	}

	@JSON
	@Override
	public String getData() {
		if (_data == null) {
			return "";
		}
		else {
			return _data;
		}
	}

	@Override
	public void setData(String data) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_data = data;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AnimeteoImg.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnimeteoImg toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AnimeteoImg>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnimeteoImgImpl animeteoImgImpl = new AnimeteoImgImpl();

		animeteoImgImpl.setId(getId());
		animeteoImgImpl.setName(getName());
		animeteoImgImpl.setType(getType());
		animeteoImgImpl.setInserted(getInserted());
		animeteoImgImpl.setData(getData());

		animeteoImgImpl.resetOriginalValues();

		return animeteoImgImpl;
	}

	@Override
	public AnimeteoImg cloneWithOriginalValues() {
		AnimeteoImgImpl animeteoImgImpl = new AnimeteoImgImpl();

		animeteoImgImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		animeteoImgImpl.setName(this.<String>getColumnOriginalValue("name"));
		animeteoImgImpl.setType(this.<String>getColumnOriginalValue("type_"));
		animeteoImgImpl.setInserted(
			this.<Date>getColumnOriginalValue("inserted"));
		animeteoImgImpl.setData(this.<String>getColumnOriginalValue("data_"));

		return animeteoImgImpl;
	}

	@Override
	public int compareTo(AnimeteoImg animeteoImg) {
		int value = 0;

		if (getId() < animeteoImg.getId()) {
			value = -1;
		}
		else if (getId() > animeteoImg.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AnimeteoImg)) {
			return false;
		}

		AnimeteoImg animeteoImg = (AnimeteoImg)object;

		long primaryKey = animeteoImg.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AnimeteoImg> toCacheModel() {
		AnimeteoImgCacheModel animeteoImgCacheModel =
			new AnimeteoImgCacheModel();

		animeteoImgCacheModel.id = getId();

		animeteoImgCacheModel.name = getName();

		String name = animeteoImgCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			animeteoImgCacheModel.name = null;
		}

		animeteoImgCacheModel.type = getType();

		String type = animeteoImgCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			animeteoImgCacheModel.type = null;
		}

		Date inserted = getInserted();

		if (inserted != null) {
			animeteoImgCacheModel.inserted = inserted.getTime();
		}
		else {
			animeteoImgCacheModel.inserted = Long.MIN_VALUE;
		}

		animeteoImgCacheModel.data = getData();

		String data = animeteoImgCacheModel.data;

		if ((data != null) && (data.length() == 0)) {
			animeteoImgCacheModel.data = null;
		}

		return animeteoImgCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AnimeteoImg, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AnimeteoImg, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnimeteoImg, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AnimeteoImg)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AnimeteoImg>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AnimeteoImg.class, ModelWrapper.class);

	}

	private long _id;
	private String _name;
	private String _type;
	private Date _inserted;
	private String _data;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AnimeteoImg, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AnimeteoImg)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("type_", _type);
		_columnOriginalValues.put("inserted", _inserted);
		_columnOriginalValues.put("data_", _data);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");
		attributeNames.put("type_", "type");
		attributeNames.put("data_", "data");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("name", 2L);

		columnBitmasks.put("type_", 4L);

		columnBitmasks.put("inserted", 8L);

		columnBitmasks.put("data_", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AnimeteoImg _escapedModel;

}