/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerte.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.allerte.model.RubricaUtenteSito;
import it.eng.allerte.model.RubricaUtenteSitoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RubricaUtenteSito service. Represents a row in the &quot;rubrica_RubricaUtenteSito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RubricaUtenteSitoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RubricaUtenteSitoImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaUtenteSitoImpl
 * @generated
 */
@JSON(strict = true)
public class RubricaUtenteSitoModelImpl
	extends BaseModelImpl<RubricaUtenteSito> implements RubricaUtenteSitoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rubrica utente sito model instance should use the <code>RubricaUtenteSito</code> interface instead.
	 */
	public static final String TABLE_NAME = "rubrica_RubricaUtenteSito";

	public static final Object[][] TABLE_COLUMNS = {
		{"ID_UTENTE", Types.BIGINT}, {"ID_SITO", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ID_UTENTE", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ID_SITO", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rubrica_RubricaUtenteSito (ID_UTENTE LONG not null primary key,ID_SITO LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table rubrica_RubricaUtenteSito";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rubricaUtenteSito.ID_UTENTE ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rubrica_RubricaUtenteSito.ID_UTENTE ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_UTENTE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RubricaUtenteSitoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ID_UTENTE;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setID_UTENTE(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID_UTENTE;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RubricaUtenteSito.class;
	}

	@Override
	public String getModelClassName() {
		return RubricaUtenteSito.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RubricaUtenteSito, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RubricaUtenteSito, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaUtenteSito, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RubricaUtenteSito)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RubricaUtenteSito, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RubricaUtenteSito, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RubricaUtenteSito)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RubricaUtenteSito, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RubricaUtenteSito, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<RubricaUtenteSito, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<RubricaUtenteSito, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<RubricaUtenteSito, Object>>();

			attributeGetterFunctions.put(
				"ID_UTENTE", RubricaUtenteSito::getID_UTENTE);
			attributeGetterFunctions.put(
				"ID_SITO", RubricaUtenteSito::getID_SITO);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<RubricaUtenteSito, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RubricaUtenteSito, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<RubricaUtenteSito, ?>>();

			attributeSetterBiConsumers.put(
				"ID_UTENTE",
				(BiConsumer<RubricaUtenteSito, Long>)
					RubricaUtenteSito::setID_UTENTE);
			attributeSetterBiConsumers.put(
				"ID_SITO",
				(BiConsumer<RubricaUtenteSito, Long>)
					RubricaUtenteSito::setID_SITO);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getID_UTENTE() {
		return _ID_UTENTE;
	}

	@Override
	public void setID_UTENTE(long ID_UTENTE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ID_UTENTE = ID_UTENTE;
	}

	@JSON
	@Override
	public long getID_SITO() {
		return _ID_SITO;
	}

	@Override
	public void setID_SITO(long ID_SITO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ID_SITO = ID_SITO;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RubricaUtenteSito.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RubricaUtenteSito toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RubricaUtenteSito>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RubricaUtenteSitoImpl rubricaUtenteSitoImpl =
			new RubricaUtenteSitoImpl();

		rubricaUtenteSitoImpl.setID_UTENTE(getID_UTENTE());
		rubricaUtenteSitoImpl.setID_SITO(getID_SITO());

		rubricaUtenteSitoImpl.resetOriginalValues();

		return rubricaUtenteSitoImpl;
	}

	@Override
	public RubricaUtenteSito cloneWithOriginalValues() {
		RubricaUtenteSitoImpl rubricaUtenteSitoImpl =
			new RubricaUtenteSitoImpl();

		rubricaUtenteSitoImpl.setID_UTENTE(
			this.<Long>getColumnOriginalValue("ID_UTENTE"));
		rubricaUtenteSitoImpl.setID_SITO(
			this.<Long>getColumnOriginalValue("ID_SITO"));

		return rubricaUtenteSitoImpl;
	}

	@Override
	public int compareTo(RubricaUtenteSito rubricaUtenteSito) {
		long primaryKey = rubricaUtenteSito.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RubricaUtenteSito)) {
			return false;
		}

		RubricaUtenteSito rubricaUtenteSito = (RubricaUtenteSito)object;

		long primaryKey = rubricaUtenteSito.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RubricaUtenteSito> toCacheModel() {
		RubricaUtenteSitoCacheModel rubricaUtenteSitoCacheModel =
			new RubricaUtenteSitoCacheModel();

		rubricaUtenteSitoCacheModel.ID_UTENTE = getID_UTENTE();

		rubricaUtenteSitoCacheModel.ID_SITO = getID_SITO();

		return rubricaUtenteSitoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RubricaUtenteSito, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RubricaUtenteSito, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaUtenteSito, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RubricaUtenteSito)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RubricaUtenteSito>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RubricaUtenteSito.class, ModelWrapper.class);

	}

	private long _ID_UTENTE;

	private long _ID_SITO;

	public <T> T getColumnValue(String columnName) {
		Function<RubricaUtenteSito, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RubricaUtenteSito)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ID_UTENTE", _ID_UTENTE);
		_columnOriginalValues.put("ID_SITO", _ID_SITO);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ID_UTENTE", 1L);

		columnBitmasks.put("ID_SITO", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RubricaUtenteSito _escapedModel;

}