/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerte.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.allerte.model.RubricaSito;
import it.eng.allerte.model.RubricaSitoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RubricaSito service. Represents a row in the &quot;rubrica_RubricaSito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RubricaSitoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RubricaSitoImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaSitoImpl
 * @generated
 */
@JSON(strict = true)
public class RubricaSitoModelImpl
	extends BaseModelImpl<RubricaSito> implements RubricaSitoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rubrica sito model instance should use the <code>RubricaSito</code> interface instead.
	 */
	public static final String TABLE_NAME = "rubrica_RubricaSito";

	public static final Object[][] TABLE_COLUMNS = {
		{"ID_SITO", Types.BIGINT}, {"NOME", Types.VARCHAR},
		{"FK_LIFERAY_SITE", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ID_SITO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NOME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_LIFERAY_SITE", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rubrica_RubricaSito (ID_SITO LONG not null primary key,NOME VARCHAR(75) null,FK_LIFERAY_SITE LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table rubrica_RubricaSito";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rubricaSito.ID_SITO ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rubrica_RubricaSito.ID_SITO ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FK_LIFERAY_SITE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_SITO_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RubricaSitoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ID_SITO;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setID_SITO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID_SITO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RubricaSito.class;
	}

	@Override
	public String getModelClassName() {
		return RubricaSito.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RubricaSito, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RubricaSito, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaSito, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RubricaSito)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RubricaSito, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RubricaSito, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RubricaSito)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RubricaSito, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RubricaSito, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<RubricaSito, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<RubricaSito, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<RubricaSito, Object>>();

			attributeGetterFunctions.put("ID_SITO", RubricaSito::getID_SITO);
			attributeGetterFunctions.put("NOME", RubricaSito::getNOME);
			attributeGetterFunctions.put(
				"FK_LIFERAY_SITE", RubricaSito::getFK_LIFERAY_SITE);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<RubricaSito, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RubricaSito, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<RubricaSito, ?>>();

			attributeSetterBiConsumers.put(
				"ID_SITO",
				(BiConsumer<RubricaSito, Long>)RubricaSito::setID_SITO);
			attributeSetterBiConsumers.put(
				"NOME", (BiConsumer<RubricaSito, String>)RubricaSito::setNOME);
			attributeSetterBiConsumers.put(
				"FK_LIFERAY_SITE",
				(BiConsumer<RubricaSito, Long>)RubricaSito::setFK_LIFERAY_SITE);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getID_SITO() {
		return _ID_SITO;
	}

	@Override
	public void setID_SITO(long ID_SITO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ID_SITO = ID_SITO;
	}

	@JSON
	@Override
	public String getNOME() {
		if (_NOME == null) {
			return "";
		}
		else {
			return _NOME;
		}
	}

	@Override
	public void setNOME(String NOME) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NOME = NOME;
	}

	@JSON
	@Override
	public long getFK_LIFERAY_SITE() {
		return _FK_LIFERAY_SITE;
	}

	@Override
	public void setFK_LIFERAY_SITE(long FK_LIFERAY_SITE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_LIFERAY_SITE = FK_LIFERAY_SITE;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFK_LIFERAY_SITE() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("FK_LIFERAY_SITE"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RubricaSito.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RubricaSito toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RubricaSito>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RubricaSitoImpl rubricaSitoImpl = new RubricaSitoImpl();

		rubricaSitoImpl.setID_SITO(getID_SITO());
		rubricaSitoImpl.setNOME(getNOME());
		rubricaSitoImpl.setFK_LIFERAY_SITE(getFK_LIFERAY_SITE());

		rubricaSitoImpl.resetOriginalValues();

		return rubricaSitoImpl;
	}

	@Override
	public RubricaSito cloneWithOriginalValues() {
		RubricaSitoImpl rubricaSitoImpl = new RubricaSitoImpl();

		rubricaSitoImpl.setID_SITO(
			this.<Long>getColumnOriginalValue("ID_SITO"));
		rubricaSitoImpl.setNOME(this.<String>getColumnOriginalValue("NOME"));
		rubricaSitoImpl.setFK_LIFERAY_SITE(
			this.<Long>getColumnOriginalValue("FK_LIFERAY_SITE"));

		return rubricaSitoImpl;
	}

	@Override
	public int compareTo(RubricaSito rubricaSito) {
		long primaryKey = rubricaSito.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RubricaSito)) {
			return false;
		}

		RubricaSito rubricaSito = (RubricaSito)object;

		long primaryKey = rubricaSito.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RubricaSito> toCacheModel() {
		RubricaSitoCacheModel rubricaSitoCacheModel =
			new RubricaSitoCacheModel();

		rubricaSitoCacheModel.ID_SITO = getID_SITO();

		rubricaSitoCacheModel.NOME = getNOME();

		String NOME = rubricaSitoCacheModel.NOME;

		if ((NOME != null) && (NOME.length() == 0)) {
			rubricaSitoCacheModel.NOME = null;
		}

		rubricaSitoCacheModel.FK_LIFERAY_SITE = getFK_LIFERAY_SITE();

		return rubricaSitoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RubricaSito, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RubricaSito, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaSito, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((RubricaSito)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RubricaSito>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RubricaSito.class, ModelWrapper.class);

	}

	private long _ID_SITO;

	private String _NOME;

	private long _FK_LIFERAY_SITE;

	public <T> T getColumnValue(String columnName) {
		Function<RubricaSito, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RubricaSito)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ID_SITO", _ID_SITO);
		_columnOriginalValues.put("NOME", _NOME);
		_columnOriginalValues.put("FK_LIFERAY_SITE", _FK_LIFERAY_SITE);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ID_SITO", 1L);

		columnBitmasks.put("NOME", 2L);

		columnBitmasks.put("FK_LIFERAY_SITE", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RubricaSito _escapedModel;

}