/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerte.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import it.eng.allerte.model.RubricaPermessi;
import it.eng.allerte.model.RubricaPermessiModel;
import it.eng.allerte.model.RubricaPermessiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RubricaPermessi service. Represents a row in the &quot;rubrica_RubricaPermessi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>RubricaPermessiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RubricaPermessiImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaPermessiImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RubricaPermessiModelImpl
	extends BaseModelImpl<RubricaPermessi> implements RubricaPermessiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rubrica permessi model instance should use the <code>RubricaPermessi</code> interface instead.
	 */
	public static final String TABLE_NAME = "rubrica_RubricaPermessi";

	public static final Object[][] TABLE_COLUMNS = {
		{"ID_PERMESSO", Types.VARCHAR}, {"NOME_PERMESSO", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ID_PERMESSO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("NOME_PERMESSO", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rubrica_RubricaPermessi (ID_PERMESSO VARCHAR(75) not null primary key,NOME_PERMESSO VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table rubrica_RubricaPermessi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rubricaPermessi.ID_PERMESSO ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rubrica_RubricaPermessi.ID_PERMESSO ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.rubrica.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.it.eng.allerte.model.RubricaPermessi"),
		false);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.rubrica.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.it.eng.allerte.model.RubricaPermessi"),
		false);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RubricaPermessi toModel(RubricaPermessiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RubricaPermessi model = new RubricaPermessiImpl();

		model.setID_PERMESSO(soapModel.getID_PERMESSO());
		model.setNOME_PERMESSO(soapModel.getNOME_PERMESSO());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RubricaPermessi> toModels(
		RubricaPermessiSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RubricaPermessi> models = new ArrayList<RubricaPermessi>(
			soapModels.length);

		for (RubricaPermessiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		it.eng.rubrica.service.util.ServiceProps.get(
			"lock.expiration.time.it.eng.allerte.model.RubricaPermessi"));

	public RubricaPermessiModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _ID_PERMESSO;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setID_PERMESSO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID_PERMESSO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return RubricaPermessi.class;
	}

	@Override
	public String getModelClassName() {
		return RubricaPermessi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RubricaPermessi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RubricaPermessi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaPermessi, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RubricaPermessi)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RubricaPermessi, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RubricaPermessi, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RubricaPermessi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RubricaPermessi, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RubricaPermessi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<RubricaPermessi, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RubricaPermessi, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RubricaPermessi, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<RubricaPermessi, Object>>();
		Map<String, BiConsumer<RubricaPermessi, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<RubricaPermessi, ?>>();

		attributeGetterFunctions.put(
			"ID_PERMESSO",
			new Function<RubricaPermessi, Object>() {

				@Override
				public Object apply(RubricaPermessi rubricaPermessi) {
					return rubricaPermessi.getID_PERMESSO();
				}

			});
		attributeSetterBiConsumers.put(
			"ID_PERMESSO",
			new BiConsumer<RubricaPermessi, Object>() {

				@Override
				public void accept(
					RubricaPermessi rubricaPermessi, Object ID_PERMESSO) {

					rubricaPermessi.setID_PERMESSO((String)ID_PERMESSO);
				}

			});
		attributeGetterFunctions.put(
			"NOME_PERMESSO",
			new Function<RubricaPermessi, Object>() {

				@Override
				public Object apply(RubricaPermessi rubricaPermessi) {
					return rubricaPermessi.getNOME_PERMESSO();
				}

			});
		attributeSetterBiConsumers.put(
			"NOME_PERMESSO",
			new BiConsumer<RubricaPermessi, Object>() {

				@Override
				public void accept(
					RubricaPermessi rubricaPermessi, Object NOME_PERMESSO) {

					rubricaPermessi.setNOME_PERMESSO((String)NOME_PERMESSO);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getID_PERMESSO() {
		if (_ID_PERMESSO == null) {
			return "";
		}
		else {
			return _ID_PERMESSO;
		}
	}

	@Override
	public void setID_PERMESSO(String ID_PERMESSO) {
		_ID_PERMESSO = ID_PERMESSO;
	}

	@JSON
	@Override
	public String getNOME_PERMESSO() {
		if (_NOME_PERMESSO == null) {
			return "";
		}
		else {
			return _NOME_PERMESSO;
		}
	}

	@Override
	public void setNOME_PERMESSO(String NOME_PERMESSO) {
		_NOME_PERMESSO = NOME_PERMESSO;
	}

	@Override
	public RubricaPermessi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RubricaPermessi)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RubricaPermessiImpl rubricaPermessiImpl = new RubricaPermessiImpl();

		rubricaPermessiImpl.setID_PERMESSO(getID_PERMESSO());
		rubricaPermessiImpl.setNOME_PERMESSO(getNOME_PERMESSO());

		rubricaPermessiImpl.resetOriginalValues();

		return rubricaPermessiImpl;
	}

	@Override
	public int compareTo(RubricaPermessi rubricaPermessi) {
		String primaryKey = rubricaPermessi.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RubricaPermessi)) {
			return false;
		}

		RubricaPermessi rubricaPermessi = (RubricaPermessi)obj;

		String primaryKey = rubricaPermessi.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RubricaPermessi> toCacheModel() {
		RubricaPermessiCacheModel rubricaPermessiCacheModel =
			new RubricaPermessiCacheModel();

		rubricaPermessiCacheModel.ID_PERMESSO = getID_PERMESSO();

		String ID_PERMESSO = rubricaPermessiCacheModel.ID_PERMESSO;

		if ((ID_PERMESSO != null) && (ID_PERMESSO.length() == 0)) {
			rubricaPermessiCacheModel.ID_PERMESSO = null;
		}

		rubricaPermessiCacheModel.NOME_PERMESSO = getNOME_PERMESSO();

		String NOME_PERMESSO = rubricaPermessiCacheModel.NOME_PERMESSO;

		if ((NOME_PERMESSO != null) && (NOME_PERMESSO.length() == 0)) {
			rubricaPermessiCacheModel.NOME_PERMESSO = null;
		}

		return rubricaPermessiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RubricaPermessi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RubricaPermessi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaPermessi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RubricaPermessi)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RubricaPermessi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RubricaPermessi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaPermessi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RubricaPermessi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		RubricaPermessi.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		RubricaPermessi.class, ModelWrapper.class
	};

	private String _ID_PERMESSO;

	private String _NOME_PERMESSO;

	private RubricaPermessi _escapedModel;

}