/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerte.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.allerte.model.RubricaGruppo;
import it.eng.allerte.model.RubricaGruppoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RubricaGruppo service. Represents a row in the &quot;rubrica_RubricaGruppo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RubricaGruppoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RubricaGruppoImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaGruppoImpl
 * @generated
 */
@JSON(strict = true)
public class RubricaGruppoModelImpl
	extends BaseModelImpl<RubricaGruppo> implements RubricaGruppoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rubrica gruppo model instance should use the <code>RubricaGruppo</code> interface instead.
	 */
	public static final String TABLE_NAME = "rubrica_RubricaGruppo";

	public static final Object[][] TABLE_COLUMNS = {
		{"ID_GRUPPO", Types.BIGINT}, {"NOME", Types.VARCHAR},
		{"FK_SITO_PROPRIETARIO", Types.BIGINT}, {"NOTE", Types.VARCHAR},
		{"FK_UTENTE_CREAZIONE", Types.BIGINT},
		{"DATA_CREAZIONE", Types.TIMESTAMP},
		{"FK_UTENTE_MODIFICA", Types.BIGINT},
		{"DATA_MODIFICA", Types.TIMESTAMP}, {"DISABLED", Types.BOOLEAN},
		{"FK_CATEGORIA", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ID_GRUPPO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NOME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_SITO_PROPRIETARIO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NOTE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_UTENTE_CREAZIONE", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DATA_CREAZIONE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("FK_UTENTE_MODIFICA", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DATA_MODIFICA", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DISABLED", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("FK_CATEGORIA", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rubrica_RubricaGruppo (ID_GRUPPO LONG not null primary key,NOME VARCHAR(75) null,FK_SITO_PROPRIETARIO LONG,NOTE VARCHAR(75) null,FK_UTENTE_CREAZIONE LONG,DATA_CREAZIONE DATE null,FK_UTENTE_MODIFICA LONG,DATA_MODIFICA DATE null,DISABLED BOOLEAN,FK_CATEGORIA LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table rubrica_RubricaGruppo";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rubricaGruppo.ID_GRUPPO ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rubrica_RubricaGruppo.ID_GRUPPO ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DISABLED_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FK_CATEGORIA_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FK_SITO_PROPRIETARIO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_GRUPPO_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RubricaGruppoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ID_GRUPPO;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setID_GRUPPO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID_GRUPPO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RubricaGruppo.class;
	}

	@Override
	public String getModelClassName() {
		return RubricaGruppo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RubricaGruppo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RubricaGruppo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaGruppo, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RubricaGruppo)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RubricaGruppo, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RubricaGruppo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RubricaGruppo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RubricaGruppo, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RubricaGruppo, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<RubricaGruppo, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<RubricaGruppo, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<RubricaGruppo, Object>>();

			attributeGetterFunctions.put(
				"ID_GRUPPO", RubricaGruppo::getID_GRUPPO);
			attributeGetterFunctions.put("NOME", RubricaGruppo::getNOME);
			attributeGetterFunctions.put(
				"FK_SITO_PROPRIETARIO", RubricaGruppo::getFK_SITO_PROPRIETARIO);
			attributeGetterFunctions.put("NOTE", RubricaGruppo::getNOTE);
			attributeGetterFunctions.put(
				"FK_UTENTE_CREAZIONE", RubricaGruppo::getFK_UTENTE_CREAZIONE);
			attributeGetterFunctions.put(
				"DATA_CREAZIONE", RubricaGruppo::getDATA_CREAZIONE);
			attributeGetterFunctions.put(
				"FK_UTENTE_MODIFICA", RubricaGruppo::getFK_UTENTE_MODIFICA);
			attributeGetterFunctions.put(
				"DATA_MODIFICA", RubricaGruppo::getDATA_MODIFICA);
			attributeGetterFunctions.put(
				"DISABLED", RubricaGruppo::getDISABLED);
			attributeGetterFunctions.put(
				"FK_CATEGORIA", RubricaGruppo::getFK_CATEGORIA);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<RubricaGruppo, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RubricaGruppo, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<RubricaGruppo, ?>>();

			attributeSetterBiConsumers.put(
				"ID_GRUPPO",
				(BiConsumer<RubricaGruppo, Long>)RubricaGruppo::setID_GRUPPO);
			attributeSetterBiConsumers.put(
				"NOME",
				(BiConsumer<RubricaGruppo, String>)RubricaGruppo::setNOME);
			attributeSetterBiConsumers.put(
				"FK_SITO_PROPRIETARIO",
				(BiConsumer<RubricaGruppo, Long>)
					RubricaGruppo::setFK_SITO_PROPRIETARIO);
			attributeSetterBiConsumers.put(
				"NOTE",
				(BiConsumer<RubricaGruppo, String>)RubricaGruppo::setNOTE);
			attributeSetterBiConsumers.put(
				"FK_UTENTE_CREAZIONE",
				(BiConsumer<RubricaGruppo, Long>)
					RubricaGruppo::setFK_UTENTE_CREAZIONE);
			attributeSetterBiConsumers.put(
				"DATA_CREAZIONE",
				(BiConsumer<RubricaGruppo, Date>)
					RubricaGruppo::setDATA_CREAZIONE);
			attributeSetterBiConsumers.put(
				"FK_UTENTE_MODIFICA",
				(BiConsumer<RubricaGruppo, Long>)
					RubricaGruppo::setFK_UTENTE_MODIFICA);
			attributeSetterBiConsumers.put(
				"DATA_MODIFICA",
				(BiConsumer<RubricaGruppo, Date>)
					RubricaGruppo::setDATA_MODIFICA);
			attributeSetterBiConsumers.put(
				"DISABLED",
				(BiConsumer<RubricaGruppo, Boolean>)RubricaGruppo::setDISABLED);
			attributeSetterBiConsumers.put(
				"FK_CATEGORIA",
				(BiConsumer<RubricaGruppo, Long>)
					RubricaGruppo::setFK_CATEGORIA);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getID_GRUPPO() {
		return _ID_GRUPPO;
	}

	@Override
	public void setID_GRUPPO(long ID_GRUPPO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ID_GRUPPO = ID_GRUPPO;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalID_GRUPPO() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("ID_GRUPPO"));
	}

	@JSON
	@Override
	public String getNOME() {
		if (_NOME == null) {
			return "";
		}
		else {
			return _NOME;
		}
	}

	@Override
	public void setNOME(String NOME) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NOME = NOME;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNOME() {
		return getColumnOriginalValue("NOME");
	}

	@JSON
	@Override
	public long getFK_SITO_PROPRIETARIO() {
		return _FK_SITO_PROPRIETARIO;
	}

	@Override
	public void setFK_SITO_PROPRIETARIO(long FK_SITO_PROPRIETARIO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_SITO_PROPRIETARIO = FK_SITO_PROPRIETARIO;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFK_SITO_PROPRIETARIO() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("FK_SITO_PROPRIETARIO"));
	}

	@JSON
	@Override
	public String getNOTE() {
		if (_NOTE == null) {
			return "";
		}
		else {
			return _NOTE;
		}
	}

	@Override
	public void setNOTE(String NOTE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NOTE = NOTE;
	}

	@JSON
	@Override
	public long getFK_UTENTE_CREAZIONE() {
		return _FK_UTENTE_CREAZIONE;
	}

	@Override
	public void setFK_UTENTE_CREAZIONE(long FK_UTENTE_CREAZIONE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_UTENTE_CREAZIONE = FK_UTENTE_CREAZIONE;
	}

	@JSON
	@Override
	public Date getDATA_CREAZIONE() {
		return _DATA_CREAZIONE;
	}

	@Override
	public void setDATA_CREAZIONE(Date DATA_CREAZIONE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DATA_CREAZIONE = DATA_CREAZIONE;
	}

	@JSON
	@Override
	public long getFK_UTENTE_MODIFICA() {
		return _FK_UTENTE_MODIFICA;
	}

	@Override
	public void setFK_UTENTE_MODIFICA(long FK_UTENTE_MODIFICA) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_UTENTE_MODIFICA = FK_UTENTE_MODIFICA;
	}

	@JSON
	@Override
	public Date getDATA_MODIFICA() {
		return _DATA_MODIFICA;
	}

	@Override
	public void setDATA_MODIFICA(Date DATA_MODIFICA) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DATA_MODIFICA = DATA_MODIFICA;
	}

	@JSON
	@Override
	public boolean getDISABLED() {
		return _DISABLED;
	}

	@JSON
	@Override
	public boolean isDISABLED() {
		return _DISABLED;
	}

	@Override
	public void setDISABLED(boolean DISABLED) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DISABLED = DISABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalDISABLED() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("DISABLED"));
	}

	@JSON
	@Override
	public long getFK_CATEGORIA() {
		return _FK_CATEGORIA;
	}

	@Override
	public void setFK_CATEGORIA(long FK_CATEGORIA) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_CATEGORIA = FK_CATEGORIA;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFK_CATEGORIA() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("FK_CATEGORIA"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RubricaGruppo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RubricaGruppo toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RubricaGruppo>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RubricaGruppoImpl rubricaGruppoImpl = new RubricaGruppoImpl();

		rubricaGruppoImpl.setID_GRUPPO(getID_GRUPPO());
		rubricaGruppoImpl.setNOME(getNOME());
		rubricaGruppoImpl.setFK_SITO_PROPRIETARIO(getFK_SITO_PROPRIETARIO());
		rubricaGruppoImpl.setNOTE(getNOTE());
		rubricaGruppoImpl.setFK_UTENTE_CREAZIONE(getFK_UTENTE_CREAZIONE());
		rubricaGruppoImpl.setDATA_CREAZIONE(getDATA_CREAZIONE());
		rubricaGruppoImpl.setFK_UTENTE_MODIFICA(getFK_UTENTE_MODIFICA());
		rubricaGruppoImpl.setDATA_MODIFICA(getDATA_MODIFICA());
		rubricaGruppoImpl.setDISABLED(isDISABLED());
		rubricaGruppoImpl.setFK_CATEGORIA(getFK_CATEGORIA());

		rubricaGruppoImpl.resetOriginalValues();

		return rubricaGruppoImpl;
	}

	@Override
	public RubricaGruppo cloneWithOriginalValues() {
		RubricaGruppoImpl rubricaGruppoImpl = new RubricaGruppoImpl();

		rubricaGruppoImpl.setID_GRUPPO(
			this.<Long>getColumnOriginalValue("ID_GRUPPO"));
		rubricaGruppoImpl.setNOME(this.<String>getColumnOriginalValue("NOME"));
		rubricaGruppoImpl.setFK_SITO_PROPRIETARIO(
			this.<Long>getColumnOriginalValue("FK_SITO_PROPRIETARIO"));
		rubricaGruppoImpl.setNOTE(this.<String>getColumnOriginalValue("NOTE"));
		rubricaGruppoImpl.setFK_UTENTE_CREAZIONE(
			this.<Long>getColumnOriginalValue("FK_UTENTE_CREAZIONE"));
		rubricaGruppoImpl.setDATA_CREAZIONE(
			this.<Date>getColumnOriginalValue("DATA_CREAZIONE"));
		rubricaGruppoImpl.setFK_UTENTE_MODIFICA(
			this.<Long>getColumnOriginalValue("FK_UTENTE_MODIFICA"));
		rubricaGruppoImpl.setDATA_MODIFICA(
			this.<Date>getColumnOriginalValue("DATA_MODIFICA"));
		rubricaGruppoImpl.setDISABLED(
			this.<Boolean>getColumnOriginalValue("DISABLED"));
		rubricaGruppoImpl.setFK_CATEGORIA(
			this.<Long>getColumnOriginalValue("FK_CATEGORIA"));

		return rubricaGruppoImpl;
	}

	@Override
	public int compareTo(RubricaGruppo rubricaGruppo) {
		long primaryKey = rubricaGruppo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RubricaGruppo)) {
			return false;
		}

		RubricaGruppo rubricaGruppo = (RubricaGruppo)object;

		long primaryKey = rubricaGruppo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RubricaGruppo> toCacheModel() {
		RubricaGruppoCacheModel rubricaGruppoCacheModel =
			new RubricaGruppoCacheModel();

		rubricaGruppoCacheModel.ID_GRUPPO = getID_GRUPPO();

		rubricaGruppoCacheModel.NOME = getNOME();

		String NOME = rubricaGruppoCacheModel.NOME;

		if ((NOME != null) && (NOME.length() == 0)) {
			rubricaGruppoCacheModel.NOME = null;
		}

		rubricaGruppoCacheModel.FK_SITO_PROPRIETARIO =
			getFK_SITO_PROPRIETARIO();

		rubricaGruppoCacheModel.NOTE = getNOTE();

		String NOTE = rubricaGruppoCacheModel.NOTE;

		if ((NOTE != null) && (NOTE.length() == 0)) {
			rubricaGruppoCacheModel.NOTE = null;
		}

		rubricaGruppoCacheModel.FK_UTENTE_CREAZIONE = getFK_UTENTE_CREAZIONE();

		Date DATA_CREAZIONE = getDATA_CREAZIONE();

		if (DATA_CREAZIONE != null) {
			rubricaGruppoCacheModel.DATA_CREAZIONE = DATA_CREAZIONE.getTime();
		}
		else {
			rubricaGruppoCacheModel.DATA_CREAZIONE = Long.MIN_VALUE;
		}

		rubricaGruppoCacheModel.FK_UTENTE_MODIFICA = getFK_UTENTE_MODIFICA();

		Date DATA_MODIFICA = getDATA_MODIFICA();

		if (DATA_MODIFICA != null) {
			rubricaGruppoCacheModel.DATA_MODIFICA = DATA_MODIFICA.getTime();
		}
		else {
			rubricaGruppoCacheModel.DATA_MODIFICA = Long.MIN_VALUE;
		}

		rubricaGruppoCacheModel.DISABLED = isDISABLED();

		rubricaGruppoCacheModel.FK_CATEGORIA = getFK_CATEGORIA();

		return rubricaGruppoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RubricaGruppo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RubricaGruppo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaGruppo, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((RubricaGruppo)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RubricaGruppo>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RubricaGruppo.class, ModelWrapper.class);

	}

	private long _ID_GRUPPO;

	private String _NOME;

	private long _FK_SITO_PROPRIETARIO;

	private String _NOTE;

	private long _FK_UTENTE_CREAZIONE;

	private Date _DATA_CREAZIONE;

	private long _FK_UTENTE_MODIFICA;

	private Date _DATA_MODIFICA;

	private boolean _DISABLED;

	private long _FK_CATEGORIA;

	public <T> T getColumnValue(String columnName) {
		Function<RubricaGruppo, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RubricaGruppo)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ID_GRUPPO", _ID_GRUPPO);
		_columnOriginalValues.put("NOME", _NOME);
		_columnOriginalValues.put(
			"FK_SITO_PROPRIETARIO", _FK_SITO_PROPRIETARIO);
		_columnOriginalValues.put("NOTE", _NOTE);
		_columnOriginalValues.put("FK_UTENTE_CREAZIONE", _FK_UTENTE_CREAZIONE);
		_columnOriginalValues.put("DATA_CREAZIONE", _DATA_CREAZIONE);
		_columnOriginalValues.put("FK_UTENTE_MODIFICA", _FK_UTENTE_MODIFICA);
		_columnOriginalValues.put("DATA_MODIFICA", _DATA_MODIFICA);
		_columnOriginalValues.put("DISABLED", _DISABLED);
		_columnOriginalValues.put("FK_CATEGORIA", _FK_CATEGORIA);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ID_GRUPPO", 1L);

		columnBitmasks.put("NOME", 2L);

		columnBitmasks.put("FK_SITO_PROPRIETARIO", 4L);

		columnBitmasks.put("NOTE", 8L);

		columnBitmasks.put("FK_UTENTE_CREAZIONE", 16L);

		columnBitmasks.put("DATA_CREAZIONE", 32L);

		columnBitmasks.put("FK_UTENTE_MODIFICA", 64L);

		columnBitmasks.put("DATA_MODIFICA", 128L);

		columnBitmasks.put("DISABLED", 256L);

		columnBitmasks.put("FK_CATEGORIA", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RubricaGruppo _escapedModel;

}