/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerte.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import it.eng.allerte.model.RubricaRuoloRubrica;
import it.eng.allerte.model.RubricaRuoloRubricaModel;
import it.eng.allerte.model.RubricaRuoloRubricaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RubricaRuoloRubrica service. Represents a row in the &quot;rubrica_RubricaRuoloRubrica&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>RubricaRuoloRubricaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RubricaRuoloRubricaImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaRuoloRubricaImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RubricaRuoloRubricaModelImpl
	extends BaseModelImpl<RubricaRuoloRubrica>
	implements RubricaRuoloRubricaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rubrica ruolo rubrica model instance should use the <code>RubricaRuoloRubrica</code> interface instead.
	 */
	public static final String TABLE_NAME = "rubrica_RubricaRuoloRubrica";

	public static final Object[][] TABLE_COLUMNS = {
		{"ID_RUOLO", Types.BIGINT}, {"DESCRIZIONE", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ID_RUOLO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("DESCRIZIONE", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table rubrica_RubricaRuoloRubrica (ID_RUOLO LONG not null primary key,DESCRIZIONE VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table rubrica_RubricaRuoloRubrica";

	public static final String ORDER_BY_JPQL =
		" ORDER BY rubricaRuoloRubrica.ID_RUOLO ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY rubrica_RubricaRuoloRubrica.ID_RUOLO ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.rubrica.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.it.eng.allerte.model.RubricaRuoloRubrica"),
		false);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.rubrica.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.it.eng.allerte.model.RubricaRuoloRubrica"),
		false);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RubricaRuoloRubrica toModel(
		RubricaRuoloRubricaSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		RubricaRuoloRubrica model = new RubricaRuoloRubricaImpl();

		model.setID_RUOLO(soapModel.getID_RUOLO());
		model.setDESCRIZIONE(soapModel.getDESCRIZIONE());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RubricaRuoloRubrica> toModels(
		RubricaRuoloRubricaSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<RubricaRuoloRubrica> models = new ArrayList<RubricaRuoloRubrica>(
			soapModels.length);

		for (RubricaRuoloRubricaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		it.eng.rubrica.service.util.ServiceProps.get(
			"lock.expiration.time.it.eng.allerte.model.RubricaRuoloRubrica"));

	public RubricaRuoloRubricaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ID_RUOLO;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setID_RUOLO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID_RUOLO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RubricaRuoloRubrica.class;
	}

	@Override
	public String getModelClassName() {
		return RubricaRuoloRubrica.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RubricaRuoloRubrica, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RubricaRuoloRubrica, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaRuoloRubrica, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RubricaRuoloRubrica)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RubricaRuoloRubrica, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RubricaRuoloRubrica, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RubricaRuoloRubrica)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RubricaRuoloRubrica, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RubricaRuoloRubrica, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<RubricaRuoloRubrica, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<RubricaRuoloRubrica, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<RubricaRuoloRubrica, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<RubricaRuoloRubrica, Object>>();
		Map<String, BiConsumer<RubricaRuoloRubrica, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<RubricaRuoloRubrica, ?>>();

		attributeGetterFunctions.put(
			"ID_RUOLO",
			new Function<RubricaRuoloRubrica, Object>() {

				@Override
				public Object apply(RubricaRuoloRubrica rubricaRuoloRubrica) {
					return rubricaRuoloRubrica.getID_RUOLO();
				}

			});
		attributeSetterBiConsumers.put(
			"ID_RUOLO",
			new BiConsumer<RubricaRuoloRubrica, Object>() {

				@Override
				public void accept(
					RubricaRuoloRubrica rubricaRuoloRubrica, Object ID_RUOLO) {

					rubricaRuoloRubrica.setID_RUOLO((Long)ID_RUOLO);
				}

			});
		attributeGetterFunctions.put(
			"DESCRIZIONE",
			new Function<RubricaRuoloRubrica, Object>() {

				@Override
				public Object apply(RubricaRuoloRubrica rubricaRuoloRubrica) {
					return rubricaRuoloRubrica.getDESCRIZIONE();
				}

			});
		attributeSetterBiConsumers.put(
			"DESCRIZIONE",
			new BiConsumer<RubricaRuoloRubrica, Object>() {

				@Override
				public void accept(
					RubricaRuoloRubrica rubricaRuoloRubrica,
					Object DESCRIZIONE) {

					rubricaRuoloRubrica.setDESCRIZIONE((String)DESCRIZIONE);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getID_RUOLO() {
		return _ID_RUOLO;
	}

	@Override
	public void setID_RUOLO(long ID_RUOLO) {
		_ID_RUOLO = ID_RUOLO;
	}

	@JSON
	@Override
	public String getDESCRIZIONE() {
		if (_DESCRIZIONE == null) {
			return "";
		}
		else {
			return _DESCRIZIONE;
		}
	}

	@Override
	public void setDESCRIZIONE(String DESCRIZIONE) {
		_DESCRIZIONE = DESCRIZIONE;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RubricaRuoloRubrica.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RubricaRuoloRubrica toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RubricaRuoloRubrica)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RubricaRuoloRubricaImpl rubricaRuoloRubricaImpl =
			new RubricaRuoloRubricaImpl();

		rubricaRuoloRubricaImpl.setID_RUOLO(getID_RUOLO());
		rubricaRuoloRubricaImpl.setDESCRIZIONE(getDESCRIZIONE());

		rubricaRuoloRubricaImpl.resetOriginalValues();

		return rubricaRuoloRubricaImpl;
	}

	@Override
	public int compareTo(RubricaRuoloRubrica rubricaRuoloRubrica) {
		long primaryKey = rubricaRuoloRubrica.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RubricaRuoloRubrica)) {
			return false;
		}

		RubricaRuoloRubrica rubricaRuoloRubrica = (RubricaRuoloRubrica)obj;

		long primaryKey = rubricaRuoloRubrica.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RubricaRuoloRubrica> toCacheModel() {
		RubricaRuoloRubricaCacheModel rubricaRuoloRubricaCacheModel =
			new RubricaRuoloRubricaCacheModel();

		rubricaRuoloRubricaCacheModel.ID_RUOLO = getID_RUOLO();

		rubricaRuoloRubricaCacheModel.DESCRIZIONE = getDESCRIZIONE();

		String DESCRIZIONE = rubricaRuoloRubricaCacheModel.DESCRIZIONE;

		if ((DESCRIZIONE != null) && (DESCRIZIONE.length() == 0)) {
			rubricaRuoloRubricaCacheModel.DESCRIZIONE = null;
		}

		return rubricaRuoloRubricaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RubricaRuoloRubrica, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RubricaRuoloRubrica, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaRuoloRubrica, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((RubricaRuoloRubrica)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<RubricaRuoloRubrica, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<RubricaRuoloRubrica, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RubricaRuoloRubrica, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((RubricaRuoloRubrica)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		RubricaRuoloRubrica.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		RubricaRuoloRubrica.class, ModelWrapper.class
	};

	private long _ID_RUOLO;

	private String _DESCRIZIONE;

	private RubricaRuoloRubrica _escapedModel;

}