/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.animazione.image.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PioggiaCumulativa service. Represents a row in the &quot;img_animazioni_PioggiaCumulativa&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.animazione.image.model.impl.PioggiaCumulativaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.animazione.image.model.impl.PioggiaCumulativaImpl</code>.
 * </p>
 *
 * @author UTENTE
 * @see PioggiaCumulativa
 * @generated
 */
@ProviderType
public interface PioggiaCumulativaModel extends BaseModel<PioggiaCumulativa> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pioggia cumulativa model instance should use the {@link PioggiaCumulativa} interface instead.
	 */

	/**
	 * Returns the primary key of this pioggia cumulativa.
	 *
	 * @return the primary key of this pioggia cumulativa
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pioggia cumulativa.
	 *
	 * @param primaryKey the primary key of this pioggia cumulativa
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this pioggia cumulativa.
	 *
	 * @return the ID of this pioggia cumulativa
	 */
	public long getId();

	/**
	 * Sets the ID of this pioggia cumulativa.
	 *
	 * @param id the ID of this pioggia cumulativa
	 */
	public void setId(long id);

	/**
	 * Returns the nome of this pioggia cumulativa.
	 *
	 * @return the nome of this pioggia cumulativa
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this pioggia cumulativa.
	 *
	 * @param nome the nome of this pioggia cumulativa
	 */
	public void setNome(String nome);

	/**
	 * Returns the cumulazione of this pioggia cumulativa.
	 *
	 * @return the cumulazione of this pioggia cumulativa
	 */
	@AutoEscape
	public String getCumulazione();

	/**
	 * Sets the cumulazione of this pioggia cumulativa.
	 *
	 * @param cumulazione the cumulazione of this pioggia cumulativa
	 */
	public void setCumulazione(String cumulazione);

	/**
	 * Returns the inzio cumulazione of this pioggia cumulativa.
	 *
	 * @return the inzio cumulazione of this pioggia cumulativa
	 */
	public Date getInzioCumulazione();

	/**
	 * Sets the inzio cumulazione of this pioggia cumulativa.
	 *
	 * @param inzioCumulazione the inzio cumulazione of this pioggia cumulativa
	 */
	public void setInzioCumulazione(Date inzioCumulazione);

	/**
	 * Returns the fine cumulazione of this pioggia cumulativa.
	 *
	 * @return the fine cumulazione of this pioggia cumulativa
	 */
	public Date getFineCumulazione();

	/**
	 * Sets the fine cumulazione of this pioggia cumulativa.
	 *
	 * @param fineCumulazione the fine cumulazione of this pioggia cumulativa
	 */
	public void setFineCumulazione(Date fineCumulazione);

	/**
	 * Returns the img data of this pioggia cumulativa.
	 *
	 * @return the img data of this pioggia cumulativa
	 */
	@AutoEscape
	public String getImgData();

	/**
	 * Sets the img data of this pioggia cumulativa.
	 *
	 * @param imgData the img data of this pioggia cumulativa
	 */
	public void setImgData(String imgData);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.eng.animazione.image.model.PioggiaCumulativa pioggiaCumulativa);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.animazione.image.model.PioggiaCumulativa>
		toCacheModel();

	@Override
	public it.eng.animazione.image.model.PioggiaCumulativa toEscapedModel();

	@Override
	public it.eng.animazione.image.model.PioggiaCumulativa toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}