/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.previsioni.meteo.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.previsioni.meteo.model.Bollettino;
import it.eng.previsioni.meteo.model.BollettinoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Bollettino service. Represents a row in the &quot;prev_meteo_Bollettino&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BollettinoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BollettinoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BollettinoImpl
 * @generated
 */
@JSON(strict = true)
public class BollettinoModelImpl
	extends BaseModelImpl<Bollettino> implements BollettinoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bollettino model instance should use the <code>Bollettino</code> interface instead.
	 */
	public static final String TABLE_NAME = "prev_meteo_Bollettino";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"tipo", Types.VARCHAR},
		{"timestamp", Types.BIGINT}, {"emissione", Types.VARCHAR},
		{"validita", Types.VARCHAR}, {"xml_content", Types.VARCHAR},
		{"json", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tipo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timestamp", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("emissione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("validita", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("xml_content", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("json", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table prev_meteo_Bollettino (id_ LONG not null primary key,tipo VARCHAR(75) null,timestamp LONG,emissione VARCHAR(75) null,validita VARCHAR(75) null,xml_content VARCHAR(75) null,json VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table prev_meteo_Bollettino";

	public static final String ORDER_BY_JPQL = " ORDER BY bollettino.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY prev_meteo_Bollettino.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TIPO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BollettinoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Bollettino.class;
	}

	@Override
	public String getModelClassName() {
		return Bollettino.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Bollettino, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Bollettino, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Bollettino, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Bollettino)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Bollettino, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Bollettino, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Bollettino)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Bollettino, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Bollettino, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Bollettino, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Bollettino, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Bollettino, Object>>();

			attributeGetterFunctions.put("id", Bollettino::getId);
			attributeGetterFunctions.put("tipo", Bollettino::getTipo);
			attributeGetterFunctions.put("timestamp", Bollettino::getTimestamp);
			attributeGetterFunctions.put("emissione", Bollettino::getEmissione);
			attributeGetterFunctions.put("validita", Bollettino::getValidita);
			attributeGetterFunctions.put(
				"xml_content", Bollettino::getXml_content);
			attributeGetterFunctions.put("json", Bollettino::getJson);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Bollettino, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Bollettino, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Bollettino, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Bollettino, Long>)Bollettino::setId);
			attributeSetterBiConsumers.put(
				"tipo", (BiConsumer<Bollettino, String>)Bollettino::setTipo);
			attributeSetterBiConsumers.put(
				"timestamp",
				(BiConsumer<Bollettino, Long>)Bollettino::setTimestamp);
			attributeSetterBiConsumers.put(
				"emissione",
				(BiConsumer<Bollettino, String>)Bollettino::setEmissione);
			attributeSetterBiConsumers.put(
				"validita",
				(BiConsumer<Bollettino, String>)Bollettino::setValidita);
			attributeSetterBiConsumers.put(
				"xml_content",
				(BiConsumer<Bollettino, String>)Bollettino::setXml_content);
			attributeSetterBiConsumers.put(
				"json", (BiConsumer<Bollettino, String>)Bollettino::setJson);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getTipo() {
		if (_tipo == null) {
			return "";
		}
		else {
			return _tipo;
		}
	}

	@Override
	public void setTipo(String tipo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tipo = tipo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTipo() {
		return getColumnOriginalValue("tipo");
	}

	@JSON
	@Override
	public long getTimestamp() {
		return _timestamp;
	}

	@Override
	public void setTimestamp(long timestamp) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timestamp = timestamp;
	}

	@JSON
	@Override
	public String getEmissione() {
		if (_emissione == null) {
			return "";
		}
		else {
			return _emissione;
		}
	}

	@Override
	public void setEmissione(String emissione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_emissione = emissione;
	}

	@JSON
	@Override
	public String getValidita() {
		if (_validita == null) {
			return "";
		}
		else {
			return _validita;
		}
	}

	@Override
	public void setValidita(String validita) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_validita = validita;
	}

	@JSON
	@Override
	public String getXml_content() {
		if (_xml_content == null) {
			return "";
		}
		else {
			return _xml_content;
		}
	}

	@Override
	public void setXml_content(String xml_content) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_xml_content = xml_content;
	}

	@JSON
	@Override
	public String getJson() {
		if (_json == null) {
			return "";
		}
		else {
			return _json;
		}
	}

	@Override
	public void setJson(String json) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_json = json;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Bollettino.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Bollettino toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Bollettino>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BollettinoImpl bollettinoImpl = new BollettinoImpl();

		bollettinoImpl.setId(getId());
		bollettinoImpl.setTipo(getTipo());
		bollettinoImpl.setTimestamp(getTimestamp());
		bollettinoImpl.setEmissione(getEmissione());
		bollettinoImpl.setValidita(getValidita());
		bollettinoImpl.setXml_content(getXml_content());
		bollettinoImpl.setJson(getJson());

		bollettinoImpl.resetOriginalValues();

		return bollettinoImpl;
	}

	@Override
	public Bollettino cloneWithOriginalValues() {
		BollettinoImpl bollettinoImpl = new BollettinoImpl();

		bollettinoImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		bollettinoImpl.setTipo(this.<String>getColumnOriginalValue("tipo"));
		bollettinoImpl.setTimestamp(
			this.<Long>getColumnOriginalValue("timestamp"));
		bollettinoImpl.setEmissione(
			this.<String>getColumnOriginalValue("emissione"));
		bollettinoImpl.setValidita(
			this.<String>getColumnOriginalValue("validita"));
		bollettinoImpl.setXml_content(
			this.<String>getColumnOriginalValue("xml_content"));
		bollettinoImpl.setJson(this.<String>getColumnOriginalValue("json"));

		return bollettinoImpl;
	}

	@Override
	public int compareTo(Bollettino bollettino) {
		int value = 0;

		if (getId() < bollettino.getId()) {
			value = -1;
		}
		else if (getId() > bollettino.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Bollettino)) {
			return false;
		}

		Bollettino bollettino = (Bollettino)object;

		long primaryKey = bollettino.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Bollettino> toCacheModel() {
		BollettinoCacheModel bollettinoCacheModel = new BollettinoCacheModel();

		bollettinoCacheModel.id = getId();

		bollettinoCacheModel.tipo = getTipo();

		String tipo = bollettinoCacheModel.tipo;

		if ((tipo != null) && (tipo.length() == 0)) {
			bollettinoCacheModel.tipo = null;
		}

		bollettinoCacheModel.timestamp = getTimestamp();

		bollettinoCacheModel.emissione = getEmissione();

		String emissione = bollettinoCacheModel.emissione;

		if ((emissione != null) && (emissione.length() == 0)) {
			bollettinoCacheModel.emissione = null;
		}

		bollettinoCacheModel.validita = getValidita();

		String validita = bollettinoCacheModel.validita;

		if ((validita != null) && (validita.length() == 0)) {
			bollettinoCacheModel.validita = null;
		}

		bollettinoCacheModel.xml_content = getXml_content();

		String xml_content = bollettinoCacheModel.xml_content;

		if ((xml_content != null) && (xml_content.length() == 0)) {
			bollettinoCacheModel.xml_content = null;
		}

		bollettinoCacheModel.json = getJson();

		String json = bollettinoCacheModel.json;

		if ((json != null) && (json.length() == 0)) {
			bollettinoCacheModel.json = null;
		}

		return bollettinoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Bollettino, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Bollettino, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Bollettino, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Bollettino)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Bollettino>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Bollettino.class, ModelWrapper.class);

	}

	private long _id;
	private String _tipo;
	private long _timestamp;
	private String _emissione;
	private String _validita;
	private String _xml_content;
	private String _json;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Bollettino, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Bollettino)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("tipo", _tipo);
		_columnOriginalValues.put("timestamp", _timestamp);
		_columnOriginalValues.put("emissione", _emissione);
		_columnOriginalValues.put("validita", _validita);
		_columnOriginalValues.put("xml_content", _xml_content);
		_columnOriginalValues.put("json", _json);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("tipo", 2L);

		columnBitmasks.put("timestamp", 4L);

		columnBitmasks.put("emissione", 8L);

		columnBitmasks.put("validita", 16L);

		columnBitmasks.put("xml_content", 32L);

		columnBitmasks.put("json", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Bollettino _escapedModel;

}