/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.animazione.image.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.animazione.image.model.altezzaOndaAdriac;
import it.eng.animazione.image.model.altezzaOndaAdriacModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the altezzaOndaAdriac service. Represents a row in the &quot;img_animazioni_altezzaOndaAdriac&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>altezzaOndaAdriacModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link altezzaOndaAdriacImpl}.
 * </p>
 *
 * @author UTENTE
 * @see altezzaOndaAdriacImpl
 * @generated
 */
public class altezzaOndaAdriacModelImpl
	extends BaseModelImpl<altezzaOndaAdriac> implements altezzaOndaAdriacModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a altezza onda adriac model instance should use the <code>altezzaOndaAdriac</code> interface instead.
	 */
	public static final String TABLE_NAME = "img_animazioni_altezzaOndaAdriac";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"im", Types.VARCHAR},
		{"text_LOC", Types.VARCHAR}, {"timestamp", Types.BIGINT},
		{"imgData", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("im", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("text_LOC", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timestamp", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("imgData", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table img_animazioni_altezzaOndaAdriac (id_ LONG not null primary key,im VARCHAR(75) null,text_LOC VARCHAR(75) null,timestamp LONG,imgData VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table img_animazioni_altezzaOndaAdriac";

	public static final String ORDER_BY_JPQL =
		" ORDER BY altezzaOndaAdriac.id DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY img_animazioni_altezzaOndaAdriac.id_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public altezzaOndaAdriacModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return altezzaOndaAdriac.class;
	}

	@Override
	public String getModelClassName() {
		return altezzaOndaAdriac.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<altezzaOndaAdriac, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<altezzaOndaAdriac, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<altezzaOndaAdriac, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((altezzaOndaAdriac)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<altezzaOndaAdriac, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<altezzaOndaAdriac, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(altezzaOndaAdriac)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<altezzaOndaAdriac, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<altezzaOndaAdriac, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<altezzaOndaAdriac, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<altezzaOndaAdriac, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<altezzaOndaAdriac, Object>>();

			attributeGetterFunctions.put("id", altezzaOndaAdriac::getId);
			attributeGetterFunctions.put("im", altezzaOndaAdriac::getIm);
			attributeGetterFunctions.put(
				"text_LOC", altezzaOndaAdriac::getText_LOC);
			attributeGetterFunctions.put(
				"ts_UTC", altezzaOndaAdriac::getTs_UTC);
			attributeGetterFunctions.put(
				"imgData", altezzaOndaAdriac::getImgData);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<altezzaOndaAdriac, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<altezzaOndaAdriac, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<altezzaOndaAdriac, ?>>();

			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<altezzaOndaAdriac, Long>)altezzaOndaAdriac::setId);
			attributeSetterBiConsumers.put(
				"im",
				(BiConsumer<altezzaOndaAdriac, String>)
					altezzaOndaAdriac::setIm);
			attributeSetterBiConsumers.put(
				"text_LOC",
				(BiConsumer<altezzaOndaAdriac, String>)
					altezzaOndaAdriac::setText_LOC);
			attributeSetterBiConsumers.put(
				"ts_UTC",
				(BiConsumer<altezzaOndaAdriac, Long>)
					altezzaOndaAdriac::setTs_UTC);
			attributeSetterBiConsumers.put(
				"imgData",
				(BiConsumer<altezzaOndaAdriac, String>)
					altezzaOndaAdriac::setImgData);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@Override
	public String getIm() {
		if (_im == null) {
			return "";
		}
		else {
			return _im;
		}
	}

	@Override
	public void setIm(String im) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_im = im;
	}

	@Override
	public String getText_LOC() {
		if (_text_LOC == null) {
			return "";
		}
		else {
			return _text_LOC;
		}
	}

	@Override
	public void setText_LOC(String text_LOC) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_text_LOC = text_LOC;
	}

	@Override
	public long getTs_UTC() {
		return _ts_UTC;
	}

	@Override
	public void setTs_UTC(long ts_UTC) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ts_UTC = ts_UTC;
	}

	@Override
	public String getImgData() {
		if (_imgData == null) {
			return "";
		}
		else {
			return _imgData;
		}
	}

	@Override
	public void setImgData(String imgData) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_imgData = imgData;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, altezzaOndaAdriac.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public altezzaOndaAdriac toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, altezzaOndaAdriac>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		altezzaOndaAdriacImpl altezzaOndaAdriacImpl =
			new altezzaOndaAdriacImpl();

		altezzaOndaAdriacImpl.setId(getId());
		altezzaOndaAdriacImpl.setIm(getIm());
		altezzaOndaAdriacImpl.setText_LOC(getText_LOC());
		altezzaOndaAdriacImpl.setTs_UTC(getTs_UTC());
		altezzaOndaAdriacImpl.setImgData(getImgData());

		altezzaOndaAdriacImpl.resetOriginalValues();

		return altezzaOndaAdriacImpl;
	}

	@Override
	public altezzaOndaAdriac cloneWithOriginalValues() {
		altezzaOndaAdriacImpl altezzaOndaAdriacImpl =
			new altezzaOndaAdriacImpl();

		altezzaOndaAdriacImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		altezzaOndaAdriacImpl.setIm(this.<String>getColumnOriginalValue("im"));
		altezzaOndaAdriacImpl.setText_LOC(
			this.<String>getColumnOriginalValue("text_LOC"));
		altezzaOndaAdriacImpl.setTs_UTC(
			this.<Long>getColumnOriginalValue("timestamp"));
		altezzaOndaAdriacImpl.setImgData(
			this.<String>getColumnOriginalValue("imgData"));

		return altezzaOndaAdriacImpl;
	}

	@Override
	public int compareTo(altezzaOndaAdriac altezzaOndaAdriac) {
		int value = 0;

		if (getId() < altezzaOndaAdriac.getId()) {
			value = -1;
		}
		else if (getId() > altezzaOndaAdriac.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof altezzaOndaAdriac)) {
			return false;
		}

		altezzaOndaAdriac altezzaOndaAdriac = (altezzaOndaAdriac)object;

		long primaryKey = altezzaOndaAdriac.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<altezzaOndaAdriac> toCacheModel() {
		altezzaOndaAdriacCacheModel altezzaOndaAdriacCacheModel =
			new altezzaOndaAdriacCacheModel();

		altezzaOndaAdriacCacheModel.id = getId();

		altezzaOndaAdriacCacheModel.im = getIm();

		String im = altezzaOndaAdriacCacheModel.im;

		if ((im != null) && (im.length() == 0)) {
			altezzaOndaAdriacCacheModel.im = null;
		}

		altezzaOndaAdriacCacheModel.text_LOC = getText_LOC();

		String text_LOC = altezzaOndaAdriacCacheModel.text_LOC;

		if ((text_LOC != null) && (text_LOC.length() == 0)) {
			altezzaOndaAdriacCacheModel.text_LOC = null;
		}

		altezzaOndaAdriacCacheModel.ts_UTC = getTs_UTC();

		altezzaOndaAdriacCacheModel.imgData = getImgData();

		String imgData = altezzaOndaAdriacCacheModel.imgData;

		if ((imgData != null) && (imgData.length() == 0)) {
			altezzaOndaAdriacCacheModel.imgData = null;
		}

		return altezzaOndaAdriacCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<altezzaOndaAdriac, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<altezzaOndaAdriac, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<altezzaOndaAdriac, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(altezzaOndaAdriac)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, altezzaOndaAdriac>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					altezzaOndaAdriac.class, ModelWrapper.class);

	}

	private long _id;
	private String _im;
	private String _text_LOC;
	private long _ts_UTC;
	private String _imgData;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<altezzaOndaAdriac, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((altezzaOndaAdriac)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("im", _im);
		_columnOriginalValues.put("text_LOC", _text_LOC);
		_columnOriginalValues.put("timestamp", _ts_UTC);
		_columnOriginalValues.put("imgData", _imgData);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");
		attributeNames.put("timestamp", "ts_UTC");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("im", 2L);

		columnBitmasks.put("text_LOC", 4L);

		columnBitmasks.put("timestamp", 8L);

		columnBitmasks.put("imgData", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private altezzaOndaAdriac _escapedModel;

}