/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Allarme service. Represents a row in the &quot;BOLLETTINO_Allarme&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.AllarmeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.AllarmeImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see Allarme
 * @generated
 */
@ProviderType
public interface AllarmeModel
	extends BaseModel<Allarme>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a allarme model instance should use the {@link Allarme} interface instead.
	 */

	/**
	 * Returns the primary key of this allarme.
	 *
	 * @return the primary key of this allarme
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this allarme.
	 *
	 * @param primaryKey the primary key of this allarme
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this allarme.
	 *
	 * @return the uuid of this allarme
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this allarme.
	 *
	 * @param uuid the uuid of this allarme
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the allarme ID of this allarme.
	 *
	 * @return the allarme ID of this allarme
	 */
	public long getAllarmeId();

	/**
	 * Sets the allarme ID of this allarme.
	 *
	 * @param allarmeId the allarme ID of this allarme
	 */
	public void setAllarmeId(long allarmeId);

	/**
	 * Returns the group ID of this allarme.
	 *
	 * @return the group ID of this allarme
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this allarme.
	 *
	 * @param groupId the group ID of this allarme
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this allarme.
	 *
	 * @return the company ID of this allarme
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this allarme.
	 *
	 * @param companyId the company ID of this allarme
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this allarme.
	 *
	 * @return the user ID of this allarme
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this allarme.
	 *
	 * @param userId the user ID of this allarme
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this allarme.
	 *
	 * @return the user uuid of this allarme
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this allarme.
	 *
	 * @param userUuid the user uuid of this allarme
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this allarme.
	 *
	 * @return the user name of this allarme
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this allarme.
	 *
	 * @param userName the user name of this allarme
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this allarme.
	 *
	 * @return the create date of this allarme
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this allarme.
	 *
	 * @param createDate the create date of this allarme
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this allarme.
	 *
	 * @return the modified date of this allarme
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this allarme.
	 *
	 * @param modifiedDate the modified date of this allarme
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the stato of this allarme.
	 *
	 * @return the stato of this allarme
	 */
	public int getStato();

	/**
	 * Sets the stato of this allarme.
	 *
	 * @param stato the stato of this allarme
	 */
	public void setStato(int stato);

	/**
	 * Returns the id approvatore of this allarme.
	 *
	 * @return the id approvatore of this allarme
	 */
	public long getIdApprovatore();

	/**
	 * Sets the id approvatore of this allarme.
	 *
	 * @param idApprovatore the id approvatore of this allarme
	 */
	public void setIdApprovatore(long idApprovatore);

	/**
	 * Returns the data approvazione of this allarme.
	 *
	 * @return the data approvazione of this allarme
	 */
	public Date getDataApprovazione();

	/**
	 * Sets the data approvazione of this allarme.
	 *
	 * @param dataApprovazione the data approvazione of this allarme
	 */
	public void setDataApprovazione(Date dataApprovazione);

	/**
	 * Returns the id regola of this allarme.
	 *
	 * @return the id regola of this allarme
	 */
	public long getIdRegola();

	/**
	 * Sets the id regola of this allarme.
	 *
	 * @param idRegola the id regola of this allarme
	 */
	public void setIdRegola(long idRegola);

	/**
	 * Returns the colore of this allarme.
	 *
	 * @return the colore of this allarme
	 */
	public int getColore();

	/**
	 * Sets the colore of this allarme.
	 *
	 * @param colore the colore of this allarme
	 */
	public void setColore(int colore);

	/**
	 * Returns the data inizio of this allarme.
	 *
	 * @return the data inizio of this allarme
	 */
	public Date getDataInizio();

	/**
	 * Sets the data inizio of this allarme.
	 *
	 * @param dataInizio the data inizio of this allarme
	 */
	public void setDataInizio(Date dataInizio);

	/**
	 * Returns the data fine of this allarme.
	 *
	 * @return the data fine of this allarme
	 */
	public Date getDataFine();

	/**
	 * Sets the data fine of this allarme.
	 *
	 * @param dataFine the data fine of this allarme
	 */
	public void setDataFine(Date dataFine);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.bollettino.model.Allarme allarme);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.Allarme> toCacheModel();

	@Override
	public it.eng.bollettino.model.Allarme toEscapedModel();

	@Override
	public it.eng.bollettino.model.Allarme toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}