/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AttivazioneFiume service. Represents a row in the &quot;BOLLETTINO_AttivazioneFiume&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.AttivazioneFiumeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.AttivazioneFiumeImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see AttivazioneFiume
 * @generated
 */
@ProviderType
public interface AttivazioneFiumeModel extends BaseModel<AttivazioneFiume> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a attivazione fiume model instance should use the {@link AttivazioneFiume} interface instead.
	 */

	/**
	 * Returns the primary key of this attivazione fiume.
	 *
	 * @return the primary key of this attivazione fiume
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this attivazione fiume.
	 *
	 * @param primaryKey the primary key of this attivazione fiume
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the fiume ID of this attivazione fiume.
	 *
	 * @return the fiume ID of this attivazione fiume
	 */
	@AutoEscape
	public String getFiumeId();

	/**
	 * Sets the fiume ID of this attivazione fiume.
	 *
	 * @param fiumeId the fiume ID of this attivazione fiume
	 */
	public void setFiumeId(String fiumeId);

	/**
	 * Returns the attivo of this attivazione fiume.
	 *
	 * @return the attivo of this attivazione fiume
	 */
	public boolean getAttivo();

	/**
	 * Returns <code>true</code> if this attivazione fiume is attivo.
	 *
	 * @return <code>true</code> if this attivazione fiume is attivo; <code>false</code> otherwise
	 */
	public boolean isAttivo();

	/**
	 * Sets whether this attivazione fiume is attivo.
	 *
	 * @param attivo the attivo of this attivazione fiume
	 */
	public void setAttivo(boolean attivo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.eng.bollettino.model.AttivazioneFiume attivazioneFiume);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.AttivazioneFiume> toCacheModel();

	@Override
	public it.eng.bollettino.model.AttivazioneFiume toEscapedModel();

	@Override
	public it.eng.bollettino.model.AttivazioneFiume toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}