/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Bacino service. Represents a row in the &quot;BOLLETTINO_Bacino&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.BacinoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.BacinoImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see Bacino
 * @generated
 */
@ProviderType
public interface BacinoModel extends BaseModel<Bacino> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bacino model instance should use the {@link Bacino} interface instead.
	 */

	/**
	 * Returns the primary key of this bacino.
	 *
	 * @return the primary key of this bacino
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this bacino.
	 *
	 * @param primaryKey the primary key of this bacino
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this bacino.
	 *
	 * @return the uuid of this bacino
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this bacino.
	 *
	 * @param uuid the uuid of this bacino
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this bacino.
	 *
	 * @return the ID of this bacino
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this bacino.
	 *
	 * @param id the ID of this bacino
	 */
	public void setId(String id);

	/**
	 * Returns the nome of this bacino.
	 *
	 * @return the nome of this bacino
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this bacino.
	 *
	 * @param nome the nome of this bacino
	 */
	public void setNome(String nome);

	/**
	 * Returns the progressivo of this bacino.
	 *
	 * @return the progressivo of this bacino
	 */
	public int getProgressivo();

	/**
	 * Sets the progressivo of this bacino.
	 *
	 * @param progressivo the progressivo of this bacino
	 */
	public void setProgressivo(int progressivo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.bollettino.model.Bacino bacino);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.Bacino> toCacheModel();

	@Override
	public it.eng.bollettino.model.Bacino toEscapedModel();

	@Override
	public it.eng.bollettino.model.Bacino toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}