/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Bollettino service. Represents a row in the &quot;BOLLETTINO_Bollettino&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.BollettinoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.BollettinoImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see Bollettino
 * @generated
 */
@ProviderType
public interface BollettinoModel
	extends BaseModel<Bollettino>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bollettino model instance should use the {@link Bollettino} interface instead.
	 */

	/**
	 * Returns the primary key of this bollettino.
	 *
	 * @return the primary key of this bollettino
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bollettino.
	 *
	 * @param primaryKey the primary key of this bollettino
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this bollettino.
	 *
	 * @return the uuid of this bollettino
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this bollettino.
	 *
	 * @param uuid the uuid of this bollettino
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the bollettino ID of this bollettino.
	 *
	 * @return the bollettino ID of this bollettino
	 */
	public long getBollettinoId();

	/**
	 * Sets the bollettino ID of this bollettino.
	 *
	 * @param bollettinoId the bollettino ID of this bollettino
	 */
	public void setBollettinoId(long bollettinoId);

	/**
	 * Returns the group ID of this bollettino.
	 *
	 * @return the group ID of this bollettino
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this bollettino.
	 *
	 * @param groupId the group ID of this bollettino
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this bollettino.
	 *
	 * @return the company ID of this bollettino
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bollettino.
	 *
	 * @param companyId the company ID of this bollettino
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bollettino.
	 *
	 * @return the user ID of this bollettino
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bollettino.
	 *
	 * @param userId the user ID of this bollettino
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bollettino.
	 *
	 * @return the user uuid of this bollettino
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this bollettino.
	 *
	 * @param userUuid the user uuid of this bollettino
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bollettino.
	 *
	 * @return the user name of this bollettino
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bollettino.
	 *
	 * @param userName the user name of this bollettino
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bollettino.
	 *
	 * @return the create date of this bollettino
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bollettino.
	 *
	 * @param createDate the create date of this bollettino
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bollettino.
	 *
	 * @return the modified date of this bollettino
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bollettino.
	 *
	 * @param modifiedDate the modified date of this bollettino
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the stato of this bollettino.
	 *
	 * @return the stato of this bollettino
	 */
	public int getStato();

	/**
	 * Sets the stato of this bollettino.
	 *
	 * @param stato the stato of this bollettino
	 */
	public void setStato(int stato);

	/**
	 * Returns the id approvatore of this bollettino.
	 *
	 * @return the id approvatore of this bollettino
	 */
	public long getIdApprovatore();

	/**
	 * Sets the id approvatore of this bollettino.
	 *
	 * @param idApprovatore the id approvatore of this bollettino
	 */
	public void setIdApprovatore(long idApprovatore);

	/**
	 * Returns the data approvazione of this bollettino.
	 *
	 * @return the data approvazione of this bollettino
	 */
	public Date getDataApprovazione();

	/**
	 * Sets the data approvazione of this bollettino.
	 *
	 * @param dataApprovazione the data approvazione of this bollettino
	 */
	public void setDataApprovazione(Date dataApprovazione);

	/**
	 * Returns the numero of this bollettino.
	 *
	 * @return the numero of this bollettino
	 */
	@AutoEscape
	public String getNumero();

	/**
	 * Sets the numero of this bollettino.
	 *
	 * @param numero the numero of this bollettino
	 */
	public void setNumero(String numero);

	/**
	 * Returns the progressivo of this bollettino.
	 *
	 * @return the progressivo of this bollettino
	 */
	public int getProgressivo();

	/**
	 * Sets the progressivo of this bollettino.
	 *
	 * @param progressivo the progressivo of this bollettino
	 */
	public void setProgressivo(int progressivo);

	/**
	 * Returns the anno of this bollettino.
	 *
	 * @return the anno of this bollettino
	 */
	public int getAnno();

	/**
	 * Sets the anno of this bollettino.
	 *
	 * @param anno the anno of this bollettino
	 */
	public void setAnno(int anno);

	/**
	 * Returns the data emissione of this bollettino.
	 *
	 * @return the data emissione of this bollettino
	 */
	public Date getDataEmissione();

	/**
	 * Sets the data emissione of this bollettino.
	 *
	 * @param dataEmissione the data emissione of this bollettino
	 */
	public void setDataEmissione(Date dataEmissione);

	/**
	 * Returns the data inizio of this bollettino.
	 *
	 * @return the data inizio of this bollettino
	 */
	public Date getDataInizio();

	/**
	 * Sets the data inizio of this bollettino.
	 *
	 * @param dataInizio the data inizio of this bollettino
	 */
	public void setDataInizio(Date dataInizio);

	/**
	 * Returns the data fine of this bollettino.
	 *
	 * @return the data fine of this bollettino
	 */
	public Date getDataFine();

	/**
	 * Sets the data fine of this bollettino.
	 *
	 * @param dataFine the data fine of this bollettino
	 */
	public void setDataFine(Date dataFine);

	/**
	 * Returns the note meteo of this bollettino.
	 *
	 * @return the note meteo of this bollettino
	 */
	@AutoEscape
	public String getNoteMeteo();

	/**
	 * Sets the note meteo of this bollettino.
	 *
	 * @param noteMeteo the note meteo of this bollettino
	 */
	public void setNoteMeteo(String noteMeteo);

	/**
	 * Returns the stringa meteo of this bollettino.
	 *
	 * @return the stringa meteo of this bollettino
	 */
	@AutoEscape
	public String getStringaMeteo();

	/**
	 * Sets the stringa meteo of this bollettino.
	 *
	 * @param stringaMeteo the stringa meteo of this bollettino
	 */
	public void setStringaMeteo(String stringaMeteo);

	/**
	 * Returns the link of this bollettino.
	 *
	 * @return the link of this bollettino
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this bollettino.
	 *
	 * @param link the link of this bollettino
	 */
	public void setLink(String link);

	/**
	 * Returns the ultimo of this bollettino.
	 *
	 * @return the ultimo of this bollettino
	 */
	public boolean getUltimo();

	/**
	 * Returns <code>true</code> if this bollettino is ultimo.
	 *
	 * @return <code>true</code> if this bollettino is ultimo; <code>false</code> otherwise
	 */
	public boolean isUltimo();

	/**
	 * Sets whether this bollettino is ultimo.
	 *
	 * @param ultimo the ultimo of this bollettino
	 */
	public void setUltimo(boolean ultimo);

	/**
	 * Returns the hash of this bollettino.
	 *
	 * @return the hash of this bollettino
	 */
	@AutoEscape
	public String getHash();

	/**
	 * Sets the hash of this bollettino.
	 *
	 * @param hash the hash of this bollettino
	 */
	public void setHash(String hash);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.bollettino.model.Bollettino bollettino);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.Bollettino> toCacheModel();

	@Override
	public it.eng.bollettino.model.Bollettino toEscapedModel();

	@Override
	public it.eng.bollettino.model.Bollettino toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}