/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the BollettinoSensore service. Represents a row in the &quot;BOLLETTINO_BollettinoSensore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.BollettinoSensoreModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.BollettinoSensoreImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see BollettinoSensore
 * @generated
 */
@ProviderType
public interface BollettinoSensoreModel extends BaseModel<BollettinoSensore> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bollettino sensore model instance should use the {@link BollettinoSensore} interface instead.
	 */

	/**
	 * Returns the primary key of this bollettino sensore.
	 *
	 * @return the primary key of this bollettino sensore
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bollettino sensore.
	 *
	 * @param primaryKey the primary key of this bollettino sensore
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this bollettino sensore.
	 *
	 * @return the uuid of this bollettino sensore
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this bollettino sensore.
	 *
	 * @param uuid the uuid of this bollettino sensore
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this bollettino sensore.
	 *
	 * @return the ID of this bollettino sensore
	 */
	public long getId();

	/**
	 * Sets the ID of this bollettino sensore.
	 *
	 * @param id the ID of this bollettino sensore
	 */
	public void setId(long id);

	/**
	 * Returns the id bollettino of this bollettino sensore.
	 *
	 * @return the id bollettino of this bollettino sensore
	 */
	public long getIdBollettino();

	/**
	 * Sets the id bollettino of this bollettino sensore.
	 *
	 * @param idBollettino the id bollettino of this bollettino sensore
	 */
	public void setIdBollettino(long idBollettino);

	/**
	 * Returns the id stazione of this bollettino sensore.
	 *
	 * @return the id stazione of this bollettino sensore
	 */
	public long getIdStazione();

	/**
	 * Sets the id stazione of this bollettino sensore.
	 *
	 * @param idStazione the id stazione of this bollettino sensore
	 */
	public void setIdStazione(long idStazione);

	/**
	 * Returns the id bollettino bacino of this bollettino sensore.
	 *
	 * @return the id bollettino bacino of this bollettino sensore
	 */
	public long getIdBollettinoBacino();

	/**
	 * Sets the id bollettino bacino of this bollettino sensore.
	 *
	 * @param idBollettinoBacino the id bollettino bacino of this bollettino sensore
	 */
	public void setIdBollettinoBacino(long idBollettinoBacino);

	/**
	 * Returns the progressivo of this bollettino sensore.
	 *
	 * @return the progressivo of this bollettino sensore
	 */
	public int getProgressivo();

	/**
	 * Sets the progressivo of this bollettino sensore.
	 *
	 * @param progressivo the progressivo of this bollettino sensore
	 */
	public void setProgressivo(int progressivo);

	/**
	 * Returns the nome stazione of this bollettino sensore.
	 *
	 * @return the nome stazione of this bollettino sensore
	 */
	@AutoEscape
	public String getNomeStazione();

	/**
	 * Sets the nome stazione of this bollettino sensore.
	 *
	 * @param nomeStazione the nome stazione of this bollettino sensore
	 */
	public void setNomeStazione(String nomeStazione);

	/**
	 * Returns the ore osservazione of this bollettino sensore.
	 *
	 * @return the ore osservazione of this bollettino sensore
	 */
	@AutoEscape
	public String getOreOsservazione();

	/**
	 * Sets the ore osservazione of this bollettino sensore.
	 *
	 * @param oreOsservazione the ore osservazione of this bollettino sensore
	 */
	public void setOreOsservazione(String oreOsservazione);

	/**
	 * Returns the osservazione of this bollettino sensore.
	 *
	 * @return the osservazione of this bollettino sensore
	 */
	public double getOsservazione();

	/**
	 * Sets the osservazione of this bollettino sensore.
	 *
	 * @param osservazione the osservazione of this bollettino sensore
	 */
	public void setOsservazione(double osservazione);

	/**
	 * Returns the tendenza of this bollettino sensore.
	 *
	 * @return the tendenza of this bollettino sensore
	 */
	public int getTendenza();

	/**
	 * Sets the tendenza of this bollettino sensore.
	 *
	 * @param tendenza the tendenza of this bollettino sensore
	 */
	public void setTendenza(int tendenza);

	/**
	 * Returns the colmo previsto of this bollettino sensore.
	 *
	 * @return the colmo previsto of this bollettino sensore
	 */
	@AutoEscape
	public String getColmoPrevisto();

	/**
	 * Sets the colmo previsto of this bollettino sensore.
	 *
	 * @param colmoPrevisto the colmo previsto of this bollettino sensore
	 */
	public void setColmoPrevisto(String colmoPrevisto);

	/**
	 * Returns the ora prevista of this bollettino sensore.
	 *
	 * @return the ora prevista of this bollettino sensore
	 */
	@AutoEscape
	public String getOraPrevista();

	/**
	 * Sets the ora prevista of this bollettino sensore.
	 *
	 * @param oraPrevista the ora prevista of this bollettino sensore
	 */
	public void setOraPrevista(String oraPrevista);

	/**
	 * Returns the soglia1 of this bollettino sensore.
	 *
	 * @return the soglia1 of this bollettino sensore
	 */
	public double getSoglia1();

	/**
	 * Sets the soglia1 of this bollettino sensore.
	 *
	 * @param soglia1 the soglia1 of this bollettino sensore
	 */
	public void setSoglia1(double soglia1);

	/**
	 * Returns the soglia2 of this bollettino sensore.
	 *
	 * @return the soglia2 of this bollettino sensore
	 */
	public double getSoglia2();

	/**
	 * Sets the soglia2 of this bollettino sensore.
	 *
	 * @param soglia2 the soglia2 of this bollettino sensore
	 */
	public void setSoglia2(double soglia2);

	/**
	 * Returns the soglia3 of this bollettino sensore.
	 *
	 * @return the soglia3 of this bollettino sensore
	 */
	public double getSoglia3();

	/**
	 * Sets the soglia3 of this bollettino sensore.
	 *
	 * @param soglia3 the soglia3 of this bollettino sensore
	 */
	public void setSoglia3(double soglia3);

	/**
	 * Returns the giorno previsto of this bollettino sensore.
	 *
	 * @return the giorno previsto of this bollettino sensore
	 */
	@AutoEscape
	public String getGiornoPrevisto();

	/**
	 * Sets the giorno previsto of this bollettino sensore.
	 *
	 * @param giornoPrevisto the giorno previsto of this bollettino sensore
	 */
	public void setGiornoPrevisto(String giornoPrevisto);

	/**
	 * Returns the osservato of this bollettino sensore.
	 *
	 * @return the osservato of this bollettino sensore
	 */
	public boolean getOsservato();

	/**
	 * Returns <code>true</code> if this bollettino sensore is osservato.
	 *
	 * @return <code>true</code> if this bollettino sensore is osservato; <code>false</code> otherwise
	 */
	public boolean isOsservato();

	/**
	 * Sets whether this bollettino sensore is osservato.
	 *
	 * @param osservato the osservato of this bollettino sensore
	 */
	public void setOsservato(boolean osservato);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.eng.bollettino.model.BollettinoSensore bollettinoSensore);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.BollettinoSensore> toCacheModel();

	@Override
	public it.eng.bollettino.model.BollettinoSensore toEscapedModel();

	@Override
	public it.eng.bollettino.model.BollettinoSensore toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}