/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the BollettinoBacino service. Represents a row in the &quot;BOLLETTINO_BollettinoBacino&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.BollettinoBacinoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.BollettinoBacinoImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see BollettinoBacino
 * @generated
 */
@ProviderType
public interface BollettinoBacinoModel extends BaseModel<BollettinoBacino> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bollettino bacino model instance should use the {@link BollettinoBacino} interface instead.
	 */

	/**
	 * Returns the primary key of this bollettino bacino.
	 *
	 * @return the primary key of this bollettino bacino
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bollettino bacino.
	 *
	 * @param primaryKey the primary key of this bollettino bacino
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this bollettino bacino.
	 *
	 * @return the uuid of this bollettino bacino
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this bollettino bacino.
	 *
	 * @param uuid the uuid of this bollettino bacino
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this bollettino bacino.
	 *
	 * @return the ID of this bollettino bacino
	 */
	public long getId();

	/**
	 * Sets the ID of this bollettino bacino.
	 *
	 * @param id the ID of this bollettino bacino
	 */
	public void setId(long id);

	/**
	 * Returns the id bollettino of this bollettino bacino.
	 *
	 * @return the id bollettino of this bollettino bacino
	 */
	public long getIdBollettino();

	/**
	 * Sets the id bollettino of this bollettino bacino.
	 *
	 * @param idBollettino the id bollettino of this bollettino bacino
	 */
	public void setIdBollettino(long idBollettino);

	/**
	 * Returns the progressivo of this bollettino bacino.
	 *
	 * @return the progressivo of this bollettino bacino
	 */
	public int getProgressivo();

	/**
	 * Sets the progressivo of this bollettino bacino.
	 *
	 * @param progressivo the progressivo of this bollettino bacino
	 */
	public void setProgressivo(int progressivo);

	/**
	 * Returns the id bacino of this bollettino bacino.
	 *
	 * @return the id bacino of this bollettino bacino
	 */
	@AutoEscape
	public String getIdBacino();

	/**
	 * Sets the id bacino of this bollettino bacino.
	 *
	 * @param idBacino the id bacino of this bollettino bacino
	 */
	public void setIdBacino(String idBacino);

	/**
	 * Returns the nome bacino of this bollettino bacino.
	 *
	 * @return the nome bacino of this bollettino bacino
	 */
	@AutoEscape
	public String getNomeBacino();

	/**
	 * Sets the nome bacino of this bollettino bacino.
	 *
	 * @param nomeBacino the nome bacino of this bollettino bacino
	 */
	public void setNomeBacino(String nomeBacino);

	/**
	 * Returns the ore osservazione of this bollettino bacino.
	 *
	 * @return the ore osservazione of this bollettino bacino
	 */
	@AutoEscape
	public String getOreOsservazione();

	/**
	 * Sets the ore osservazione of this bollettino bacino.
	 *
	 * @param oreOsservazione the ore osservazione of this bollettino bacino
	 */
	public void setOreOsservazione(String oreOsservazione);

	/**
	 * Returns the note of this bollettino bacino.
	 *
	 * @return the note of this bollettino bacino
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this bollettino bacino.
	 *
	 * @param note the note of this bollettino bacino
	 */
	public void setNote(String note);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.eng.bollettino.model.BollettinoBacino bollettinoBacino);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.BollettinoBacino> toCacheModel();

	@Override
	public it.eng.bollettino.model.BollettinoBacino toEscapedModel();

	@Override
	public it.eng.bollettino.model.BollettinoBacino toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}