/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Pluviometro service. Represents a row in the &quot;BOLLETTINO_Pluviometro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.PluviometroModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.PluviometroImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see Pluviometro
 * @generated
 */
@ProviderType
public interface PluviometroModel extends BaseModel<Pluviometro> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pluviometro model instance should use the {@link Pluviometro} interface instead.
	 */

	/**
	 * Returns the primary key of this pluviometro.
	 *
	 * @return the primary key of this pluviometro
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this pluviometro.
	 *
	 * @param primaryKey the primary key of this pluviometro
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the stazione ID of this pluviometro.
	 *
	 * @return the stazione ID of this pluviometro
	 */
	@AutoEscape
	public String getStazioneId();

	/**
	 * Sets the stazione ID of this pluviometro.
	 *
	 * @param stazioneId the stazione ID of this pluviometro
	 */
	public void setStazioneId(String stazioneId);

	/**
	 * Returns the nome gruppo of this pluviometro.
	 *
	 * @return the nome gruppo of this pluviometro
	 */
	@AutoEscape
	public String getNomeGruppo();

	/**
	 * Sets the nome gruppo of this pluviometro.
	 *
	 * @param nomeGruppo the nome gruppo of this pluviometro
	 */
	public void setNomeGruppo(String nomeGruppo);

	/**
	 * Returns the nome rubrica of this pluviometro.
	 *
	 * @return the nome rubrica of this pluviometro
	 */
	@AutoEscape
	public String getNomeRubrica();

	/**
	 * Sets the nome rubrica of this pluviometro.
	 *
	 * @param nomeRubrica the nome rubrica of this pluviometro
	 */
	public void setNomeRubrica(String nomeRubrica);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.bollettino.model.Pluviometro pluviometro);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.Pluviometro> toCacheModel();

	@Override
	public it.eng.bollettino.model.Pluviometro toEscapedModel();

	@Override
	public it.eng.bollettino.model.Pluviometro toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}