/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RegolaAllarmeCondizione service. Represents a row in the &quot;BOLLETTINO_RegolaAllarmeCondizione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.RegolaAllarmeCondizioneModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.RegolaAllarmeCondizioneImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see RegolaAllarmeCondizione
 * @generated
 */
@ProviderType
public interface RegolaAllarmeCondizioneModel
	extends BaseModel<RegolaAllarmeCondizione> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a regola allarme condizione model instance should use the {@link RegolaAllarmeCondizione} interface instead.
	 */

	/**
	 * Returns the primary key of this regola allarme condizione.
	 *
	 * @return the primary key of this regola allarme condizione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this regola allarme condizione.
	 *
	 * @param primaryKey the primary key of this regola allarme condizione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this regola allarme condizione.
	 *
	 * @return the uuid of this regola allarme condizione
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this regola allarme condizione.
	 *
	 * @param uuid the uuid of this regola allarme condizione
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this regola allarme condizione.
	 *
	 * @return the ID of this regola allarme condizione
	 */
	public long getId();

	/**
	 * Sets the ID of this regola allarme condizione.
	 *
	 * @param id the ID of this regola allarme condizione
	 */
	public void setId(long id);

	/**
	 * Returns the id regola of this regola allarme condizione.
	 *
	 * @return the id regola of this regola allarme condizione
	 */
	public long getIdRegola();

	/**
	 * Sets the id regola of this regola allarme condizione.
	 *
	 * @param idRegola the id regola of this regola allarme condizione
	 */
	public void setIdRegola(long idRegola);

	/**
	 * Returns the lettera of this regola allarme condizione.
	 *
	 * @return the lettera of this regola allarme condizione
	 */
	@AutoEscape
	public String getLettera();

	/**
	 * Sets the lettera of this regola allarme condizione.
	 *
	 * @param lettera the lettera of this regola allarme condizione
	 */
	public void setLettera(String lettera);

	/**
	 * Returns the id variabile of this regola allarme condizione.
	 *
	 * @return the id variabile of this regola allarme condizione
	 */
	@AutoEscape
	public String getIdVariabile();

	/**
	 * Sets the id variabile of this regola allarme condizione.
	 *
	 * @param idVariabile the id variabile of this regola allarme condizione
	 */
	public void setIdVariabile(String idVariabile);

	/**
	 * Returns the id stazione of this regola allarme condizione.
	 *
	 * @return the id stazione of this regola allarme condizione
	 */
	@AutoEscape
	public String getIdStazione();

	/**
	 * Sets the id stazione of this regola allarme condizione.
	 *
	 * @param idStazione the id stazione of this regola allarme condizione
	 */
	public void setIdStazione(String idStazione);

	/**
	 * Returns the id stazione variabile of this regola allarme condizione.
	 *
	 * @return the id stazione variabile of this regola allarme condizione
	 */
	public long getIdStazioneVariabile();

	/**
	 * Sets the id stazione variabile of this regola allarme condizione.
	 *
	 * @param idStazioneVariabile the id stazione variabile of this regola allarme condizione
	 */
	public void setIdStazioneVariabile(long idStazioneVariabile);

	/**
	 * Returns the soglia of this regola allarme condizione.
	 *
	 * @return the soglia of this regola allarme condizione
	 */
	public int getSoglia();

	/**
	 * Sets the soglia of this regola allarme condizione.
	 *
	 * @param soglia the soglia of this regola allarme condizione
	 */
	public void setSoglia(int soglia);

	/**
	 * Returns the valore soglia of this regola allarme condizione.
	 *
	 * @return the valore soglia of this regola allarme condizione
	 */
	public double getValoreSoglia();

	/**
	 * Sets the valore soglia of this regola allarme condizione.
	 *
	 * @param valoreSoglia the valore soglia of this regola allarme condizione
	 */
	public void setValoreSoglia(double valoreSoglia);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.eng.bollettino.model.RegolaAllarmeCondizione
			regolaAllarmeCondizione);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.RegolaAllarmeCondizione>
		toCacheModel();

	@Override
	public it.eng.bollettino.model.RegolaAllarmeCondizione toEscapedModel();

	@Override
	public it.eng.bollettino.model.RegolaAllarmeCondizione toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}