/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Variabile service. Represents a row in the &quot;BOLLETTINO_Variabile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.bollettino.model.impl.VariabileModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.bollettino.model.impl.VariabileImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see Variabile
 * @generated
 */
@ProviderType
public interface VariabileModel extends BaseModel<Variabile> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a variabile model instance should use the {@link Variabile} interface instead.
	 */

	/**
	 * Returns the primary key of this variabile.
	 *
	 * @return the primary key of this variabile
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this variabile.
	 *
	 * @param primaryKey the primary key of this variabile
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this variabile.
	 *
	 * @return the uuid of this variabile
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this variabile.
	 *
	 * @param uuid the uuid of this variabile
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this variabile.
	 *
	 * @return the ID of this variabile
	 */
	@AutoEscape
	public String getId();

	/**
	 * Sets the ID of this variabile.
	 *
	 * @param id the ID of this variabile
	 */
	public void setId(String id);

	/**
	 * Returns the description_it of this variabile.
	 *
	 * @return the description_it of this variabile
	 */
	@AutoEscape
	public String getDescription_it();

	/**
	 * Sets the description_it of this variabile.
	 *
	 * @param description_it the description_it of this variabile
	 */
	public void setDescription_it(String description_it);

	/**
	 * Returns the level_t1 of this variabile.
	 *
	 * @return the level_t1 of this variabile
	 */
	public int getLevel_t1();

	/**
	 * Sets the level_t1 of this variabile.
	 *
	 * @param level_t1 the level_t1 of this variabile
	 */
	public void setLevel_t1(int level_t1);

	/**
	 * Returns the level_t2 of this variabile.
	 *
	 * @return the level_t2 of this variabile
	 */
	public int getLevel_t2();

	/**
	 * Sets the level_t2 of this variabile.
	 *
	 * @param level_t2 the level_t2 of this variabile
	 */
	public void setLevel_t2(int level_t2);

	/**
	 * Returns the level_v1 of this variabile.
	 *
	 * @return the level_v1 of this variabile
	 */
	public int getLevel_v1();

	/**
	 * Sets the level_v1 of this variabile.
	 *
	 * @param level_v1 the level_v1 of this variabile
	 */
	public void setLevel_v1(int level_v1);

	/**
	 * Returns the level_v2 of this variabile.
	 *
	 * @return the level_v2 of this variabile
	 */
	public int getLevel_v2();

	/**
	 * Sets the level_v2 of this variabile.
	 *
	 * @param level_v2 the level_v2 of this variabile
	 */
	public void setLevel_v2(int level_v2);

	/**
	 * Returns the trange_p1 of this variabile.
	 *
	 * @return the trange_p1 of this variabile
	 */
	public int getTrange_p1();

	/**
	 * Sets the trange_p1 of this variabile.
	 *
	 * @param trange_p1 the trange_p1 of this variabile
	 */
	public void setTrange_p1(int trange_p1);

	/**
	 * Returns the trange_p2 of this variabile.
	 *
	 * @return the trange_p2 of this variabile
	 */
	public int getTrange_p2();

	/**
	 * Sets the trange_p2 of this variabile.
	 *
	 * @param trange_p2 the trange_p2 of this variabile
	 */
	public void setTrange_p2(int trange_p2);

	/**
	 * Returns the trange_pind of this variabile.
	 *
	 * @return the trange_pind of this variabile
	 */
	public int getTrange_pind();

	/**
	 * Sets the trange_pind of this variabile.
	 *
	 * @param trange_pind the trange_pind of this variabile
	 */
	public void setTrange_pind(int trange_pind);

	/**
	 * Returns the unit of this variabile.
	 *
	 * @return the unit of this variabile
	 */
	@AutoEscape
	public String getUnit();

	/**
	 * Sets the unit of this variabile.
	 *
	 * @param unit the unit of this variabile
	 */
	public void setUnit(String unit);

	/**
	 * Returns the bcode of this variabile.
	 *
	 * @return the bcode of this variabile
	 */
	@AutoEscape
	public String getBcode();

	/**
	 * Sets the bcode of this variabile.
	 *
	 * @param bcode the bcode of this variabile
	 */
	public void setBcode(String bcode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.bollettino.model.Variabile variabile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.bollettino.model.Variabile> toCacheModel();

	@Override
	public it.eng.bollettino.model.Variabile toEscapedModel();

	@Override
	public it.eng.bollettino.model.Variabile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}