//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.16 at 05:20:21 PM CET 
//


package it.eng.parer.xmlGen.monitoraggio;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DatiSpecificiType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatiSpecificiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VersioneDatiSpecifici" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="MonitoraggioID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataCreazione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="Compilatore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataInizioValidita" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="DataFineValidita" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="ApprovatoreARPAE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DataFirmaARPAE" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="InvioResponsabiliTerritorio">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="SI"/>
 *               &lt;enumeration value="NO"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatiSpecificiType", namespace="m", propOrder = {
    "versioneDatiSpecifici",
    "monitoraggioID",
    "dataCreazione",
    "compilatore",
    "dataInizioValidita",
    "dataFineValidita",
    "approvatoreARPAE",
    "dataFirmaARPAE",
    "invioResponsabiliTerritorio"
})
public class DatiSpecificiTypeMonitoraggio {

    @XmlElement(name = "VersioneDatiSpecifici", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String versioneDatiSpecifici;
    @XmlElement(name = "MonitoraggioID", required = true)
    protected String monitoraggioID;
    @XmlElement(name = "DataCreazione", required = true)
    @XmlSchemaType(name = "dateTime")
    protected String dataCreazione;
    @XmlElement(name = "Compilatore", required = true)
    protected String compilatore;
    @XmlElement(name = "DataInizioValidita", required = true)
    @XmlSchemaType(name = "dateTime")
    protected String dataInizioValidita;
    @XmlElement(name = "DataFineValidita", required = true)
    @XmlSchemaType(name = "dateTime")
    protected String dataFineValidita;
    @XmlElement(name = "ApprovatoreARPAE", required = true)
    protected String approvatoreARPAE;
    @XmlElement(name = "DataFirmaARPAE", required = true)
    @XmlSchemaType(name = "dateTime")
    protected String dataFirmaARPAE;
    @XmlElement(name = "InvioResponsabiliTerritorio", required = true)
    protected String invioResponsabiliTerritorio;

    /**
     * Gets the value of the versioneDatiSpecifici property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersioneDatiSpecifici() {
        return versioneDatiSpecifici;
    }

    /**
     * Sets the value of the versioneDatiSpecifici property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersioneDatiSpecifici(String value) {
        this.versioneDatiSpecifici = value;
    }

    /**
     * Gets the value of the monitoraggioID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMonitoraggioID() {
        return monitoraggioID;
    }

    /**
     * Sets the value of the monitoraggioID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMonitoraggioID(String value) {
        this.monitoraggioID = value;
    }

    /**
     * Gets the value of the dataCreazione property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDataCreazione() {
        return dataCreazione;
    }

    /**
     * Sets the value of the dataCreazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataCreazione(String value) {
        this.dataCreazione = value;
    }

    /**
     * Gets the value of the compilatore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompilatore() {
        return compilatore;
    }

    /**
     * Sets the value of the compilatore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompilatore(String value) {
        this.compilatore = value;
    }

    /**
     * Gets the value of the dataInizioValidita property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDataInizioValidita() {
        return dataInizioValidita;
    }

    /**
     * Sets the value of the dataInizioValidita property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataInizioValidita(String value) {
        this.dataInizioValidita = value;
    }

    /**
     * Gets the value of the dataFineValidita property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDataFineValidita() {
        return dataFineValidita;
    }

    /**
     * Sets the value of the dataFineValidita property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataFineValidita(String value) {
        this.dataFineValidita = value;
    }

    /**
     * Gets the value of the approvatoreARPAE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovatoreARPAE() {
        return approvatoreARPAE;
    }

    /**
     * Sets the value of the approvatoreARPAE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovatoreARPAE(String value) {
        this.approvatoreARPAE = value;
    }

    /**
     * Gets the value of the dataFirmaARPAE property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public String getDataFirmaARPAE() {
        return dataFirmaARPAE;
    }

    /**
     * Sets the value of the dataFirmaARPAE property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataFirmaARPAE(String value) {
        this.dataFirmaARPAE = value;
    }

    /**
     * Gets the value of the invioResponsabiliTerritorio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvioResponsabiliTerritorio() {
        return invioResponsabiliTerritorio;
    }

    /**
     * Sets the value of the invioResponsabiliTerritorio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvioResponsabiliTerritorio(String value) {
        this.invioResponsabiliTerritorio = value;
    }

}
