/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerter.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import it.eng.allerter.model.AllertaParametro;
import it.eng.allerter.service.AllertaParametroLocalService;
import it.eng.allerter.service.persistence.AllertaFinder;
import it.eng.allerter.service.persistence.AllertaParametroPersistence;
import it.eng.allerter.service.persistence.AllertaPersistence;
import it.eng.allerter.service.persistence.AllertaStatoPersistence;
import it.eng.allerter.service.persistence.AllertaValangheFinder;
import it.eng.allerter.service.persistence.AllertaValanghePersistence;
import it.eng.allerter.service.persistence.AllertaValangheStatoPersistence;
import it.eng.allerter.service.persistence.AreaPersistence;
import it.eng.allerter.service.persistence.EmailPersistence;
import it.eng.allerter.service.persistence.FeedPersistence;
import it.eng.allerter.service.persistence.GeografiaPersistence;
import it.eng.allerter.service.persistence.LogInternoPersistence;
import it.eng.allerter.service.persistence.SMSFinder;
import it.eng.allerter.service.persistence.SMSPersistence;
import it.eng.allerter.service.persistence.StatoAllertamentoPersistence;
import it.eng.allerter.service.persistence.TipoEventoPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the allerta parametro local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.allerter.service.impl.AllertaParametroLocalServiceImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see it.eng.allerter.service.impl.AllertaParametroLocalServiceImpl
 * @generated
 */
public abstract class AllertaParametroLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AllertaParametroLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AllertaParametroLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.allerter.service.AllertaParametroLocalServiceUtil</code>.
	 */

	/**
	 * Adds the allerta parametro to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AllertaParametroLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param allertaParametro the allerta parametro
	 * @return the allerta parametro that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AllertaParametro addAllertaParametro(
		AllertaParametro allertaParametro) {

		allertaParametro.setNew(true);

		return allertaParametroPersistence.update(allertaParametro);
	}

	/**
	 * Creates a new allerta parametro with the primary key. Does not add the allerta parametro to the database.
	 *
	 * @param parametroId the primary key for the new allerta parametro
	 * @return the new allerta parametro
	 */
	@Override
	@Transactional(enabled = false)
	public AllertaParametro createAllertaParametro(String parametroId) {
		return allertaParametroPersistence.create(parametroId);
	}

	/**
	 * Deletes the allerta parametro with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AllertaParametroLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param parametroId the primary key of the allerta parametro
	 * @return the allerta parametro that was removed
	 * @throws PortalException if a allerta parametro with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AllertaParametro deleteAllertaParametro(String parametroId)
		throws PortalException {

		return allertaParametroPersistence.remove(parametroId);
	}

	/**
	 * Deletes the allerta parametro from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AllertaParametroLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param allertaParametro the allerta parametro
	 * @return the allerta parametro that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AllertaParametro deleteAllertaParametro(
		AllertaParametro allertaParametro) {

		return allertaParametroPersistence.remove(allertaParametro);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return allertaParametroPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AllertaParametro.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return allertaParametroPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerter.model.impl.AllertaParametroModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return allertaParametroPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerter.model.impl.AllertaParametroModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return allertaParametroPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return allertaParametroPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return allertaParametroPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AllertaParametro fetchAllertaParametro(String parametroId) {
		return allertaParametroPersistence.fetchByPrimaryKey(parametroId);
	}

	/**
	 * Returns the allerta parametro with the primary key.
	 *
	 * @param parametroId the primary key of the allerta parametro
	 * @return the allerta parametro
	 * @throws PortalException if a allerta parametro with the primary key could not be found
	 */
	@Override
	public AllertaParametro getAllertaParametro(String parametroId)
		throws PortalException {

		return allertaParametroPersistence.findByPrimaryKey(parametroId);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return allertaParametroPersistence.create((String)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement AllertaParametroLocalServiceImpl#deleteAllertaParametro(AllertaParametro) to avoid orphaned data");
		}

		return allertaParametroLocalService.deleteAllertaParametro(
			(AllertaParametro)persistedModel);
	}

	@Override
	public BasePersistence<AllertaParametro> getBasePersistence() {
		return allertaParametroPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return allertaParametroPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the allerta parametros.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.allerter.model.impl.AllertaParametroModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of allerta parametros
	 * @param end the upper bound of the range of allerta parametros (not inclusive)
	 * @return the range of allerta parametros
	 */
	@Override
	public List<AllertaParametro> getAllertaParametros(int start, int end) {
		return allertaParametroPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of allerta parametros.
	 *
	 * @return the number of allerta parametros
	 */
	@Override
	public int getAllertaParametrosCount() {
		return allertaParametroPersistence.countAll();
	}

	/**
	 * Updates the allerta parametro in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AllertaParametroLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param allertaParametro the allerta parametro
	 * @return the allerta parametro that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AllertaParametro updateAllertaParametro(
		AllertaParametro allertaParametro) {

		return allertaParametroPersistence.update(allertaParametro);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AllertaParametroLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		allertaParametroLocalService = (AllertaParametroLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AllertaParametroLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AllertaParametro.class;
	}

	protected String getModelClassName() {
		return AllertaParametro.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = allertaParametroPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AllertaPersistence allertaPersistence;

	@Reference
	protected AllertaFinder allertaFinder;

	protected AllertaParametroLocalService allertaParametroLocalService;

	@Reference
	protected AllertaParametroPersistence allertaParametroPersistence;

	@Reference
	protected AllertaStatoPersistence allertaStatoPersistence;

	@Reference
	protected AllertaValanghePersistence allertaValanghePersistence;

	@Reference
	protected AllertaValangheFinder allertaValangheFinder;

	@Reference
	protected AllertaValangheStatoPersistence allertaValangheStatoPersistence;

	@Reference
	protected AreaPersistence areaPersistence;

	@Reference
	protected EmailPersistence emailPersistence;

	@Reference
	protected FeedPersistence feedPersistence;

	@Reference
	protected GeografiaPersistence geografiaPersistence;

	@Reference
	protected LogInternoPersistence logInternoPersistence;

	@Reference
	protected SMSPersistence smsPersistence;

	@Reference
	protected SMSFinder smsFinder;

	@Reference
	protected StatoAllertamentoPersistence statoAllertamentoPersistence;

	@Reference
	protected TipoEventoPersistence tipoEventoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		AllertaParametroLocalServiceBaseImpl.class);

}