/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerter.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import it.eng.allerter.model.Geografia;
import it.eng.allerter.service.GeografiaService;
import it.eng.allerter.service.persistence.AllertaFinder;
import it.eng.allerter.service.persistence.AllertaParametroPersistence;
import it.eng.allerter.service.persistence.AllertaPersistence;
import it.eng.allerter.service.persistence.AllertaStatoPersistence;
import it.eng.allerter.service.persistence.AllertaValangheFinder;
import it.eng.allerter.service.persistence.AllertaValanghePersistence;
import it.eng.allerter.service.persistence.AllertaValangheStatoPersistence;
import it.eng.allerter.service.persistence.AreaPersistence;
import it.eng.allerter.service.persistence.EmailPersistence;
import it.eng.allerter.service.persistence.FeedPersistence;
import it.eng.allerter.service.persistence.GeografiaPersistence;
import it.eng.allerter.service.persistence.LogInternoPersistence;
import it.eng.allerter.service.persistence.SMSFinder;
import it.eng.allerter.service.persistence.SMSPersistence;
import it.eng.allerter.service.persistence.StatoAllertamentoPersistence;
import it.eng.allerter.service.persistence.TipoEventoPersistence;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the geografia remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.allerter.service.impl.GeografiaServiceImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see it.eng.allerter.service.impl.GeografiaServiceImpl
 * @generated
 */
public abstract class GeografiaServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, GeografiaService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>GeografiaService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.allerter.service.GeografiaServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			GeografiaService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		geografiaService = (GeografiaService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return GeografiaService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Geografia.class;
	}

	protected String getModelClassName() {
		return Geografia.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = geografiaPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected AllertaPersistence allertaPersistence;

	@Reference
	protected AllertaFinder allertaFinder;

	@Reference
	protected AllertaParametroPersistence allertaParametroPersistence;

	@Reference
	protected AllertaStatoPersistence allertaStatoPersistence;

	@Reference
	protected AllertaValanghePersistence allertaValanghePersistence;

	@Reference
	protected AllertaValangheFinder allertaValangheFinder;

	@Reference
	protected AllertaValangheStatoPersistence allertaValangheStatoPersistence;

	@Reference
	protected AreaPersistence areaPersistence;

	@Reference
	protected EmailPersistence emailPersistence;

	@Reference
	protected FeedPersistence feedPersistence;

	@Reference
	protected it.eng.allerter.service.GeografiaLocalService
		geografiaLocalService;

	protected GeografiaService geografiaService;

	@Reference
	protected GeografiaPersistence geografiaPersistence;

	@Reference
	protected LogInternoPersistence logInternoPersistence;

	@Reference
	protected SMSPersistence smsPersistence;

	@Reference
	protected SMSFinder smsFinder;

	@Reference
	protected StatoAllertamentoPersistence statoAllertamentoPersistence;

	@Reference
	protected TipoEventoPersistence tipoEventoPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		GeografiaServiceBaseImpl.class);

}