dependencies {
	api project(":modules:allerta-dewetra:allerta-dewetra-api")

	compileOnly group: "com.liferay.portal", name: "release.dxp.api"
}

buildService {
	apiDir = "../allerta-dewetra-api/src/main/java"
	testDir = "../allerta-dewetra-test/src/testIntegration/java"
}

group = "allerta.dewetra"