dependencies {
	api project(":modules:allerta-catasto:allerta-catasto-api")

	compileOnly group: "com.liferay.portal", name: "release.dxp.api"
}

buildService {
	apiDir = "../allerta-catasto-api/src/main/java"
	testDir = "../allerta-catasto-test/src/testIntegration/java"
}

group = "allerta.catasto"