/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package allerta.catasto.model.impl;

import allerta.catasto.model.EffettiSub;
import allerta.catasto.model.EffettiSubModel;
import allerta.catasto.service.persistence.EffettiSubPK;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the EffettiSub service. Represents a row in the &quot;CATASTO_EffettiSub&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EffettiSubModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EffettiSubImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EffettiSubImpl
 * @generated
 */
@JSON(strict = true)
public class EffettiSubModelImpl
	extends BaseModelImpl<EffettiSub> implements EffettiSubModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a effetti sub model instance should use the <code>EffettiSub</code> interface instead.
	 */
	public static final String TABLE_NAME = "CATASTO_EffettiSub";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"idEffetti", Types.BIGINT},
		{"descrizione", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idEffetti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CATASTO_EffettiSub (id_ LONG not null,idEffetti LONG not null,descrizione VARCHAR(75) null,primary key (id_, idEffetti))";

	public static final String TABLE_SQL_DROP = "drop table CATASTO_EffettiSub";

	public static final String ORDER_BY_JPQL = " ORDER BY effettiSub.id.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CATASTO_EffettiSub.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EffettiSubModelImpl() {
	}

	@Override
	public EffettiSubPK getPrimaryKey() {
		return new EffettiSubPK(_id, _idEffetti);
	}

	@Override
	public void setPrimaryKey(EffettiSubPK primaryKey) {
		setId(primaryKey.id);
		setIdEffetti(primaryKey.idEffetti);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new EffettiSubPK(_id, _idEffetti);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((EffettiSubPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return EffettiSub.class;
	}

	@Override
	public String getModelClassName() {
		return EffettiSub.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EffettiSub, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EffettiSub, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EffettiSub, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((EffettiSub)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EffettiSub, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EffettiSub, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EffettiSub)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EffettiSub, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EffettiSub, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EffettiSub, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EffettiSub, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<EffettiSub, Object>>();

			attributeGetterFunctions.put("id", EffettiSub::getId);
			attributeGetterFunctions.put("idEffetti", EffettiSub::getIdEffetti);
			attributeGetterFunctions.put(
				"descrizione", EffettiSub::getDescrizione);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EffettiSub, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EffettiSub, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<EffettiSub, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<EffettiSub, Long>)EffettiSub::setId);
			attributeSetterBiConsumers.put(
				"idEffetti",
				(BiConsumer<EffettiSub, Long>)EffettiSub::setIdEffetti);
			attributeSetterBiConsumers.put(
				"descrizione",
				(BiConsumer<EffettiSub, String>)EffettiSub::setDescrizione);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getIdEffetti() {
		return _idEffetti;
	}

	@Override
	public void setIdEffetti(long idEffetti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idEffetti = idEffetti;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return "";
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descrizione = descrizione;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public EffettiSub toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EffettiSub>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EffettiSubImpl effettiSubImpl = new EffettiSubImpl();

		effettiSubImpl.setId(getId());
		effettiSubImpl.setIdEffetti(getIdEffetti());
		effettiSubImpl.setDescrizione(getDescrizione());

		effettiSubImpl.resetOriginalValues();

		return effettiSubImpl;
	}

	@Override
	public EffettiSub cloneWithOriginalValues() {
		EffettiSubImpl effettiSubImpl = new EffettiSubImpl();

		effettiSubImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		effettiSubImpl.setIdEffetti(
			this.<Long>getColumnOriginalValue("idEffetti"));
		effettiSubImpl.setDescrizione(
			this.<String>getColumnOriginalValue("descrizione"));

		return effettiSubImpl;
	}

	@Override
	public int compareTo(EffettiSub effettiSub) {
		int value = 0;

		if (getId() < effettiSub.getId()) {
			value = -1;
		}
		else if (getId() > effettiSub.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EffettiSub)) {
			return false;
		}

		EffettiSub effettiSub = (EffettiSub)object;

		EffettiSubPK primaryKey = effettiSub.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EffettiSub> toCacheModel() {
		EffettiSubCacheModel effettiSubCacheModel = new EffettiSubCacheModel();

		effettiSubCacheModel.effettiSubPK = getPrimaryKey();

		effettiSubCacheModel.id = getId();

		effettiSubCacheModel.idEffetti = getIdEffetti();

		effettiSubCacheModel.descrizione = getDescrizione();

		String descrizione = effettiSubCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			effettiSubCacheModel.descrizione = null;
		}

		return effettiSubCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EffettiSub, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EffettiSub, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EffettiSub, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EffettiSub)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EffettiSub>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EffettiSub.class, ModelWrapper.class);

	}

	private long _id;
	private long _idEffetti;
	private String _descrizione;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EffettiSub, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EffettiSub)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("idEffetti", _idEffetti);
		_columnOriginalValues.put("descrizione", _descrizione);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("idEffetti", 2L);

		columnBitmasks.put("descrizione", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EffettiSub _escapedModel;

}