/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package allerta.catasto.model.impl;

import aQute.bnd.annotation.ProviderType;

import allerta.catasto.model.Effetti;
import allerta.catasto.model.EffettiModel;
import allerta.catasto.model.EffettiSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Effetti service. Represents a row in the &quot;CATASTO_Effetti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>EffettiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EffettiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EffettiImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class EffettiModelImpl
	extends BaseModelImpl<Effetti> implements EffettiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a effetti model instance should use the <code>Effetti</code> interface instead.
	 */
	public static final String TABLE_NAME = "CATASTO_Effetti";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"descrizione", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CATASTO_Effetti (id_ LONG not null primary key,descrizione VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table CATASTO_Effetti";

	public static final String ORDER_BY_JPQL = " ORDER BY effetti.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CATASTO_Effetti.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		allerta.catasto.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.allerta.catasto.model.Effetti"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		allerta.catasto.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.allerta.catasto.model.Effetti"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Effetti toModel(EffettiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Effetti model = new EffettiImpl();

		model.setId(soapModel.getId());
		model.setDescrizione(soapModel.getDescrizione());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Effetti> toModels(EffettiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Effetti> models = new ArrayList<Effetti>(soapModels.length);

		for (EffettiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		allerta.catasto.service.util.ServiceProps.get(
			"lock.expiration.time.allerta.catasto.model.Effetti"));

	public EffettiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Effetti.class;
	}

	@Override
	public String getModelClassName() {
		return Effetti.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Effetti, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Effetti, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Effetti, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Effetti)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Effetti, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Effetti, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Effetti)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Effetti, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Effetti, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Effetti, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Effetti, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Effetti, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Effetti, Object>>();
		Map<String, BiConsumer<Effetti, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Effetti, ?>>();

		attributeGetterFunctions.put(
			"id",
			new Function<Effetti, Object>() {

				@Override
				public Object apply(Effetti effetti) {
					return effetti.getId();
				}

			});
		attributeSetterBiConsumers.put(
			"id",
			new BiConsumer<Effetti, Object>() {

				@Override
				public void accept(Effetti effetti, Object id) {
					effetti.setId((Long)id);
				}

			});
		attributeGetterFunctions.put(
			"descrizione",
			new Function<Effetti, Object>() {

				@Override
				public Object apply(Effetti effetti) {
					return effetti.getDescrizione();
				}

			});
		attributeSetterBiConsumers.put(
			"descrizione",
			new BiConsumer<Effetti, Object>() {

				@Override
				public void accept(Effetti effetti, Object descrizione) {
					effetti.setDescrizione((String)descrizione);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return "";
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Effetti.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Effetti toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Effetti)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EffettiImpl effettiImpl = new EffettiImpl();

		effettiImpl.setId(getId());
		effettiImpl.setDescrizione(getDescrizione());

		effettiImpl.resetOriginalValues();

		return effettiImpl;
	}

	@Override
	public int compareTo(Effetti effetti) {
		int value = 0;

		if (getId() < effetti.getId()) {
			value = -1;
		}
		else if (getId() > effetti.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Effetti)) {
			return false;
		}

		Effetti effetti = (Effetti)obj;

		long primaryKey = effetti.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Effetti> toCacheModel() {
		EffettiCacheModel effettiCacheModel = new EffettiCacheModel();

		effettiCacheModel.id = getId();

		effettiCacheModel.descrizione = getDescrizione();

		String descrizione = effettiCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			effettiCacheModel.descrizione = null;
		}

		return effettiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Effetti, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Effetti, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Effetti, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Effetti)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Effetti, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Effetti, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Effetti, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Effetti)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		Effetti.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		Effetti.class, ModelWrapper.class
	};

	private long _id;
	private String _descrizione;
	private Effetti _escapedModel;

}