/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package allerta.catasto.model.impl;

import allerta.catasto.model.Segnalazione;
import allerta.catasto.model.SegnalazioneModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Segnalazione service. Represents a row in the &quot;CATASTO_Segnalazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SegnalazioneModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SegnalazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SegnalazioneImpl
 * @generated
 */
@JSON(strict = true)
public class SegnalazioneModelImpl
	extends BaseModelImpl<Segnalazione> implements SegnalazioneModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a segnalazione model instance should use the <code>Segnalazione</code> interface instead.
	 */
	public static final String TABLE_NAME = "CATASTO_Segnalazione";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"documentoAssociato", Types.BIGINT},
		{"dataEvento", Types.TIMESTAMP}, {"enteSegnalante", Types.VARCHAR},
		{"fonte", Types.BIGINT}, {"categoria", Types.BIGINT},
		{"sottocategoria", Types.BIGINT}, {"riferimento", Types.VARCHAR},
		{"descrizione", Types.VARCHAR}, {"note", Types.VARCHAR},
		{"area", Types.VARCHAR}, {"provincia", Types.VARCHAR},
		{"comune", Types.VARCHAR}, {"indirizzo", Types.VARCHAR},
		{"civico", Types.VARCHAR}, {"lat", Types.DOUBLE}, {"lon", Types.DOUBLE},
		{"effetti", Types.BIGINT}, {"effettiSub", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("documentoAssociato", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataEvento", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("enteSegnalante", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fonte", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoria", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sottocategoria", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("riferimento", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("note", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("area", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("provincia", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("comune", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("indirizzo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("civico", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lat", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("lon", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("effetti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("effettiSub", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CATASTO_Segnalazione (id_ LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,documentoAssociato LONG,dataEvento DATE null,enteSegnalante VARCHAR(75) null,fonte LONG,categoria LONG,sottocategoria LONG,riferimento VARCHAR(75) null,descrizione VARCHAR(75) null,note VARCHAR(75) null,area VARCHAR(75) null,provincia VARCHAR(75) null,comune VARCHAR(75) null,indirizzo VARCHAR(75) null,civico VARCHAR(75) null,lat DOUBLE,lon DOUBLE,effetti LONG,effettiSub LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table CATASTO_Segnalazione";

	public static final String ORDER_BY_JPQL = " ORDER BY segnalazione.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY CATASTO_Segnalazione.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOCUMENTOASSOCIATO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SegnalazioneModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Segnalazione.class;
	}

	@Override
	public String getModelClassName() {
		return Segnalazione.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Segnalazione, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Segnalazione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Segnalazione, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Segnalazione)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Segnalazione, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Segnalazione, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Segnalazione)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Segnalazione, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Segnalazione, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Segnalazione, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Segnalazione, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Segnalazione, Object>>();

			attributeGetterFunctions.put("id", Segnalazione::getId);
			attributeGetterFunctions.put("groupId", Segnalazione::getGroupId);
			attributeGetterFunctions.put(
				"companyId", Segnalazione::getCompanyId);
			attributeGetterFunctions.put("userId", Segnalazione::getUserId);
			attributeGetterFunctions.put("userName", Segnalazione::getUserName);
			attributeGetterFunctions.put(
				"createDate", Segnalazione::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Segnalazione::getModifiedDate);
			attributeGetterFunctions.put(
				"documentoAssociato", Segnalazione::getDocumentoAssociato);
			attributeGetterFunctions.put(
				"dataEvento", Segnalazione::getDataEvento);
			attributeGetterFunctions.put(
				"enteSegnalante", Segnalazione::getEnteSegnalante);
			attributeGetterFunctions.put("fonte", Segnalazione::getFonte);
			attributeGetterFunctions.put(
				"categoria", Segnalazione::getCategoria);
			attributeGetterFunctions.put(
				"sottocategoria", Segnalazione::getSottocategoria);
			attributeGetterFunctions.put(
				"riferimento", Segnalazione::getRiferimento);
			attributeGetterFunctions.put(
				"descrizione", Segnalazione::getDescrizione);
			attributeGetterFunctions.put("note", Segnalazione::getNote);
			attributeGetterFunctions.put("area", Segnalazione::getArea);
			attributeGetterFunctions.put(
				"provincia", Segnalazione::getProvincia);
			attributeGetterFunctions.put("comune", Segnalazione::getComune);
			attributeGetterFunctions.put(
				"indirizzo", Segnalazione::getIndirizzo);
			attributeGetterFunctions.put("civico", Segnalazione::getCivico);
			attributeGetterFunctions.put("lat", Segnalazione::getLat);
			attributeGetterFunctions.put("lon", Segnalazione::getLon);
			attributeGetterFunctions.put("effetti", Segnalazione::getEffetti);
			attributeGetterFunctions.put(
				"effettiSub", Segnalazione::getEffettiSub);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Segnalazione, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Segnalazione, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<Segnalazione, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Segnalazione, Long>)Segnalazione::setId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Segnalazione, Long>)Segnalazione::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Segnalazione, Long>)Segnalazione::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<Segnalazione, Long>)Segnalazione::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Segnalazione, String>)Segnalazione::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Segnalazione, Date>)Segnalazione::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Segnalazione, Date>)Segnalazione::setModifiedDate);
			attributeSetterBiConsumers.put(
				"documentoAssociato",
				(BiConsumer<Segnalazione, Long>)
					Segnalazione::setDocumentoAssociato);
			attributeSetterBiConsumers.put(
				"dataEvento",
				(BiConsumer<Segnalazione, Date>)Segnalazione::setDataEvento);
			attributeSetterBiConsumers.put(
				"enteSegnalante",
				(BiConsumer<Segnalazione, String>)
					Segnalazione::setEnteSegnalante);
			attributeSetterBiConsumers.put(
				"fonte",
				(BiConsumer<Segnalazione, Long>)Segnalazione::setFonte);
			attributeSetterBiConsumers.put(
				"categoria",
				(BiConsumer<Segnalazione, Long>)Segnalazione::setCategoria);
			attributeSetterBiConsumers.put(
				"sottocategoria",
				(BiConsumer<Segnalazione, Long>)
					Segnalazione::setSottocategoria);
			attributeSetterBiConsumers.put(
				"riferimento",
				(BiConsumer<Segnalazione, String>)Segnalazione::setRiferimento);
			attributeSetterBiConsumers.put(
				"descrizione",
				(BiConsumer<Segnalazione, String>)Segnalazione::setDescrizione);
			attributeSetterBiConsumers.put(
				"note",
				(BiConsumer<Segnalazione, String>)Segnalazione::setNote);
			attributeSetterBiConsumers.put(
				"area",
				(BiConsumer<Segnalazione, String>)Segnalazione::setArea);
			attributeSetterBiConsumers.put(
				"provincia",
				(BiConsumer<Segnalazione, String>)Segnalazione::setProvincia);
			attributeSetterBiConsumers.put(
				"comune",
				(BiConsumer<Segnalazione, String>)Segnalazione::setComune);
			attributeSetterBiConsumers.put(
				"indirizzo",
				(BiConsumer<Segnalazione, String>)Segnalazione::setIndirizzo);
			attributeSetterBiConsumers.put(
				"civico",
				(BiConsumer<Segnalazione, String>)Segnalazione::setCivico);
			attributeSetterBiConsumers.put(
				"lat", (BiConsumer<Segnalazione, Double>)Segnalazione::setLat);
			attributeSetterBiConsumers.put(
				"lon", (BiConsumer<Segnalazione, Double>)Segnalazione::setLon);
			attributeSetterBiConsumers.put(
				"effetti",
				(BiConsumer<Segnalazione, Long>)Segnalazione::setEffetti);
			attributeSetterBiConsumers.put(
				"effettiSub",
				(BiConsumer<Segnalazione, Long>)Segnalazione::setEffettiSub);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getDocumentoAssociato() {
		return _documentoAssociato;
	}

	@Override
	public void setDocumentoAssociato(long documentoAssociato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_documentoAssociato = documentoAssociato;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDocumentoAssociato() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("documentoAssociato"));
	}

	@JSON
	@Override
	public Date getDataEvento() {
		return _dataEvento;
	}

	@Override
	public void setDataEvento(Date dataEvento) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataEvento = dataEvento;
	}

	@JSON
	@Override
	public String getEnteSegnalante() {
		if (_enteSegnalante == null) {
			return "";
		}
		else {
			return _enteSegnalante;
		}
	}

	@Override
	public void setEnteSegnalante(String enteSegnalante) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_enteSegnalante = enteSegnalante;
	}

	@JSON
	@Override
	public long getFonte() {
		return _fonte;
	}

	@Override
	public void setFonte(long fonte) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fonte = fonte;
	}

	@JSON
	@Override
	public long getCategoria() {
		return _categoria;
	}

	@Override
	public void setCategoria(long categoria) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_categoria = categoria;
	}

	@JSON
	@Override
	public long getSottocategoria() {
		return _sottocategoria;
	}

	@Override
	public void setSottocategoria(long sottocategoria) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sottocategoria = sottocategoria;
	}

	@JSON
	@Override
	public String getRiferimento() {
		if (_riferimento == null) {
			return "";
		}
		else {
			return _riferimento;
		}
	}

	@Override
	public void setRiferimento(String riferimento) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_riferimento = riferimento;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return "";
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descrizione = descrizione;
	}

	@JSON
	@Override
	public String getNote() {
		if (_note == null) {
			return "";
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_note = note;
	}

	@JSON
	@Override
	public String getArea() {
		if (_area == null) {
			return "";
		}
		else {
			return _area;
		}
	}

	@Override
	public void setArea(String area) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_area = area;
	}

	@JSON
	@Override
	public String getProvincia() {
		if (_provincia == null) {
			return "";
		}
		else {
			return _provincia;
		}
	}

	@Override
	public void setProvincia(String provincia) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_provincia = provincia;
	}

	@JSON
	@Override
	public String getComune() {
		if (_comune == null) {
			return "";
		}
		else {
			return _comune;
		}
	}

	@Override
	public void setComune(String comune) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comune = comune;
	}

	@JSON
	@Override
	public String getIndirizzo() {
		if (_indirizzo == null) {
			return "";
		}
		else {
			return _indirizzo;
		}
	}

	@Override
	public void setIndirizzo(String indirizzo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_indirizzo = indirizzo;
	}

	@JSON
	@Override
	public String getCivico() {
		if (_civico == null) {
			return "";
		}
		else {
			return _civico;
		}
	}

	@Override
	public void setCivico(String civico) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_civico = civico;
	}

	@JSON
	@Override
	public double getLat() {
		return _lat;
	}

	@Override
	public void setLat(double lat) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lat = lat;
	}

	@JSON
	@Override
	public double getLon() {
		return _lon;
	}

	@Override
	public void setLon(double lon) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lon = lon;
	}

	@JSON
	@Override
	public long getEffetti() {
		return _effetti;
	}

	@Override
	public void setEffetti(long effetti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_effetti = effetti;
	}

	@JSON
	@Override
	public long getEffettiSub() {
		return _effettiSub;
	}

	@Override
	public void setEffettiSub(long effettiSub) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_effettiSub = effettiSub;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Segnalazione.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Segnalazione toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Segnalazione>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SegnalazioneImpl segnalazioneImpl = new SegnalazioneImpl();

		segnalazioneImpl.setId(getId());
		segnalazioneImpl.setGroupId(getGroupId());
		segnalazioneImpl.setCompanyId(getCompanyId());
		segnalazioneImpl.setUserId(getUserId());
		segnalazioneImpl.setUserName(getUserName());
		segnalazioneImpl.setCreateDate(getCreateDate());
		segnalazioneImpl.setModifiedDate(getModifiedDate());
		segnalazioneImpl.setDocumentoAssociato(getDocumentoAssociato());
		segnalazioneImpl.setDataEvento(getDataEvento());
		segnalazioneImpl.setEnteSegnalante(getEnteSegnalante());
		segnalazioneImpl.setFonte(getFonte());
		segnalazioneImpl.setCategoria(getCategoria());
		segnalazioneImpl.setSottocategoria(getSottocategoria());
		segnalazioneImpl.setRiferimento(getRiferimento());
		segnalazioneImpl.setDescrizione(getDescrizione());
		segnalazioneImpl.setNote(getNote());
		segnalazioneImpl.setArea(getArea());
		segnalazioneImpl.setProvincia(getProvincia());
		segnalazioneImpl.setComune(getComune());
		segnalazioneImpl.setIndirizzo(getIndirizzo());
		segnalazioneImpl.setCivico(getCivico());
		segnalazioneImpl.setLat(getLat());
		segnalazioneImpl.setLon(getLon());
		segnalazioneImpl.setEffetti(getEffetti());
		segnalazioneImpl.setEffettiSub(getEffettiSub());

		segnalazioneImpl.resetOriginalValues();

		return segnalazioneImpl;
	}

	@Override
	public Segnalazione cloneWithOriginalValues() {
		SegnalazioneImpl segnalazioneImpl = new SegnalazioneImpl();

		segnalazioneImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		segnalazioneImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		segnalazioneImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		segnalazioneImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		segnalazioneImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		segnalazioneImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		segnalazioneImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		segnalazioneImpl.setDocumentoAssociato(
			this.<Long>getColumnOriginalValue("documentoAssociato"));
		segnalazioneImpl.setDataEvento(
			this.<Date>getColumnOriginalValue("dataEvento"));
		segnalazioneImpl.setEnteSegnalante(
			this.<String>getColumnOriginalValue("enteSegnalante"));
		segnalazioneImpl.setFonte(this.<Long>getColumnOriginalValue("fonte"));
		segnalazioneImpl.setCategoria(
			this.<Long>getColumnOriginalValue("categoria"));
		segnalazioneImpl.setSottocategoria(
			this.<Long>getColumnOriginalValue("sottocategoria"));
		segnalazioneImpl.setRiferimento(
			this.<String>getColumnOriginalValue("riferimento"));
		segnalazioneImpl.setDescrizione(
			this.<String>getColumnOriginalValue("descrizione"));
		segnalazioneImpl.setNote(this.<String>getColumnOriginalValue("note"));
		segnalazioneImpl.setArea(this.<String>getColumnOriginalValue("area"));
		segnalazioneImpl.setProvincia(
			this.<String>getColumnOriginalValue("provincia"));
		segnalazioneImpl.setComune(
			this.<String>getColumnOriginalValue("comune"));
		segnalazioneImpl.setIndirizzo(
			this.<String>getColumnOriginalValue("indirizzo"));
		segnalazioneImpl.setCivico(
			this.<String>getColumnOriginalValue("civico"));
		segnalazioneImpl.setLat(this.<Double>getColumnOriginalValue("lat"));
		segnalazioneImpl.setLon(this.<Double>getColumnOriginalValue("lon"));
		segnalazioneImpl.setEffetti(
			this.<Long>getColumnOriginalValue("effetti"));
		segnalazioneImpl.setEffettiSub(
			this.<Long>getColumnOriginalValue("effettiSub"));

		return segnalazioneImpl;
	}

	@Override
	public int compareTo(Segnalazione segnalazione) {
		int value = 0;

		if (getId() < segnalazione.getId()) {
			value = -1;
		}
		else if (getId() > segnalazione.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Segnalazione)) {
			return false;
		}

		Segnalazione segnalazione = (Segnalazione)object;

		long primaryKey = segnalazione.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Segnalazione> toCacheModel() {
		SegnalazioneCacheModel segnalazioneCacheModel =
			new SegnalazioneCacheModel();

		segnalazioneCacheModel.id = getId();

		segnalazioneCacheModel.groupId = getGroupId();

		segnalazioneCacheModel.companyId = getCompanyId();

		segnalazioneCacheModel.userId = getUserId();

		segnalazioneCacheModel.userName = getUserName();

		String userName = segnalazioneCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			segnalazioneCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			segnalazioneCacheModel.createDate = createDate.getTime();
		}
		else {
			segnalazioneCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			segnalazioneCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			segnalazioneCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		segnalazioneCacheModel.documentoAssociato = getDocumentoAssociato();

		Date dataEvento = getDataEvento();

		if (dataEvento != null) {
			segnalazioneCacheModel.dataEvento = dataEvento.getTime();
		}
		else {
			segnalazioneCacheModel.dataEvento = Long.MIN_VALUE;
		}

		segnalazioneCacheModel.enteSegnalante = getEnteSegnalante();

		String enteSegnalante = segnalazioneCacheModel.enteSegnalante;

		if ((enteSegnalante != null) && (enteSegnalante.length() == 0)) {
			segnalazioneCacheModel.enteSegnalante = null;
		}

		segnalazioneCacheModel.fonte = getFonte();

		segnalazioneCacheModel.categoria = getCategoria();

		segnalazioneCacheModel.sottocategoria = getSottocategoria();

		segnalazioneCacheModel.riferimento = getRiferimento();

		String riferimento = segnalazioneCacheModel.riferimento;

		if ((riferimento != null) && (riferimento.length() == 0)) {
			segnalazioneCacheModel.riferimento = null;
		}

		segnalazioneCacheModel.descrizione = getDescrizione();

		String descrizione = segnalazioneCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			segnalazioneCacheModel.descrizione = null;
		}

		segnalazioneCacheModel.note = getNote();

		String note = segnalazioneCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			segnalazioneCacheModel.note = null;
		}

		segnalazioneCacheModel.area = getArea();

		String area = segnalazioneCacheModel.area;

		if ((area != null) && (area.length() == 0)) {
			segnalazioneCacheModel.area = null;
		}

		segnalazioneCacheModel.provincia = getProvincia();

		String provincia = segnalazioneCacheModel.provincia;

		if ((provincia != null) && (provincia.length() == 0)) {
			segnalazioneCacheModel.provincia = null;
		}

		segnalazioneCacheModel.comune = getComune();

		String comune = segnalazioneCacheModel.comune;

		if ((comune != null) && (comune.length() == 0)) {
			segnalazioneCacheModel.comune = null;
		}

		segnalazioneCacheModel.indirizzo = getIndirizzo();

		String indirizzo = segnalazioneCacheModel.indirizzo;

		if ((indirizzo != null) && (indirizzo.length() == 0)) {
			segnalazioneCacheModel.indirizzo = null;
		}

		segnalazioneCacheModel.civico = getCivico();

		String civico = segnalazioneCacheModel.civico;

		if ((civico != null) && (civico.length() == 0)) {
			segnalazioneCacheModel.civico = null;
		}

		segnalazioneCacheModel.lat = getLat();

		segnalazioneCacheModel.lon = getLon();

		segnalazioneCacheModel.effetti = getEffetti();

		segnalazioneCacheModel.effettiSub = getEffettiSub();

		return segnalazioneCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Segnalazione, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Segnalazione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Segnalazione, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Segnalazione)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Segnalazione>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Segnalazione.class, ModelWrapper.class);

	}

	private long _id;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _documentoAssociato;
	private Date _dataEvento;
	private String _enteSegnalante;
	private long _fonte;
	private long _categoria;
	private long _sottocategoria;
	private String _riferimento;
	private String _descrizione;
	private String _note;
	private String _area;
	private String _provincia;
	private String _comune;
	private String _indirizzo;
	private String _civico;
	private double _lat;
	private double _lon;
	private long _effetti;
	private long _effettiSub;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Segnalazione, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Segnalazione)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("documentoAssociato", _documentoAssociato);
		_columnOriginalValues.put("dataEvento", _dataEvento);
		_columnOriginalValues.put("enteSegnalante", _enteSegnalante);
		_columnOriginalValues.put("fonte", _fonte);
		_columnOriginalValues.put("categoria", _categoria);
		_columnOriginalValues.put("sottocategoria", _sottocategoria);
		_columnOriginalValues.put("riferimento", _riferimento);
		_columnOriginalValues.put("descrizione", _descrizione);
		_columnOriginalValues.put("note", _note);
		_columnOriginalValues.put("area", _area);
		_columnOriginalValues.put("provincia", _provincia);
		_columnOriginalValues.put("comune", _comune);
		_columnOriginalValues.put("indirizzo", _indirizzo);
		_columnOriginalValues.put("civico", _civico);
		_columnOriginalValues.put("lat", _lat);
		_columnOriginalValues.put("lon", _lon);
		_columnOriginalValues.put("effetti", _effetti);
		_columnOriginalValues.put("effettiSub", _effettiSub);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("createDate", 32L);

		columnBitmasks.put("modifiedDate", 64L);

		columnBitmasks.put("documentoAssociato", 128L);

		columnBitmasks.put("dataEvento", 256L);

		columnBitmasks.put("enteSegnalante", 512L);

		columnBitmasks.put("fonte", 1024L);

		columnBitmasks.put("categoria", 2048L);

		columnBitmasks.put("sottocategoria", 4096L);

		columnBitmasks.put("riferimento", 8192L);

		columnBitmasks.put("descrizione", 16384L);

		columnBitmasks.put("note", 32768L);

		columnBitmasks.put("area", 65536L);

		columnBitmasks.put("provincia", 131072L);

		columnBitmasks.put("comune", 262144L);

		columnBitmasks.put("indirizzo", 524288L);

		columnBitmasks.put("civico", 1048576L);

		columnBitmasks.put("lat", 2097152L);

		columnBitmasks.put("lon", 4194304L);

		columnBitmasks.put("effetti", 8388608L);

		columnBitmasks.put("effettiSub", 16777216L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Segnalazione _escapedModel;

}