/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.cache.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.cache.model.Dati;
import it.eng.cache.model.DatiModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Dati service. Represents a row in the &quot;CACHE_Dati&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DatiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DatiImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see DatiImpl
 * @generated
 */
@JSON(strict = true)
public class DatiModelImpl extends BaseModelImpl<Dati> implements DatiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dati model instance should use the <code>Dati</code> interface instead.
	 */
	public static final String TABLE_NAME = "CACHE_Dati";

	public static final Object[][] TABLE_COLUMNS = {
		{"idDati", Types.VARCHAR}, {"dato", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("idDati", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dato", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table CACHE_Dati (idDati VARCHAR(75) not null primary key,dato VARCHAR(75) null,createDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table CACHE_Dati";

	public static final String ORDER_BY_JPQL = " ORDER BY dati.dato ASC";

	public static final String ORDER_BY_SQL = " ORDER BY CACHE_Dati.dato ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DatiModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _idDati;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setIdDati(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idDati;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Dati.class;
	}

	@Override
	public String getModelClassName() {
		return Dati.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Dati, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Dati, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dati, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Dati)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Dati, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Dati, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Dati)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Dati, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Dati, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Dati, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Dati, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Dati, Object>>();

			attributeGetterFunctions.put("idDati", Dati::getIdDati);
			attributeGetterFunctions.put("dato", Dati::getDato);
			attributeGetterFunctions.put("createDate", Dati::getCreateDate);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Dati, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Dati, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Dati, ?>>();

			attributeSetterBiConsumers.put(
				"idDati", (BiConsumer<Dati, String>)Dati::setIdDati);
			attributeSetterBiConsumers.put(
				"dato", (BiConsumer<Dati, String>)Dati::setDato);
			attributeSetterBiConsumers.put(
				"createDate", (BiConsumer<Dati, Date>)Dati::setCreateDate);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getIdDati() {
		if (_idDati == null) {
			return "";
		}
		else {
			return _idDati;
		}
	}

	@Override
	public void setIdDati(String idDati) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idDati = idDati;
	}

	@JSON
	@Override
	public String getDato() {
		if (_dato == null) {
			return "";
		}
		else {
			return _dato;
		}
	}

	@Override
	public void setDato(String dato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dato = dato;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Dati toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Dati>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DatiImpl datiImpl = new DatiImpl();

		datiImpl.setIdDati(getIdDati());
		datiImpl.setDato(getDato());
		datiImpl.setCreateDate(getCreateDate());

		datiImpl.resetOriginalValues();

		return datiImpl;
	}

	@Override
	public Dati cloneWithOriginalValues() {
		DatiImpl datiImpl = new DatiImpl();

		datiImpl.setIdDati(this.<String>getColumnOriginalValue("idDati"));
		datiImpl.setDato(this.<String>getColumnOriginalValue("dato"));
		datiImpl.setCreateDate(this.<Date>getColumnOriginalValue("createDate"));

		return datiImpl;
	}

	@Override
	public int compareTo(Dati dati) {
		int value = 0;

		value = getDato().compareTo(dati.getDato());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Dati)) {
			return false;
		}

		Dati dati = (Dati)object;

		String primaryKey = dati.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Dati> toCacheModel() {
		DatiCacheModel datiCacheModel = new DatiCacheModel();

		datiCacheModel.idDati = getIdDati();

		String idDati = datiCacheModel.idDati;

		if ((idDati != null) && (idDati.length() == 0)) {
			datiCacheModel.idDati = null;
		}

		datiCacheModel.dato = getDato();

		String dato = datiCacheModel.dato;

		if ((dato != null) && (dato.length() == 0)) {
			datiCacheModel.dato = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			datiCacheModel.createDate = createDate.getTime();
		}
		else {
			datiCacheModel.createDate = Long.MIN_VALUE;
		}

		return datiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Dati, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Dati, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Dati, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Dati)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Dati>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Dati.class, ModelWrapper.class);

	}

	private String _idDati;
	private String _dato;
	private Date _createDate;

	public <T> T getColumnValue(String columnName) {
		Function<Dati, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Dati)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("idDati", _idDati);
		_columnOriginalValues.put("dato", _dato);
		_columnOriginalValues.put("createDate", _createDate);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("idDati", 1L);

		columnBitmasks.put("dato", 2L);

		columnBitmasks.put("createDate", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Dati _escapedModel;

}