dependencies {
	compileOnly group: "com.liferay.portal", name: "release.dxp.api"

	cssBuilder group: "com.liferay", name: "com.liferay.css.builder", version: "3.1.4"

	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel"
	compileOnly group: "com.liferay.portal", name: "com.liferay.util.taglib"
	compileOnly group: "javax.portlet", name: "portlet-api"
	compileOnly group: "jstl", name: "jstl"
	compileOnly group: "org.osgi", name: "org.osgi.service.component.annotations"
	compileOnly group: 'javax.mail', name: 'mail', version: '1.4.7'
	
	compileOnly project(":modules:allerta-base")
	compileOnly project(":modules:allerta-allertaer:allerta-allertaer-api")
	compileOnly project(":modules:allerta-bollettino:allerta-bollettino-api")
	//compileOnly project(":modules:allerta-bollettino:allerta-bollettino-service")
	compileOnly project(":modules:allerta-legacy")

}