/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.previsioni.meteo.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Img service. Represents a row in the &quot;prev_meteo_Img&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.previsioni.meteo.model.impl.ImgModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.previsioni.meteo.model.impl.ImgImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Img
 * @generated
 */
@ProviderType
public interface ImgModel extends BaseModel<Img> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a img model instance should use the {@link Img} interface instead.
	 */

	/**
	 * Returns the primary key of this img.
	 *
	 * @return the primary key of this img
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this img.
	 *
	 * @param primaryKey the primary key of this img
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this img.
	 *
	 * @return the ID of this img
	 */
	public long getId();

	/**
	 * Sets the ID of this img.
	 *
	 * @param id the ID of this img
	 */
	public void setId(long id);

	/**
	 * Returns the daypart of this img.
	 *
	 * @return the daypart of this img
	 */
	@AutoEscape
	public String getDaypart();

	/**
	 * Sets the daypart of this img.
	 *
	 * @param daypart the daypart of this img
	 */
	public void setDaypart(String daypart);

	/**
	 * Returns the day of this img.
	 *
	 * @return the day of this img
	 */
	@AutoEscape
	public String getDay();

	/**
	 * Sets the day of this img.
	 *
	 * @param day the day of this img
	 */
	public void setDay(String day);

	/**
	 * Returns the provincia of this img.
	 *
	 * @return the provincia of this img
	 */
	@AutoEscape
	public String getProvincia();

	/**
	 * Sets the provincia of this img.
	 *
	 * @param provincia the provincia of this img
	 */
	public void setProvincia(String provincia);

	/**
	 * Returns the inserted of this img.
	 *
	 * @return the inserted of this img
	 */
	public Date getInserted();

	/**
	 * Sets the inserted of this img.
	 *
	 * @param inserted the inserted of this img
	 */
	public void setInserted(Date inserted);

	/**
	 * Returns the data of this img.
	 *
	 * @return the data of this img
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this img.
	 *
	 * @param data the data of this img
	 */
	public void setData(String data);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.previsioni.meteo.model.Img img);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.previsioni.meteo.model.Img> toCacheModel();

	@Override
	public it.eng.previsioni.meteo.model.Img toEscapedModel();

	@Override
	public it.eng.previsioni.meteo.model.Img toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}