/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package allerta.catasto.service.base;

import aQute.bnd.annotation.ProviderType;

import allerta.catasto.model.Effetti;
import allerta.catasto.service.EffettiLocalService;
import allerta.catasto.service.persistence.CategoriaPersistence;
import allerta.catasto.service.persistence.EffettiPersistence;
import allerta.catasto.service.persistence.EffettiSubPersistence;
import allerta.catasto.service.persistence.FontePersistence;
import allerta.catasto.service.persistence.SegnalazionePersistence;
import allerta.catasto.service.persistence.SottocategoriaPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the effetti local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link allerta.catasto.service.impl.EffettiLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see allerta.catasto.service.impl.EffettiLocalServiceImpl
 * @generated
 */
@ProviderType
public abstract class EffettiLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements EffettiLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EffettiLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>allerta.catasto.service.EffettiLocalServiceUtil</code>.
	 */

	/**
	 * Adds the effetti to the database. Also notifies the appropriate model listeners.
	 *
	 * @param effetti the effetti
	 * @return the effetti that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Effetti addEffetti(Effetti effetti) {
		effetti.setNew(true);

		return effettiPersistence.update(effetti);
	}

	/**
	 * Creates a new effetti with the primary key. Does not add the effetti to the database.
	 *
	 * @param id the primary key for the new effetti
	 * @return the new effetti
	 */
	@Override
	@Transactional(enabled = false)
	public Effetti createEffetti(long id) {
		return effettiPersistence.create(id);
	}

	/**
	 * Deletes the effetti with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the effetti
	 * @return the effetti that was removed
	 * @throws PortalException if a effetti with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Effetti deleteEffetti(long id) throws PortalException {
		return effettiPersistence.remove(id);
	}

	/**
	 * Deletes the effetti from the database. Also notifies the appropriate model listeners.
	 *
	 * @param effetti the effetti
	 * @return the effetti that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Effetti deleteEffetti(Effetti effetti) {
		return effettiPersistence.remove(effetti);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			Effetti.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return effettiPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>allerta.catasto.model.impl.EffettiModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return effettiPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>allerta.catasto.model.impl.EffettiModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return effettiPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return effettiPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return effettiPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public Effetti fetchEffetti(long id) {
		return effettiPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the effetti with the primary key.
	 *
	 * @param id the primary key of the effetti
	 * @return the effetti
	 * @throws PortalException if a effetti with the primary key could not be found
	 */
	@Override
	public Effetti getEffetti(long id) throws PortalException {
		return effettiPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(effettiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Effetti.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			effettiLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Effetti.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(effettiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Effetti.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return effettiLocalService.deleteEffetti((Effetti)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return effettiPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the effettis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code>), then the query will include the default ORDER BY logic from <code>allerta.catasto.model.impl.EffettiModelImpl</code>. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of effettis
	 * @param end the upper bound of the range of effettis (not inclusive)
	 * @return the range of effettis
	 */
	@Override
	public List<Effetti> getEffettis(int start, int end) {
		return effettiPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of effettis.
	 *
	 * @return the number of effettis
	 */
	@Override
	public int getEffettisCount() {
		return effettiPersistence.countAll();
	}

	/**
	 * Updates the effetti in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param effetti the effetti
	 * @return the effetti that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Effetti updateEffetti(Effetti effetti) {
		return effettiPersistence.update(effetti);
	}

	/**
	 * Returns the categoria local service.
	 *
	 * @return the categoria local service
	 */
	public allerta.catasto.service.CategoriaLocalService
		getCategoriaLocalService() {

		return categoriaLocalService;
	}

	/**
	 * Sets the categoria local service.
	 *
	 * @param categoriaLocalService the categoria local service
	 */
	public void setCategoriaLocalService(
		allerta.catasto.service.CategoriaLocalService categoriaLocalService) {

		this.categoriaLocalService = categoriaLocalService;
	}

	/**
	 * Returns the categoria persistence.
	 *
	 * @return the categoria persistence
	 */
	public CategoriaPersistence getCategoriaPersistence() {
		return categoriaPersistence;
	}

	/**
	 * Sets the categoria persistence.
	 *
	 * @param categoriaPersistence the categoria persistence
	 */
	public void setCategoriaPersistence(
		CategoriaPersistence categoriaPersistence) {

		this.categoriaPersistence = categoriaPersistence;
	}

	/**
	 * Returns the effetti local service.
	 *
	 * @return the effetti local service
	 */
	public EffettiLocalService getEffettiLocalService() {
		return effettiLocalService;
	}

	/**
	 * Sets the effetti local service.
	 *
	 * @param effettiLocalService the effetti local service
	 */
	public void setEffettiLocalService(
		EffettiLocalService effettiLocalService) {

		this.effettiLocalService = effettiLocalService;
	}

	/**
	 * Returns the effetti persistence.
	 *
	 * @return the effetti persistence
	 */
	public EffettiPersistence getEffettiPersistence() {
		return effettiPersistence;
	}

	/**
	 * Sets the effetti persistence.
	 *
	 * @param effettiPersistence the effetti persistence
	 */
	public void setEffettiPersistence(EffettiPersistence effettiPersistence) {
		this.effettiPersistence = effettiPersistence;
	}

	/**
	 * Returns the effetti sub local service.
	 *
	 * @return the effetti sub local service
	 */
	public allerta.catasto.service.EffettiSubLocalService
		getEffettiSubLocalService() {

		return effettiSubLocalService;
	}

	/**
	 * Sets the effetti sub local service.
	 *
	 * @param effettiSubLocalService the effetti sub local service
	 */
	public void setEffettiSubLocalService(
		allerta.catasto.service.EffettiSubLocalService effettiSubLocalService) {

		this.effettiSubLocalService = effettiSubLocalService;
	}

	/**
	 * Returns the effetti sub persistence.
	 *
	 * @return the effetti sub persistence
	 */
	public EffettiSubPersistence getEffettiSubPersistence() {
		return effettiSubPersistence;
	}

	/**
	 * Sets the effetti sub persistence.
	 *
	 * @param effettiSubPersistence the effetti sub persistence
	 */
	public void setEffettiSubPersistence(
		EffettiSubPersistence effettiSubPersistence) {

		this.effettiSubPersistence = effettiSubPersistence;
	}

	/**
	 * Returns the fonte local service.
	 *
	 * @return the fonte local service
	 */
	public allerta.catasto.service.FonteLocalService getFonteLocalService() {
		return fonteLocalService;
	}

	/**
	 * Sets the fonte local service.
	 *
	 * @param fonteLocalService the fonte local service
	 */
	public void setFonteLocalService(
		allerta.catasto.service.FonteLocalService fonteLocalService) {

		this.fonteLocalService = fonteLocalService;
	}

	/**
	 * Returns the fonte persistence.
	 *
	 * @return the fonte persistence
	 */
	public FontePersistence getFontePersistence() {
		return fontePersistence;
	}

	/**
	 * Sets the fonte persistence.
	 *
	 * @param fontePersistence the fonte persistence
	 */
	public void setFontePersistence(FontePersistence fontePersistence) {
		this.fontePersistence = fontePersistence;
	}

	/**
	 * Returns the segnalazione local service.
	 *
	 * @return the segnalazione local service
	 */
	public allerta.catasto.service.SegnalazioneLocalService
		getSegnalazioneLocalService() {

		return segnalazioneLocalService;
	}

	/**
	 * Sets the segnalazione local service.
	 *
	 * @param segnalazioneLocalService the segnalazione local service
	 */
	public void setSegnalazioneLocalService(
		allerta.catasto.service.SegnalazioneLocalService
			segnalazioneLocalService) {

		this.segnalazioneLocalService = segnalazioneLocalService;
	}

	/**
	 * Returns the segnalazione persistence.
	 *
	 * @return the segnalazione persistence
	 */
	public SegnalazionePersistence getSegnalazionePersistence() {
		return segnalazionePersistence;
	}

	/**
	 * Sets the segnalazione persistence.
	 *
	 * @param segnalazionePersistence the segnalazione persistence
	 */
	public void setSegnalazionePersistence(
		SegnalazionePersistence segnalazionePersistence) {

		this.segnalazionePersistence = segnalazionePersistence;
	}

	/**
	 * Returns the sottocategoria local service.
	 *
	 * @return the sottocategoria local service
	 */
	public allerta.catasto.service.SottocategoriaLocalService
		getSottocategoriaLocalService() {

		return sottocategoriaLocalService;
	}

	/**
	 * Sets the sottocategoria local service.
	 *
	 * @param sottocategoriaLocalService the sottocategoria local service
	 */
	public void setSottocategoriaLocalService(
		allerta.catasto.service.SottocategoriaLocalService
			sottocategoriaLocalService) {

		this.sottocategoriaLocalService = sottocategoriaLocalService;
	}

	/**
	 * Returns the sottocategoria persistence.
	 *
	 * @return the sottocategoria persistence
	 */
	public SottocategoriaPersistence getSottocategoriaPersistence() {
		return sottocategoriaPersistence;
	}

	/**
	 * Sets the sottocategoria persistence.
	 *
	 * @param sottocategoriaPersistence the sottocategoria persistence
	 */
	public void setSottocategoriaPersistence(
		SottocategoriaPersistence sottocategoriaPersistence) {

		this.sottocategoriaPersistence = sottocategoriaPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService
		getClassNameLocalService() {

		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService
			classNameLocalService) {

		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {

		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService
		getResourceLocalService() {

		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService
			resourceLocalService) {

		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService
		getUserLocalService() {

		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {

		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"allerta.catasto.model.Effetti", effettiLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"allerta.catasto.model.Effetti");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EffettiLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Effetti.class;
	}

	protected String getModelClassName() {
		return Effetti.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = effettiPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = allerta.catasto.service.CategoriaLocalService.class)
	protected allerta.catasto.service.CategoriaLocalService
		categoriaLocalService;

	@BeanReference(type = CategoriaPersistence.class)
	protected CategoriaPersistence categoriaPersistence;

	@BeanReference(type = EffettiLocalService.class)
	protected EffettiLocalService effettiLocalService;

	@BeanReference(type = EffettiPersistence.class)
	protected EffettiPersistence effettiPersistence;

	@BeanReference(type = allerta.catasto.service.EffettiSubLocalService.class)
	protected allerta.catasto.service.EffettiSubLocalService
		effettiSubLocalService;

	@BeanReference(type = EffettiSubPersistence.class)
	protected EffettiSubPersistence effettiSubPersistence;

	@BeanReference(type = allerta.catasto.service.FonteLocalService.class)
	protected allerta.catasto.service.FonteLocalService fonteLocalService;

	@BeanReference(type = FontePersistence.class)
	protected FontePersistence fontePersistence;

	@BeanReference(
		type = allerta.catasto.service.SegnalazioneLocalService.class
	)
	protected allerta.catasto.service.SegnalazioneLocalService
		segnalazioneLocalService;

	@BeanReference(type = SegnalazionePersistence.class)
	protected SegnalazionePersistence segnalazionePersistence;

	@BeanReference(
		type = allerta.catasto.service.SottocategoriaLocalService.class
	)
	protected allerta.catasto.service.SottocategoriaLocalService
		sottocategoriaLocalService;

	@BeanReference(type = SottocategoriaPersistence.class)
	protected SottocategoriaPersistence sottocategoriaPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ClassNameLocalService.class
	)
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.ResourceLocalService.class
	)
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@ServiceReference(
		type = com.liferay.portal.kernel.service.UserLocalService.class
	)
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}