dependencies {
	api project(":modules:allerta-verifica:allerta-verifica-api")

	compileOnly group: "com.liferay.portal", name: "release.dxp.api"
}

buildService {
	apiDir = "../allerta-verifica-api/src/main/java"
	testDir = "../allerta-verifica-test/src/testIntegration/java"
}

group = "allerta.verifica"