/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.allerter.model.Allerta;
import it.eng.allerter.model.AllertaModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Allerta service. Represents a row in the &quot;ALLERTER_Allerta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AllertaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AllertaImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see AllertaImpl
 * @generated
 */
@JSON(strict = true)
public class AllertaModelImpl
	extends BaseModelImpl<Allerta> implements AllertaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a allerta model instance should use the <code>Allerta</code> interface instead.
	 */
	public static final String TABLE_NAME = "ALLERTER_Allerta";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"allertaId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"creatorName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"stato", Types.INTEGER},
		{"numero", Types.VARCHAR}, {"progressivo", Types.INTEGER},
		{"anno", Types.INTEGER}, {"dataEmissione", Types.TIMESTAMP},
		{"dataInizio", Types.TIMESTAMP}, {"dataFine", Types.TIMESTAMP},
		{"descrizioneMeteo", Types.VARCHAR}, {"tendenza", Types.INTEGER},
		{"note", Types.VARCHAR}, {"riferimenti", Types.VARCHAR},
		{"utenteFirmaArpaId", Types.BIGINT}, {"dataFirmaArpa", Types.TIMESTAMP},
		{"utenteFirmaProtId", Types.BIGINT}, {"dataFirmaProt", Types.TIMESTAMP},
		{"parentId", Types.BIGINT}, {"sintesi", Types.VARCHAR},
		{"sintesiEng", Types.VARCHAR}, {"link", Types.VARCHAR},
		{"titolo", Types.VARCHAR}, {"titoloEng", Types.VARCHAR},
		{"tipoAllerta", Types.BOOLEAN}, {"hash", Types.VARCHAR},
		{"sintesiBriefing", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("allertaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("creatorName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("stato", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("numero", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("progressivo", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("anno", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dataEmissione", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataInizio", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataFine", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("descrizioneMeteo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tendenza", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("note", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("riferimenti", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utenteFirmaArpaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataFirmaArpa", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("utenteFirmaProtId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataFirmaProt", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sintesi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sintesiEng", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("link", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("titolo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("titoloEng", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tipoAllerta", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hash", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sintesiBriefing", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ALLERTER_Allerta (uuid_ VARCHAR(75) null,allertaId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,creatorName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,stato INTEGER,numero VARCHAR(75) null,progressivo INTEGER,anno INTEGER,dataEmissione DATE null,dataInizio DATE null,dataFine DATE null,descrizioneMeteo VARCHAR(75) null,tendenza INTEGER,note VARCHAR(75) null,riferimenti VARCHAR(75) null,utenteFirmaArpaId LONG,dataFirmaArpa DATE null,utenteFirmaProtId LONG,dataFirmaProt DATE null,parentId LONG,sintesi VARCHAR(75) null,sintesiEng VARCHAR(75) null,link VARCHAR(75) null,titolo VARCHAR(75) null,titoloEng VARCHAR(75) null,tipoAllerta BOOLEAN,hash VARCHAR(75) null,sintesiBriefing VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ALLERTER_Allerta";

	public static final String ORDER_BY_JPQL = " ORDER BY allerta.numero ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ALLERTER_Allerta.numero ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NUMERO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AllertaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _allertaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAllertaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _allertaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Allerta.class;
	}

	@Override
	public String getModelClassName() {
		return Allerta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Allerta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Allerta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Allerta, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Allerta)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Allerta, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Allerta, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Allerta)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Allerta, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Allerta, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Allerta, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Allerta, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Allerta, Object>>();

			attributeGetterFunctions.put("uuid", Allerta::getUuid);
			attributeGetterFunctions.put("allertaId", Allerta::getAllertaId);
			attributeGetterFunctions.put("groupId", Allerta::getGroupId);
			attributeGetterFunctions.put("companyId", Allerta::getCompanyId);
			attributeGetterFunctions.put("userId", Allerta::getUserId);
			attributeGetterFunctions.put("userName", Allerta::getUserName);
			attributeGetterFunctions.put(
				"creatorName", Allerta::getCreatorName);
			attributeGetterFunctions.put("createDate", Allerta::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Allerta::getModifiedDate);
			attributeGetterFunctions.put("stato", Allerta::getStato);
			attributeGetterFunctions.put("numero", Allerta::getNumero);
			attributeGetterFunctions.put(
				"progressivo", Allerta::getProgressivo);
			attributeGetterFunctions.put("anno", Allerta::getAnno);
			attributeGetterFunctions.put(
				"dataEmissione", Allerta::getDataEmissione);
			attributeGetterFunctions.put("dataInizio", Allerta::getDataInizio);
			attributeGetterFunctions.put("dataFine", Allerta::getDataFine);
			attributeGetterFunctions.put(
				"descrizioneMeteo", Allerta::getDescrizioneMeteo);
			attributeGetterFunctions.put("tendenza", Allerta::getTendenza);
			attributeGetterFunctions.put("note", Allerta::getNote);
			attributeGetterFunctions.put(
				"riferimenti", Allerta::getRiferimenti);
			attributeGetterFunctions.put(
				"utenteFirmaArpaId", Allerta::getUtenteFirmaArpaId);
			attributeGetterFunctions.put(
				"dataFirmaArpa", Allerta::getDataFirmaArpa);
			attributeGetterFunctions.put(
				"utenteFirmaProtId", Allerta::getUtenteFirmaProtId);
			attributeGetterFunctions.put(
				"dataFirmaProt", Allerta::getDataFirmaProt);
			attributeGetterFunctions.put("parentId", Allerta::getParentId);
			attributeGetterFunctions.put("sintesi", Allerta::getSintesi);
			attributeGetterFunctions.put("sintesiEng", Allerta::getSintesiEng);
			attributeGetterFunctions.put("link", Allerta::getLink);
			attributeGetterFunctions.put("titolo", Allerta::getTitolo);
			attributeGetterFunctions.put("titoloEng", Allerta::getTitoloEng);
			attributeGetterFunctions.put(
				"tipoAllerta", Allerta::getTipoAllerta);
			attributeGetterFunctions.put("hash", Allerta::getHash);
			attributeGetterFunctions.put(
				"sintesiBriefing", Allerta::getSintesiBriefing);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Allerta, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Allerta, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Allerta, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Allerta, String>)Allerta::setUuid);
			attributeSetterBiConsumers.put(
				"allertaId", (BiConsumer<Allerta, Long>)Allerta::setAllertaId);
			attributeSetterBiConsumers.put(
				"groupId", (BiConsumer<Allerta, Long>)Allerta::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId", (BiConsumer<Allerta, Long>)Allerta::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Allerta, Long>)Allerta::setUserId);
			attributeSetterBiConsumers.put(
				"userName", (BiConsumer<Allerta, String>)Allerta::setUserName);
			attributeSetterBiConsumers.put(
				"creatorName",
				(BiConsumer<Allerta, String>)Allerta::setCreatorName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Allerta, Date>)Allerta::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Allerta, Date>)Allerta::setModifiedDate);
			attributeSetterBiConsumers.put(
				"stato", (BiConsumer<Allerta, Integer>)Allerta::setStato);
			attributeSetterBiConsumers.put(
				"numero", (BiConsumer<Allerta, String>)Allerta::setNumero);
			attributeSetterBiConsumers.put(
				"progressivo",
				(BiConsumer<Allerta, Integer>)Allerta::setProgressivo);
			attributeSetterBiConsumers.put(
				"anno", (BiConsumer<Allerta, Integer>)Allerta::setAnno);
			attributeSetterBiConsumers.put(
				"dataEmissione",
				(BiConsumer<Allerta, Date>)Allerta::setDataEmissione);
			attributeSetterBiConsumers.put(
				"dataInizio",
				(BiConsumer<Allerta, Date>)Allerta::setDataInizio);
			attributeSetterBiConsumers.put(
				"dataFine", (BiConsumer<Allerta, Date>)Allerta::setDataFine);
			attributeSetterBiConsumers.put(
				"descrizioneMeteo",
				(BiConsumer<Allerta, String>)Allerta::setDescrizioneMeteo);
			attributeSetterBiConsumers.put(
				"tendenza", (BiConsumer<Allerta, Integer>)Allerta::setTendenza);
			attributeSetterBiConsumers.put(
				"note", (BiConsumer<Allerta, String>)Allerta::setNote);
			attributeSetterBiConsumers.put(
				"riferimenti",
				(BiConsumer<Allerta, String>)Allerta::setRiferimenti);
			attributeSetterBiConsumers.put(
				"utenteFirmaArpaId",
				(BiConsumer<Allerta, Long>)Allerta::setUtenteFirmaArpaId);
			attributeSetterBiConsumers.put(
				"dataFirmaArpa",
				(BiConsumer<Allerta, Date>)Allerta::setDataFirmaArpa);
			attributeSetterBiConsumers.put(
				"utenteFirmaProtId",
				(BiConsumer<Allerta, Long>)Allerta::setUtenteFirmaProtId);
			attributeSetterBiConsumers.put(
				"dataFirmaProt",
				(BiConsumer<Allerta, Date>)Allerta::setDataFirmaProt);
			attributeSetterBiConsumers.put(
				"parentId", (BiConsumer<Allerta, Long>)Allerta::setParentId);
			attributeSetterBiConsumers.put(
				"sintesi", (BiConsumer<Allerta, String>)Allerta::setSintesi);
			attributeSetterBiConsumers.put(
				"sintesiEng",
				(BiConsumer<Allerta, String>)Allerta::setSintesiEng);
			attributeSetterBiConsumers.put(
				"link", (BiConsumer<Allerta, String>)Allerta::setLink);
			attributeSetterBiConsumers.put(
				"titolo", (BiConsumer<Allerta, String>)Allerta::setTitolo);
			attributeSetterBiConsumers.put(
				"titoloEng",
				(BiConsumer<Allerta, String>)Allerta::setTitoloEng);
			attributeSetterBiConsumers.put(
				"tipoAllerta",
				(BiConsumer<Allerta, Boolean>)Allerta::setTipoAllerta);
			attributeSetterBiConsumers.put(
				"hash", (BiConsumer<Allerta, String>)Allerta::setHash);
			attributeSetterBiConsumers.put(
				"sintesiBriefing",
				(BiConsumer<Allerta, String>)Allerta::setSintesiBriefing);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAllertaId() {
		return _allertaId;
	}

	@Override
	public void setAllertaId(long allertaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allertaId = allertaId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public String getCreatorName() {
		if (_creatorName == null) {
			return "";
		}
		else {
			return _creatorName;
		}
	}

	@Override
	public void setCreatorName(String creatorName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creatorName = creatorName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStato() {
		return _stato;
	}

	@Override
	public void setStato(int stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stato = stato;
	}

	@JSON
	@Override
	public String getNumero() {
		if (_numero == null) {
			return "";
		}
		else {
			return _numero;
		}
	}

	@Override
	public void setNumero(String numero) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numero = numero;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNumero() {
		return getColumnOriginalValue("numero");
	}

	@JSON
	@Override
	public int getProgressivo() {
		return _progressivo;
	}

	@Override
	public void setProgressivo(int progressivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_progressivo = progressivo;
	}

	@JSON
	@Override
	public int getAnno() {
		return _anno;
	}

	@Override
	public void setAnno(int anno) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anno = anno;
	}

	@JSON
	@Override
	public Date getDataEmissione() {
		return _dataEmissione;
	}

	@Override
	public void setDataEmissione(Date dataEmissione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataEmissione = dataEmissione;
	}

	@JSON
	@Override
	public Date getDataInizio() {
		return _dataInizio;
	}

	@Override
	public void setDataInizio(Date dataInizio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataInizio = dataInizio;
	}

	@JSON
	@Override
	public Date getDataFine() {
		return _dataFine;
	}

	@Override
	public void setDataFine(Date dataFine) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataFine = dataFine;
	}

	@JSON
	@Override
	public String getDescrizioneMeteo() {
		if (_descrizioneMeteo == null) {
			return "";
		}
		else {
			return _descrizioneMeteo;
		}
	}

	@Override
	public void setDescrizioneMeteo(String descrizioneMeteo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descrizioneMeteo = descrizioneMeteo;
	}

	@JSON
	@Override
	public int getTendenza() {
		return _tendenza;
	}

	@Override
	public void setTendenza(int tendenza) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tendenza = tendenza;
	}

	@JSON
	@Override
	public String getNote() {
		if (_note == null) {
			return "";
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_note = note;
	}

	@JSON
	@Override
	public String getRiferimenti() {
		if (_riferimenti == null) {
			return "";
		}
		else {
			return _riferimenti;
		}
	}

	@Override
	public void setRiferimenti(String riferimenti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_riferimenti = riferimenti;
	}

	@JSON
	@Override
	public long getUtenteFirmaArpaId() {
		return _utenteFirmaArpaId;
	}

	@Override
	public void setUtenteFirmaArpaId(long utenteFirmaArpaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utenteFirmaArpaId = utenteFirmaArpaId;
	}

	@JSON
	@Override
	public Date getDataFirmaArpa() {
		return _dataFirmaArpa;
	}

	@Override
	public void setDataFirmaArpa(Date dataFirmaArpa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataFirmaArpa = dataFirmaArpa;
	}

	@JSON
	@Override
	public long getUtenteFirmaProtId() {
		return _utenteFirmaProtId;
	}

	@Override
	public void setUtenteFirmaProtId(long utenteFirmaProtId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_utenteFirmaProtId = utenteFirmaProtId;
	}

	@JSON
	@Override
	public Date getDataFirmaProt() {
		return _dataFirmaProt;
	}

	@Override
	public void setDataFirmaProt(Date dataFirmaProt) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataFirmaProt = dataFirmaProt;
	}

	@JSON
	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentId = parentId;
	}

	@JSON
	@Override
	public String getSintesi() {
		if (_sintesi == null) {
			return "";
		}
		else {
			return _sintesi;
		}
	}

	@Override
	public void setSintesi(String sintesi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sintesi = sintesi;
	}

	@JSON
	@Override
	public String getSintesiEng() {
		if (_sintesiEng == null) {
			return "";
		}
		else {
			return _sintesiEng;
		}
	}

	@Override
	public void setSintesiEng(String sintesiEng) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sintesiEng = sintesiEng;
	}

	@JSON
	@Override
	public String getLink() {
		if (_link == null) {
			return "";
		}
		else {
			return _link;
		}
	}

	@Override
	public void setLink(String link) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_link = link;
	}

	@JSON
	@Override
	public String getTitolo() {
		if (_titolo == null) {
			return "";
		}
		else {
			return _titolo;
		}
	}

	@Override
	public void setTitolo(String titolo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_titolo = titolo;
	}

	@JSON
	@Override
	public String getTitoloEng() {
		if (_titoloEng == null) {
			return "";
		}
		else {
			return _titoloEng;
		}
	}

	@Override
	public void setTitoloEng(String titoloEng) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_titoloEng = titoloEng;
	}

	@JSON
	@Override
	public boolean getTipoAllerta() {
		return _tipoAllerta;
	}

	@JSON
	@Override
	public boolean isTipoAllerta() {
		return _tipoAllerta;
	}

	@Override
	public void setTipoAllerta(boolean tipoAllerta) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tipoAllerta = tipoAllerta;
	}

	@JSON
	@Override
	public String getHash() {
		if (_hash == null) {
			return "";
		}
		else {
			return _hash;
		}
	}

	@Override
	public void setHash(String hash) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hash = hash;
	}

	@JSON
	@Override
	public String getSintesiBriefing() {
		if (_sintesiBriefing == null) {
			return "";
		}
		else {
			return _sintesiBriefing;
		}
	}

	@Override
	public void setSintesiBriefing(String sintesiBriefing) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sintesiBriefing = sintesiBriefing;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Allerta.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Allerta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Allerta toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Allerta>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AllertaImpl allertaImpl = new AllertaImpl();

		allertaImpl.setUuid(getUuid());
		allertaImpl.setAllertaId(getAllertaId());
		allertaImpl.setGroupId(getGroupId());
		allertaImpl.setCompanyId(getCompanyId());
		allertaImpl.setUserId(getUserId());
		allertaImpl.setUserName(getUserName());
		allertaImpl.setCreatorName(getCreatorName());
		allertaImpl.setCreateDate(getCreateDate());
		allertaImpl.setModifiedDate(getModifiedDate());
		allertaImpl.setStato(getStato());
		allertaImpl.setNumero(getNumero());
		allertaImpl.setProgressivo(getProgressivo());
		allertaImpl.setAnno(getAnno());
		allertaImpl.setDataEmissione(getDataEmissione());
		allertaImpl.setDataInizio(getDataInizio());
		allertaImpl.setDataFine(getDataFine());
		allertaImpl.setDescrizioneMeteo(getDescrizioneMeteo());
		allertaImpl.setTendenza(getTendenza());
		allertaImpl.setNote(getNote());
		allertaImpl.setRiferimenti(getRiferimenti());
		allertaImpl.setUtenteFirmaArpaId(getUtenteFirmaArpaId());
		allertaImpl.setDataFirmaArpa(getDataFirmaArpa());
		allertaImpl.setUtenteFirmaProtId(getUtenteFirmaProtId());
		allertaImpl.setDataFirmaProt(getDataFirmaProt());
		allertaImpl.setParentId(getParentId());
		allertaImpl.setSintesi(getSintesi());
		allertaImpl.setSintesiEng(getSintesiEng());
		allertaImpl.setLink(getLink());
		allertaImpl.setTitolo(getTitolo());
		allertaImpl.setTitoloEng(getTitoloEng());
		allertaImpl.setTipoAllerta(isTipoAllerta());
		allertaImpl.setHash(getHash());
		allertaImpl.setSintesiBriefing(getSintesiBriefing());

		allertaImpl.resetOriginalValues();

		return allertaImpl;
	}

	@Override
	public Allerta cloneWithOriginalValues() {
		AllertaImpl allertaImpl = new AllertaImpl();

		allertaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		allertaImpl.setAllertaId(
			this.<Long>getColumnOriginalValue("allertaId"));
		allertaImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		allertaImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		allertaImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		allertaImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		allertaImpl.setCreatorName(
			this.<String>getColumnOriginalValue("creatorName"));
		allertaImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		allertaImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		allertaImpl.setStato(this.<Integer>getColumnOriginalValue("stato"));
		allertaImpl.setNumero(this.<String>getColumnOriginalValue("numero"));
		allertaImpl.setProgressivo(
			this.<Integer>getColumnOriginalValue("progressivo"));
		allertaImpl.setAnno(this.<Integer>getColumnOriginalValue("anno"));
		allertaImpl.setDataEmissione(
			this.<Date>getColumnOriginalValue("dataEmissione"));
		allertaImpl.setDataInizio(
			this.<Date>getColumnOriginalValue("dataInizio"));
		allertaImpl.setDataFine(this.<Date>getColumnOriginalValue("dataFine"));
		allertaImpl.setDescrizioneMeteo(
			this.<String>getColumnOriginalValue("descrizioneMeteo"));
		allertaImpl.setTendenza(
			this.<Integer>getColumnOriginalValue("tendenza"));
		allertaImpl.setNote(this.<String>getColumnOriginalValue("note"));
		allertaImpl.setRiferimenti(
			this.<String>getColumnOriginalValue("riferimenti"));
		allertaImpl.setUtenteFirmaArpaId(
			this.<Long>getColumnOriginalValue("utenteFirmaArpaId"));
		allertaImpl.setDataFirmaArpa(
			this.<Date>getColumnOriginalValue("dataFirmaArpa"));
		allertaImpl.setUtenteFirmaProtId(
			this.<Long>getColumnOriginalValue("utenteFirmaProtId"));
		allertaImpl.setDataFirmaProt(
			this.<Date>getColumnOriginalValue("dataFirmaProt"));
		allertaImpl.setParentId(this.<Long>getColumnOriginalValue("parentId"));
		allertaImpl.setSintesi(this.<String>getColumnOriginalValue("sintesi"));
		allertaImpl.setSintesiEng(
			this.<String>getColumnOriginalValue("sintesiEng"));
		allertaImpl.setLink(this.<String>getColumnOriginalValue("link"));
		allertaImpl.setTitolo(this.<String>getColumnOriginalValue("titolo"));
		allertaImpl.setTitoloEng(
			this.<String>getColumnOriginalValue("titoloEng"));
		allertaImpl.setTipoAllerta(
			this.<Boolean>getColumnOriginalValue("tipoAllerta"));
		allertaImpl.setHash(this.<String>getColumnOriginalValue("hash"));
		allertaImpl.setSintesiBriefing(
			this.<String>getColumnOriginalValue("sintesiBriefing"));

		return allertaImpl;
	}

	@Override
	public int compareTo(Allerta allerta) {
		int value = 0;

		value = getNumero().compareTo(allerta.getNumero());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Allerta)) {
			return false;
		}

		Allerta allerta = (Allerta)object;

		long primaryKey = allerta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Allerta> toCacheModel() {
		AllertaCacheModel allertaCacheModel = new AllertaCacheModel();

		allertaCacheModel.uuid = getUuid();

		String uuid = allertaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			allertaCacheModel.uuid = null;
		}

		allertaCacheModel.allertaId = getAllertaId();

		allertaCacheModel.groupId = getGroupId();

		allertaCacheModel.companyId = getCompanyId();

		allertaCacheModel.userId = getUserId();

		allertaCacheModel.userName = getUserName();

		String userName = allertaCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			allertaCacheModel.userName = null;
		}

		allertaCacheModel.creatorName = getCreatorName();

		String creatorName = allertaCacheModel.creatorName;

		if ((creatorName != null) && (creatorName.length() == 0)) {
			allertaCacheModel.creatorName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			allertaCacheModel.createDate = createDate.getTime();
		}
		else {
			allertaCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			allertaCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			allertaCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		allertaCacheModel.stato = getStato();

		allertaCacheModel.numero = getNumero();

		String numero = allertaCacheModel.numero;

		if ((numero != null) && (numero.length() == 0)) {
			allertaCacheModel.numero = null;
		}

		allertaCacheModel.progressivo = getProgressivo();

		allertaCacheModel.anno = getAnno();

		Date dataEmissione = getDataEmissione();

		if (dataEmissione != null) {
			allertaCacheModel.dataEmissione = dataEmissione.getTime();
		}
		else {
			allertaCacheModel.dataEmissione = Long.MIN_VALUE;
		}

		Date dataInizio = getDataInizio();

		if (dataInizio != null) {
			allertaCacheModel.dataInizio = dataInizio.getTime();
		}
		else {
			allertaCacheModel.dataInizio = Long.MIN_VALUE;
		}

		Date dataFine = getDataFine();

		if (dataFine != null) {
			allertaCacheModel.dataFine = dataFine.getTime();
		}
		else {
			allertaCacheModel.dataFine = Long.MIN_VALUE;
		}

		allertaCacheModel.descrizioneMeteo = getDescrizioneMeteo();

		String descrizioneMeteo = allertaCacheModel.descrizioneMeteo;

		if ((descrizioneMeteo != null) && (descrizioneMeteo.length() == 0)) {
			allertaCacheModel.descrizioneMeteo = null;
		}

		allertaCacheModel.tendenza = getTendenza();

		allertaCacheModel.note = getNote();

		String note = allertaCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			allertaCacheModel.note = null;
		}

		allertaCacheModel.riferimenti = getRiferimenti();

		String riferimenti = allertaCacheModel.riferimenti;

		if ((riferimenti != null) && (riferimenti.length() == 0)) {
			allertaCacheModel.riferimenti = null;
		}

		allertaCacheModel.utenteFirmaArpaId = getUtenteFirmaArpaId();

		Date dataFirmaArpa = getDataFirmaArpa();

		if (dataFirmaArpa != null) {
			allertaCacheModel.dataFirmaArpa = dataFirmaArpa.getTime();
		}
		else {
			allertaCacheModel.dataFirmaArpa = Long.MIN_VALUE;
		}

		allertaCacheModel.utenteFirmaProtId = getUtenteFirmaProtId();

		Date dataFirmaProt = getDataFirmaProt();

		if (dataFirmaProt != null) {
			allertaCacheModel.dataFirmaProt = dataFirmaProt.getTime();
		}
		else {
			allertaCacheModel.dataFirmaProt = Long.MIN_VALUE;
		}

		allertaCacheModel.parentId = getParentId();

		allertaCacheModel.sintesi = getSintesi();

		String sintesi = allertaCacheModel.sintesi;

		if ((sintesi != null) && (sintesi.length() == 0)) {
			allertaCacheModel.sintesi = null;
		}

		allertaCacheModel.sintesiEng = getSintesiEng();

		String sintesiEng = allertaCacheModel.sintesiEng;

		if ((sintesiEng != null) && (sintesiEng.length() == 0)) {
			allertaCacheModel.sintesiEng = null;
		}

		allertaCacheModel.link = getLink();

		String link = allertaCacheModel.link;

		if ((link != null) && (link.length() == 0)) {
			allertaCacheModel.link = null;
		}

		allertaCacheModel.titolo = getTitolo();

		String titolo = allertaCacheModel.titolo;

		if ((titolo != null) && (titolo.length() == 0)) {
			allertaCacheModel.titolo = null;
		}

		allertaCacheModel.titoloEng = getTitoloEng();

		String titoloEng = allertaCacheModel.titoloEng;

		if ((titoloEng != null) && (titoloEng.length() == 0)) {
			allertaCacheModel.titoloEng = null;
		}

		allertaCacheModel.tipoAllerta = isTipoAllerta();

		allertaCacheModel.hash = getHash();

		String hash = allertaCacheModel.hash;

		if ((hash != null) && (hash.length() == 0)) {
			allertaCacheModel.hash = null;
		}

		allertaCacheModel.sintesiBriefing = getSintesiBriefing();

		String sintesiBriefing = allertaCacheModel.sintesiBriefing;

		if ((sintesiBriefing != null) && (sintesiBriefing.length() == 0)) {
			allertaCacheModel.sintesiBriefing = null;
		}

		return allertaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Allerta, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Allerta, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Allerta, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Allerta)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Allerta>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Allerta.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _allertaId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private String _creatorName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _stato;
	private String _numero;
	private int _progressivo;
	private int _anno;
	private Date _dataEmissione;
	private Date _dataInizio;
	private Date _dataFine;
	private String _descrizioneMeteo;
	private int _tendenza;
	private String _note;
	private String _riferimenti;
	private long _utenteFirmaArpaId;
	private Date _dataFirmaArpa;
	private long _utenteFirmaProtId;
	private Date _dataFirmaProt;
	private long _parentId;
	private String _sintesi;
	private String _sintesiEng;
	private String _link;
	private String _titolo;
	private String _titoloEng;
	private boolean _tipoAllerta;
	private String _hash;
	private String _sintesiBriefing;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Allerta, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Allerta)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("allertaId", _allertaId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("creatorName", _creatorName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("stato", _stato);
		_columnOriginalValues.put("numero", _numero);
		_columnOriginalValues.put("progressivo", _progressivo);
		_columnOriginalValues.put("anno", _anno);
		_columnOriginalValues.put("dataEmissione", _dataEmissione);
		_columnOriginalValues.put("dataInizio", _dataInizio);
		_columnOriginalValues.put("dataFine", _dataFine);
		_columnOriginalValues.put("descrizioneMeteo", _descrizioneMeteo);
		_columnOriginalValues.put("tendenza", _tendenza);
		_columnOriginalValues.put("note", _note);
		_columnOriginalValues.put("riferimenti", _riferimenti);
		_columnOriginalValues.put("utenteFirmaArpaId", _utenteFirmaArpaId);
		_columnOriginalValues.put("dataFirmaArpa", _dataFirmaArpa);
		_columnOriginalValues.put("utenteFirmaProtId", _utenteFirmaProtId);
		_columnOriginalValues.put("dataFirmaProt", _dataFirmaProt);
		_columnOriginalValues.put("parentId", _parentId);
		_columnOriginalValues.put("sintesi", _sintesi);
		_columnOriginalValues.put("sintesiEng", _sintesiEng);
		_columnOriginalValues.put("link", _link);
		_columnOriginalValues.put("titolo", _titolo);
		_columnOriginalValues.put("titoloEng", _titoloEng);
		_columnOriginalValues.put("tipoAllerta", _tipoAllerta);
		_columnOriginalValues.put("hash", _hash);
		_columnOriginalValues.put("sintesiBriefing", _sintesiBriefing);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("allertaId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("creatorName", 64L);

		columnBitmasks.put("createDate", 128L);

		columnBitmasks.put("modifiedDate", 256L);

		columnBitmasks.put("stato", 512L);

		columnBitmasks.put("numero", 1024L);

		columnBitmasks.put("progressivo", 2048L);

		columnBitmasks.put("anno", 4096L);

		columnBitmasks.put("dataEmissione", 8192L);

		columnBitmasks.put("dataInizio", 16384L);

		columnBitmasks.put("dataFine", 32768L);

		columnBitmasks.put("descrizioneMeteo", 65536L);

		columnBitmasks.put("tendenza", 131072L);

		columnBitmasks.put("note", 262144L);

		columnBitmasks.put("riferimenti", 524288L);

		columnBitmasks.put("utenteFirmaArpaId", 1048576L);

		columnBitmasks.put("dataFirmaArpa", 2097152L);

		columnBitmasks.put("utenteFirmaProtId", 4194304L);

		columnBitmasks.put("dataFirmaProt", 8388608L);

		columnBitmasks.put("parentId", 16777216L);

		columnBitmasks.put("sintesi", 33554432L);

		columnBitmasks.put("sintesiEng", 67108864L);

		columnBitmasks.put("link", 134217728L);

		columnBitmasks.put("titolo", 268435456L);

		columnBitmasks.put("titoloEng", 536870912L);

		columnBitmasks.put("tipoAllerta", 1073741824L);

		columnBitmasks.put("hash", 2147483648L);

		columnBitmasks.put("sintesiBriefing", 4294967296L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Allerta _escapedModel;

}