/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.allerter.model.AllertaValangheStato;
import it.eng.allerter.model.AllertaValangheStatoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AllertaValangheStato service. Represents a row in the &quot;ALLERTER_AllertaValangheStato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AllertaValangheStatoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AllertaValangheStatoImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see AllertaValangheStatoImpl
 * @generated
 */
@JSON(strict = true)
public class AllertaValangheStatoModelImpl
	extends BaseModelImpl<AllertaValangheStato>
	implements AllertaValangheStatoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a allerta valanghe stato model instance should use the <code>AllertaValangheStato</code> interface instead.
	 */
	public static final String TABLE_NAME = "ALLERTER_AllertaValangheStato";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"allertaValangheStatoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"nome", Types.VARCHAR}, {"dataInizio", Types.TIMESTAMP},
		{"dataFine", Types.TIMESTAMP}, {"parentId", Types.BIGINT},
		{"allertaValangheId", Types.BIGINT}, {"statoId", Types.BIGINT},
		{"eventoId", Types.BIGINT}, {"areaId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("allertaValangheStatoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataInizio", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataFine", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("parentId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("allertaValangheId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("eventoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("areaId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ALLERTER_AllertaValangheStato (uuid_ VARCHAR(75) null,allertaValangheStatoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,nome VARCHAR(75) null,dataInizio DATE null,dataFine DATE null,parentId LONG,allertaValangheId LONG,statoId LONG,eventoId LONG,areaId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ALLERTER_AllertaValangheStato";

	public static final String ORDER_BY_JPQL =
		" ORDER BY allertaValangheStato.nome ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ALLERTER_AllertaValangheStato.nome ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ALLERTAVALANGHEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AllertaValangheStatoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _allertaValangheStatoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAllertaValangheStatoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _allertaValangheStatoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AllertaValangheStato.class;
	}

	@Override
	public String getModelClassName() {
		return AllertaValangheStato.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AllertaValangheStato, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AllertaValangheStato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AllertaValangheStato, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AllertaValangheStato)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AllertaValangheStato, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AllertaValangheStato, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AllertaValangheStato)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AllertaValangheStato, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AllertaValangheStato, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AllertaValangheStato, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AllertaValangheStato, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AllertaValangheStato, Object>>();

			attributeGetterFunctions.put("uuid", AllertaValangheStato::getUuid);
			attributeGetterFunctions.put(
				"allertaValangheStatoId",
				AllertaValangheStato::getAllertaValangheStatoId);
			attributeGetterFunctions.put(
				"groupId", AllertaValangheStato::getGroupId);
			attributeGetterFunctions.put(
				"companyId", AllertaValangheStato::getCompanyId);
			attributeGetterFunctions.put(
				"userId", AllertaValangheStato::getUserId);
			attributeGetterFunctions.put(
				"userName", AllertaValangheStato::getUserName);
			attributeGetterFunctions.put(
				"createDate", AllertaValangheStato::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", AllertaValangheStato::getModifiedDate);
			attributeGetterFunctions.put("nome", AllertaValangheStato::getNome);
			attributeGetterFunctions.put(
				"dataInizio", AllertaValangheStato::getDataInizio);
			attributeGetterFunctions.put(
				"dataFine", AllertaValangheStato::getDataFine);
			attributeGetterFunctions.put(
				"parentId", AllertaValangheStato::getParentId);
			attributeGetterFunctions.put(
				"allertaValangheId",
				AllertaValangheStato::getAllertaValangheId);
			attributeGetterFunctions.put(
				"statoId", AllertaValangheStato::getStatoId);
			attributeGetterFunctions.put(
				"eventoId", AllertaValangheStato::getEventoId);
			attributeGetterFunctions.put(
				"areaId", AllertaValangheStato::getAreaId);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AllertaValangheStato, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AllertaValangheStato, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AllertaValangheStato, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<AllertaValangheStato, String>)
					AllertaValangheStato::setUuid);
			attributeSetterBiConsumers.put(
				"allertaValangheStatoId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setAllertaValangheStatoId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<AllertaValangheStato, String>)
					AllertaValangheStato::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AllertaValangheStato, Date>)
					AllertaValangheStato::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<AllertaValangheStato, Date>)
					AllertaValangheStato::setModifiedDate);
			attributeSetterBiConsumers.put(
				"nome",
				(BiConsumer<AllertaValangheStato, String>)
					AllertaValangheStato::setNome);
			attributeSetterBiConsumers.put(
				"dataInizio",
				(BiConsumer<AllertaValangheStato, Date>)
					AllertaValangheStato::setDataInizio);
			attributeSetterBiConsumers.put(
				"dataFine",
				(BiConsumer<AllertaValangheStato, Date>)
					AllertaValangheStato::setDataFine);
			attributeSetterBiConsumers.put(
				"parentId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setParentId);
			attributeSetterBiConsumers.put(
				"allertaValangheId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setAllertaValangheId);
			attributeSetterBiConsumers.put(
				"statoId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setStatoId);
			attributeSetterBiConsumers.put(
				"eventoId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setEventoId);
			attributeSetterBiConsumers.put(
				"areaId",
				(BiConsumer<AllertaValangheStato, Long>)
					AllertaValangheStato::setAreaId);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAllertaValangheStatoId() {
		return _allertaValangheStatoId;
	}

	@Override
	public void setAllertaValangheStatoId(long allertaValangheStatoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allertaValangheStatoId = allertaValangheStatoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nome = nome;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNome() {
		return getColumnOriginalValue("nome");
	}

	@JSON
	@Override
	public Date getDataInizio() {
		return _dataInizio;
	}

	@Override
	public void setDataInizio(Date dataInizio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataInizio = dataInizio;
	}

	@JSON
	@Override
	public Date getDataFine() {
		return _dataFine;
	}

	@Override
	public void setDataFine(Date dataFine) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataFine = dataFine;
	}

	@JSON
	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentId = parentId;
	}

	@JSON
	@Override
	public long getAllertaValangheId() {
		return _allertaValangheId;
	}

	@Override
	public void setAllertaValangheId(long allertaValangheId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_allertaValangheId = allertaValangheId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAllertaValangheId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("allertaValangheId"));
	}

	@JSON
	@Override
	public long getStatoId() {
		return _statoId;
	}

	@Override
	public void setStatoId(long statoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statoId = statoId;
	}

	@JSON
	@Override
	public long getEventoId() {
		return _eventoId;
	}

	@Override
	public void setEventoId(long eventoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_eventoId = eventoId;
	}

	@JSON
	@Override
	public long getAreaId() {
		return _areaId;
	}

	@Override
	public void setAreaId(long areaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_areaId = areaId;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(AllertaValangheStato.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AllertaValangheStato.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AllertaValangheStato toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AllertaValangheStato>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AllertaValangheStatoImpl allertaValangheStatoImpl =
			new AllertaValangheStatoImpl();

		allertaValangheStatoImpl.setUuid(getUuid());
		allertaValangheStatoImpl.setAllertaValangheStatoId(
			getAllertaValangheStatoId());
		allertaValangheStatoImpl.setGroupId(getGroupId());
		allertaValangheStatoImpl.setCompanyId(getCompanyId());
		allertaValangheStatoImpl.setUserId(getUserId());
		allertaValangheStatoImpl.setUserName(getUserName());
		allertaValangheStatoImpl.setCreateDate(getCreateDate());
		allertaValangheStatoImpl.setModifiedDate(getModifiedDate());
		allertaValangheStatoImpl.setNome(getNome());
		allertaValangheStatoImpl.setDataInizio(getDataInizio());
		allertaValangheStatoImpl.setDataFine(getDataFine());
		allertaValangheStatoImpl.setParentId(getParentId());
		allertaValangheStatoImpl.setAllertaValangheId(getAllertaValangheId());
		allertaValangheStatoImpl.setStatoId(getStatoId());
		allertaValangheStatoImpl.setEventoId(getEventoId());
		allertaValangheStatoImpl.setAreaId(getAreaId());

		allertaValangheStatoImpl.resetOriginalValues();

		return allertaValangheStatoImpl;
	}

	@Override
	public AllertaValangheStato cloneWithOriginalValues() {
		AllertaValangheStatoImpl allertaValangheStatoImpl =
			new AllertaValangheStatoImpl();

		allertaValangheStatoImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		allertaValangheStatoImpl.setAllertaValangheStatoId(
			this.<Long>getColumnOriginalValue("allertaValangheStatoId"));
		allertaValangheStatoImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		allertaValangheStatoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		allertaValangheStatoImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		allertaValangheStatoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		allertaValangheStatoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		allertaValangheStatoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		allertaValangheStatoImpl.setNome(
			this.<String>getColumnOriginalValue("nome"));
		allertaValangheStatoImpl.setDataInizio(
			this.<Date>getColumnOriginalValue("dataInizio"));
		allertaValangheStatoImpl.setDataFine(
			this.<Date>getColumnOriginalValue("dataFine"));
		allertaValangheStatoImpl.setParentId(
			this.<Long>getColumnOriginalValue("parentId"));
		allertaValangheStatoImpl.setAllertaValangheId(
			this.<Long>getColumnOriginalValue("allertaValangheId"));
		allertaValangheStatoImpl.setStatoId(
			this.<Long>getColumnOriginalValue("statoId"));
		allertaValangheStatoImpl.setEventoId(
			this.<Long>getColumnOriginalValue("eventoId"));
		allertaValangheStatoImpl.setAreaId(
			this.<Long>getColumnOriginalValue("areaId"));

		return allertaValangheStatoImpl;
	}

	@Override
	public int compareTo(AllertaValangheStato allertaValangheStato) {
		int value = 0;

		value = getNome().compareTo(allertaValangheStato.getNome());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AllertaValangheStato)) {
			return false;
		}

		AllertaValangheStato allertaValangheStato =
			(AllertaValangheStato)object;

		long primaryKey = allertaValangheStato.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AllertaValangheStato> toCacheModel() {
		AllertaValangheStatoCacheModel allertaValangheStatoCacheModel =
			new AllertaValangheStatoCacheModel();

		allertaValangheStatoCacheModel.uuid = getUuid();

		String uuid = allertaValangheStatoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			allertaValangheStatoCacheModel.uuid = null;
		}

		allertaValangheStatoCacheModel.allertaValangheStatoId =
			getAllertaValangheStatoId();

		allertaValangheStatoCacheModel.groupId = getGroupId();

		allertaValangheStatoCacheModel.companyId = getCompanyId();

		allertaValangheStatoCacheModel.userId = getUserId();

		allertaValangheStatoCacheModel.userName = getUserName();

		String userName = allertaValangheStatoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			allertaValangheStatoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			allertaValangheStatoCacheModel.createDate = createDate.getTime();
		}
		else {
			allertaValangheStatoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			allertaValangheStatoCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			allertaValangheStatoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		allertaValangheStatoCacheModel.nome = getNome();

		String nome = allertaValangheStatoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			allertaValangheStatoCacheModel.nome = null;
		}

		Date dataInizio = getDataInizio();

		if (dataInizio != null) {
			allertaValangheStatoCacheModel.dataInizio = dataInizio.getTime();
		}
		else {
			allertaValangheStatoCacheModel.dataInizio = Long.MIN_VALUE;
		}

		Date dataFine = getDataFine();

		if (dataFine != null) {
			allertaValangheStatoCacheModel.dataFine = dataFine.getTime();
		}
		else {
			allertaValangheStatoCacheModel.dataFine = Long.MIN_VALUE;
		}

		allertaValangheStatoCacheModel.parentId = getParentId();

		allertaValangheStatoCacheModel.allertaValangheId =
			getAllertaValangheId();

		allertaValangheStatoCacheModel.statoId = getStatoId();

		allertaValangheStatoCacheModel.eventoId = getEventoId();

		allertaValangheStatoCacheModel.areaId = getAreaId();

		return allertaValangheStatoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AllertaValangheStato, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AllertaValangheStato, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AllertaValangheStato, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AllertaValangheStato)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AllertaValangheStato>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AllertaValangheStato.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _allertaValangheStatoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _nome;
	private Date _dataInizio;
	private Date _dataFine;
	private long _parentId;
	private long _allertaValangheId;
	private long _statoId;
	private long _eventoId;
	private long _areaId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AllertaValangheStato, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AllertaValangheStato)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put(
			"allertaValangheStatoId", _allertaValangheStatoId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("nome", _nome);
		_columnOriginalValues.put("dataInizio", _dataInizio);
		_columnOriginalValues.put("dataFine", _dataFine);
		_columnOriginalValues.put("parentId", _parentId);
		_columnOriginalValues.put("allertaValangheId", _allertaValangheId);
		_columnOriginalValues.put("statoId", _statoId);
		_columnOriginalValues.put("eventoId", _eventoId);
		_columnOriginalValues.put("areaId", _areaId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("allertaValangheStatoId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("nome", 256L);

		columnBitmasks.put("dataInizio", 512L);

		columnBitmasks.put("dataFine", 1024L);

		columnBitmasks.put("parentId", 2048L);

		columnBitmasks.put("allertaValangheId", 4096L);

		columnBitmasks.put("statoId", 8192L);

		columnBitmasks.put("eventoId", 16384L);

		columnBitmasks.put("areaId", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AllertaValangheStato _escapedModel;

}