/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.allerter.model.Email;
import it.eng.allerter.model.EmailModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Email service. Represents a row in the &quot;ALLERTER_Email&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmailModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmailImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see EmailImpl
 * @generated
 */
@JSON(strict = true)
public class EmailModelImpl extends BaseModelImpl<Email> implements EmailModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a email model instance should use the <code>Email</code> interface instead.
	 */
	public static final String TABLE_NAME = "ALLERTER_Email";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"tipo", Types.VARCHAR},
		{"sottotipo", Types.VARCHAR}, {"param", Types.BIGINT},
		{"destinatario", Types.BIGINT}, {"indirizzo", Types.VARCHAR},
		{"nomeDestinatario", Types.VARCHAR}, {"stato", Types.BIGINT},
		{"dataInvio", Types.TIMESTAMP}, {"testo", Types.VARCHAR},
		{"oggetto", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tipo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sottotipo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("param", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("destinatario", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("indirizzo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomeDestinatario", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stato", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataInvio", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("testo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oggetto", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ALLERTER_Email (id_ LONG not null primary key,tipo VARCHAR(75) null,sottotipo VARCHAR(75) null,param LONG,destinatario LONG,indirizzo VARCHAR(75) null,nomeDestinatario VARCHAR(75) null,stato LONG,dataInvio DATE null,testo VARCHAR(75) null,oggetto VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ALLERTER_Email";

	public static final String ORDER_BY_JPQL = " ORDER BY email.id DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ALLERTER_Email.id_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESTINATARIO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INDIRIZZO_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARAM_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SOTTOTIPO_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TIPO_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmailModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Email.class;
	}

	@Override
	public String getModelClassName() {
		return Email.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Email, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Email, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Email, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Email)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Email, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Email, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Email)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Email, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Email, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Email, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Email, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Email, Object>>();

			attributeGetterFunctions.put("id", Email::getId);
			attributeGetterFunctions.put("tipo", Email::getTipo);
			attributeGetterFunctions.put("sottotipo", Email::getSottotipo);
			attributeGetterFunctions.put("param", Email::getParam);
			attributeGetterFunctions.put(
				"destinatario", Email::getDestinatario);
			attributeGetterFunctions.put("indirizzo", Email::getIndirizzo);
			attributeGetterFunctions.put(
				"nomeDestinatario", Email::getNomeDestinatario);
			attributeGetterFunctions.put("stato", Email::getStato);
			attributeGetterFunctions.put("dataInvio", Email::getDataInvio);
			attributeGetterFunctions.put("testo", Email::getTesto);
			attributeGetterFunctions.put("oggetto", Email::getOggetto);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Email, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Email, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Email, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<Email, Long>)Email::setId);
			attributeSetterBiConsumers.put(
				"tipo", (BiConsumer<Email, String>)Email::setTipo);
			attributeSetterBiConsumers.put(
				"sottotipo", (BiConsumer<Email, String>)Email::setSottotipo);
			attributeSetterBiConsumers.put(
				"param", (BiConsumer<Email, Long>)Email::setParam);
			attributeSetterBiConsumers.put(
				"destinatario",
				(BiConsumer<Email, Long>)Email::setDestinatario);
			attributeSetterBiConsumers.put(
				"indirizzo", (BiConsumer<Email, String>)Email::setIndirizzo);
			attributeSetterBiConsumers.put(
				"nomeDestinatario",
				(BiConsumer<Email, String>)Email::setNomeDestinatario);
			attributeSetterBiConsumers.put(
				"stato", (BiConsumer<Email, Long>)Email::setStato);
			attributeSetterBiConsumers.put(
				"dataInvio", (BiConsumer<Email, Date>)Email::setDataInvio);
			attributeSetterBiConsumers.put(
				"testo", (BiConsumer<Email, String>)Email::setTesto);
			attributeSetterBiConsumers.put(
				"oggetto", (BiConsumer<Email, String>)Email::setOggetto);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getTipo() {
		if (_tipo == null) {
			return "";
		}
		else {
			return _tipo;
		}
	}

	@Override
	public void setTipo(String tipo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tipo = tipo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTipo() {
		return getColumnOriginalValue("tipo");
	}

	@JSON
	@Override
	public String getSottotipo() {
		if (_sottotipo == null) {
			return "";
		}
		else {
			return _sottotipo;
		}
	}

	@Override
	public void setSottotipo(String sottotipo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sottotipo = sottotipo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSottotipo() {
		return getColumnOriginalValue("sottotipo");
	}

	@JSON
	@Override
	public long getParam() {
		return _param;
	}

	@Override
	public void setParam(long param) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_param = param;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParam() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("param"));
	}

	@JSON
	@Override
	public long getDestinatario() {
		return _destinatario;
	}

	@Override
	public void setDestinatario(long destinatario) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_destinatario = destinatario;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDestinatario() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("destinatario"));
	}

	@JSON
	@Override
	public String getIndirizzo() {
		if (_indirizzo == null) {
			return "";
		}
		else {
			return _indirizzo;
		}
	}

	@Override
	public void setIndirizzo(String indirizzo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_indirizzo = indirizzo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalIndirizzo() {
		return getColumnOriginalValue("indirizzo");
	}

	@JSON
	@Override
	public String getNomeDestinatario() {
		if (_nomeDestinatario == null) {
			return "";
		}
		else {
			return _nomeDestinatario;
		}
	}

	@Override
	public void setNomeDestinatario(String nomeDestinatario) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeDestinatario = nomeDestinatario;
	}

	@JSON
	@Override
	public long getStato() {
		return _stato;
	}

	@Override
	public void setStato(long stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stato = stato;
	}

	@JSON
	@Override
	public Date getDataInvio() {
		return _dataInvio;
	}

	@Override
	public void setDataInvio(Date dataInvio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataInvio = dataInvio;
	}

	@JSON
	@Override
	public String getTesto() {
		if (_testo == null) {
			return "";
		}
		else {
			return _testo;
		}
	}

	@Override
	public void setTesto(String testo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_testo = testo;
	}

	@JSON
	@Override
	public String getOggetto() {
		if (_oggetto == null) {
			return "";
		}
		else {
			return _oggetto;
		}
	}

	@Override
	public void setOggetto(String oggetto) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oggetto = oggetto;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Email.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Email toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Email>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmailImpl emailImpl = new EmailImpl();

		emailImpl.setId(getId());
		emailImpl.setTipo(getTipo());
		emailImpl.setSottotipo(getSottotipo());
		emailImpl.setParam(getParam());
		emailImpl.setDestinatario(getDestinatario());
		emailImpl.setIndirizzo(getIndirizzo());
		emailImpl.setNomeDestinatario(getNomeDestinatario());
		emailImpl.setStato(getStato());
		emailImpl.setDataInvio(getDataInvio());
		emailImpl.setTesto(getTesto());
		emailImpl.setOggetto(getOggetto());

		emailImpl.resetOriginalValues();

		return emailImpl;
	}

	@Override
	public Email cloneWithOriginalValues() {
		EmailImpl emailImpl = new EmailImpl();

		emailImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		emailImpl.setTipo(this.<String>getColumnOriginalValue("tipo"));
		emailImpl.setSottotipo(
			this.<String>getColumnOriginalValue("sottotipo"));
		emailImpl.setParam(this.<Long>getColumnOriginalValue("param"));
		emailImpl.setDestinatario(
			this.<Long>getColumnOriginalValue("destinatario"));
		emailImpl.setIndirizzo(
			this.<String>getColumnOriginalValue("indirizzo"));
		emailImpl.setNomeDestinatario(
			this.<String>getColumnOriginalValue("nomeDestinatario"));
		emailImpl.setStato(this.<Long>getColumnOriginalValue("stato"));
		emailImpl.setDataInvio(this.<Date>getColumnOriginalValue("dataInvio"));
		emailImpl.setTesto(this.<String>getColumnOriginalValue("testo"));
		emailImpl.setOggetto(this.<String>getColumnOriginalValue("oggetto"));

		return emailImpl;
	}

	@Override
	public int compareTo(Email email) {
		int value = 0;

		if (getId() < email.getId()) {
			value = -1;
		}
		else if (getId() > email.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Email)) {
			return false;
		}

		Email email = (Email)object;

		long primaryKey = email.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Email> toCacheModel() {
		EmailCacheModel emailCacheModel = new EmailCacheModel();

		emailCacheModel.id = getId();

		emailCacheModel.tipo = getTipo();

		String tipo = emailCacheModel.tipo;

		if ((tipo != null) && (tipo.length() == 0)) {
			emailCacheModel.tipo = null;
		}

		emailCacheModel.sottotipo = getSottotipo();

		String sottotipo = emailCacheModel.sottotipo;

		if ((sottotipo != null) && (sottotipo.length() == 0)) {
			emailCacheModel.sottotipo = null;
		}

		emailCacheModel.param = getParam();

		emailCacheModel.destinatario = getDestinatario();

		emailCacheModel.indirizzo = getIndirizzo();

		String indirizzo = emailCacheModel.indirizzo;

		if ((indirizzo != null) && (indirizzo.length() == 0)) {
			emailCacheModel.indirizzo = null;
		}

		emailCacheModel.nomeDestinatario = getNomeDestinatario();

		String nomeDestinatario = emailCacheModel.nomeDestinatario;

		if ((nomeDestinatario != null) && (nomeDestinatario.length() == 0)) {
			emailCacheModel.nomeDestinatario = null;
		}

		emailCacheModel.stato = getStato();

		Date dataInvio = getDataInvio();

		if (dataInvio != null) {
			emailCacheModel.dataInvio = dataInvio.getTime();
		}
		else {
			emailCacheModel.dataInvio = Long.MIN_VALUE;
		}

		emailCacheModel.testo = getTesto();

		String testo = emailCacheModel.testo;

		if ((testo != null) && (testo.length() == 0)) {
			emailCacheModel.testo = null;
		}

		emailCacheModel.oggetto = getOggetto();

		String oggetto = emailCacheModel.oggetto;

		if ((oggetto != null) && (oggetto.length() == 0)) {
			emailCacheModel.oggetto = null;
		}

		return emailCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Email, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Email, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Email, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Email)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Email>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Email.class, ModelWrapper.class);

	}

	private long _id;
	private String _tipo;
	private String _sottotipo;
	private long _param;
	private long _destinatario;
	private String _indirizzo;
	private String _nomeDestinatario;
	private long _stato;
	private Date _dataInvio;
	private String _testo;
	private String _oggetto;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Email, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Email)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("tipo", _tipo);
		_columnOriginalValues.put("sottotipo", _sottotipo);
		_columnOriginalValues.put("param", _param);
		_columnOriginalValues.put("destinatario", _destinatario);
		_columnOriginalValues.put("indirizzo", _indirizzo);
		_columnOriginalValues.put("nomeDestinatario", _nomeDestinatario);
		_columnOriginalValues.put("stato", _stato);
		_columnOriginalValues.put("dataInvio", _dataInvio);
		_columnOriginalValues.put("testo", _testo);
		_columnOriginalValues.put("oggetto", _oggetto);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("tipo", 2L);

		columnBitmasks.put("sottotipo", 4L);

		columnBitmasks.put("param", 8L);

		columnBitmasks.put("destinatario", 16L);

		columnBitmasks.put("indirizzo", 32L);

		columnBitmasks.put("nomeDestinatario", 64L);

		columnBitmasks.put("stato", 128L);

		columnBitmasks.put("dataInvio", 256L);

		columnBitmasks.put("testo", 512L);

		columnBitmasks.put("oggetto", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Email _escapedModel;

}