/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.allerter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.allerter.model.SMS;
import it.eng.allerter.model.SMSModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SMS service. Represents a row in the &quot;ALLERTER_SMS&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SMSModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SMSImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see SMSImpl
 * @generated
 */
@JSON(strict = true)
public class SMSModelImpl extends BaseModelImpl<SMS> implements SMSModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sms model instance should use the <code>SMS</code> interface instead.
	 */
	public static final String TABLE_NAME = "ALLERTER_SMS";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"tipo", Types.VARCHAR},
		{"sottotipo", Types.VARCHAR}, {"param", Types.BIGINT},
		{"testo", Types.VARCHAR}, {"destinatario", Types.BIGINT},
		{"numeroDa", Types.VARCHAR}, {"numero", Types.VARCHAR},
		{"nomeDestinatario", Types.VARCHAR}, {"stato", Types.BIGINT},
		{"dataInvio", Types.TIMESTAMP}, {"dataAck", Types.TIMESTAMP},
		{"dataRicevuta", Types.TIMESTAMP}, {"tentativi", Types.BIGINT},
		{"prossimoInvio", Types.TIMESTAMP}, {"codiceErrore", Types.VARCHAR},
		{"descrizioneErrore", Types.VARCHAR}, {"timestamp", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tipo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sottotipo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("param", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("testo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("destinatario", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("numeroDa", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("numero", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomeDestinatario", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stato", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataInvio", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataAck", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataRicevuta", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("tentativi", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("prossimoInvio", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("codiceErrore", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descrizioneErrore", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timestamp", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ALLERTER_SMS (id_ LONG not null primary key,tipo VARCHAR(75) null,sottotipo VARCHAR(75) null,param LONG,testo VARCHAR(75) null,destinatario LONG,numeroDa VARCHAR(75) null,numero VARCHAR(75) null,nomeDestinatario VARCHAR(75) null,stato LONG,dataInvio DATE null,dataAck DATE null,dataRicevuta DATE null,tentativi LONG,prossimoInvio DATE null,codiceErrore VARCHAR(75) null,descrizioneErrore VARCHAR(75) null,timestamp VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ALLERTER_SMS";

	public static final String ORDER_BY_JPQL = " ORDER BY sms.id DESC";

	public static final String ORDER_BY_SQL = " ORDER BY ALLERTER_SMS.id_ DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DATAACK_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DESTINATARIO_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NUMERO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARAM_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SOTTOTIPO_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TIMESTAMP_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TIPO_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SMSModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SMS.class;
	}

	@Override
	public String getModelClassName() {
		return SMS.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SMS, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SMS, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SMS, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SMS)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SMS, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SMS, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((SMS)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SMS, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SMS, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SMS, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SMS, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<SMS, Object>>();

			attributeGetterFunctions.put("id", SMS::getId);
			attributeGetterFunctions.put("tipo", SMS::getTipo);
			attributeGetterFunctions.put("sottotipo", SMS::getSottotipo);
			attributeGetterFunctions.put("param", SMS::getParam);
			attributeGetterFunctions.put("testo", SMS::getTesto);
			attributeGetterFunctions.put("destinatario", SMS::getDestinatario);
			attributeGetterFunctions.put("numeroDa", SMS::getNumeroDa);
			attributeGetterFunctions.put("numero", SMS::getNumero);
			attributeGetterFunctions.put(
				"nomeDestinatario", SMS::getNomeDestinatario);
			attributeGetterFunctions.put("stato", SMS::getStato);
			attributeGetterFunctions.put("dataInvio", SMS::getDataInvio);
			attributeGetterFunctions.put("dataAck", SMS::getDataAck);
			attributeGetterFunctions.put("dataRicevuta", SMS::getDataRicevuta);
			attributeGetterFunctions.put("tentativi", SMS::getTentativi);
			attributeGetterFunctions.put(
				"prossimoInvio", SMS::getProssimoInvio);
			attributeGetterFunctions.put("codiceErrore", SMS::getCodiceErrore);
			attributeGetterFunctions.put(
				"descrizioneErrore", SMS::getDescrizioneErrore);
			attributeGetterFunctions.put("timestamp", SMS::getTimestamp);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<SMS, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SMS, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SMS, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<SMS, Long>)SMS::setId);
			attributeSetterBiConsumers.put(
				"tipo", (BiConsumer<SMS, String>)SMS::setTipo);
			attributeSetterBiConsumers.put(
				"sottotipo", (BiConsumer<SMS, String>)SMS::setSottotipo);
			attributeSetterBiConsumers.put(
				"param", (BiConsumer<SMS, Long>)SMS::setParam);
			attributeSetterBiConsumers.put(
				"testo", (BiConsumer<SMS, String>)SMS::setTesto);
			attributeSetterBiConsumers.put(
				"destinatario", (BiConsumer<SMS, Long>)SMS::setDestinatario);
			attributeSetterBiConsumers.put(
				"numeroDa", (BiConsumer<SMS, String>)SMS::setNumeroDa);
			attributeSetterBiConsumers.put(
				"numero", (BiConsumer<SMS, String>)SMS::setNumero);
			attributeSetterBiConsumers.put(
				"nomeDestinatario",
				(BiConsumer<SMS, String>)SMS::setNomeDestinatario);
			attributeSetterBiConsumers.put(
				"stato", (BiConsumer<SMS, Long>)SMS::setStato);
			attributeSetterBiConsumers.put(
				"dataInvio", (BiConsumer<SMS, Date>)SMS::setDataInvio);
			attributeSetterBiConsumers.put(
				"dataAck", (BiConsumer<SMS, Date>)SMS::setDataAck);
			attributeSetterBiConsumers.put(
				"dataRicevuta", (BiConsumer<SMS, Date>)SMS::setDataRicevuta);
			attributeSetterBiConsumers.put(
				"tentativi", (BiConsumer<SMS, Long>)SMS::setTentativi);
			attributeSetterBiConsumers.put(
				"prossimoInvio", (BiConsumer<SMS, Date>)SMS::setProssimoInvio);
			attributeSetterBiConsumers.put(
				"codiceErrore", (BiConsumer<SMS, String>)SMS::setCodiceErrore);
			attributeSetterBiConsumers.put(
				"descrizioneErrore",
				(BiConsumer<SMS, String>)SMS::setDescrizioneErrore);
			attributeSetterBiConsumers.put(
				"timestamp", (BiConsumer<SMS, String>)SMS::setTimestamp);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getTipo() {
		if (_tipo == null) {
			return "";
		}
		else {
			return _tipo;
		}
	}

	@Override
	public void setTipo(String tipo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tipo = tipo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTipo() {
		return getColumnOriginalValue("tipo");
	}

	@JSON
	@Override
	public String getSottotipo() {
		if (_sottotipo == null) {
			return "";
		}
		else {
			return _sottotipo;
		}
	}

	@Override
	public void setSottotipo(String sottotipo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_sottotipo = sottotipo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSottotipo() {
		return getColumnOriginalValue("sottotipo");
	}

	@JSON
	@Override
	public long getParam() {
		return _param;
	}

	@Override
	public void setParam(long param) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_param = param;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalParam() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("param"));
	}

	@JSON
	@Override
	public String getTesto() {
		if (_testo == null) {
			return "";
		}
		else {
			return _testo;
		}
	}

	@Override
	public void setTesto(String testo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_testo = testo;
	}

	@JSON
	@Override
	public long getDestinatario() {
		return _destinatario;
	}

	@Override
	public void setDestinatario(long destinatario) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_destinatario = destinatario;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalDestinatario() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("destinatario"));
	}

	@JSON
	@Override
	public String getNumeroDa() {
		if (_numeroDa == null) {
			return "";
		}
		else {
			return _numeroDa;
		}
	}

	@Override
	public void setNumeroDa(String numeroDa) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numeroDa = numeroDa;
	}

	@JSON
	@Override
	public String getNumero() {
		if (_numero == null) {
			return "";
		}
		else {
			return _numero;
		}
	}

	@Override
	public void setNumero(String numero) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numero = numero;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNumero() {
		return getColumnOriginalValue("numero");
	}

	@JSON
	@Override
	public String getNomeDestinatario() {
		if (_nomeDestinatario == null) {
			return "";
		}
		else {
			return _nomeDestinatario;
		}
	}

	@Override
	public void setNomeDestinatario(String nomeDestinatario) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeDestinatario = nomeDestinatario;
	}

	@JSON
	@Override
	public long getStato() {
		return _stato;
	}

	@Override
	public void setStato(long stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stato = stato;
	}

	@JSON
	@Override
	public Date getDataInvio() {
		return _dataInvio;
	}

	@Override
	public void setDataInvio(Date dataInvio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataInvio = dataInvio;
	}

	@JSON
	@Override
	public Date getDataAck() {
		return _dataAck;
	}

	@Override
	public void setDataAck(Date dataAck) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAck = dataAck;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalDataAck() {
		return getColumnOriginalValue("dataAck");
	}

	@JSON
	@Override
	public Date getDataRicevuta() {
		return _dataRicevuta;
	}

	@Override
	public void setDataRicevuta(Date dataRicevuta) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataRicevuta = dataRicevuta;
	}

	@JSON
	@Override
	public long getTentativi() {
		return _tentativi;
	}

	@Override
	public void setTentativi(long tentativi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tentativi = tentativi;
	}

	@JSON
	@Override
	public Date getProssimoInvio() {
		return _prossimoInvio;
	}

	@Override
	public void setProssimoInvio(Date prossimoInvio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_prossimoInvio = prossimoInvio;
	}

	@JSON
	@Override
	public String getCodiceErrore() {
		if (_codiceErrore == null) {
			return "";
		}
		else {
			return _codiceErrore;
		}
	}

	@Override
	public void setCodiceErrore(String codiceErrore) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_codiceErrore = codiceErrore;
	}

	@JSON
	@Override
	public String getDescrizioneErrore() {
		if (_descrizioneErrore == null) {
			return "";
		}
		else {
			return _descrizioneErrore;
		}
	}

	@Override
	public void setDescrizioneErrore(String descrizioneErrore) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_descrizioneErrore = descrizioneErrore;
	}

	@JSON
	@Override
	public String getTimestamp() {
		if (_timestamp == null) {
			return "";
		}
		else {
			return _timestamp;
		}
	}

	@Override
	public void setTimestamp(String timestamp) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timestamp = timestamp;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTimestamp() {
		return getColumnOriginalValue("timestamp");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, SMS.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SMS toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SMS> escapedModelProxyProviderFunction =
				EscapedModelProxyProviderFunctionHolder.
					_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SMSImpl smsImpl = new SMSImpl();

		smsImpl.setId(getId());
		smsImpl.setTipo(getTipo());
		smsImpl.setSottotipo(getSottotipo());
		smsImpl.setParam(getParam());
		smsImpl.setTesto(getTesto());
		smsImpl.setDestinatario(getDestinatario());
		smsImpl.setNumeroDa(getNumeroDa());
		smsImpl.setNumero(getNumero());
		smsImpl.setNomeDestinatario(getNomeDestinatario());
		smsImpl.setStato(getStato());
		smsImpl.setDataInvio(getDataInvio());
		smsImpl.setDataAck(getDataAck());
		smsImpl.setDataRicevuta(getDataRicevuta());
		smsImpl.setTentativi(getTentativi());
		smsImpl.setProssimoInvio(getProssimoInvio());
		smsImpl.setCodiceErrore(getCodiceErrore());
		smsImpl.setDescrizioneErrore(getDescrizioneErrore());
		smsImpl.setTimestamp(getTimestamp());

		smsImpl.resetOriginalValues();

		return smsImpl;
	}

	@Override
	public SMS cloneWithOriginalValues() {
		SMSImpl smsImpl = new SMSImpl();

		smsImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		smsImpl.setTipo(this.<String>getColumnOriginalValue("tipo"));
		smsImpl.setSottotipo(this.<String>getColumnOriginalValue("sottotipo"));
		smsImpl.setParam(this.<Long>getColumnOriginalValue("param"));
		smsImpl.setTesto(this.<String>getColumnOriginalValue("testo"));
		smsImpl.setDestinatario(
			this.<Long>getColumnOriginalValue("destinatario"));
		smsImpl.setNumeroDa(this.<String>getColumnOriginalValue("numeroDa"));
		smsImpl.setNumero(this.<String>getColumnOriginalValue("numero"));
		smsImpl.setNomeDestinatario(
			this.<String>getColumnOriginalValue("nomeDestinatario"));
		smsImpl.setStato(this.<Long>getColumnOriginalValue("stato"));
		smsImpl.setDataInvio(this.<Date>getColumnOriginalValue("dataInvio"));
		smsImpl.setDataAck(this.<Date>getColumnOriginalValue("dataAck"));
		smsImpl.setDataRicevuta(
			this.<Date>getColumnOriginalValue("dataRicevuta"));
		smsImpl.setTentativi(this.<Long>getColumnOriginalValue("tentativi"));
		smsImpl.setProssimoInvio(
			this.<Date>getColumnOriginalValue("prossimoInvio"));
		smsImpl.setCodiceErrore(
			this.<String>getColumnOriginalValue("codiceErrore"));
		smsImpl.setDescrizioneErrore(
			this.<String>getColumnOriginalValue("descrizioneErrore"));
		smsImpl.setTimestamp(this.<String>getColumnOriginalValue("timestamp"));

		return smsImpl;
	}

	@Override
	public int compareTo(SMS sms) {
		int value = 0;

		if (getId() < sms.getId()) {
			value = -1;
		}
		else if (getId() > sms.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SMS)) {
			return false;
		}

		SMS sms = (SMS)object;

		long primaryKey = sms.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SMS> toCacheModel() {
		SMSCacheModel smsCacheModel = new SMSCacheModel();

		smsCacheModel.id = getId();

		smsCacheModel.tipo = getTipo();

		String tipo = smsCacheModel.tipo;

		if ((tipo != null) && (tipo.length() == 0)) {
			smsCacheModel.tipo = null;
		}

		smsCacheModel.sottotipo = getSottotipo();

		String sottotipo = smsCacheModel.sottotipo;

		if ((sottotipo != null) && (sottotipo.length() == 0)) {
			smsCacheModel.sottotipo = null;
		}

		smsCacheModel.param = getParam();

		smsCacheModel.testo = getTesto();

		String testo = smsCacheModel.testo;

		if ((testo != null) && (testo.length() == 0)) {
			smsCacheModel.testo = null;
		}

		smsCacheModel.destinatario = getDestinatario();

		smsCacheModel.numeroDa = getNumeroDa();

		String numeroDa = smsCacheModel.numeroDa;

		if ((numeroDa != null) && (numeroDa.length() == 0)) {
			smsCacheModel.numeroDa = null;
		}

		smsCacheModel.numero = getNumero();

		String numero = smsCacheModel.numero;

		if ((numero != null) && (numero.length() == 0)) {
			smsCacheModel.numero = null;
		}

		smsCacheModel.nomeDestinatario = getNomeDestinatario();

		String nomeDestinatario = smsCacheModel.nomeDestinatario;

		if ((nomeDestinatario != null) && (nomeDestinatario.length() == 0)) {
			smsCacheModel.nomeDestinatario = null;
		}

		smsCacheModel.stato = getStato();

		Date dataInvio = getDataInvio();

		if (dataInvio != null) {
			smsCacheModel.dataInvio = dataInvio.getTime();
		}
		else {
			smsCacheModel.dataInvio = Long.MIN_VALUE;
		}

		Date dataAck = getDataAck();

		if (dataAck != null) {
			smsCacheModel.dataAck = dataAck.getTime();
		}
		else {
			smsCacheModel.dataAck = Long.MIN_VALUE;
		}

		Date dataRicevuta = getDataRicevuta();

		if (dataRicevuta != null) {
			smsCacheModel.dataRicevuta = dataRicevuta.getTime();
		}
		else {
			smsCacheModel.dataRicevuta = Long.MIN_VALUE;
		}

		smsCacheModel.tentativi = getTentativi();

		Date prossimoInvio = getProssimoInvio();

		if (prossimoInvio != null) {
			smsCacheModel.prossimoInvio = prossimoInvio.getTime();
		}
		else {
			smsCacheModel.prossimoInvio = Long.MIN_VALUE;
		}

		smsCacheModel.codiceErrore = getCodiceErrore();

		String codiceErrore = smsCacheModel.codiceErrore;

		if ((codiceErrore != null) && (codiceErrore.length() == 0)) {
			smsCacheModel.codiceErrore = null;
		}

		smsCacheModel.descrizioneErrore = getDescrizioneErrore();

		String descrizioneErrore = smsCacheModel.descrizioneErrore;

		if ((descrizioneErrore != null) && (descrizioneErrore.length() == 0)) {
			smsCacheModel.descrizioneErrore = null;
		}

		smsCacheModel.timestamp = getTimestamp();

		String timestamp = smsCacheModel.timestamp;

		if ((timestamp != null) && (timestamp.length() == 0)) {
			smsCacheModel.timestamp = null;
		}

		return smsCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SMS, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SMS, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SMS, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SMS)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SMS>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SMS.class, ModelWrapper.class);

	}

	private long _id;
	private String _tipo;
	private String _sottotipo;
	private long _param;
	private String _testo;
	private long _destinatario;
	private String _numeroDa;
	private String _numero;
	private String _nomeDestinatario;
	private long _stato;
	private Date _dataInvio;
	private Date _dataAck;
	private Date _dataRicevuta;
	private long _tentativi;
	private Date _prossimoInvio;
	private String _codiceErrore;
	private String _descrizioneErrore;
	private String _timestamp;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SMS, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SMS)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("tipo", _tipo);
		_columnOriginalValues.put("sottotipo", _sottotipo);
		_columnOriginalValues.put("param", _param);
		_columnOriginalValues.put("testo", _testo);
		_columnOriginalValues.put("destinatario", _destinatario);
		_columnOriginalValues.put("numeroDa", _numeroDa);
		_columnOriginalValues.put("numero", _numero);
		_columnOriginalValues.put("nomeDestinatario", _nomeDestinatario);
		_columnOriginalValues.put("stato", _stato);
		_columnOriginalValues.put("dataInvio", _dataInvio);
		_columnOriginalValues.put("dataAck", _dataAck);
		_columnOriginalValues.put("dataRicevuta", _dataRicevuta);
		_columnOriginalValues.put("tentativi", _tentativi);
		_columnOriginalValues.put("prossimoInvio", _prossimoInvio);
		_columnOriginalValues.put("codiceErrore", _codiceErrore);
		_columnOriginalValues.put("descrizioneErrore", _descrizioneErrore);
		_columnOriginalValues.put("timestamp", _timestamp);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("tipo", 2L);

		columnBitmasks.put("sottotipo", 4L);

		columnBitmasks.put("param", 8L);

		columnBitmasks.put("testo", 16L);

		columnBitmasks.put("destinatario", 32L);

		columnBitmasks.put("numeroDa", 64L);

		columnBitmasks.put("numero", 128L);

		columnBitmasks.put("nomeDestinatario", 256L);

		columnBitmasks.put("stato", 512L);

		columnBitmasks.put("dataInvio", 1024L);

		columnBitmasks.put("dataAck", 2048L);

		columnBitmasks.put("dataRicevuta", 4096L);

		columnBitmasks.put("tentativi", 8192L);

		columnBitmasks.put("prossimoInvio", 16384L);

		columnBitmasks.put("codiceErrore", 32768L);

		columnBitmasks.put("descrizioneErrore", 65536L);

		columnBitmasks.put("timestamp", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SMS _escapedModel;

}