/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerta.messages.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import it.eng.allerta.messages.services.model.Nodo;
import it.eng.allerta.messages.services.model.NodoModel;
import it.eng.allerta.messages.services.model.NodoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Nodo service. Represents a row in the &quot;smsService_Nodo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>NodoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NodoImpl}.
 * </p>
 *
 * @author Giorgianni_F
 * @see NodoImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class NodoModelImpl extends BaseModelImpl<Nodo> implements NodoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a nodo model instance should use the <code>Nodo</code> interface instead.
	 */
	public static final String TABLE_NAME = "smsService_Nodo";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id", Types.BIGINT}, {"ip", Types.VARCHAR}, {"porta", Types.INTEGER},
		{"nodoConnesso", Types.VARCHAR}, {"dataConnessione", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ip", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("porta", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("nodoConnesso", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataConnessione", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table smsService_Nodo (Id LONG not null primary key,ip VARCHAR(75) null,porta INTEGER,nodoConnesso VARCHAR(75) null,dataConnessione DATE null)";

	public static final String TABLE_SQL_DROP = "drop table smsService_Nodo";

	public static final String ORDER_BY_JPQL = " ORDER BY nodo.Id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY smsService_Nodo.Id ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.allerta.messages.services.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.it.eng.allerta.messages.services.model.Nodo"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.allerta.messages.services.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.it.eng.allerta.messages.services.model.Nodo"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		it.eng.allerta.messages.services.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.it.eng.allerta.messages.services.model.Nodo"),
		true);

	public static final long IP_COLUMN_BITMASK = 1L;

	public static final long NODOCONNESSO_COLUMN_BITMASK = 2L;

	public static final long ID_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Nodo toModel(NodoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Nodo model = new NodoImpl();

		model.setId(soapModel.getId());
		model.setIp(soapModel.getIp());
		model.setPorta(soapModel.getPorta());
		model.setNodoConnesso(soapModel.getNodoConnesso());
		model.setDataConnessione(soapModel.getDataConnessione());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Nodo> toModels(NodoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Nodo> models = new ArrayList<Nodo>(soapModels.length);

		for (NodoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		it.eng.allerta.messages.services.service.util.ServiceProps.get(
			"lock.expiration.time.it.eng.allerta.messages.services.model.Nodo"));

	public NodoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Nodo.class;
	}

	@Override
	public String getModelClassName() {
		return Nodo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Nodo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Nodo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Nodo, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Nodo)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Nodo, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Nodo, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Nodo)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Nodo, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Nodo, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Nodo, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Nodo, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Nodo, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Nodo, Object>>();
		Map<String, BiConsumer<Nodo, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Nodo, ?>>();

		attributeGetterFunctions.put(
			"Id",
			new Function<Nodo, Object>() {

				@Override
				public Object apply(Nodo nodo) {
					return nodo.getId();
				}

			});
		attributeSetterBiConsumers.put(
			"Id",
			new BiConsumer<Nodo, Object>() {

				@Override
				public void accept(Nodo nodo, Object Id) {
					nodo.setId((Long)Id);
				}

			});
		attributeGetterFunctions.put(
			"ip",
			new Function<Nodo, Object>() {

				@Override
				public Object apply(Nodo nodo) {
					return nodo.getIp();
				}

			});
		attributeSetterBiConsumers.put(
			"ip",
			new BiConsumer<Nodo, Object>() {

				@Override
				public void accept(Nodo nodo, Object ip) {
					nodo.setIp((String)ip);
				}

			});
		attributeGetterFunctions.put(
			"porta",
			new Function<Nodo, Object>() {

				@Override
				public Object apply(Nodo nodo) {
					return nodo.getPorta();
				}

			});
		attributeSetterBiConsumers.put(
			"porta",
			new BiConsumer<Nodo, Object>() {

				@Override
				public void accept(Nodo nodo, Object porta) {
					nodo.setPorta((Integer)porta);
				}

			});
		attributeGetterFunctions.put(
			"nodoConnesso",
			new Function<Nodo, Object>() {

				@Override
				public Object apply(Nodo nodo) {
					return nodo.getNodoConnesso();
				}

			});
		attributeSetterBiConsumers.put(
			"nodoConnesso",
			new BiConsumer<Nodo, Object>() {

				@Override
				public void accept(Nodo nodo, Object nodoConnesso) {
					nodo.setNodoConnesso((String)nodoConnesso);
				}

			});
		attributeGetterFunctions.put(
			"dataConnessione",
			new Function<Nodo, Object>() {

				@Override
				public Object apply(Nodo nodo) {
					return nodo.getDataConnessione();
				}

			});
		attributeSetterBiConsumers.put(
			"dataConnessione",
			new BiConsumer<Nodo, Object>() {

				@Override
				public void accept(Nodo nodo, Object dataConnessione) {
					nodo.setDataConnessione((Date)dataConnessione);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getId() {
		return _Id;
	}

	@Override
	public void setId(long Id) {
		_columnBitmask = -1L;

		_Id = Id;
	}

	@JSON
	@Override
	public String getIp() {
		if (_ip == null) {
			return "";
		}
		else {
			return _ip;
		}
	}

	@Override
	public void setIp(String ip) {
		_columnBitmask |= IP_COLUMN_BITMASK;

		if (_originalIp == null) {
			_originalIp = _ip;
		}

		_ip = ip;
	}

	public String getOriginalIp() {
		return GetterUtil.getString(_originalIp);
	}

	@JSON
	@Override
	public int getPorta() {
		return _porta;
	}

	@Override
	public void setPorta(int porta) {
		_porta = porta;
	}

	@JSON
	@Override
	public String getNodoConnesso() {
		if (_nodoConnesso == null) {
			return "";
		}
		else {
			return _nodoConnesso;
		}
	}

	@Override
	public void setNodoConnesso(String nodoConnesso) {
		_columnBitmask |= NODOCONNESSO_COLUMN_BITMASK;

		if (_originalNodoConnesso == null) {
			_originalNodoConnesso = _nodoConnesso;
		}

		_nodoConnesso = nodoConnesso;
	}

	public String getOriginalNodoConnesso() {
		return GetterUtil.getString(_originalNodoConnesso);
	}

	@JSON
	@Override
	public Date getDataConnessione() {
		return _dataConnessione;
	}

	@Override
	public void setDataConnessione(Date dataConnessione) {
		_dataConnessione = dataConnessione;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Nodo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Nodo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Nodo)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NodoImpl nodoImpl = new NodoImpl();

		nodoImpl.setId(getId());
		nodoImpl.setIp(getIp());
		nodoImpl.setPorta(getPorta());
		nodoImpl.setNodoConnesso(getNodoConnesso());
		nodoImpl.setDataConnessione(getDataConnessione());

		nodoImpl.resetOriginalValues();

		return nodoImpl;
	}

	@Override
	public int compareTo(Nodo nodo) {
		int value = 0;

		if (getId() < nodo.getId()) {
			value = -1;
		}
		else if (getId() > nodo.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Nodo)) {
			return false;
		}

		Nodo nodo = (Nodo)obj;

		long primaryKey = nodo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		NodoModelImpl nodoModelImpl = this;

		nodoModelImpl._originalIp = nodoModelImpl._ip;

		nodoModelImpl._originalNodoConnesso = nodoModelImpl._nodoConnesso;

		nodoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Nodo> toCacheModel() {
		NodoCacheModel nodoCacheModel = new NodoCacheModel();

		nodoCacheModel.Id = getId();

		nodoCacheModel.ip = getIp();

		String ip = nodoCacheModel.ip;

		if ((ip != null) && (ip.length() == 0)) {
			nodoCacheModel.ip = null;
		}

		nodoCacheModel.porta = getPorta();

		nodoCacheModel.nodoConnesso = getNodoConnesso();

		String nodoConnesso = nodoCacheModel.nodoConnesso;

		if ((nodoConnesso != null) && (nodoConnesso.length() == 0)) {
			nodoCacheModel.nodoConnesso = null;
		}

		Date dataConnessione = getDataConnessione();

		if (dataConnessione != null) {
			nodoCacheModel.dataConnessione = dataConnessione.getTime();
		}
		else {
			nodoCacheModel.dataConnessione = Long.MIN_VALUE;
		}

		return nodoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Nodo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Nodo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Nodo, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Nodo)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Nodo, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Nodo, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Nodo, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Nodo)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Nodo.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		Nodo.class, ModelWrapper.class
	};

	private long _Id;
	private String _ip;
	private String _originalIp;
	private int _porta;
	private String _nodoConnesso;
	private String _originalNodoConnesso;
	private Date _dataConnessione;
	private long _columnBitmask;
	private Nodo _escapedModel;

}