/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerta.messages.services.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import it.eng.allerta.messages.services.model.SmsSchedulerContext;
import it.eng.allerta.messages.services.model.SmsSchedulerContextModel;
import it.eng.allerta.messages.services.model.SmsSchedulerContextSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SmsSchedulerContext service. Represents a row in the &quot;smsService_SmsSchedulerContext&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>SmsSchedulerContextModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SmsSchedulerContextImpl}.
 * </p>
 *
 * @author Giorgianni_F
 * @see SmsSchedulerContextImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SmsSchedulerContextModelImpl
	extends BaseModelImpl<SmsSchedulerContext>
	implements SmsSchedulerContextModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a sms scheduler context model instance should use the <code>SmsSchedulerContext</code> interface instead.
	 */
	public static final String TABLE_NAME = "smsService_SmsSchedulerContext";

	public static final Object[][] TABLE_COLUMNS = {
		{"varId", Types.VARCHAR}, {"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("varId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table smsService_SmsSchedulerContext (varId VARCHAR(75) not null primary key,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table smsService_SmsSchedulerContext";

	public static final String ORDER_BY_JPQL =
		" ORDER BY smsSchedulerContext.varId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY smsService_SmsSchedulerContext.varId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.allerta.messages.services.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.it.eng.allerta.messages.services.model.SmsSchedulerContext"),
		false);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.allerta.messages.services.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.it.eng.allerta.messages.services.model.SmsSchedulerContext"),
		false);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SmsSchedulerContext toModel(
		SmsSchedulerContextSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		SmsSchedulerContext model = new SmsSchedulerContextImpl();

		model.setVarId(soapModel.getVarId());
		model.setValue(soapModel.getValue());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SmsSchedulerContext> toModels(
		SmsSchedulerContextSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<SmsSchedulerContext> models = new ArrayList<SmsSchedulerContext>(
			soapModels.length);

		for (SmsSchedulerContextSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		it.eng.allerta.messages.services.service.util.ServiceProps.get(
			"lock.expiration.time.it.eng.allerta.messages.services.model.SmsSchedulerContext"));

	public SmsSchedulerContextModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _varId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setVarId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _varId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return SmsSchedulerContext.class;
	}

	@Override
	public String getModelClassName() {
		return SmsSchedulerContext.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SmsSchedulerContext, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SmsSchedulerContext, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmsSchedulerContext, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SmsSchedulerContext)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SmsSchedulerContext, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SmsSchedulerContext, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SmsSchedulerContext)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SmsSchedulerContext, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SmsSchedulerContext, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<SmsSchedulerContext, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SmsSchedulerContext, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<SmsSchedulerContext, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<SmsSchedulerContext, Object>>();
		Map<String, BiConsumer<SmsSchedulerContext, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SmsSchedulerContext, ?>>();

		attributeGetterFunctions.put(
			"varId",
			new Function<SmsSchedulerContext, Object>() {

				@Override
				public Object apply(SmsSchedulerContext smsSchedulerContext) {
					return smsSchedulerContext.getVarId();
				}

			});
		attributeSetterBiConsumers.put(
			"varId",
			new BiConsumer<SmsSchedulerContext, Object>() {

				@Override
				public void accept(
					SmsSchedulerContext smsSchedulerContext, Object varId) {

					smsSchedulerContext.setVarId((String)varId);
				}

			});
		attributeGetterFunctions.put(
			"value",
			new Function<SmsSchedulerContext, Object>() {

				@Override
				public Object apply(SmsSchedulerContext smsSchedulerContext) {
					return smsSchedulerContext.getValue();
				}

			});
		attributeSetterBiConsumers.put(
			"value",
			new BiConsumer<SmsSchedulerContext, Object>() {

				@Override
				public void accept(
					SmsSchedulerContext smsSchedulerContext, Object value) {

					smsSchedulerContext.setValue((String)value);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getVarId() {
		if (_varId == null) {
			return "";
		}
		else {
			return _varId;
		}
	}

	@Override
	public void setVarId(String varId) {
		_varId = varId;
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	@Override
	public SmsSchedulerContext toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SmsSchedulerContext)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SmsSchedulerContextImpl smsSchedulerContextImpl =
			new SmsSchedulerContextImpl();

		smsSchedulerContextImpl.setVarId(getVarId());
		smsSchedulerContextImpl.setValue(getValue());

		smsSchedulerContextImpl.resetOriginalValues();

		return smsSchedulerContextImpl;
	}

	@Override
	public int compareTo(SmsSchedulerContext smsSchedulerContext) {
		String primaryKey = smsSchedulerContext.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SmsSchedulerContext)) {
			return false;
		}

		SmsSchedulerContext smsSchedulerContext = (SmsSchedulerContext)obj;

		String primaryKey = smsSchedulerContext.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<SmsSchedulerContext> toCacheModel() {
		SmsSchedulerContextCacheModel smsSchedulerContextCacheModel =
			new SmsSchedulerContextCacheModel();

		smsSchedulerContextCacheModel.varId = getVarId();

		String varId = smsSchedulerContextCacheModel.varId;

		if ((varId != null) && (varId.length() == 0)) {
			smsSchedulerContextCacheModel.varId = null;
		}

		smsSchedulerContextCacheModel.value = getValue();

		String value = smsSchedulerContextCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			smsSchedulerContextCacheModel.value = null;
		}

		return smsSchedulerContextCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SmsSchedulerContext, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SmsSchedulerContext, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmsSchedulerContext, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((SmsSchedulerContext)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SmsSchedulerContext, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SmsSchedulerContext, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SmsSchedulerContext, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SmsSchedulerContext)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		SmsSchedulerContext.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		SmsSchedulerContext.class, ModelWrapper.class
	};

	private String _varId;
	private String _value;
	private SmsSchedulerContext _escapedModel;

}