/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.bollettino.model.AttivazioneFiume;
import it.eng.bollettino.model.AttivazioneFiumeModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AttivazioneFiume service. Represents a row in the &quot;BOLLETTINO_AttivazioneFiume&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AttivazioneFiumeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AttivazioneFiumeImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see AttivazioneFiumeImpl
 * @generated
 */
@JSON(strict = true)
public class AttivazioneFiumeModelImpl
	extends BaseModelImpl<AttivazioneFiume> implements AttivazioneFiumeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a attivazione fiume model instance should use the <code>AttivazioneFiume</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOLLETTINO_AttivazioneFiume";

	public static final Object[][] TABLE_COLUMNS = {
		{"fiumeId", Types.VARCHAR}, {"attivo", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("fiumeId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("attivo", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOLLETTINO_AttivazioneFiume (fiumeId VARCHAR(75) not null primary key,attivo BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table BOLLETTINO_AttivazioneFiume";

	public static final String ORDER_BY_JPQL =
		" ORDER BY attivazioneFiume.fiumeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOLLETTINO_AttivazioneFiume.fiumeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FIUMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AttivazioneFiumeModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _fiumeId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setFiumeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _fiumeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return AttivazioneFiume.class;
	}

	@Override
	public String getModelClassName() {
		return AttivazioneFiume.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AttivazioneFiume, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AttivazioneFiume, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AttivazioneFiume, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AttivazioneFiume)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AttivazioneFiume, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AttivazioneFiume, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AttivazioneFiume)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AttivazioneFiume, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AttivazioneFiume, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AttivazioneFiume, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AttivazioneFiume, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AttivazioneFiume, Object>>();

			attributeGetterFunctions.put(
				"fiumeId", AttivazioneFiume::getFiumeId);
			attributeGetterFunctions.put("attivo", AttivazioneFiume::getAttivo);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AttivazioneFiume, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AttivazioneFiume, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AttivazioneFiume, ?>>();

			attributeSetterBiConsumers.put(
				"fiumeId",
				(BiConsumer<AttivazioneFiume, String>)
					AttivazioneFiume::setFiumeId);
			attributeSetterBiConsumers.put(
				"attivo",
				(BiConsumer<AttivazioneFiume, Boolean>)
					AttivazioneFiume::setAttivo);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getFiumeId() {
		if (_fiumeId == null) {
			return "";
		}
		else {
			return _fiumeId;
		}
	}

	@Override
	public void setFiumeId(String fiumeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fiumeId = fiumeId;
	}

	@JSON
	@Override
	public boolean getAttivo() {
		return _attivo;
	}

	@JSON
	@Override
	public boolean isAttivo() {
		return _attivo;
	}

	@Override
	public void setAttivo(boolean attivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_attivo = attivo;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public AttivazioneFiume toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AttivazioneFiume>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AttivazioneFiumeImpl attivazioneFiumeImpl = new AttivazioneFiumeImpl();

		attivazioneFiumeImpl.setFiumeId(getFiumeId());
		attivazioneFiumeImpl.setAttivo(isAttivo());

		attivazioneFiumeImpl.resetOriginalValues();

		return attivazioneFiumeImpl;
	}

	@Override
	public AttivazioneFiume cloneWithOriginalValues() {
		AttivazioneFiumeImpl attivazioneFiumeImpl = new AttivazioneFiumeImpl();

		attivazioneFiumeImpl.setFiumeId(
			this.<String>getColumnOriginalValue("fiumeId"));
		attivazioneFiumeImpl.setAttivo(
			this.<Boolean>getColumnOriginalValue("attivo"));

		return attivazioneFiumeImpl;
	}

	@Override
	public int compareTo(AttivazioneFiume attivazioneFiume) {
		int value = 0;

		value = getFiumeId().compareTo(attivazioneFiume.getFiumeId());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AttivazioneFiume)) {
			return false;
		}

		AttivazioneFiume attivazioneFiume = (AttivazioneFiume)object;

		String primaryKey = attivazioneFiume.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AttivazioneFiume> toCacheModel() {
		AttivazioneFiumeCacheModel attivazioneFiumeCacheModel =
			new AttivazioneFiumeCacheModel();

		attivazioneFiumeCacheModel.fiumeId = getFiumeId();

		String fiumeId = attivazioneFiumeCacheModel.fiumeId;

		if ((fiumeId != null) && (fiumeId.length() == 0)) {
			attivazioneFiumeCacheModel.fiumeId = null;
		}

		attivazioneFiumeCacheModel.attivo = isAttivo();

		return attivazioneFiumeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AttivazioneFiume, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AttivazioneFiume, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AttivazioneFiume, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AttivazioneFiume)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AttivazioneFiume>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AttivazioneFiume.class, ModelWrapper.class);

	}

	private String _fiumeId;
	private boolean _attivo;

	public <T> T getColumnValue(String columnName) {
		Function<AttivazioneFiume, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AttivazioneFiume)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("fiumeId", _fiumeId);
		_columnOriginalValues.put("attivo", _attivo);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("fiumeId", 1L);

		columnBitmasks.put("attivo", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AttivazioneFiume _escapedModel;

}