/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.bollettino.model.BollettinoParametro;
import it.eng.bollettino.model.BollettinoParametroModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BollettinoParametro service. Represents a row in the &quot;BOLLETTINO_BollettinoParametro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BollettinoParametroModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BollettinoParametroImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see BollettinoParametroImpl
 * @generated
 */
@JSON(strict = true)
public class BollettinoParametroModelImpl
	extends BaseModelImpl<BollettinoParametro>
	implements BollettinoParametroModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bollettino parametro model instance should use the <code>BollettinoParametro</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOLLETTINO_BollettinoParametro";

	public static final Object[][] TABLE_COLUMNS = {
		{"parametroId", Types.VARCHAR}, {"valore", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("parametroId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valore", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOLLETTINO_BollettinoParametro (parametroId VARCHAR(75) not null primary key,valore VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table BOLLETTINO_BollettinoParametro";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bollettinoParametro.parametroId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOLLETTINO_BollettinoParametro.parametroId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PARAMETROID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BollettinoParametroModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _parametroId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setParametroId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _parametroId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return BollettinoParametro.class;
	}

	@Override
	public String getModelClassName() {
		return BollettinoParametro.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BollettinoParametro, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BollettinoParametro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BollettinoParametro, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BollettinoParametro)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BollettinoParametro, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BollettinoParametro, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BollettinoParametro)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BollettinoParametro, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BollettinoParametro, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BollettinoParametro, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BollettinoParametro, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BollettinoParametro, Object>>();

			attributeGetterFunctions.put(
				"parametroId", BollettinoParametro::getParametroId);
			attributeGetterFunctions.put(
				"valore", BollettinoParametro::getValore);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<BollettinoParametro, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BollettinoParametro, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<BollettinoParametro, ?>>();

			attributeSetterBiConsumers.put(
				"parametroId",
				(BiConsumer<BollettinoParametro, String>)
					BollettinoParametro::setParametroId);
			attributeSetterBiConsumers.put(
				"valore",
				(BiConsumer<BollettinoParametro, String>)
					BollettinoParametro::setValore);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getParametroId() {
		if (_parametroId == null) {
			return "";
		}
		else {
			return _parametroId;
		}
	}

	@Override
	public void setParametroId(String parametroId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parametroId = parametroId;
	}

	@JSON
	@Override
	public String getValore() {
		if (_valore == null) {
			return "";
		}
		else {
			return _valore;
		}
	}

	@Override
	public void setValore(String valore) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valore = valore;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public BollettinoParametro toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BollettinoParametro>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BollettinoParametroImpl bollettinoParametroImpl =
			new BollettinoParametroImpl();

		bollettinoParametroImpl.setParametroId(getParametroId());
		bollettinoParametroImpl.setValore(getValore());

		bollettinoParametroImpl.resetOriginalValues();

		return bollettinoParametroImpl;
	}

	@Override
	public BollettinoParametro cloneWithOriginalValues() {
		BollettinoParametroImpl bollettinoParametroImpl =
			new BollettinoParametroImpl();

		bollettinoParametroImpl.setParametroId(
			this.<String>getColumnOriginalValue("parametroId"));
		bollettinoParametroImpl.setValore(
			this.<String>getColumnOriginalValue("valore"));

		return bollettinoParametroImpl;
	}

	@Override
	public int compareTo(BollettinoParametro bollettinoParametro) {
		int value = 0;

		value = getParametroId().compareTo(
			bollettinoParametro.getParametroId());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BollettinoParametro)) {
			return false;
		}

		BollettinoParametro bollettinoParametro = (BollettinoParametro)object;

		String primaryKey = bollettinoParametro.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BollettinoParametro> toCacheModel() {
		BollettinoParametroCacheModel bollettinoParametroCacheModel =
			new BollettinoParametroCacheModel();

		bollettinoParametroCacheModel.parametroId = getParametroId();

		String parametroId = bollettinoParametroCacheModel.parametroId;

		if ((parametroId != null) && (parametroId.length() == 0)) {
			bollettinoParametroCacheModel.parametroId = null;
		}

		bollettinoParametroCacheModel.valore = getValore();

		String valore = bollettinoParametroCacheModel.valore;

		if ((valore != null) && (valore.length() == 0)) {
			bollettinoParametroCacheModel.valore = null;
		}

		return bollettinoParametroCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BollettinoParametro, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BollettinoParametro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BollettinoParametro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BollettinoParametro)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BollettinoParametro>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BollettinoParametro.class, ModelWrapper.class);

	}

	private String _parametroId;
	private String _valore;

	public <T> T getColumnValue(String columnName) {
		Function<BollettinoParametro, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BollettinoParametro)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("parametroId", _parametroId);
		_columnOriginalValues.put("valore", _valore);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("parametroId", 1L);

		columnBitmasks.put("valore", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BollettinoParametro _escapedModel;

}