/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.bollettino.model.BollettinoIcona;
import it.eng.bollettino.model.BollettinoIconaModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BollettinoIcona service. Represents a row in the &quot;BOLLETTINO_BollettinoIcona&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BollettinoIconaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BollettinoIconaImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see BollettinoIconaImpl
 * @generated
 */
@JSON(strict = true)
public class BollettinoIconaModelImpl
	extends BaseModelImpl<BollettinoIcona> implements BollettinoIconaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bollettino icona model instance should use the <code>BollettinoIcona</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOLLETTINO_BollettinoIcona";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"idBollettino", Types.BIGINT}, {"idIcona", Types.BIGINT},
		{"x", Types.DOUBLE}, {"y", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idBollettino", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idIcona", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("x", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("y", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOLLETTINO_BollettinoIcona (uuid_ VARCHAR(75) null,id_ LONG not null primary key,idBollettino LONG,idIcona LONG,x DOUBLE,y DOUBLE)";

	public static final String TABLE_SQL_DROP =
		"drop table BOLLETTINO_BollettinoIcona";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bollettinoIcona.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOLLETTINO_BollettinoIcona.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDBOLLETTINO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BollettinoIconaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BollettinoIcona.class;
	}

	@Override
	public String getModelClassName() {
		return BollettinoIcona.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BollettinoIcona, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BollettinoIcona, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BollettinoIcona, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BollettinoIcona)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BollettinoIcona, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BollettinoIcona, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BollettinoIcona)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BollettinoIcona, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BollettinoIcona, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BollettinoIcona, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BollettinoIcona, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BollettinoIcona, Object>>();

			attributeGetterFunctions.put("uuid", BollettinoIcona::getUuid);
			attributeGetterFunctions.put("id", BollettinoIcona::getId);
			attributeGetterFunctions.put(
				"idBollettino", BollettinoIcona::getIdBollettino);
			attributeGetterFunctions.put(
				"idIcona", BollettinoIcona::getIdIcona);
			attributeGetterFunctions.put("x", BollettinoIcona::getX);
			attributeGetterFunctions.put("y", BollettinoIcona::getY);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BollettinoIcona, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BollettinoIcona, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<BollettinoIcona, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<BollettinoIcona, String>)BollettinoIcona::setUuid);
			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<BollettinoIcona, Long>)BollettinoIcona::setId);
			attributeSetterBiConsumers.put(
				"idBollettino",
				(BiConsumer<BollettinoIcona, Long>)
					BollettinoIcona::setIdBollettino);
			attributeSetterBiConsumers.put(
				"idIcona",
				(BiConsumer<BollettinoIcona, Long>)BollettinoIcona::setIdIcona);
			attributeSetterBiConsumers.put(
				"x",
				(BiConsumer<BollettinoIcona, Double>)BollettinoIcona::setX);
			attributeSetterBiConsumers.put(
				"y",
				(BiConsumer<BollettinoIcona, Double>)BollettinoIcona::setY);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getIdBollettino() {
		return _idBollettino;
	}

	@Override
	public void setIdBollettino(long idBollettino) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idBollettino = idBollettino;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdBollettino() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idBollettino"));
	}

	@JSON
	@Override
	public long getIdIcona() {
		return _idIcona;
	}

	@Override
	public void setIdIcona(long idIcona) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idIcona = idIcona;
	}

	@JSON
	@Override
	public double getX() {
		return _x;
	}

	@Override
	public void setX(double x) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_x = x;
	}

	@JSON
	@Override
	public double getY() {
		return _y;
	}

	@Override
	public void setY(double y) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_y = y;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BollettinoIcona.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BollettinoIcona toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BollettinoIcona>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BollettinoIconaImpl bollettinoIconaImpl = new BollettinoIconaImpl();

		bollettinoIconaImpl.setUuid(getUuid());
		bollettinoIconaImpl.setId(getId());
		bollettinoIconaImpl.setIdBollettino(getIdBollettino());
		bollettinoIconaImpl.setIdIcona(getIdIcona());
		bollettinoIconaImpl.setX(getX());
		bollettinoIconaImpl.setY(getY());

		bollettinoIconaImpl.resetOriginalValues();

		return bollettinoIconaImpl;
	}

	@Override
	public BollettinoIcona cloneWithOriginalValues() {
		BollettinoIconaImpl bollettinoIconaImpl = new BollettinoIconaImpl();

		bollettinoIconaImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		bollettinoIconaImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		bollettinoIconaImpl.setIdBollettino(
			this.<Long>getColumnOriginalValue("idBollettino"));
		bollettinoIconaImpl.setIdIcona(
			this.<Long>getColumnOriginalValue("idIcona"));
		bollettinoIconaImpl.setX(this.<Double>getColumnOriginalValue("x"));
		bollettinoIconaImpl.setY(this.<Double>getColumnOriginalValue("y"));

		return bollettinoIconaImpl;
	}

	@Override
	public int compareTo(BollettinoIcona bollettinoIcona) {
		int value = 0;

		if (getId() < bollettinoIcona.getId()) {
			value = -1;
		}
		else if (getId() > bollettinoIcona.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BollettinoIcona)) {
			return false;
		}

		BollettinoIcona bollettinoIcona = (BollettinoIcona)object;

		long primaryKey = bollettinoIcona.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BollettinoIcona> toCacheModel() {
		BollettinoIconaCacheModel bollettinoIconaCacheModel =
			new BollettinoIconaCacheModel();

		bollettinoIconaCacheModel.uuid = getUuid();

		String uuid = bollettinoIconaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			bollettinoIconaCacheModel.uuid = null;
		}

		bollettinoIconaCacheModel.id = getId();

		bollettinoIconaCacheModel.idBollettino = getIdBollettino();

		bollettinoIconaCacheModel.idIcona = getIdIcona();

		bollettinoIconaCacheModel.x = getX();

		bollettinoIconaCacheModel.y = getY();

		return bollettinoIconaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BollettinoIcona, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BollettinoIcona, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BollettinoIcona, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((BollettinoIcona)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BollettinoIcona>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BollettinoIcona.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _id;
	private long _idBollettino;
	private long _idIcona;
	private double _x;
	private double _y;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BollettinoIcona, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BollettinoIcona)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("idBollettino", _idBollettino);
		_columnOriginalValues.put("idIcona", _idIcona);
		_columnOriginalValues.put("x", _x);
		_columnOriginalValues.put("y", _y);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("id_", 2L);

		columnBitmasks.put("idBollettino", 4L);

		columnBitmasks.put("idIcona", 8L);

		columnBitmasks.put("x", 16L);

		columnBitmasks.put("y", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BollettinoIcona _escapedModel;

}