/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.bollettino.model.Bollettino;
import it.eng.bollettino.model.BollettinoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Bollettino service. Represents a row in the &quot;BOLLETTINO_Bollettino&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BollettinoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BollettinoImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see BollettinoImpl
 * @generated
 */
@JSON(strict = true)
public class BollettinoModelImpl
	extends BaseModelImpl<Bollettino> implements BollettinoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bollettino model instance should use the <code>Bollettino</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOLLETTINO_Bollettino";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"bollettinoId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"stato", Types.INTEGER}, {"idApprovatore", Types.BIGINT},
		{"dataApprovazione", Types.TIMESTAMP}, {"numero", Types.VARCHAR},
		{"progressivo", Types.INTEGER}, {"anno", Types.INTEGER},
		{"dataEmissione", Types.TIMESTAMP}, {"dataInizio", Types.TIMESTAMP},
		{"dataFine", Types.TIMESTAMP}, {"noteMeteo", Types.VARCHAR},
		{"stringaMeteo", Types.VARCHAR}, {"link", Types.VARCHAR},
		{"ultimo", Types.BOOLEAN}, {"hash", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bollettinoId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("stato", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("idApprovatore", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dataApprovazione", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("numero", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("progressivo", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("anno", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dataEmissione", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataInizio", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataFine", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("noteMeteo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("stringaMeteo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("link", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ultimo", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hash", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOLLETTINO_Bollettino (uuid_ VARCHAR(75) null,bollettinoId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,stato INTEGER,idApprovatore LONG,dataApprovazione DATE null,numero VARCHAR(75) null,progressivo INTEGER,anno INTEGER,dataEmissione DATE null,dataInizio DATE null,dataFine DATE null,noteMeteo VARCHAR(75) null,stringaMeteo VARCHAR(75) null,link VARCHAR(75) null,ultimo BOOLEAN,hash VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table BOLLETTINO_Bollettino";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bollettino.numero ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOLLETTINO_Bollettino.numero ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NUMERO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BollettinoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bollettinoId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBollettinoId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bollettinoId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Bollettino.class;
	}

	@Override
	public String getModelClassName() {
		return Bollettino.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Bollettino, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Bollettino, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Bollettino, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Bollettino)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Bollettino, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Bollettino, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Bollettino)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Bollettino, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Bollettino, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Bollettino, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Bollettino, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Bollettino, Object>>();

			attributeGetterFunctions.put("uuid", Bollettino::getUuid);
			attributeGetterFunctions.put(
				"bollettinoId", Bollettino::getBollettinoId);
			attributeGetterFunctions.put("groupId", Bollettino::getGroupId);
			attributeGetterFunctions.put("companyId", Bollettino::getCompanyId);
			attributeGetterFunctions.put("userId", Bollettino::getUserId);
			attributeGetterFunctions.put("userName", Bollettino::getUserName);
			attributeGetterFunctions.put(
				"createDate", Bollettino::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Bollettino::getModifiedDate);
			attributeGetterFunctions.put("stato", Bollettino::getStato);
			attributeGetterFunctions.put(
				"idApprovatore", Bollettino::getIdApprovatore);
			attributeGetterFunctions.put(
				"dataApprovazione", Bollettino::getDataApprovazione);
			attributeGetterFunctions.put("numero", Bollettino::getNumero);
			attributeGetterFunctions.put(
				"progressivo", Bollettino::getProgressivo);
			attributeGetterFunctions.put("anno", Bollettino::getAnno);
			attributeGetterFunctions.put(
				"dataEmissione", Bollettino::getDataEmissione);
			attributeGetterFunctions.put(
				"dataInizio", Bollettino::getDataInizio);
			attributeGetterFunctions.put("dataFine", Bollettino::getDataFine);
			attributeGetterFunctions.put("noteMeteo", Bollettino::getNoteMeteo);
			attributeGetterFunctions.put(
				"stringaMeteo", Bollettino::getStringaMeteo);
			attributeGetterFunctions.put("link", Bollettino::getLink);
			attributeGetterFunctions.put("ultimo", Bollettino::getUltimo);
			attributeGetterFunctions.put("hash", Bollettino::getHash);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Bollettino, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Bollettino, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Bollettino, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Bollettino, String>)Bollettino::setUuid);
			attributeSetterBiConsumers.put(
				"bollettinoId",
				(BiConsumer<Bollettino, Long>)Bollettino::setBollettinoId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<Bollettino, Long>)Bollettino::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<Bollettino, Long>)Bollettino::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<Bollettino, Long>)Bollettino::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<Bollettino, String>)Bollettino::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Bollettino, Date>)Bollettino::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Bollettino, Date>)Bollettino::setModifiedDate);
			attributeSetterBiConsumers.put(
				"stato", (BiConsumer<Bollettino, Integer>)Bollettino::setStato);
			attributeSetterBiConsumers.put(
				"idApprovatore",
				(BiConsumer<Bollettino, Long>)Bollettino::setIdApprovatore);
			attributeSetterBiConsumers.put(
				"dataApprovazione",
				(BiConsumer<Bollettino, Date>)Bollettino::setDataApprovazione);
			attributeSetterBiConsumers.put(
				"numero",
				(BiConsumer<Bollettino, String>)Bollettino::setNumero);
			attributeSetterBiConsumers.put(
				"progressivo",
				(BiConsumer<Bollettino, Integer>)Bollettino::setProgressivo);
			attributeSetterBiConsumers.put(
				"anno", (BiConsumer<Bollettino, Integer>)Bollettino::setAnno);
			attributeSetterBiConsumers.put(
				"dataEmissione",
				(BiConsumer<Bollettino, Date>)Bollettino::setDataEmissione);
			attributeSetterBiConsumers.put(
				"dataInizio",
				(BiConsumer<Bollettino, Date>)Bollettino::setDataInizio);
			attributeSetterBiConsumers.put(
				"dataFine",
				(BiConsumer<Bollettino, Date>)Bollettino::setDataFine);
			attributeSetterBiConsumers.put(
				"noteMeteo",
				(BiConsumer<Bollettino, String>)Bollettino::setNoteMeteo);
			attributeSetterBiConsumers.put(
				"stringaMeteo",
				(BiConsumer<Bollettino, String>)Bollettino::setStringaMeteo);
			attributeSetterBiConsumers.put(
				"link", (BiConsumer<Bollettino, String>)Bollettino::setLink);
			attributeSetterBiConsumers.put(
				"ultimo",
				(BiConsumer<Bollettino, Boolean>)Bollettino::setUltimo);
			attributeSetterBiConsumers.put(
				"hash", (BiConsumer<Bollettino, String>)Bollettino::setHash);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getBollettinoId() {
		return _bollettinoId;
	}

	@Override
	public void setBollettinoId(long bollettinoId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_bollettinoId = bollettinoId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStato() {
		return _stato;
	}

	@Override
	public void setStato(int stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stato = stato;
	}

	@JSON
	@Override
	public long getIdApprovatore() {
		return _idApprovatore;
	}

	@Override
	public void setIdApprovatore(long idApprovatore) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idApprovatore = idApprovatore;
	}

	@JSON
	@Override
	public Date getDataApprovazione() {
		return _dataApprovazione;
	}

	@Override
	public void setDataApprovazione(Date dataApprovazione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataApprovazione = dataApprovazione;
	}

	@JSON
	@Override
	public String getNumero() {
		if (_numero == null) {
			return "";
		}
		else {
			return _numero;
		}
	}

	@Override
	public void setNumero(String numero) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numero = numero;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNumero() {
		return getColumnOriginalValue("numero");
	}

	@JSON
	@Override
	public int getProgressivo() {
		return _progressivo;
	}

	@Override
	public void setProgressivo(int progressivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_progressivo = progressivo;
	}

	@JSON
	@Override
	public int getAnno() {
		return _anno;
	}

	@Override
	public void setAnno(int anno) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_anno = anno;
	}

	@JSON
	@Override
	public Date getDataEmissione() {
		return _dataEmissione;
	}

	@Override
	public void setDataEmissione(Date dataEmissione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataEmissione = dataEmissione;
	}

	@JSON
	@Override
	public Date getDataInizio() {
		return _dataInizio;
	}

	@Override
	public void setDataInizio(Date dataInizio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataInizio = dataInizio;
	}

	@JSON
	@Override
	public Date getDataFine() {
		return _dataFine;
	}

	@Override
	public void setDataFine(Date dataFine) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataFine = dataFine;
	}

	@JSON
	@Override
	public String getNoteMeteo() {
		if (_noteMeteo == null) {
			return "";
		}
		else {
			return _noteMeteo;
		}
	}

	@Override
	public void setNoteMeteo(String noteMeteo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_noteMeteo = noteMeteo;
	}

	@JSON
	@Override
	public String getStringaMeteo() {
		if (_stringaMeteo == null) {
			return "";
		}
		else {
			return _stringaMeteo;
		}
	}

	@Override
	public void setStringaMeteo(String stringaMeteo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stringaMeteo = stringaMeteo;
	}

	@JSON
	@Override
	public String getLink() {
		if (_link == null) {
			return "";
		}
		else {
			return _link;
		}
	}

	@Override
	public void setLink(String link) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_link = link;
	}

	@JSON
	@Override
	public boolean getUltimo() {
		return _ultimo;
	}

	@JSON
	@Override
	public boolean isUltimo() {
		return _ultimo;
	}

	@Override
	public void setUltimo(boolean ultimo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ultimo = ultimo;
	}

	@JSON
	@Override
	public String getHash() {
		if (_hash == null) {
			return "";
		}
		else {
			return _hash;
		}
	}

	@Override
	public void setHash(String hash) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_hash = hash;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Bollettino.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Bollettino.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Bollettino toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Bollettino>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BollettinoImpl bollettinoImpl = new BollettinoImpl();

		bollettinoImpl.setUuid(getUuid());
		bollettinoImpl.setBollettinoId(getBollettinoId());
		bollettinoImpl.setGroupId(getGroupId());
		bollettinoImpl.setCompanyId(getCompanyId());
		bollettinoImpl.setUserId(getUserId());
		bollettinoImpl.setUserName(getUserName());
		bollettinoImpl.setCreateDate(getCreateDate());
		bollettinoImpl.setModifiedDate(getModifiedDate());
		bollettinoImpl.setStato(getStato());
		bollettinoImpl.setIdApprovatore(getIdApprovatore());
		bollettinoImpl.setDataApprovazione(getDataApprovazione());
		bollettinoImpl.setNumero(getNumero());
		bollettinoImpl.setProgressivo(getProgressivo());
		bollettinoImpl.setAnno(getAnno());
		bollettinoImpl.setDataEmissione(getDataEmissione());
		bollettinoImpl.setDataInizio(getDataInizio());
		bollettinoImpl.setDataFine(getDataFine());
		bollettinoImpl.setNoteMeteo(getNoteMeteo());
		bollettinoImpl.setStringaMeteo(getStringaMeteo());
		bollettinoImpl.setLink(getLink());
		bollettinoImpl.setUltimo(isUltimo());
		bollettinoImpl.setHash(getHash());

		bollettinoImpl.resetOriginalValues();

		return bollettinoImpl;
	}

	@Override
	public Bollettino cloneWithOriginalValues() {
		BollettinoImpl bollettinoImpl = new BollettinoImpl();

		bollettinoImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		bollettinoImpl.setBollettinoId(
			this.<Long>getColumnOriginalValue("bollettinoId"));
		bollettinoImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		bollettinoImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		bollettinoImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		bollettinoImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		bollettinoImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		bollettinoImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		bollettinoImpl.setStato(this.<Integer>getColumnOriginalValue("stato"));
		bollettinoImpl.setIdApprovatore(
			this.<Long>getColumnOriginalValue("idApprovatore"));
		bollettinoImpl.setDataApprovazione(
			this.<Date>getColumnOriginalValue("dataApprovazione"));
		bollettinoImpl.setNumero(this.<String>getColumnOriginalValue("numero"));
		bollettinoImpl.setProgressivo(
			this.<Integer>getColumnOriginalValue("progressivo"));
		bollettinoImpl.setAnno(this.<Integer>getColumnOriginalValue("anno"));
		bollettinoImpl.setDataEmissione(
			this.<Date>getColumnOriginalValue("dataEmissione"));
		bollettinoImpl.setDataInizio(
			this.<Date>getColumnOriginalValue("dataInizio"));
		bollettinoImpl.setDataFine(
			this.<Date>getColumnOriginalValue("dataFine"));
		bollettinoImpl.setNoteMeteo(
			this.<String>getColumnOriginalValue("noteMeteo"));
		bollettinoImpl.setStringaMeteo(
			this.<String>getColumnOriginalValue("stringaMeteo"));
		bollettinoImpl.setLink(this.<String>getColumnOriginalValue("link"));
		bollettinoImpl.setUltimo(
			this.<Boolean>getColumnOriginalValue("ultimo"));
		bollettinoImpl.setHash(this.<String>getColumnOriginalValue("hash"));

		return bollettinoImpl;
	}

	@Override
	public int compareTo(Bollettino bollettino) {
		int value = 0;

		value = getNumero().compareTo(bollettino.getNumero());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Bollettino)) {
			return false;
		}

		Bollettino bollettino = (Bollettino)object;

		long primaryKey = bollettino.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Bollettino> toCacheModel() {
		BollettinoCacheModel bollettinoCacheModel = new BollettinoCacheModel();

		bollettinoCacheModel.uuid = getUuid();

		String uuid = bollettinoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			bollettinoCacheModel.uuid = null;
		}

		bollettinoCacheModel.bollettinoId = getBollettinoId();

		bollettinoCacheModel.groupId = getGroupId();

		bollettinoCacheModel.companyId = getCompanyId();

		bollettinoCacheModel.userId = getUserId();

		bollettinoCacheModel.userName = getUserName();

		String userName = bollettinoCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			bollettinoCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			bollettinoCacheModel.createDate = createDate.getTime();
		}
		else {
			bollettinoCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			bollettinoCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			bollettinoCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		bollettinoCacheModel.stato = getStato();

		bollettinoCacheModel.idApprovatore = getIdApprovatore();

		Date dataApprovazione = getDataApprovazione();

		if (dataApprovazione != null) {
			bollettinoCacheModel.dataApprovazione = dataApprovazione.getTime();
		}
		else {
			bollettinoCacheModel.dataApprovazione = Long.MIN_VALUE;
		}

		bollettinoCacheModel.numero = getNumero();

		String numero = bollettinoCacheModel.numero;

		if ((numero != null) && (numero.length() == 0)) {
			bollettinoCacheModel.numero = null;
		}

		bollettinoCacheModel.progressivo = getProgressivo();

		bollettinoCacheModel.anno = getAnno();

		Date dataEmissione = getDataEmissione();

		if (dataEmissione != null) {
			bollettinoCacheModel.dataEmissione = dataEmissione.getTime();
		}
		else {
			bollettinoCacheModel.dataEmissione = Long.MIN_VALUE;
		}

		Date dataInizio = getDataInizio();

		if (dataInizio != null) {
			bollettinoCacheModel.dataInizio = dataInizio.getTime();
		}
		else {
			bollettinoCacheModel.dataInizio = Long.MIN_VALUE;
		}

		Date dataFine = getDataFine();

		if (dataFine != null) {
			bollettinoCacheModel.dataFine = dataFine.getTime();
		}
		else {
			bollettinoCacheModel.dataFine = Long.MIN_VALUE;
		}

		bollettinoCacheModel.noteMeteo = getNoteMeteo();

		String noteMeteo = bollettinoCacheModel.noteMeteo;

		if ((noteMeteo != null) && (noteMeteo.length() == 0)) {
			bollettinoCacheModel.noteMeteo = null;
		}

		bollettinoCacheModel.stringaMeteo = getStringaMeteo();

		String stringaMeteo = bollettinoCacheModel.stringaMeteo;

		if ((stringaMeteo != null) && (stringaMeteo.length() == 0)) {
			bollettinoCacheModel.stringaMeteo = null;
		}

		bollettinoCacheModel.link = getLink();

		String link = bollettinoCacheModel.link;

		if ((link != null) && (link.length() == 0)) {
			bollettinoCacheModel.link = null;
		}

		bollettinoCacheModel.ultimo = isUltimo();

		bollettinoCacheModel.hash = getHash();

		String hash = bollettinoCacheModel.hash;

		if ((hash != null) && (hash.length() == 0)) {
			bollettinoCacheModel.hash = null;
		}

		return bollettinoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Bollettino, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Bollettino, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Bollettino, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Bollettino)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Bollettino>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Bollettino.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _bollettinoId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _stato;
	private long _idApprovatore;
	private Date _dataApprovazione;
	private String _numero;
	private int _progressivo;
	private int _anno;
	private Date _dataEmissione;
	private Date _dataInizio;
	private Date _dataFine;
	private String _noteMeteo;
	private String _stringaMeteo;
	private String _link;
	private boolean _ultimo;
	private String _hash;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Bollettino, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Bollettino)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("bollettinoId", _bollettinoId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("stato", _stato);
		_columnOriginalValues.put("idApprovatore", _idApprovatore);
		_columnOriginalValues.put("dataApprovazione", _dataApprovazione);
		_columnOriginalValues.put("numero", _numero);
		_columnOriginalValues.put("progressivo", _progressivo);
		_columnOriginalValues.put("anno", _anno);
		_columnOriginalValues.put("dataEmissione", _dataEmissione);
		_columnOriginalValues.put("dataInizio", _dataInizio);
		_columnOriginalValues.put("dataFine", _dataFine);
		_columnOriginalValues.put("noteMeteo", _noteMeteo);
		_columnOriginalValues.put("stringaMeteo", _stringaMeteo);
		_columnOriginalValues.put("link", _link);
		_columnOriginalValues.put("ultimo", _ultimo);
		_columnOriginalValues.put("hash", _hash);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("bollettinoId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("stato", 256L);

		columnBitmasks.put("idApprovatore", 512L);

		columnBitmasks.put("dataApprovazione", 1024L);

		columnBitmasks.put("numero", 2048L);

		columnBitmasks.put("progressivo", 4096L);

		columnBitmasks.put("anno", 8192L);

		columnBitmasks.put("dataEmissione", 16384L);

		columnBitmasks.put("dataInizio", 32768L);

		columnBitmasks.put("dataFine", 65536L);

		columnBitmasks.put("noteMeteo", 131072L);

		columnBitmasks.put("stringaMeteo", 262144L);

		columnBitmasks.put("link", 524288L);

		columnBitmasks.put("ultimo", 1048576L);

		columnBitmasks.put("hash", 2097152L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Bollettino _escapedModel;

}