/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.bollettino.model.BollettinoBacino;
import it.eng.bollettino.model.BollettinoBacinoModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the BollettinoBacino service. Represents a row in the &quot;BOLLETTINO_BollettinoBacino&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>BollettinoBacinoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BollettinoBacinoImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see BollettinoBacinoImpl
 * @generated
 */
@JSON(strict = true)
public class BollettinoBacinoModelImpl
	extends BaseModelImpl<BollettinoBacino> implements BollettinoBacinoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bollettino bacino model instance should use the <code>BollettinoBacino</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOLLETTINO_BollettinoBacino";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"idBollettino", Types.BIGINT}, {"progressivo", Types.INTEGER},
		{"idBacino", Types.VARCHAR}, {"nomeBacino", Types.VARCHAR},
		{"oreOsservazione", Types.VARCHAR}, {"note", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idBollettino", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("progressivo", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("idBacino", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomeBacino", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("oreOsservazione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("note", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOLLETTINO_BollettinoBacino (uuid_ VARCHAR(75) null,id_ LONG not null primary key,idBollettino LONG,progressivo INTEGER,idBacino VARCHAR(75) null,nomeBacino VARCHAR(75) null,oreOsservazione VARCHAR(75) null,note VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table BOLLETTINO_BollettinoBacino";

	public static final String ORDER_BY_JPQL =
		" ORDER BY bollettinoBacino.progressivo ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOLLETTINO_BollettinoBacino.progressivo ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDBOLLETTINO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PROGRESSIVO_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public BollettinoBacinoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BollettinoBacino.class;
	}

	@Override
	public String getModelClassName() {
		return BollettinoBacino.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<BollettinoBacino, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<BollettinoBacino, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BollettinoBacino, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((BollettinoBacino)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<BollettinoBacino, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<BollettinoBacino, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(BollettinoBacino)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<BollettinoBacino, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<BollettinoBacino, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<BollettinoBacino, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<BollettinoBacino, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<BollettinoBacino, Object>>();

			attributeGetterFunctions.put("uuid", BollettinoBacino::getUuid);
			attributeGetterFunctions.put("id", BollettinoBacino::getId);
			attributeGetterFunctions.put(
				"idBollettino", BollettinoBacino::getIdBollettino);
			attributeGetterFunctions.put(
				"progressivo", BollettinoBacino::getProgressivo);
			attributeGetterFunctions.put(
				"idBacino", BollettinoBacino::getIdBacino);
			attributeGetterFunctions.put(
				"nomeBacino", BollettinoBacino::getNomeBacino);
			attributeGetterFunctions.put(
				"oreOsservazione", BollettinoBacino::getOreOsservazione);
			attributeGetterFunctions.put("note", BollettinoBacino::getNote);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<BollettinoBacino, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<BollettinoBacino, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<BollettinoBacino, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<BollettinoBacino, String>)
					BollettinoBacino::setUuid);
			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<BollettinoBacino, Long>)BollettinoBacino::setId);
			attributeSetterBiConsumers.put(
				"idBollettino",
				(BiConsumer<BollettinoBacino, Long>)
					BollettinoBacino::setIdBollettino);
			attributeSetterBiConsumers.put(
				"progressivo",
				(BiConsumer<BollettinoBacino, Integer>)
					BollettinoBacino::setProgressivo);
			attributeSetterBiConsumers.put(
				"idBacino",
				(BiConsumer<BollettinoBacino, String>)
					BollettinoBacino::setIdBacino);
			attributeSetterBiConsumers.put(
				"nomeBacino",
				(BiConsumer<BollettinoBacino, String>)
					BollettinoBacino::setNomeBacino);
			attributeSetterBiConsumers.put(
				"oreOsservazione",
				(BiConsumer<BollettinoBacino, String>)
					BollettinoBacino::setOreOsservazione);
			attributeSetterBiConsumers.put(
				"note",
				(BiConsumer<BollettinoBacino, String>)
					BollettinoBacino::setNote);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getIdBollettino() {
		return _idBollettino;
	}

	@Override
	public void setIdBollettino(long idBollettino) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idBollettino = idBollettino;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdBollettino() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idBollettino"));
	}

	@JSON
	@Override
	public int getProgressivo() {
		return _progressivo;
	}

	@Override
	public void setProgressivo(int progressivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_progressivo = progressivo;
	}

	@JSON
	@Override
	public String getIdBacino() {
		if (_idBacino == null) {
			return "";
		}
		else {
			return _idBacino;
		}
	}

	@Override
	public void setIdBacino(String idBacino) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idBacino = idBacino;
	}

	@JSON
	@Override
	public String getNomeBacino() {
		if (_nomeBacino == null) {
			return "";
		}
		else {
			return _nomeBacino;
		}
	}

	@Override
	public void setNomeBacino(String nomeBacino) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeBacino = nomeBacino;
	}

	@JSON
	@Override
	public String getOreOsservazione() {
		if (_oreOsservazione == null) {
			return "";
		}
		else {
			return _oreOsservazione;
		}
	}

	@Override
	public void setOreOsservazione(String oreOsservazione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_oreOsservazione = oreOsservazione;
	}

	@JSON
	@Override
	public String getNote() {
		if (_note == null) {
			return "";
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_note = note;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, BollettinoBacino.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BollettinoBacino toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, BollettinoBacino>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BollettinoBacinoImpl bollettinoBacinoImpl = new BollettinoBacinoImpl();

		bollettinoBacinoImpl.setUuid(getUuid());
		bollettinoBacinoImpl.setId(getId());
		bollettinoBacinoImpl.setIdBollettino(getIdBollettino());
		bollettinoBacinoImpl.setProgressivo(getProgressivo());
		bollettinoBacinoImpl.setIdBacino(getIdBacino());
		bollettinoBacinoImpl.setNomeBacino(getNomeBacino());
		bollettinoBacinoImpl.setOreOsservazione(getOreOsservazione());
		bollettinoBacinoImpl.setNote(getNote());

		bollettinoBacinoImpl.resetOriginalValues();

		return bollettinoBacinoImpl;
	}

	@Override
	public BollettinoBacino cloneWithOriginalValues() {
		BollettinoBacinoImpl bollettinoBacinoImpl = new BollettinoBacinoImpl();

		bollettinoBacinoImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		bollettinoBacinoImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		bollettinoBacinoImpl.setIdBollettino(
			this.<Long>getColumnOriginalValue("idBollettino"));
		bollettinoBacinoImpl.setProgressivo(
			this.<Integer>getColumnOriginalValue("progressivo"));
		bollettinoBacinoImpl.setIdBacino(
			this.<String>getColumnOriginalValue("idBacino"));
		bollettinoBacinoImpl.setNomeBacino(
			this.<String>getColumnOriginalValue("nomeBacino"));
		bollettinoBacinoImpl.setOreOsservazione(
			this.<String>getColumnOriginalValue("oreOsservazione"));
		bollettinoBacinoImpl.setNote(
			this.<String>getColumnOriginalValue("note"));

		return bollettinoBacinoImpl;
	}

	@Override
	public int compareTo(BollettinoBacino bollettinoBacino) {
		int value = 0;

		if (getProgressivo() < bollettinoBacino.getProgressivo()) {
			value = -1;
		}
		else if (getProgressivo() > bollettinoBacino.getProgressivo()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof BollettinoBacino)) {
			return false;
		}

		BollettinoBacino bollettinoBacino = (BollettinoBacino)object;

		long primaryKey = bollettinoBacino.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<BollettinoBacino> toCacheModel() {
		BollettinoBacinoCacheModel bollettinoBacinoCacheModel =
			new BollettinoBacinoCacheModel();

		bollettinoBacinoCacheModel.uuid = getUuid();

		String uuid = bollettinoBacinoCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			bollettinoBacinoCacheModel.uuid = null;
		}

		bollettinoBacinoCacheModel.id = getId();

		bollettinoBacinoCacheModel.idBollettino = getIdBollettino();

		bollettinoBacinoCacheModel.progressivo = getProgressivo();

		bollettinoBacinoCacheModel.idBacino = getIdBacino();

		String idBacino = bollettinoBacinoCacheModel.idBacino;

		if ((idBacino != null) && (idBacino.length() == 0)) {
			bollettinoBacinoCacheModel.idBacino = null;
		}

		bollettinoBacinoCacheModel.nomeBacino = getNomeBacino();

		String nomeBacino = bollettinoBacinoCacheModel.nomeBacino;

		if ((nomeBacino != null) && (nomeBacino.length() == 0)) {
			bollettinoBacinoCacheModel.nomeBacino = null;
		}

		bollettinoBacinoCacheModel.oreOsservazione = getOreOsservazione();

		String oreOsservazione = bollettinoBacinoCacheModel.oreOsservazione;

		if ((oreOsservazione != null) && (oreOsservazione.length() == 0)) {
			bollettinoBacinoCacheModel.oreOsservazione = null;
		}

		bollettinoBacinoCacheModel.note = getNote();

		String note = bollettinoBacinoCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			bollettinoBacinoCacheModel.note = null;
		}

		return bollettinoBacinoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<BollettinoBacino, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<BollettinoBacino, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<BollettinoBacino, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(BollettinoBacino)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, BollettinoBacino>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					BollettinoBacino.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _id;
	private long _idBollettino;
	private int _progressivo;
	private String _idBacino;
	private String _nomeBacino;
	private String _oreOsservazione;
	private String _note;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<BollettinoBacino, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((BollettinoBacino)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("idBollettino", _idBollettino);
		_columnOriginalValues.put("progressivo", _progressivo);
		_columnOriginalValues.put("idBacino", _idBacino);
		_columnOriginalValues.put("nomeBacino", _nomeBacino);
		_columnOriginalValues.put("oreOsservazione", _oreOsservazione);
		_columnOriginalValues.put("note", _note);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("id_", 2L);

		columnBitmasks.put("idBollettino", 4L);

		columnBitmasks.put("progressivo", 8L);

		columnBitmasks.put("idBacino", 16L);

		columnBitmasks.put("nomeBacino", 32L);

		columnBitmasks.put("oreOsservazione", 64L);

		columnBitmasks.put("note", 128L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private BollettinoBacino _escapedModel;

}