/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.bollettino.model.Pluviometro;
import it.eng.bollettino.model.PluviometroModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Pluviometro service. Represents a row in the &quot;BOLLETTINO_Pluviometro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PluviometroModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PluviometroImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see PluviometroImpl
 * @generated
 */
@JSON(strict = true)
public class PluviometroModelImpl
	extends BaseModelImpl<Pluviometro> implements PluviometroModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pluviometro model instance should use the <code>Pluviometro</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOLLETTINO_Pluviometro";

	public static final Object[][] TABLE_COLUMNS = {
		{"stazioneId", Types.VARCHAR}, {"nomeGruppo", Types.VARCHAR},
		{"nomeRubrica", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("stazioneId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomeGruppo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nomeRubrica", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOLLETTINO_Pluviometro (stazioneId VARCHAR(75) not null primary key,nomeGruppo VARCHAR(75) null,nomeRubrica VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table BOLLETTINO_Pluviometro";

	public static final String ORDER_BY_JPQL =
		" ORDER BY pluviometro.stazioneId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOLLETTINO_Pluviometro.stazioneId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOMEGRUPPO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOMERUBRICA_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long STAZIONEID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PluviometroModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _stazioneId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setStazioneId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _stazioneId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Pluviometro.class;
	}

	@Override
	public String getModelClassName() {
		return Pluviometro.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Pluviometro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Pluviometro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Pluviometro, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Pluviometro)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Pluviometro, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Pluviometro, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Pluviometro)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Pluviometro, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Pluviometro, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Pluviometro, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Pluviometro, Object>>
				attributeGetterFunctions =
					new LinkedHashMap<String, Function<Pluviometro, Object>>();

			attributeGetterFunctions.put(
				"stazioneId", Pluviometro::getStazioneId);
			attributeGetterFunctions.put(
				"nomeGruppo", Pluviometro::getNomeGruppo);
			attributeGetterFunctions.put(
				"nomeRubrica", Pluviometro::getNomeRubrica);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Pluviometro, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Pluviometro, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Pluviometro, ?>>();

			attributeSetterBiConsumers.put(
				"stazioneId",
				(BiConsumer<Pluviometro, String>)Pluviometro::setStazioneId);
			attributeSetterBiConsumers.put(
				"nomeGruppo",
				(BiConsumer<Pluviometro, String>)Pluviometro::setNomeGruppo);
			attributeSetterBiConsumers.put(
				"nomeRubrica",
				(BiConsumer<Pluviometro, String>)Pluviometro::setNomeRubrica);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getStazioneId() {
		if (_stazioneId == null) {
			return "";
		}
		else {
			return _stazioneId;
		}
	}

	@Override
	public void setStazioneId(String stazioneId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_stazioneId = stazioneId;
	}

	@JSON
	@Override
	public String getNomeGruppo() {
		if (_nomeGruppo == null) {
			return "";
		}
		else {
			return _nomeGruppo;
		}
	}

	@Override
	public void setNomeGruppo(String nomeGruppo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeGruppo = nomeGruppo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNomeGruppo() {
		return getColumnOriginalValue("nomeGruppo");
	}

	@JSON
	@Override
	public String getNomeRubrica() {
		if (_nomeRubrica == null) {
			return "";
		}
		else {
			return _nomeRubrica;
		}
	}

	@Override
	public void setNomeRubrica(String nomeRubrica) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nomeRubrica = nomeRubrica;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNomeRubrica() {
		return getColumnOriginalValue("nomeRubrica");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Pluviometro toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Pluviometro>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PluviometroImpl pluviometroImpl = new PluviometroImpl();

		pluviometroImpl.setStazioneId(getStazioneId());
		pluviometroImpl.setNomeGruppo(getNomeGruppo());
		pluviometroImpl.setNomeRubrica(getNomeRubrica());

		pluviometroImpl.resetOriginalValues();

		return pluviometroImpl;
	}

	@Override
	public Pluviometro cloneWithOriginalValues() {
		PluviometroImpl pluviometroImpl = new PluviometroImpl();

		pluviometroImpl.setStazioneId(
			this.<String>getColumnOriginalValue("stazioneId"));
		pluviometroImpl.setNomeGruppo(
			this.<String>getColumnOriginalValue("nomeGruppo"));
		pluviometroImpl.setNomeRubrica(
			this.<String>getColumnOriginalValue("nomeRubrica"));

		return pluviometroImpl;
	}

	@Override
	public int compareTo(Pluviometro pluviometro) {
		int value = 0;

		value = getStazioneId().compareTo(pluviometro.getStazioneId());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Pluviometro)) {
			return false;
		}

		Pluviometro pluviometro = (Pluviometro)object;

		String primaryKey = pluviometro.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Pluviometro> toCacheModel() {
		PluviometroCacheModel pluviometroCacheModel =
			new PluviometroCacheModel();

		pluviometroCacheModel.stazioneId = getStazioneId();

		String stazioneId = pluviometroCacheModel.stazioneId;

		if ((stazioneId != null) && (stazioneId.length() == 0)) {
			pluviometroCacheModel.stazioneId = null;
		}

		pluviometroCacheModel.nomeGruppo = getNomeGruppo();

		String nomeGruppo = pluviometroCacheModel.nomeGruppo;

		if ((nomeGruppo != null) && (nomeGruppo.length() == 0)) {
			pluviometroCacheModel.nomeGruppo = null;
		}

		pluviometroCacheModel.nomeRubrica = getNomeRubrica();

		String nomeRubrica = pluviometroCacheModel.nomeRubrica;

		if ((nomeRubrica != null) && (nomeRubrica.length() == 0)) {
			pluviometroCacheModel.nomeRubrica = null;
		}

		return pluviometroCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Pluviometro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Pluviometro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Pluviometro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Pluviometro)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Pluviometro>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Pluviometro.class, ModelWrapper.class);

	}

	private String _stazioneId;
	private String _nomeGruppo;
	private String _nomeRubrica;

	public <T> T getColumnValue(String columnName) {
		Function<Pluviometro, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Pluviometro)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("stazioneId", _stazioneId);
		_columnOriginalValues.put("nomeGruppo", _nomeGruppo);
		_columnOriginalValues.put("nomeRubrica", _nomeRubrica);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("stazioneId", 1L);

		columnBitmasks.put("nomeGruppo", 2L);

		columnBitmasks.put("nomeRubrica", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Pluviometro _escapedModel;

}