/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.bollettino.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.bollettino.model.RegolaAllarmeComune;
import it.eng.bollettino.model.RegolaAllarmeComuneModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the RegolaAllarmeComune service. Represents a row in the &quot;BOLLETTINO_RegolaAllarmeComune&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>RegolaAllarmeComuneModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RegolaAllarmeComuneImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see RegolaAllarmeComuneImpl
 * @generated
 */
@JSON(strict = true)
public class RegolaAllarmeComuneModelImpl
	extends BaseModelImpl<RegolaAllarmeComune>
	implements RegolaAllarmeComuneModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a regola allarme comune model instance should use the <code>RegolaAllarmeComune</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOLLETTINO_RegolaAllarmeComune";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"idRegola", Types.BIGINT}, {"idComune", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idRegola", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idComune", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOLLETTINO_RegolaAllarmeComune (uuid_ VARCHAR(75) null,id_ LONG not null primary key,idRegola LONG,idComune LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table BOLLETTINO_RegolaAllarmeComune";

	public static final String ORDER_BY_JPQL =
		" ORDER BY regolaAllarmeComune.id ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOLLETTINO_RegolaAllarmeComune.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDCOMUNE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDREGOLA_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public RegolaAllarmeComuneModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RegolaAllarmeComune.class;
	}

	@Override
	public String getModelClassName() {
		return RegolaAllarmeComune.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<RegolaAllarmeComune, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<RegolaAllarmeComune, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegolaAllarmeComune, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((RegolaAllarmeComune)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<RegolaAllarmeComune, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<RegolaAllarmeComune, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(RegolaAllarmeComune)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<RegolaAllarmeComune, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<RegolaAllarmeComune, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<RegolaAllarmeComune, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<RegolaAllarmeComune, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<RegolaAllarmeComune, Object>>();

			attributeGetterFunctions.put("uuid", RegolaAllarmeComune::getUuid);
			attributeGetterFunctions.put("id", RegolaAllarmeComune::getId);
			attributeGetterFunctions.put(
				"idRegola", RegolaAllarmeComune::getIdRegola);
			attributeGetterFunctions.put(
				"idComune", RegolaAllarmeComune::getIdComune);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<RegolaAllarmeComune, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<RegolaAllarmeComune, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<RegolaAllarmeComune, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<RegolaAllarmeComune, String>)
					RegolaAllarmeComune::setUuid);
			attributeSetterBiConsumers.put(
				"id",
				(BiConsumer<RegolaAllarmeComune, Long>)
					RegolaAllarmeComune::setId);
			attributeSetterBiConsumers.put(
				"idRegola",
				(BiConsumer<RegolaAllarmeComune, Long>)
					RegolaAllarmeComune::setIdRegola);
			attributeSetterBiConsumers.put(
				"idComune",
				(BiConsumer<RegolaAllarmeComune, Long>)
					RegolaAllarmeComune::setIdComune);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getIdRegola() {
		return _idRegola;
	}

	@Override
	public void setIdRegola(long idRegola) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idRegola = idRegola;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdRegola() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idRegola"));
	}

	@JSON
	@Override
	public long getIdComune() {
		return _idComune;
	}

	@Override
	public void setIdComune(long idComune) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idComune = idComune;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdComune() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idComune"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, RegolaAllarmeComune.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RegolaAllarmeComune toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, RegolaAllarmeComune>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RegolaAllarmeComuneImpl regolaAllarmeComuneImpl =
			new RegolaAllarmeComuneImpl();

		regolaAllarmeComuneImpl.setUuid(getUuid());
		regolaAllarmeComuneImpl.setId(getId());
		regolaAllarmeComuneImpl.setIdRegola(getIdRegola());
		regolaAllarmeComuneImpl.setIdComune(getIdComune());

		regolaAllarmeComuneImpl.resetOriginalValues();

		return regolaAllarmeComuneImpl;
	}

	@Override
	public RegolaAllarmeComune cloneWithOriginalValues() {
		RegolaAllarmeComuneImpl regolaAllarmeComuneImpl =
			new RegolaAllarmeComuneImpl();

		regolaAllarmeComuneImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		regolaAllarmeComuneImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		regolaAllarmeComuneImpl.setIdRegola(
			this.<Long>getColumnOriginalValue("idRegola"));
		regolaAllarmeComuneImpl.setIdComune(
			this.<Long>getColumnOriginalValue("idComune"));

		return regolaAllarmeComuneImpl;
	}

	@Override
	public int compareTo(RegolaAllarmeComune regolaAllarmeComune) {
		int value = 0;

		if (getId() < regolaAllarmeComune.getId()) {
			value = -1;
		}
		else if (getId() > regolaAllarmeComune.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof RegolaAllarmeComune)) {
			return false;
		}

		RegolaAllarmeComune regolaAllarmeComune = (RegolaAllarmeComune)object;

		long primaryKey = regolaAllarmeComune.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<RegolaAllarmeComune> toCacheModel() {
		RegolaAllarmeComuneCacheModel regolaAllarmeComuneCacheModel =
			new RegolaAllarmeComuneCacheModel();

		regolaAllarmeComuneCacheModel.uuid = getUuid();

		String uuid = regolaAllarmeComuneCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			regolaAllarmeComuneCacheModel.uuid = null;
		}

		regolaAllarmeComuneCacheModel.id = getId();

		regolaAllarmeComuneCacheModel.idRegola = getIdRegola();

		regolaAllarmeComuneCacheModel.idComune = getIdComune();

		return regolaAllarmeComuneCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<RegolaAllarmeComune, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<RegolaAllarmeComune, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<RegolaAllarmeComune, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(RegolaAllarmeComune)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, RegolaAllarmeComune>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					RegolaAllarmeComune.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _id;
	private long _idRegola;
	private long _idComune;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<RegolaAllarmeComune, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((RegolaAllarmeComune)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("idRegola", _idRegola);
		_columnOriginalValues.put("idComune", _idComune);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("id_", 2L);

		columnBitmasks.put("idRegola", 4L);

		columnBitmasks.put("idComune", 8L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private RegolaAllarmeComune _escapedModel;

}