/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.bollettino.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import it.eng.bollettino.model.ValoreSensore;
import it.eng.bollettino.model.ValoreSensoreModel;
import it.eng.bollettino.model.ValoreSensoreSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ValoreSensore service. Represents a row in the &quot;BOLLETTINO_ValoreSensore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ValoreSensoreModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ValoreSensoreImpl}.
 * </p>
 *
 * @author GFAVINI
 * @see ValoreSensoreImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class ValoreSensoreModelImpl
	extends BaseModelImpl<ValoreSensore> implements ValoreSensoreModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a valore sensore model instance should use the <code>ValoreSensore</code> interface instead.
	 */
	public static final String TABLE_NAME = "BOLLETTINO_ValoreSensore";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"value", Types.DOUBLE}, {"datetime", Types.TIMESTAMP},
		{"idVariabile", Types.VARCHAR}, {"idStazione", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("value", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("datetime", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("idVariabile", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idStazione", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BOLLETTINO_ValoreSensore (uuid_ VARCHAR(75) null,id_ LONG not null primary key,value DOUBLE,datetime DATE null,idVariabile VARCHAR(75) null,idStazione VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table BOLLETTINO_ValoreSensore";

	public static final String ORDER_BY_JPQL =
		" ORDER BY valoreSensore.datetime DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BOLLETTINO_ValoreSensore.datetime DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		allerta.bollettino.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.it.eng.bollettino.model.ValoreSensore"),
		false);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		allerta.bollettino.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.it.eng.bollettino.model.ValoreSensore"),
		false);

	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(
		allerta.bollettino.service.util.ServiceProps.get(
			"value.object.column.bitmask.enabled.it.eng.bollettino.model.ValoreSensore"),
		true);

	public static final long IDSTAZIONE_COLUMN_BITMASK = 1L;

	public static final long IDVARIABILE_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long DATETIME_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static ValoreSensore toModel(ValoreSensoreSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		ValoreSensore model = new ValoreSensoreImpl();

		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setValue(soapModel.getValue());
		model.setDatetime(soapModel.getDatetime());
		model.setIdVariabile(soapModel.getIdVariabile());
		model.setIdStazione(soapModel.getIdStazione());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<ValoreSensore> toModels(ValoreSensoreSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<ValoreSensore> models = new ArrayList<ValoreSensore>(
			soapModels.length);

		for (ValoreSensoreSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		allerta.bollettino.service.util.ServiceProps.get(
			"lock.expiration.time.it.eng.bollettino.model.ValoreSensore"));

	public ValoreSensoreModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ValoreSensore.class;
	}

	@Override
	public String getModelClassName() {
		return ValoreSensore.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ValoreSensore, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ValoreSensore, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ValoreSensore, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ValoreSensore)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ValoreSensore, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ValoreSensore, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ValoreSensore)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ValoreSensore, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ValoreSensore, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ValoreSensore, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ValoreSensore, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ValoreSensore, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<ValoreSensore, Object>>();
		Map<String, BiConsumer<ValoreSensore, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ValoreSensore, ?>>();

		attributeGetterFunctions.put(
			"uuid",
			new Function<ValoreSensore, Object>() {

				@Override
				public Object apply(ValoreSensore valoreSensore) {
					return valoreSensore.getUuid();
				}

			});
		attributeSetterBiConsumers.put(
			"uuid",
			new BiConsumer<ValoreSensore, Object>() {

				@Override
				public void accept(ValoreSensore valoreSensore, Object uuid) {
					valoreSensore.setUuid((String)uuid);
				}

			});
		attributeGetterFunctions.put(
			"id",
			new Function<ValoreSensore, Object>() {

				@Override
				public Object apply(ValoreSensore valoreSensore) {
					return valoreSensore.getId();
				}

			});
		attributeSetterBiConsumers.put(
			"id",
			new BiConsumer<ValoreSensore, Object>() {

				@Override
				public void accept(ValoreSensore valoreSensore, Object id) {
					valoreSensore.setId((Long)id);
				}

			});
		attributeGetterFunctions.put(
			"value",
			new Function<ValoreSensore, Object>() {

				@Override
				public Object apply(ValoreSensore valoreSensore) {
					return valoreSensore.getValue();
				}

			});
		attributeSetterBiConsumers.put(
			"value",
			new BiConsumer<ValoreSensore, Object>() {

				@Override
				public void accept(ValoreSensore valoreSensore, Object value) {
					valoreSensore.setValue((Double)value);
				}

			});
		attributeGetterFunctions.put(
			"datetime",
			new Function<ValoreSensore, Object>() {

				@Override
				public Object apply(ValoreSensore valoreSensore) {
					return valoreSensore.getDatetime();
				}

			});
		attributeSetterBiConsumers.put(
			"datetime",
			new BiConsumer<ValoreSensore, Object>() {

				@Override
				public void accept(
					ValoreSensore valoreSensore, Object datetime) {

					valoreSensore.setDatetime((Date)datetime);
				}

			});
		attributeGetterFunctions.put(
			"idVariabile",
			new Function<ValoreSensore, Object>() {

				@Override
				public Object apply(ValoreSensore valoreSensore) {
					return valoreSensore.getIdVariabile();
				}

			});
		attributeSetterBiConsumers.put(
			"idVariabile",
			new BiConsumer<ValoreSensore, Object>() {

				@Override
				public void accept(
					ValoreSensore valoreSensore, Object idVariabile) {

					valoreSensore.setIdVariabile((String)idVariabile);
				}

			});
		attributeGetterFunctions.put(
			"idStazione",
			new Function<ValoreSensore, Object>() {

				@Override
				public Object apply(ValoreSensore valoreSensore) {
					return valoreSensore.getIdStazione();
				}

			});
		attributeSetterBiConsumers.put(
			"idStazione",
			new BiConsumer<ValoreSensore, Object>() {

				@Override
				public void accept(
					ValoreSensore valoreSensore, Object idStazione) {

					valoreSensore.setIdStazione((String)idStazione);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public double getValue() {
		return _value;
	}

	@Override
	public void setValue(double value) {
		_value = value;
	}

	@JSON
	@Override
	public Date getDatetime() {
		return _datetime;
	}

	@Override
	public void setDatetime(Date datetime) {
		_columnBitmask = -1L;

		_datetime = datetime;
	}

	@JSON
	@Override
	public String getIdVariabile() {
		if (_idVariabile == null) {
			return "";
		}
		else {
			return _idVariabile;
		}
	}

	@Override
	public void setIdVariabile(String idVariabile) {
		_columnBitmask |= IDVARIABILE_COLUMN_BITMASK;

		if (_originalIdVariabile == null) {
			_originalIdVariabile = _idVariabile;
		}

		_idVariabile = idVariabile;
	}

	public String getOriginalIdVariabile() {
		return GetterUtil.getString(_originalIdVariabile);
	}

	@JSON
	@Override
	public String getIdStazione() {
		if (_idStazione == null) {
			return "";
		}
		else {
			return _idStazione;
		}
	}

	@Override
	public void setIdStazione(String idStazione) {
		_columnBitmask |= IDSTAZIONE_COLUMN_BITMASK;

		if (_originalIdStazione == null) {
			_originalIdStazione = _idStazione;
		}

		_idStazione = idStazione;
	}

	public String getOriginalIdStazione() {
		return GetterUtil.getString(_originalIdStazione);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ValoreSensore.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ValoreSensore toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ValoreSensore)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ValoreSensoreImpl valoreSensoreImpl = new ValoreSensoreImpl();

		valoreSensoreImpl.setUuid(getUuid());
		valoreSensoreImpl.setId(getId());
		valoreSensoreImpl.setValue(getValue());
		valoreSensoreImpl.setDatetime(getDatetime());
		valoreSensoreImpl.setIdVariabile(getIdVariabile());
		valoreSensoreImpl.setIdStazione(getIdStazione());

		valoreSensoreImpl.resetOriginalValues();

		return valoreSensoreImpl;
	}

	@Override
	public int compareTo(ValoreSensore valoreSensore) {
		int value = 0;

		value = DateUtil.compareTo(getDatetime(), valoreSensore.getDatetime());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ValoreSensore)) {
			return false;
		}

		ValoreSensore valoreSensore = (ValoreSensore)obj;

		long primaryKey = valoreSensore.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ValoreSensoreModelImpl valoreSensoreModelImpl = this;

		valoreSensoreModelImpl._originalUuid = valoreSensoreModelImpl._uuid;

		valoreSensoreModelImpl._originalIdVariabile =
			valoreSensoreModelImpl._idVariabile;

		valoreSensoreModelImpl._originalIdStazione =
			valoreSensoreModelImpl._idStazione;

		valoreSensoreModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ValoreSensore> toCacheModel() {
		ValoreSensoreCacheModel valoreSensoreCacheModel =
			new ValoreSensoreCacheModel();

		valoreSensoreCacheModel.uuid = getUuid();

		String uuid = valoreSensoreCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			valoreSensoreCacheModel.uuid = null;
		}

		valoreSensoreCacheModel.id = getId();

		valoreSensoreCacheModel.value = getValue();

		Date datetime = getDatetime();

		if (datetime != null) {
			valoreSensoreCacheModel.datetime = datetime.getTime();
		}
		else {
			valoreSensoreCacheModel.datetime = Long.MIN_VALUE;
		}

		valoreSensoreCacheModel.idVariabile = getIdVariabile();

		String idVariabile = valoreSensoreCacheModel.idVariabile;

		if ((idVariabile != null) && (idVariabile.length() == 0)) {
			valoreSensoreCacheModel.idVariabile = null;
		}

		valoreSensoreCacheModel.idStazione = getIdStazione();

		String idStazione = valoreSensoreCacheModel.idStazione;

		if ((idStazione != null) && (idStazione.length() == 0)) {
			valoreSensoreCacheModel.idStazione = null;
		}

		return valoreSensoreCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ValoreSensore, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ValoreSensore, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ValoreSensore, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ValoreSensore)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ValoreSensore, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ValoreSensore, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ValoreSensore, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ValoreSensore)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		ValoreSensore.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		ValoreSensore.class, ModelWrapper.class
	};

	private String _uuid;
	private String _originalUuid;
	private long _id;
	private double _value;
	private Date _datetime;
	private String _idVariabile;
	private String _originalIdVariabile;
	private String _idStazione;
	private String _originalIdStazione;
	private long _columnBitmask;
	private ValoreSensore _escapedModel;

}