/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package allerta.dewetra.model.impl;

import allerta.dewetra.model.HRW;
import allerta.dewetra.model.HRWModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the HRW service. Represents a row in the &quot;DEWETRA_HRW&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>HRWModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HRWImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see HRWImpl
 * @generated
 */
@JSON(strict = true)
public class HRWModelImpl extends BaseModelImpl<HRW> implements HRWModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hrw model instance should use the <code>HRW</code> interface instead.
	 */
	public static final String TABLE_NAME = "DEWETRA_HRW";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.BIGINT}, {"comune", Types.VARCHAR},
		{"timestamp", Types.TIMESTAMP}, {"HRI", Types.DOUBLE},
		{"SSI", Types.DOUBLE}, {"SRI", Types.DOUBLE}, {"VMI", Types.DOUBLE},
		{"VIL", Types.DOUBLE}, {"POH", Types.DOUBLE}, {"ETM", Types.DOUBLE},
		{"TOP", Types.DOUBLE}, {"LGT", Types.DOUBLE}, {"Pers", Types.DOUBLE},
		{"SRT", Types.DOUBLE}, {"SRT_3", Types.DOUBLE}, {"SRT_6", Types.DOUBLE},
		{"Vel", Types.DOUBLE}, {"Dir", Types.DOUBLE}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("comune", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timestamp", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("HRI", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("SSI", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("SRI", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("VMI", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("VIL", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("POH", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("ETM", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("TOP", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("LGT", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("Pers", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("SRT", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("SRT_3", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("SRT_6", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("Vel", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("Dir", Types.DOUBLE);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DEWETRA_HRW (id_ LONG not null primary key,comune VARCHAR(75) null,timestamp DATE null,HRI DOUBLE,SSI DOUBLE,SRI DOUBLE,VMI DOUBLE,VIL DOUBLE,POH DOUBLE,ETM DOUBLE,TOP DOUBLE,LGT DOUBLE,Pers DOUBLE,SRT DOUBLE,SRT_3 DOUBLE,SRT_6 DOUBLE,Vel DOUBLE,Dir DOUBLE)";

	public static final String TABLE_SQL_DROP = "drop table DEWETRA_HRW";

	public static final String ORDER_BY_JPQL = " ORDER BY hrw.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY DEWETRA_HRW.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMUNE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public HRWModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return HRW.class;
	}

	@Override
	public String getModelClassName() {
		return HRW.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<HRW, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<HRW, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HRW, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((HRW)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<HRW, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<HRW, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((HRW)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<HRW, Object>> getAttributeGetterFunctions() {
		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<HRW, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<HRW, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<HRW, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<HRW, Object>>();

			attributeGetterFunctions.put("id", HRW::getId);
			attributeGetterFunctions.put("comune", HRW::getComune);
			attributeGetterFunctions.put("timestamp", HRW::getTimestamp);
			attributeGetterFunctions.put("HRI", HRW::getHRI);
			attributeGetterFunctions.put("SSI", HRW::getSSI);
			attributeGetterFunctions.put("SRI", HRW::getSRI);
			attributeGetterFunctions.put("VMI", HRW::getVMI);
			attributeGetterFunctions.put("VIL", HRW::getVIL);
			attributeGetterFunctions.put("POH", HRW::getPOH);
			attributeGetterFunctions.put("ETM", HRW::getETM);
			attributeGetterFunctions.put("TOP", HRW::getTOP);
			attributeGetterFunctions.put("LGT", HRW::getLGT);
			attributeGetterFunctions.put("Pers", HRW::getPers);
			attributeGetterFunctions.put("SRT", HRW::getSRT);
			attributeGetterFunctions.put("SRT_3", HRW::getSRT_3);
			attributeGetterFunctions.put("SRT_6", HRW::getSRT_6);
			attributeGetterFunctions.put("Vel", HRW::getVel);
			attributeGetterFunctions.put("Dir", HRW::getDir);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<HRW, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<HRW, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<HRW, ?>>();

			attributeSetterBiConsumers.put(
				"id", (BiConsumer<HRW, Long>)HRW::setId);
			attributeSetterBiConsumers.put(
				"comune", (BiConsumer<HRW, String>)HRW::setComune);
			attributeSetterBiConsumers.put(
				"timestamp", (BiConsumer<HRW, Date>)HRW::setTimestamp);
			attributeSetterBiConsumers.put(
				"HRI", (BiConsumer<HRW, Double>)HRW::setHRI);
			attributeSetterBiConsumers.put(
				"SSI", (BiConsumer<HRW, Double>)HRW::setSSI);
			attributeSetterBiConsumers.put(
				"SRI", (BiConsumer<HRW, Double>)HRW::setSRI);
			attributeSetterBiConsumers.put(
				"VMI", (BiConsumer<HRW, Double>)HRW::setVMI);
			attributeSetterBiConsumers.put(
				"VIL", (BiConsumer<HRW, Double>)HRW::setVIL);
			attributeSetterBiConsumers.put(
				"POH", (BiConsumer<HRW, Double>)HRW::setPOH);
			attributeSetterBiConsumers.put(
				"ETM", (BiConsumer<HRW, Double>)HRW::setETM);
			attributeSetterBiConsumers.put(
				"TOP", (BiConsumer<HRW, Double>)HRW::setTOP);
			attributeSetterBiConsumers.put(
				"LGT", (BiConsumer<HRW, Double>)HRW::setLGT);
			attributeSetterBiConsumers.put(
				"Pers", (BiConsumer<HRW, Double>)HRW::setPers);
			attributeSetterBiConsumers.put(
				"SRT", (BiConsumer<HRW, Double>)HRW::setSRT);
			attributeSetterBiConsumers.put(
				"SRT_3", (BiConsumer<HRW, Double>)HRW::setSRT_3);
			attributeSetterBiConsumers.put(
				"SRT_6", (BiConsumer<HRW, Double>)HRW::setSRT_6);
			attributeSetterBiConsumers.put(
				"Vel", (BiConsumer<HRW, Double>)HRW::setVel);
			attributeSetterBiConsumers.put(
				"Dir", (BiConsumer<HRW, Double>)HRW::setDir);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getComune() {
		if (_comune == null) {
			return "";
		}
		else {
			return _comune;
		}
	}

	@Override
	public void setComune(String comune) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_comune = comune;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalComune() {
		return getColumnOriginalValue("comune");
	}

	@JSON
	@Override
	public Date getTimestamp() {
		return _timestamp;
	}

	@Override
	public void setTimestamp(Date timestamp) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_timestamp = timestamp;
	}

	@JSON
	@Override
	public double getHRI() {
		return _HRI;
	}

	@Override
	public void setHRI(double HRI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_HRI = HRI;
	}

	@JSON
	@Override
	public double getSSI() {
		return _SSI;
	}

	@Override
	public void setSSI(double SSI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_SSI = SSI;
	}

	@JSON
	@Override
	public double getSRI() {
		return _SRI;
	}

	@Override
	public void setSRI(double SRI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_SRI = SRI;
	}

	@JSON
	@Override
	public double getVMI() {
		return _VMI;
	}

	@Override
	public void setVMI(double VMI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_VMI = VMI;
	}

	@JSON
	@Override
	public double getVIL() {
		return _VIL;
	}

	@Override
	public void setVIL(double VIL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_VIL = VIL;
	}

	@JSON
	@Override
	public double getPOH() {
		return _POH;
	}

	@Override
	public void setPOH(double POH) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_POH = POH;
	}

	@JSON
	@Override
	public double getETM() {
		return _ETM;
	}

	@Override
	public void setETM(double ETM) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ETM = ETM;
	}

	@JSON
	@Override
	public double getTOP() {
		return _TOP;
	}

	@Override
	public void setTOP(double TOP) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TOP = TOP;
	}

	@JSON
	@Override
	public double getLGT() {
		return _LGT;
	}

	@Override
	public void setLGT(double LGT) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_LGT = LGT;
	}

	@JSON
	@Override
	public double getPers() {
		return _Pers;
	}

	@Override
	public void setPers(double Pers) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Pers = Pers;
	}

	@JSON
	@Override
	public double getSRT() {
		return _SRT;
	}

	@Override
	public void setSRT(double SRT) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_SRT = SRT;
	}

	@JSON
	@Override
	public double getSRT_3() {
		return _SRT_3;
	}

	@Override
	public void setSRT_3(double SRT_3) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_SRT_3 = SRT_3;
	}

	@JSON
	@Override
	public double getSRT_6() {
		return _SRT_6;
	}

	@Override
	public void setSRT_6(double SRT_6) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_SRT_6 = SRT_6;
	}

	@JSON
	@Override
	public double getVel() {
		return _Vel;
	}

	@Override
	public void setVel(double Vel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Vel = Vel;
	}

	@JSON
	@Override
	public double getDir() {
		return _Dir;
	}

	@Override
	public void setDir(double Dir) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Dir = Dir;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, HRW.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public HRW toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, HRW> escapedModelProxyProviderFunction =
				EscapedModelProxyProviderFunctionHolder.
					_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HRWImpl hrwImpl = new HRWImpl();

		hrwImpl.setId(getId());
		hrwImpl.setComune(getComune());
		hrwImpl.setTimestamp(getTimestamp());
		hrwImpl.setHRI(getHRI());
		hrwImpl.setSSI(getSSI());
		hrwImpl.setSRI(getSRI());
		hrwImpl.setVMI(getVMI());
		hrwImpl.setVIL(getVIL());
		hrwImpl.setPOH(getPOH());
		hrwImpl.setETM(getETM());
		hrwImpl.setTOP(getTOP());
		hrwImpl.setLGT(getLGT());
		hrwImpl.setPers(getPers());
		hrwImpl.setSRT(getSRT());
		hrwImpl.setSRT_3(getSRT_3());
		hrwImpl.setSRT_6(getSRT_6());
		hrwImpl.setVel(getVel());
		hrwImpl.setDir(getDir());

		hrwImpl.resetOriginalValues();

		return hrwImpl;
	}

	@Override
	public HRW cloneWithOriginalValues() {
		HRWImpl hrwImpl = new HRWImpl();

		hrwImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		hrwImpl.setComune(this.<String>getColumnOriginalValue("comune"));
		hrwImpl.setTimestamp(this.<Date>getColumnOriginalValue("timestamp"));
		hrwImpl.setHRI(this.<Double>getColumnOriginalValue("HRI"));
		hrwImpl.setSSI(this.<Double>getColumnOriginalValue("SSI"));
		hrwImpl.setSRI(this.<Double>getColumnOriginalValue("SRI"));
		hrwImpl.setVMI(this.<Double>getColumnOriginalValue("VMI"));
		hrwImpl.setVIL(this.<Double>getColumnOriginalValue("VIL"));
		hrwImpl.setPOH(this.<Double>getColumnOriginalValue("POH"));
		hrwImpl.setETM(this.<Double>getColumnOriginalValue("ETM"));
		hrwImpl.setTOP(this.<Double>getColumnOriginalValue("TOP"));
		hrwImpl.setLGT(this.<Double>getColumnOriginalValue("LGT"));
		hrwImpl.setPers(this.<Double>getColumnOriginalValue("Pers"));
		hrwImpl.setSRT(this.<Double>getColumnOriginalValue("SRT"));
		hrwImpl.setSRT_3(this.<Double>getColumnOriginalValue("SRT_3"));
		hrwImpl.setSRT_6(this.<Double>getColumnOriginalValue("SRT_6"));
		hrwImpl.setVel(this.<Double>getColumnOriginalValue("Vel"));
		hrwImpl.setDir(this.<Double>getColumnOriginalValue("Dir"));

		return hrwImpl;
	}

	@Override
	public int compareTo(HRW hrw) {
		int value = 0;

		if (getId() < hrw.getId()) {
			value = -1;
		}
		else if (getId() > hrw.getId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof HRW)) {
			return false;
		}

		HRW hrw = (HRW)object;

		long primaryKey = hrw.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<HRW> toCacheModel() {
		HRWCacheModel hrwCacheModel = new HRWCacheModel();

		hrwCacheModel.id = getId();

		hrwCacheModel.comune = getComune();

		String comune = hrwCacheModel.comune;

		if ((comune != null) && (comune.length() == 0)) {
			hrwCacheModel.comune = null;
		}

		Date timestamp = getTimestamp();

		if (timestamp != null) {
			hrwCacheModel.timestamp = timestamp.getTime();
		}
		else {
			hrwCacheModel.timestamp = Long.MIN_VALUE;
		}

		hrwCacheModel.HRI = getHRI();

		hrwCacheModel.SSI = getSSI();

		hrwCacheModel.SRI = getSRI();

		hrwCacheModel.VMI = getVMI();

		hrwCacheModel.VIL = getVIL();

		hrwCacheModel.POH = getPOH();

		hrwCacheModel.ETM = getETM();

		hrwCacheModel.TOP = getTOP();

		hrwCacheModel.LGT = getLGT();

		hrwCacheModel.Pers = getPers();

		hrwCacheModel.SRT = getSRT();

		hrwCacheModel.SRT_3 = getSRT_3();

		hrwCacheModel.SRT_6 = getSRT_6();

		hrwCacheModel.Vel = getVel();

		hrwCacheModel.Dir = getDir();

		return hrwCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<HRW, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<HRW, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<HRW, Object> attributeGetterFunction = entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((HRW)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, HRW>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					HRW.class, ModelWrapper.class);

	}

	private long _id;
	private String _comune;
	private Date _timestamp;

	private double _HRI;

	private double _SSI;

	private double _SRI;

	private double _VMI;

	private double _VIL;

	private double _POH;

	private double _ETM;

	private double _TOP;

	private double _LGT;

	private double _Pers;

	private double _SRT;

	private double _SRT_3;

	private double _SRT_6;

	private double _Vel;
	private double _Dir;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<HRW, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((HRW)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("comune", _comune);
		_columnOriginalValues.put("timestamp", _timestamp);
		_columnOriginalValues.put("HRI", _HRI);
		_columnOriginalValues.put("SSI", _SSI);
		_columnOriginalValues.put("SRI", _SRI);
		_columnOriginalValues.put("VMI", _VMI);
		_columnOriginalValues.put("VIL", _VIL);
		_columnOriginalValues.put("POH", _POH);
		_columnOriginalValues.put("ETM", _ETM);
		_columnOriginalValues.put("TOP", _TOP);
		_columnOriginalValues.put("LGT", _LGT);
		_columnOriginalValues.put("Pers", _Pers);
		_columnOriginalValues.put("SRT", _SRT);
		_columnOriginalValues.put("SRT_3", _SRT_3);
		_columnOriginalValues.put("SRT_6", _SRT_6);
		_columnOriginalValues.put("Vel", _Vel);
		_columnOriginalValues.put("Dir", _Dir);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("comune", 2L);

		columnBitmasks.put("timestamp", 4L);

		columnBitmasks.put("HRI", 8L);

		columnBitmasks.put("SSI", 16L);

		columnBitmasks.put("SRI", 32L);

		columnBitmasks.put("VMI", 64L);

		columnBitmasks.put("VIL", 128L);

		columnBitmasks.put("POH", 256L);

		columnBitmasks.put("ETM", 512L);

		columnBitmasks.put("TOP", 1024L);

		columnBitmasks.put("LGT", 2048L);

		columnBitmasks.put("Pers", 4096L);

		columnBitmasks.put("SRT", 8192L);

		columnBitmasks.put("SRT_3", 16384L);

		columnBitmasks.put("SRT_6", 32768L);

		columnBitmasks.put("Vel", 65536L);

		columnBitmasks.put("Dir", 131072L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private HRW _escapedModel;

}