/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.cache.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Dati service. Represents a row in the &quot;CACHE_Dati&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.cache.model.impl.DatiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.cache.model.impl.DatiImpl</code>.
 * </p>
 *
 * @author GFAVINI
 * @see Dati
 * @generated
 */
@ProviderType
public interface DatiModel extends BaseModel<Dati> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dati model instance should use the {@link Dati} interface instead.
	 */

	/**
	 * Returns the primary key of this dati.
	 *
	 * @return the primary key of this dati
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this dati.
	 *
	 * @param primaryKey the primary key of this dati
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the id dati of this dati.
	 *
	 * @return the id dati of this dati
	 */
	@AutoEscape
	public String getIdDati();

	/**
	 * Sets the id dati of this dati.
	 *
	 * @param idDati the id dati of this dati
	 */
	public void setIdDati(String idDati);

	/**
	 * Returns the dato of this dati.
	 *
	 * @return the dato of this dati
	 */
	@AutoEscape
	public String getDato();

	/**
	 * Sets the dato of this dati.
	 *
	 * @param dato the dato of this dati
	 */
	public void setDato(String dato);

	/**
	 * Returns the create date of this dati.
	 *
	 * @return the create date of this dati
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dati.
	 *
	 * @param createDate the create date of this dati
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.cache.model.Dati dati);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.cache.model.Dati> toCacheModel();

	@Override
	public it.eng.cache.model.Dati toEscapedModel();

	@Override
	public it.eng.cache.model.Dati toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}