/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.parer.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DatiSpecificiInvio service. Represents a row in the &quot;parer_DatiSpecificiInvio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.parer.model.impl.DatiSpecificiInvioModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.parer.model.impl.DatiSpecificiInvioImpl</code>.
 * </p>
 *
 * @author Pratola_L
 * @see DatiSpecificiInvio
 * @generated
 */
@ProviderType
public interface DatiSpecificiInvioModel
	extends BaseModel<DatiSpecificiInvio>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dati specifici invio model instance should use the {@link DatiSpecificiInvio} interface instead.
	 */

	/**
	 * Returns the primary key of this dati specifici invio.
	 *
	 * @return the primary key of this dati specifici invio
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dati specifici invio.
	 *
	 * @param primaryKey the primary key of this dati specifici invio
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_invio of this dati specifici invio.
	 *
	 * @return the id_invio of this dati specifici invio
	 */
	public long getID_INVIO();

	/**
	 * Sets the id_invio of this dati specifici invio.
	 *
	 * @param ID_INVIO the id_invio of this dati specifici invio
	 */
	public void setID_INVIO(long ID_INVIO);

	/**
	 * Returns the ambiente of this dati specifici invio.
	 *
	 * @return the ambiente of this dati specifici invio
	 */
	@AutoEscape
	public String getAMBIENTE();

	/**
	 * Sets the ambiente of this dati specifici invio.
	 *
	 * @param AMBIENTE the ambiente of this dati specifici invio
	 */
	public void setAMBIENTE(String AMBIENTE);

	/**
	 * Returns the versione of this dati specifici invio.
	 *
	 * @return the versione of this dati specifici invio
	 */
	public double getVERSIONE();

	/**
	 * Sets the versione of this dati specifici invio.
	 *
	 * @param VERSIONE the versione of this dati specifici invio
	 */
	public void setVERSIONE(double VERSIONE);

	/**
	 * Returns the versatore_ente of this dati specifici invio.
	 *
	 * @return the versatore_ente of this dati specifici invio
	 */
	@AutoEscape
	public String getVERSATORE_ENTE();

	/**
	 * Sets the versatore_ente of this dati specifici invio.
	 *
	 * @param VERSATORE_ENTE the versatore_ente of this dati specifici invio
	 */
	public void setVERSATORE_ENTE(String VERSATORE_ENTE);

	/**
	 * Returns the versatore_user_id of this dati specifici invio.
	 *
	 * @return the versatore_user_id of this dati specifici invio
	 */
	@AutoEscape
	public String getVERSATORE_USER_ID();

	/**
	 * Sets the versatore_user_id of this dati specifici invio.
	 *
	 * @param VERSATORE_USER_ID the versatore_user_id of this dati specifici invio
	 */
	public void setVERSATORE_USER_ID(String VERSATORE_USER_ID);

	/**
	 * Returns the versatore_struttura of this dati specifici invio.
	 *
	 * @return the versatore_struttura of this dati specifici invio
	 */
	@AutoEscape
	public String getVERSATORE_STRUTTURA();

	/**
	 * Sets the versatore_struttura of this dati specifici invio.
	 *
	 * @param VERSATORE_STRUTTURA the versatore_struttura of this dati specifici invio
	 */
	public void setVERSATORE_STRUTTURA(String VERSATORE_STRUTTURA);

	/**
	 * Returns the chiave_numero of this dati specifici invio.
	 *
	 * @return the chiave_numero of this dati specifici invio
	 */
	@AutoEscape
	public String getCHIAVE_NUMERO();

	/**
	 * Sets the chiave_numero of this dati specifici invio.
	 *
	 * @param CHIAVE_NUMERO the chiave_numero of this dati specifici invio
	 */
	public void setCHIAVE_NUMERO(String CHIAVE_NUMERO);

	/**
	 * Returns the chiave_anno of this dati specifici invio.
	 *
	 * @return the chiave_anno of this dati specifici invio
	 */
	public long getCHIAVE_ANNO();

	/**
	 * Sets the chiave_anno of this dati specifici invio.
	 *
	 * @param CHIAVE_ANNO the chiave_anno of this dati specifici invio
	 */
	public void setCHIAVE_ANNO(long CHIAVE_ANNO);

	/**
	 * Returns the chiave_tipo_registro of this dati specifici invio.
	 *
	 * @return the chiave_tipo_registro of this dati specifici invio
	 */
	@AutoEscape
	public String getCHIAVE_TIPO_REGISTRO();

	/**
	 * Sets the chiave_tipo_registro of this dati specifici invio.
	 *
	 * @param CHIAVE_TIPO_REGISTRO the chiave_tipo_registro of this dati specifici invio
	 */
	public void setCHIAVE_TIPO_REGISTRO(String CHIAVE_TIPO_REGISTRO);

	/**
	 * Returns the tipologia_unita_documentaria of this dati specifici invio.
	 *
	 * @return the tipologia_unita_documentaria of this dati specifici invio
	 */
	@AutoEscape
	public String getTIPOLOGIA_UNITA_DOCUMENTARIA();

	/**
	 * Sets the tipologia_unita_documentaria of this dati specifici invio.
	 *
	 * @param TIPOLOGIA_UNITA_DOCUMENTARIA the tipologia_unita_documentaria of this dati specifici invio
	 */
	public void setTIPOLOGIA_UNITA_DOCUMENTARIA(
		String TIPOLOGIA_UNITA_DOCUMENTARIA);

	/**
	 * Returns the tipo_conservazione of this dati specifici invio.
	 *
	 * @return the tipo_conservazione of this dati specifici invio
	 */
	@AutoEscape
	public String getTIPO_CONSERVAZIONE();

	/**
	 * Sets the tipo_conservazione of this dati specifici invio.
	 *
	 * @param TIPO_CONSERVAZIONE the tipo_conservazione of this dati specifici invio
	 */
	public void setTIPO_CONSERVAZIONE(String TIPO_CONSERVAZIONE);

	/**
	 * Returns the forza_accettazione of this dati specifici invio.
	 *
	 * @return the forza_accettazione of this dati specifici invio
	 */
	@AutoEscape
	public String getFORZA_ACCETTAZIONE();

	/**
	 * Sets the forza_accettazione of this dati specifici invio.
	 *
	 * @param FORZA_ACCETTAZIONE the forza_accettazione of this dati specifici invio
	 */
	public void setFORZA_ACCETTAZIONE(String FORZA_ACCETTAZIONE);

	/**
	 * Returns the forza_conservazione of this dati specifici invio.
	 *
	 * @return the forza_conservazione of this dati specifici invio
	 */
	@AutoEscape
	public String getFORZA_CONSERVAZIONE();

	/**
	 * Sets the forza_conservazione of this dati specifici invio.
	 *
	 * @param FORZA_CONSERVAZIONE the forza_conservazione of this dati specifici invio
	 */
	public void setFORZA_CONSERVAZIONE(String FORZA_CONSERVAZIONE);

	/**
	 * Returns the forza_collegamento of this dati specifici invio.
	 *
	 * @return the forza_collegamento of this dati specifici invio
	 */
	@AutoEscape
	public String getFORZA_COLLEGAMENTO();

	/**
	 * Sets the forza_collegamento of this dati specifici invio.
	 *
	 * @param FORZA_COLLEGAMENTO the forza_collegamento of this dati specifici invio
	 */
	public void setFORZA_COLLEGAMENTO(String FORZA_COLLEGAMENTO);

	/**
	 * Returns the oggetto_unita_documentaria of this dati specifici invio.
	 *
	 * @return the oggetto_unita_documentaria of this dati specifici invio
	 */
	@AutoEscape
	public String getOGGETTO_UNITA_DOCUMENTARIA();

	/**
	 * Sets the oggetto_unita_documentaria of this dati specifici invio.
	 *
	 * @param OGGETTO_UNITA_DOCUMENTARIA the oggetto_unita_documentaria of this dati specifici invio
	 */
	public void setOGGETTO_UNITA_DOCUMENTARIA(
		String OGGETTO_UNITA_DOCUMENTARIA);

	/**
	 * Returns the data_unita_documentaria of this dati specifici invio.
	 *
	 * @return the data_unita_documentaria of this dati specifici invio
	 */
	public Date getDATA_UNITA_DOCUMENTARIA();

	/**
	 * Sets the data_unita_documentaria of this dati specifici invio.
	 *
	 * @param DATA_UNITA_DOCUMENTARIA the data_unita_documentaria of this dati specifici invio
	 */
	public void setDATA_UNITA_DOCUMENTARIA(Date DATA_UNITA_DOCUMENTARIA);

	/**
	 * Returns the versione_dati_specifici of this dati specifici invio.
	 *
	 * @return the versione_dati_specifici of this dati specifici invio
	 */
	public double getVERSIONE_DATI_SPECIFICI();

	/**
	 * Sets the versione_dati_specifici of this dati specifici invio.
	 *
	 * @param VERSIONE_DATI_SPECIFICI the versione_dati_specifici of this dati specifici invio
	 */
	public void setVERSIONE_DATI_SPECIFICI(double VERSIONE_DATI_SPECIFICI);

	/**
	 * Returns the identificativo_dato_specifico of this dati specifici invio.
	 *
	 * @return the identificativo_dato_specifico of this dati specifici invio
	 */
	@AutoEscape
	public String getIDENTIFICATIVO_DATO_SPECIFICO();

	/**
	 * Sets the identificativo_dato_specifico of this dati specifici invio.
	 *
	 * @param IDENTIFICATIVO_DATO_SPECIFICO the identificativo_dato_specifico of this dati specifici invio
	 */
	public void setIDENTIFICATIVO_DATO_SPECIFICO(
		String IDENTIFICATIVO_DATO_SPECIFICO);

	/**
	 * Returns the data_generazione of this dati specifici invio.
	 *
	 * @return the data_generazione of this dati specifici invio
	 */
	public Date getDATA_GENERAZIONE();

	/**
	 * Sets the data_generazione of this dati specifici invio.
	 *
	 * @param DATA_GENERAZIONE the data_generazione of this dati specifici invio
	 */
	public void setDATA_GENERAZIONE(Date DATA_GENERAZIONE);

	/**
	 * Returns the num_sms_generati of this dati specifici invio.
	 *
	 * @return the num_sms_generati of this dati specifici invio
	 */
	public int getNUM_SMS_GENERATI();

	/**
	 * Sets the num_sms_generati of this dati specifici invio.
	 *
	 * @param NUM_SMS_GENERATI the num_sms_generati of this dati specifici invio
	 */
	public void setNUM_SMS_GENERATI(int NUM_SMS_GENERATI);

	/**
	 * Returns the num_sms_inviati of this dati specifici invio.
	 *
	 * @return the num_sms_inviati of this dati specifici invio
	 */
	public int getNUM_SMS_INVIATI();

	/**
	 * Sets the num_sms_inviati of this dati specifici invio.
	 *
	 * @param NUM_SMS_INVIATI the num_sms_inviati of this dati specifici invio
	 */
	public void setNUM_SMS_INVIATI(int NUM_SMS_INVIATI);

	/**
	 * Returns the num_notifiche_ricezione of this dati specifici invio.
	 *
	 * @return the num_notifiche_ricezione of this dati specifici invio
	 */
	public int getNUM_NOTIFICHE_RICEZIONE();

	/**
	 * Sets the num_notifiche_ricezione of this dati specifici invio.
	 *
	 * @param NUM_NOTIFICHE_RICEZIONE the num_notifiche_ricezione of this dati specifici invio
	 */
	public void setNUM_NOTIFICHE_RICEZIONE(int NUM_NOTIFICHE_RICEZIONE);

	/**
	 * Returns the denominazione_applicativo of this dati specifici invio.
	 *
	 * @return the denominazione_applicativo of this dati specifici invio
	 */
	@AutoEscape
	public String getDENOMINAZIONE_APPLICATIVO();

	/**
	 * Sets the denominazione_applicativo of this dati specifici invio.
	 *
	 * @param DENOMINAZIONE_APPLICATIVO the denominazione_applicativo of this dati specifici invio
	 */
	public void setDENOMINAZIONE_APPLICATIVO(String DENOMINAZIONE_APPLICATIVO);

	/**
	 * Returns the oggetto_mail of this dati specifici invio.
	 *
	 * @return the oggetto_mail of this dati specifici invio
	 */
	@AutoEscape
	public String getOGGETTO_MAIL();

	/**
	 * Sets the oggetto_mail of this dati specifici invio.
	 *
	 * @param OGGETTO_MAIL the oggetto_mail of this dati specifici invio
	 */
	public void setOGGETTO_MAIL(String OGGETTO_MAIL);

	/**
	 * Returns the testo_mail of this dati specifici invio.
	 *
	 * @return the testo_mail of this dati specifici invio
	 */
	@AutoEscape
	public String getTESTO_MAIL();

	/**
	 * Sets the testo_mail of this dati specifici invio.
	 *
	 * @param TESTO_MAIL the testo_mail of this dati specifici invio
	 */
	public void setTESTO_MAIL(String TESTO_MAIL);

	/**
	 * Returns the compilatore_arpae of this dati specifici invio.
	 *
	 * @return the compilatore_arpae of this dati specifici invio
	 */
	@AutoEscape
	public String getCOMPILATORE_ARPAE();

	/**
	 * Sets the compilatore_arpae of this dati specifici invio.
	 *
	 * @param COMPILATORE_ARPAE the compilatore_arpae of this dati specifici invio
	 */
	public void setCOMPILATORE_ARPAE(String COMPILATORE_ARPAE);

	/**
	 * Returns the compilatore_protezione_civile of this dati specifici invio.
	 *
	 * @return the compilatore_protezione_civile of this dati specifici invio
	 */
	@AutoEscape
	public String getCOMPILATORE_PROTEZIONE_CIVILE();

	/**
	 * Sets the compilatore_protezione_civile of this dati specifici invio.
	 *
	 * @param COMPILATORE_PROTEZIONE_CIVILE the compilatore_protezione_civile of this dati specifici invio
	 */
	public void setCOMPILATORE_PROTEZIONE_CIVILE(
		String COMPILATORE_PROTEZIONE_CIVILE);

	/**
	 * Returns the data_inizio_validita of this dati specifici invio.
	 *
	 * @return the data_inizio_validita of this dati specifici invio
	 */
	public Date getDATA_INIZIO_VALIDITA();

	/**
	 * Sets the data_inizio_validita of this dati specifici invio.
	 *
	 * @param DATA_INIZIO_VALIDITA the data_inizio_validita of this dati specifici invio
	 */
	public void setDATA_INIZIO_VALIDITA(Date DATA_INIZIO_VALIDITA);

	/**
	 * Returns the data_fine_validita of this dati specifici invio.
	 *
	 * @return the data_fine_validita of this dati specifici invio
	 */
	public Date getDATA_FINE_VALIDITA();

	/**
	 * Sets the data_fine_validita of this dati specifici invio.
	 *
	 * @param DATA_FINE_VALIDITA the data_fine_validita of this dati specifici invio
	 */
	public void setDATA_FINE_VALIDITA(Date DATA_FINE_VALIDITA);

	/**
	 * Returns the approvatore_arpae of this dati specifici invio.
	 *
	 * @return the approvatore_arpae of this dati specifici invio
	 */
	@AutoEscape
	public String getAPPROVATORE_ARPAE();

	/**
	 * Sets the approvatore_arpae of this dati specifici invio.
	 *
	 * @param APPROVATORE_ARPAE the approvatore_arpae of this dati specifici invio
	 */
	public void setAPPROVATORE_ARPAE(String APPROVATORE_ARPAE);

	/**
	 * Returns the data_firma_arpae of this dati specifici invio.
	 *
	 * @return the data_firma_arpae of this dati specifici invio
	 */
	public Date getDATA_FIRMA_ARPAE();

	/**
	 * Sets the data_firma_arpae of this dati specifici invio.
	 *
	 * @param DATA_FIRMA_ARPAE the data_firma_arpae of this dati specifici invio
	 */
	public void setDATA_FIRMA_ARPAE(Date DATA_FIRMA_ARPAE);

	/**
	 * Returns the approvatore_protezione_civile of this dati specifici invio.
	 *
	 * @return the approvatore_protezione_civile of this dati specifici invio
	 */
	@AutoEscape
	public String getAPPROVATORE_PROTEZIONE_CIVILE();

	/**
	 * Sets the approvatore_protezione_civile of this dati specifici invio.
	 *
	 * @param APPROVATORE_PROTEZIONE_CIVILE the approvatore_protezione_civile of this dati specifici invio
	 */
	public void setAPPROVATORE_PROTEZIONE_CIVILE(
		String APPROVATORE_PROTEZIONE_CIVILE);

	/**
	 * Returns the data_firma_protezione_civile of this dati specifici invio.
	 *
	 * @return the data_firma_protezione_civile of this dati specifici invio
	 */
	public Date getDATA_FIRMA_PROTEZIONE_CIVILE();

	/**
	 * Sets the data_firma_protezione_civile of this dati specifici invio.
	 *
	 * @param DATA_FIRMA_PROTEZIONE_CIVILE the data_firma_protezione_civile of this dati specifici invio
	 */
	public void setDATA_FIRMA_PROTEZIONE_CIVILE(
		Date DATA_FIRMA_PROTEZIONE_CIVILE);

	/**
	 * Returns the invio_responsabile_territorio of this dati specifici invio.
	 *
	 * @return the invio_responsabile_territorio of this dati specifici invio
	 */
	@AutoEscape
	public String getINVIO_RESPONSABILE_TERRITORIO();

	/**
	 * Sets the invio_responsabile_territorio of this dati specifici invio.
	 *
	 * @param INVIO_RESPONSABILE_TERRITORIO the invio_responsabile_territorio of this dati specifici invio
	 */
	public void setINVIO_RESPONSABILE_TERRITORIO(
		String INVIO_RESPONSABILE_TERRITORIO);

	/**
	 * Returns the id_documento_principale of this dati specifici invio.
	 *
	 * @return the id_documento_principale of this dati specifici invio
	 */
	public long getID_DOCUMENTO_PRINCIPALE();

	/**
	 * Sets the id_documento_principale of this dati specifici invio.
	 *
	 * @param ID_DOCUMENTO_PRINCIPALE the id_documento_principale of this dati specifici invio
	 */
	public void setID_DOCUMENTO_PRINCIPALE(long ID_DOCUMENTO_PRINCIPALE);

	/**
	 * Returns the tipo_documento of this dati specifici invio.
	 *
	 * @return the tipo_documento of this dati specifici invio
	 */
	@AutoEscape
	public String getTIPO_DOCUMENTO();

	/**
	 * Sets the tipo_documento of this dati specifici invio.
	 *
	 * @param TIPO_DOCUMENTO the tipo_documento of this dati specifici invio
	 */
	public void setTIPO_DOCUMENTO(String TIPO_DOCUMENTO);

	/**
	 * Returns the tipo_struttura of this dati specifici invio.
	 *
	 * @return the tipo_struttura of this dati specifici invio
	 */
	@AutoEscape
	public String getTIPO_STRUTTURA();

	/**
	 * Sets the tipo_struttura of this dati specifici invio.
	 *
	 * @param TIPO_STRUTTURA the tipo_struttura of this dati specifici invio
	 */
	public void setTIPO_STRUTTURA(String TIPO_STRUTTURA);

	/**
	 * Returns the denominazione_sensore_rilevamento of this dati specifici invio.
	 *
	 * @return the denominazione_sensore_rilevamento of this dati specifici invio
	 */
	@AutoEscape
	public String getDENOMINAZIONE_SENSORE_RILEVAMENTO();

	/**
	 * Sets the denominazione_sensore_rilevamento of this dati specifici invio.
	 *
	 * @param DENOMINAZIONE_SENSORE_RILEVAMENTO the denominazione_sensore_rilevamento of this dati specifici invio
	 */
	public void setDENOMINAZIONE_SENSORE_RILEVAMENTO(
		String DENOMINAZIONE_SENSORE_RILEVAMENTO);

	/**
	 * Returns the regola_allarme_id of this dati specifici invio.
	 *
	 * @return the regola_allarme_id of this dati specifici invio
	 */
	@AutoEscape
	public String getREGOLA_ALLARME_ID();

	/**
	 * Sets the regola_allarme_id of this dati specifici invio.
	 *
	 * @param REGOLA_ALLARME_ID the regola_allarme_id of this dati specifici invio
	 */
	public void setREGOLA_ALLARME_ID(String REGOLA_ALLARME_ID);

	/**
	 * Returns the regola_allarme_nome of this dati specifici invio.
	 *
	 * @return the regola_allarme_nome of this dati specifici invio
	 */
	@AutoEscape
	public String getREGOLA_ALLARME_NOME();

	/**
	 * Sets the regola_allarme_nome of this dati specifici invio.
	 *
	 * @param REGOLA_ALLARME_NOME the regola_allarme_nome of this dati specifici invio
	 */
	public void setREGOLA_ALLARME_NOME(String REGOLA_ALLARME_NOME);

	/**
	 * Returns the regola_allarme_descrizione of this dati specifici invio.
	 *
	 * @return the regola_allarme_descrizione of this dati specifici invio
	 */
	@AutoEscape
	public String getREGOLA_ALLARME_DESCRIZIONE();

	/**
	 * Sets the regola_allarme_descrizione of this dati specifici invio.
	 *
	 * @param REGOLA_ALLARME_DESCRIZIONE the regola_allarme_descrizione of this dati specifici invio
	 */
	public void setREGOLA_ALLARME_DESCRIZIONE(
		String REGOLA_ALLARME_DESCRIZIONE);

	/**
	 * Returns the esito_invio of this dati specifici invio.
	 *
	 * @return the esito_invio of this dati specifici invio
	 */
	@AutoEscape
	public String getESITO_INVIO();

	/**
	 * Sets the esito_invio of this dati specifici invio.
	 *
	 * @param ESITO_INVIO the esito_invio of this dati specifici invio
	 */
	public void setESITO_INVIO(String ESITO_INVIO);

	/**
	 * Returns the user ID of this dati specifici invio.
	 *
	 * @return the user ID of this dati specifici invio
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dati specifici invio.
	 *
	 * @param userId the user ID of this dati specifici invio
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dati specifici invio.
	 *
	 * @return the user uuid of this dati specifici invio
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dati specifici invio.
	 *
	 * @param userUuid the user uuid of this dati specifici invio
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the company ID of this dati specifici invio.
	 *
	 * @return the company ID of this dati specifici invio
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dati specifici invio.
	 *
	 * @param companyId the company ID of this dati specifici invio
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this dati specifici invio.
	 *
	 * @return the group ID of this dati specifici invio
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this dati specifici invio.
	 *
	 * @param groupId the group ID of this dati specifici invio
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the data_invio of this dati specifici invio.
	 *
	 * @return the data_invio of this dati specifici invio
	 */
	public Date getData_invio();

	/**
	 * Sets the data_invio of this dati specifici invio.
	 *
	 * @param data_invio the data_invio of this dati specifici invio
	 */
	public void setData_invio(Date data_invio);

	/**
	 * Returns the data_risposta of this dati specifici invio.
	 *
	 * @return the data_risposta of this dati specifici invio
	 */
	public Date getData_risposta();

	/**
	 * Sets the data_risposta of this dati specifici invio.
	 *
	 * @param data_risposta the data_risposta of this dati specifici invio
	 */
	public void setData_risposta(Date data_risposta);

	/**
	 * Returns the codice_esito of this dati specifici invio.
	 *
	 * @return the codice_esito of this dati specifici invio
	 */
	@AutoEscape
	public String getCODICE_ESITO();

	/**
	 * Sets the codice_esito of this dati specifici invio.
	 *
	 * @param CODICE_ESITO the codice_esito of this dati specifici invio
	 */
	public void setCODICE_ESITO(String CODICE_ESITO);

	/**
	 * Returns the codice_errore of this dati specifici invio.
	 *
	 * @return the codice_errore of this dati specifici invio
	 */
	@AutoEscape
	public String getCODICE_ERRORE();

	/**
	 * Sets the codice_errore of this dati specifici invio.
	 *
	 * @param CODICE_ERRORE the codice_errore of this dati specifici invio
	 */
	public void setCODICE_ERRORE(String CODICE_ERRORE);

	/**
	 * Returns the mesg_errore of this dati specifici invio.
	 *
	 * @return the mesg_errore of this dati specifici invio
	 */
	@AutoEscape
	public String getMESG_ERRORE();

	/**
	 * Sets the mesg_errore of this dati specifici invio.
	 *
	 * @param MESG_ERRORE the mesg_errore of this dati specifici invio
	 */
	public void setMESG_ERRORE(String MESG_ERRORE);

	/**
	 * Returns the codice_tipo_invio of this dati specifici invio.
	 *
	 * @return the codice_tipo_invio of this dati specifici invio
	 */
	@AutoEscape
	public String getCODICE_TIPO_INVIO();

	/**
	 * Sets the codice_tipo_invio of this dati specifici invio.
	 *
	 * @param CODICE_TIPO_INVIO the codice_tipo_invio of this dati specifici invio
	 */
	public void setCODICE_TIPO_INVIO(String CODICE_TIPO_INVIO);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.eng.parer.model.DatiSpecificiInvio datiSpecificiInvio);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.parer.model.DatiSpecificiInvio> toCacheModel();

	@Override
	public it.eng.parer.model.DatiSpecificiInvio toEscapedModel();

	@Override
	public it.eng.parer.model.DatiSpecificiInvio toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}