/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerte.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RubricaSito service. Represents a row in the &quot;rubrica_RubricaSito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.allerte.model.impl.RubricaSitoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.allerte.model.impl.RubricaSitoImpl</code>.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaSito
 * @generated
 */
@ProviderType
public interface RubricaSitoModel extends BaseModel<RubricaSito> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rubrica sito model instance should use the {@link RubricaSito} interface instead.
	 */

	/**
	 * Returns the primary key of this rubrica sito.
	 *
	 * @return the primary key of this rubrica sito
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rubrica sito.
	 *
	 * @param primaryKey the primary key of this rubrica sito
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_sito of this rubrica sito.
	 *
	 * @return the id_sito of this rubrica sito
	 */
	public long getID_SITO();

	/**
	 * Sets the id_sito of this rubrica sito.
	 *
	 * @param ID_SITO the id_sito of this rubrica sito
	 */
	public void setID_SITO(long ID_SITO);

	/**
	 * Returns the nome of this rubrica sito.
	 *
	 * @return the nome of this rubrica sito
	 */
	@AutoEscape
	public String getNOME();

	/**
	 * Sets the nome of this rubrica sito.
	 *
	 * @param NOME the nome of this rubrica sito
	 */
	public void setNOME(String NOME);

	/**
	 * Returns the fk_liferay_site of this rubrica sito.
	 *
	 * @return the fk_liferay_site of this rubrica sito
	 */
	public long getFK_LIFERAY_SITE();

	/**
	 * Sets the fk_liferay_site of this rubrica sito.
	 *
	 * @param FK_LIFERAY_SITE the fk_liferay_site of this rubrica sito
	 */
	public void setFK_LIFERAY_SITE(long FK_LIFERAY_SITE);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.allerte.model.RubricaSito rubricaSito);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.allerte.model.RubricaSito> toCacheModel();

	@Override
	public it.eng.allerte.model.RubricaSito toEscapedModel();

	@Override
	public it.eng.allerte.model.RubricaSito toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}