/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerte.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import it.eng.allerte.service.persistence.RubricaRuoloPermessiPK;

import java.io.Serializable;

/**
 * The base model interface for the RubricaRuoloPermessi service. Represents a row in the &quot;rubrica_RubricaRuoloPermessi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.allerte.model.impl.RubricaRuoloPermessiModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.allerte.model.impl.RubricaRuoloPermessiImpl</code>.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaRuoloPermessi
 * @generated
 */
@ProviderType
public interface RubricaRuoloPermessiModel
	extends BaseModel<RubricaRuoloPermessi> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rubrica ruolo permessi model instance should use the {@link RubricaRuoloPermessi} interface instead.
	 */

	/**
	 * Returns the primary key of this rubrica ruolo permessi.
	 *
	 * @return the primary key of this rubrica ruolo permessi
	 */
	public RubricaRuoloPermessiPK getPrimaryKey();

	/**
	 * Sets the primary key of this rubrica ruolo permessi.
	 *
	 * @param primaryKey the primary key of this rubrica ruolo permessi
	 */
	public void setPrimaryKey(RubricaRuoloPermessiPK primaryKey);

	/**
	 * Returns the fk_id_ruolo of this rubrica ruolo permessi.
	 *
	 * @return the fk_id_ruolo of this rubrica ruolo permessi
	 */
	public long getFK_ID_RUOLO();

	/**
	 * Sets the fk_id_ruolo of this rubrica ruolo permessi.
	 *
	 * @param FK_ID_RUOLO the fk_id_ruolo of this rubrica ruolo permessi
	 */
	public void setFK_ID_RUOLO(long FK_ID_RUOLO);

	/**
	 * Returns the fk_id_permesso of this rubrica ruolo permessi.
	 *
	 * @return the fk_id_permesso of this rubrica ruolo permessi
	 */
	@AutoEscape
	public String getFK_ID_PERMESSO();

	/**
	 * Sets the fk_id_permesso of this rubrica ruolo permessi.
	 *
	 * @param FK_ID_PERMESSO the fk_id_permesso of this rubrica ruolo permessi
	 */
	public void setFK_ID_PERMESSO(String FK_ID_PERMESSO);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		it.eng.allerte.model.RubricaRuoloPermessi rubricaRuoloPermessi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.allerte.model.RubricaRuoloPermessi> toCacheModel();

	@Override
	public it.eng.allerte.model.RubricaRuoloPermessi toEscapedModel();

	@Override
	public it.eng.allerte.model.RubricaRuoloPermessi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}