/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerte.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RubricaCanale service. Represents a row in the &quot;rubrica_RubricaCanale&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.allerte.model.impl.RubricaCanaleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.allerte.model.impl.RubricaCanaleImpl</code>.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaCanale
 * @generated
 */
@ProviderType
public interface RubricaCanaleModel extends BaseModel<RubricaCanale> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rubrica canale model instance should use the {@link RubricaCanale} interface instead.
	 */

	/**
	 * Returns the primary key of this rubrica canale.
	 *
	 * @return the primary key of this rubrica canale
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rubrica canale.
	 *
	 * @param primaryKey the primary key of this rubrica canale
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_canale of this rubrica canale.
	 *
	 * @return the id_canale of this rubrica canale
	 */
	public long getID_CANALE();

	/**
	 * Sets the id_canale of this rubrica canale.
	 *
	 * @param ID_CANALE the id_canale of this rubrica canale
	 */
	public void setID_CANALE(long ID_CANALE);

	/**
	 * Returns the nome of this rubrica canale.
	 *
	 * @return the nome of this rubrica canale
	 */
	@AutoEscape
	public String getNOME();

	/**
	 * Sets the nome of this rubrica canale.
	 *
	 * @param NOME the nome of this rubrica canale
	 */
	public void setNOME(String NOME);

	/**
	 * Returns the icona of this rubrica canale.
	 *
	 * @return the icona of this rubrica canale
	 */
	@AutoEscape
	public String getICONA();

	/**
	 * Sets the icona of this rubrica canale.
	 *
	 * @param ICONA the icona of this rubrica canale
	 */
	public void setICONA(String ICONA);

	/**
	 * Returns the regex of this rubrica canale.
	 *
	 * @return the regex of this rubrica canale
	 */
	@AutoEscape
	public String getREGEX();

	/**
	 * Sets the regex of this rubrica canale.
	 *
	 * @param REGEX the regex of this rubrica canale
	 */
	public void setREGEX(String REGEX);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.allerte.model.RubricaCanale rubricaCanale);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.allerte.model.RubricaCanale> toCacheModel();

	@Override
	public it.eng.allerte.model.RubricaCanale toEscapedModel();

	@Override
	public it.eng.allerte.model.RubricaCanale toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}