/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.allerte.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RubricaGruppo service. Represents a row in the &quot;rubrica_RubricaGruppo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.allerte.model.impl.RubricaGruppoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.allerte.model.impl.RubricaGruppoImpl</code>.
 * </p>
 *
 * @author Pratola_L
 * @see RubricaGruppo
 * @generated
 */
@ProviderType
public interface RubricaGruppoModel extends BaseModel<RubricaGruppo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rubrica gruppo model instance should use the {@link RubricaGruppo} interface instead.
	 */

	/**
	 * Returns the primary key of this rubrica gruppo.
	 *
	 * @return the primary key of this rubrica gruppo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rubrica gruppo.
	 *
	 * @param primaryKey the primary key of this rubrica gruppo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_gruppo of this rubrica gruppo.
	 *
	 * @return the id_gruppo of this rubrica gruppo
	 */
	public long getID_GRUPPO();

	/**
	 * Sets the id_gruppo of this rubrica gruppo.
	 *
	 * @param ID_GRUPPO the id_gruppo of this rubrica gruppo
	 */
	public void setID_GRUPPO(long ID_GRUPPO);

	/**
	 * Returns the nome of this rubrica gruppo.
	 *
	 * @return the nome of this rubrica gruppo
	 */
	@AutoEscape
	public String getNOME();

	/**
	 * Sets the nome of this rubrica gruppo.
	 *
	 * @param NOME the nome of this rubrica gruppo
	 */
	public void setNOME(String NOME);

	/**
	 * Returns the fk_sito_proprietario of this rubrica gruppo.
	 *
	 * @return the fk_sito_proprietario of this rubrica gruppo
	 */
	public long getFK_SITO_PROPRIETARIO();

	/**
	 * Sets the fk_sito_proprietario of this rubrica gruppo.
	 *
	 * @param FK_SITO_PROPRIETARIO the fk_sito_proprietario of this rubrica gruppo
	 */
	public void setFK_SITO_PROPRIETARIO(long FK_SITO_PROPRIETARIO);

	/**
	 * Returns the note of this rubrica gruppo.
	 *
	 * @return the note of this rubrica gruppo
	 */
	@AutoEscape
	public String getNOTE();

	/**
	 * Sets the note of this rubrica gruppo.
	 *
	 * @param NOTE the note of this rubrica gruppo
	 */
	public void setNOTE(String NOTE);

	/**
	 * Returns the fk_utente_creazione of this rubrica gruppo.
	 *
	 * @return the fk_utente_creazione of this rubrica gruppo
	 */
	public long getFK_UTENTE_CREAZIONE();

	/**
	 * Sets the fk_utente_creazione of this rubrica gruppo.
	 *
	 * @param FK_UTENTE_CREAZIONE the fk_utente_creazione of this rubrica gruppo
	 */
	public void setFK_UTENTE_CREAZIONE(long FK_UTENTE_CREAZIONE);

	/**
	 * Returns the data_creazione of this rubrica gruppo.
	 *
	 * @return the data_creazione of this rubrica gruppo
	 */
	public Date getDATA_CREAZIONE();

	/**
	 * Sets the data_creazione of this rubrica gruppo.
	 *
	 * @param DATA_CREAZIONE the data_creazione of this rubrica gruppo
	 */
	public void setDATA_CREAZIONE(Date DATA_CREAZIONE);

	/**
	 * Returns the fk_utente_modifica of this rubrica gruppo.
	 *
	 * @return the fk_utente_modifica of this rubrica gruppo
	 */
	public long getFK_UTENTE_MODIFICA();

	/**
	 * Sets the fk_utente_modifica of this rubrica gruppo.
	 *
	 * @param FK_UTENTE_MODIFICA the fk_utente_modifica of this rubrica gruppo
	 */
	public void setFK_UTENTE_MODIFICA(long FK_UTENTE_MODIFICA);

	/**
	 * Returns the data_modifica of this rubrica gruppo.
	 *
	 * @return the data_modifica of this rubrica gruppo
	 */
	public Date getDATA_MODIFICA();

	/**
	 * Sets the data_modifica of this rubrica gruppo.
	 *
	 * @param DATA_MODIFICA the data_modifica of this rubrica gruppo
	 */
	public void setDATA_MODIFICA(Date DATA_MODIFICA);

	/**
	 * Returns the disabled of this rubrica gruppo.
	 *
	 * @return the disabled of this rubrica gruppo
	 */
	public boolean getDISABLED();

	/**
	 * Returns <code>true</code> if this rubrica gruppo is disabled.
	 *
	 * @return <code>true</code> if this rubrica gruppo is disabled; <code>false</code> otherwise
	 */
	public boolean isDISABLED();

	/**
	 * Sets whether this rubrica gruppo is disabled.
	 *
	 * @param DISABLED the disabled of this rubrica gruppo
	 */
	public void setDISABLED(boolean DISABLED);

	/**
	 * Returns the fk_categoria of this rubrica gruppo.
	 *
	 * @return the fk_categoria of this rubrica gruppo
	 */
	public long getFK_CATEGORIA();

	/**
	 * Sets the fk_categoria of this rubrica gruppo.
	 *
	 * @param FK_CATEGORIA the fk_categoria of this rubrica gruppo
	 */
	public void setFK_CATEGORIA(long FK_CATEGORIA);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.allerte.model.RubricaGruppo rubricaGruppo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.allerte.model.RubricaGruppo> toCacheModel();

	@Override
	public it.eng.allerte.model.RubricaGruppo toEscapedModel();

	@Override
	public it.eng.allerte.model.RubricaGruppo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}