/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.parer.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;

import it.eng.parer.model.ComponentiInvio;
import it.eng.parer.service.ComponentiInvioService;
import it.eng.parer.service.persistence.ComponentiInvioPersistence;
import it.eng.parer.service.persistence.DatiSpecificiInvioPersistence;
import it.eng.parer.service.persistence.DocumentiCollegatiPersistence;
import it.eng.parer.service.persistence.ParametriPersistence;

import java.sql.Connection;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the componenti invio remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.parer.service.impl.ComponentiInvioServiceImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see it.eng.parer.service.impl.ComponentiInvioServiceImpl
 * @generated
 */
public abstract class ComponentiInvioServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, ComponentiInvioService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ComponentiInvioService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.parer.service.ComponentiInvioServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ComponentiInvioService.class, IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		componentiInvioService = (ComponentiInvioService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ComponentiInvioService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ComponentiInvio.class;
	}

	protected String getModelClassName() {
		return ComponentiInvio.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = componentiInvioPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected it.eng.parer.service.ComponentiInvioLocalService
		componentiInvioLocalService;

	protected ComponentiInvioService componentiInvioService;

	@Reference
	protected ComponentiInvioPersistence componentiInvioPersistence;

	@Reference
	protected DatiSpecificiInvioPersistence datiSpecificiInvioPersistence;

	@Reference
	protected DocumentiCollegatiPersistence documentiCollegatiPersistence;

	@Reference
	protected ParametriPersistence parametriPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameService
		classNameService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserService userService;

	private static final Log _log = LogFactoryUtil.getLog(
		ComponentiInvioServiceBaseImpl.class);

}