/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.parer.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import it.eng.parer.model.DocumentiCollegati;
import it.eng.parer.service.DocumentiCollegatiLocalService;
import it.eng.parer.service.persistence.ComponentiInvioPersistence;
import it.eng.parer.service.persistence.DatiSpecificiInvioPersistence;
import it.eng.parer.service.persistence.DocumentiCollegatiPK;
import it.eng.parer.service.persistence.DocumentiCollegatiPersistence;
import it.eng.parer.service.persistence.ParametriPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the documenti collegati local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link it.eng.parer.service.impl.DocumentiCollegatiLocalServiceImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see it.eng.parer.service.impl.DocumentiCollegatiLocalServiceImpl
 * @generated
 */
public abstract class DocumentiCollegatiLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, DocumentiCollegatiLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DocumentiCollegatiLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>it.eng.parer.service.DocumentiCollegatiLocalServiceUtil</code>.
	 */

	/**
	 * Adds the documenti collegati to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DocumentiCollegatiLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param documentiCollegati the documenti collegati
	 * @return the documenti collegati that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DocumentiCollegati addDocumentiCollegati(
		DocumentiCollegati documentiCollegati) {

		documentiCollegati.setNew(true);

		return documentiCollegatiPersistence.update(documentiCollegati);
	}

	/**
	 * Creates a new documenti collegati with the primary key. Does not add the documenti collegati to the database.
	 *
	 * @param documentiCollegatiPK the primary key for the new documenti collegati
	 * @return the new documenti collegati
	 */
	@Override
	@Transactional(enabled = false)
	public DocumentiCollegati createDocumentiCollegati(
		DocumentiCollegatiPK documentiCollegatiPK) {

		return documentiCollegatiPersistence.create(documentiCollegatiPK);
	}

	/**
	 * Deletes the documenti collegati with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DocumentiCollegatiLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param documentiCollegatiPK the primary key of the documenti collegati
	 * @return the documenti collegati that was removed
	 * @throws PortalException if a documenti collegati with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DocumentiCollegati deleteDocumentiCollegati(
			DocumentiCollegatiPK documentiCollegatiPK)
		throws PortalException {

		return documentiCollegatiPersistence.remove(documentiCollegatiPK);
	}

	/**
	 * Deletes the documenti collegati from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DocumentiCollegatiLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param documentiCollegati the documenti collegati
	 * @return the documenti collegati that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DocumentiCollegati deleteDocumentiCollegati(
		DocumentiCollegati documentiCollegati) {

		return documentiCollegatiPersistence.remove(documentiCollegati);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return documentiCollegatiPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DocumentiCollegati.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return documentiCollegatiPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.parer.model.impl.DocumentiCollegatiModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return documentiCollegatiPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.parer.model.impl.DocumentiCollegatiModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return documentiCollegatiPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return documentiCollegatiPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return documentiCollegatiPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DocumentiCollegati fetchDocumentiCollegati(
		DocumentiCollegatiPK documentiCollegatiPK) {

		return documentiCollegatiPersistence.fetchByPrimaryKey(
			documentiCollegatiPK);
	}

	/**
	 * Returns the documenti collegati with the primary key.
	 *
	 * @param documentiCollegatiPK the primary key of the documenti collegati
	 * @return the documenti collegati
	 * @throws PortalException if a documenti collegati with the primary key could not be found
	 */
	@Override
	public DocumentiCollegati getDocumentiCollegati(
			DocumentiCollegatiPK documentiCollegatiPK)
		throws PortalException {

		return documentiCollegatiPersistence.findByPrimaryKey(
			documentiCollegatiPK);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return documentiCollegatiPersistence.create(
			(DocumentiCollegatiPK)primaryKeyObj);
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement DocumentiCollegatiLocalServiceImpl#deleteDocumentiCollegati(DocumentiCollegati) to avoid orphaned data");
		}

		return documentiCollegatiLocalService.deleteDocumentiCollegati(
			(DocumentiCollegati)persistedModel);
	}

	@Override
	public BasePersistence<DocumentiCollegati> getBasePersistence() {
		return documentiCollegatiPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return documentiCollegatiPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the documenti collegatis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>it.eng.parer.model.impl.DocumentiCollegatiModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of documenti collegatis
	 * @param end the upper bound of the range of documenti collegatis (not inclusive)
	 * @return the range of documenti collegatis
	 */
	@Override
	public List<DocumentiCollegati> getDocumentiCollegatis(int start, int end) {
		return documentiCollegatiPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of documenti collegatis.
	 *
	 * @return the number of documenti collegatis
	 */
	@Override
	public int getDocumentiCollegatisCount() {
		return documentiCollegatiPersistence.countAll();
	}

	/**
	 * Updates the documenti collegati in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DocumentiCollegatiLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param documentiCollegati the documenti collegati
	 * @return the documenti collegati that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DocumentiCollegati updateDocumentiCollegati(
		DocumentiCollegati documentiCollegati) {

		return documentiCollegatiPersistence.update(documentiCollegati);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			DocumentiCollegatiLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		documentiCollegatiLocalService =
			(DocumentiCollegatiLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DocumentiCollegatiLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DocumentiCollegati.class;
	}

	protected String getModelClassName() {
		return DocumentiCollegati.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = documentiCollegatiPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected ComponentiInvioPersistence componentiInvioPersistence;

	@Reference
	protected DatiSpecificiInvioPersistence datiSpecificiInvioPersistence;

	protected DocumentiCollegatiLocalService documentiCollegatiLocalService;

	@Reference
	protected DocumentiCollegatiPersistence documentiCollegatiPersistence;

	@Reference
	protected ParametriPersistence parametriPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		DocumentiCollegatiLocalServiceBaseImpl.class);

}