/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.radarMeteo.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Img service. Represents a row in the &quot;rt_portlet_img&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>it.eng.radarMeteo.model.impl.ImgModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>it.eng.radarMeteo.model.impl.ImgImpl</code>.
 * </p>
 *
 * @author Francesco
 * @see Img
 * @generated
 */
@ProviderType
public interface ImgModel extends BaseModel<Img> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a img model instance should use the {@link Img} interface instead.
	 */

	/**
	 * Returns the primary key of this img.
	 *
	 * @return the primary key of this img
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this img.
	 *
	 * @param primaryKey the primary key of this img
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this img.
	 *
	 * @return the ID of this img
	 */
	public long getId();

	/**
	 * Sets the ID of this img.
	 *
	 * @param id the ID of this img
	 */
	public void setId(long id);

	/**
	 * Returns the coord of this img.
	 *
	 * @return the coord of this img
	 */
	@AutoEscape
	public String getCoord();

	/**
	 * Sets the coord of this img.
	 *
	 * @param coord the coord of this img
	 */
	public void setCoord(String coord);

	/**
	 * Returns the palette of this img.
	 *
	 * @return the palette of this img
	 */
	@AutoEscape
	public String getPalette();

	/**
	 * Sets the palette of this img.
	 *
	 * @param palette the palette of this img
	 */
	public void setPalette(String palette);

	/**
	 * Returns the timestamp of this img.
	 *
	 * @return the timestamp of this img
	 */
	public long getTimestamp();

	/**
	 * Sets the timestamp of this img.
	 *
	 * @param timestamp the timestamp of this img
	 */
	public void setTimestamp(long timestamp);

	/**
	 * Returns the data of this img.
	 *
	 * @return the data of this img
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this img.
	 *
	 * @param data the data of this img
	 */
	public void setData(String data);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(it.eng.radarMeteo.model.Img img);

	@Override
	public int hashCode();

	@Override
	public CacheModel<it.eng.radarMeteo.model.Img> toCacheModel();

	@Override
	public it.eng.radarMeteo.model.Img toEscapedModel();

	@Override
	public it.eng.radarMeteo.model.Img toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}