
<main class="page main page--single-dato" id="main-content">

	<div class="page__head">
	
		 <div class="container d-flex">
		 
		 	<div class="row w-100 justify-content-between">
	            <div class="col-10 col-lg-10">
	                <h1 id='pageTitle'></h1>
	                <p class="lead"></p>
	            </div>   
            </div>
          </div>
     </div>
     
    <div class="breadcrumb-container">
        <div class="container d-flex">
            <nav class="row" aria-label="Hai percorso">
                <ol class="breadcrumb">
    
                    <li class="breadcrumb-item">
                        <a href="/">Home</a>
                    </li>
                    <li class="breadcrumb-item">
                       <a href="/previsioni-e-dati">Previsioni e dati</a>
                    </li>
    
                    <li class="breadcrumb-item active" aria-current="page" id='liPageTile'> </li>
    
                </ol>
            </nav>
        </div>
    </div>
    
    ${processor.processColumn("column-1", "portlet-column-content portlet-column-content-only")}
    
    
    <div class="portlet-boundary portlet-boundary_com_liferay_journal_content_web_portlet_JournalContentPortlet_  decorate portlet-journal-content  portlet-draggable yui3-dd-drop" id="p_p_id_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_">
		<span id="p_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC"></span>




	

	
		
			






































	
		
<section class="portlet" id="portlet_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC">

			<header class="portlet-topper" style="user-select: none;">
				<div class="portlet-title-default" style="user-select: none;">
					<span class="portlet-name-text">Visualizzazione Contenuto Web</span>
				</div>

					<menu class="portlet-title-menu portlet-topper-toolbar" id="portlet-title-menu_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_1" type="toolbar">


























































<div class="dropdown lfr-icon-menu " data-qa-id="addButton">
	
		
			<a class="direction-right dropdown-toggle icon-monospaced " href="javascript:;" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx_column1_1_menu" title="Aggiungi">
				<span id="qfkd__column1__1"><svg class="lexicon-icon lexicon-icon-plus" focusable="false" role="presentation" viewBox="0 0 512 512">
<path class="lexicon-icon-outline" d="M479.82 224.002h-192.41v-191.91c0-17.6-14.4-32-32-32v0c-17.6 0-32 14.4-32 32v191.91h-191.41c-17.6 0-32 14.4-32 32v0c0 17.6 14.4 32 32 32h191.41v191.91c0 17.6 14.4 32 32 32v0c17.6 0 32-14.4 32-32v-191.909h192.41c17.6 0 32-14.4 32-32v0c0-17.6-14.4-32-32-32z"></path>
</svg></span>
			</a>
		
	

	

	
		
			<ul class="dropdown-menu dropdown-menu-right">
		
	

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=30149&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__aggiornamenti_2d_dal_2d_comune" role="menuitem" data-title="Nuovi aggiornamenti dal comune" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">aggiornamenti dal comune</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=35009&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__menu_2d_lista" role="menuitem" data-title="Nuovi menu-lista" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">menu-lista</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=35013&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__preparati_2d_ed_2d_informati" role="menuitem" data-title="Nuovi preparati-ed-informati" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">preparati-ed-informati</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=36103&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__ultimi_2d_aggiornamenti" role="menuitem" data-title="Nuovi ultimi-aggiornamenti" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">ultimi-aggiornamenti</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=36104&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__menu_2d_di_2d_link" role="menuitem" data-title="Nuovi menu di link" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">menu di link</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=55979&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__componente_2d_iframe" role="menuitem" data-title="Nuovi componente-iframe" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">componente-iframe</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=56075&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__componente_2d_html" role="menuitem" data-title="Nuovi componente-html" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">componente-html</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=56524&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__preparati_2d_ed_2d_informati__1" role="menuitem" data-title="Nuovi preparati ed informati" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">preparati ed informati</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=57636&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__report_2d_post_2d_evento" role="menuitem" data-title="Nuovi Report post evento" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Report post evento</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=58044&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__menu_2d_di_2d_link_2d_con_2d_descrizione" role="menuitem" data-title="Nuovi menu di link con descrizione" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">menu di link con descrizione</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=64500&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__banner" role="menuitem" data-title="Nuovi Banner" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Banner</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=67235&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__monitoraggio" role="menuitem" data-title="Nuovi Monitoraggio" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Monitoraggio</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=72744&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__news_2d_web_2d_allerte" role="menuitem" data-title="Nuovi News web allerte" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">News web allerte</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=78116&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__piano_2d_di_2d_protezione_2d_civile" role="menuitem" data-title="Nuovi piano di protezione civile" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">piano di protezione civile</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=91775&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__site_2d_name" role="menuitem" data-title="Nuovi site-name" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">site-name</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=91955&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__menu" role="menuitem" data-title="Nuovi Menù" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Menù</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=91985&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__twitter" role="menuitem" data-title="Nuovi Twitter" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Twitter</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=93292&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__piano_2d_pc" role="menuitem" data-title="Nuovi piano pc" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">piano pc</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=127356&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__social_2d_share" role="menuitem" data-title="Nuovi social-share" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">social-share</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=139641&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__allerta" role="menuitem" data-title="Nuovi Allerta" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Allerta</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=139646&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__bollettino" role="menuitem" data-title="Nuovi Bollettino" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Bollettino</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=150446&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__rubrica" role="menuitem" data-title="Nuovi rubrica" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">rubrica</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=187552&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__contenuto_2d_di_2d_preparati_2d_ed_2d_informati" role="menuitem" data-title="Nuovi contenuto di preparati ed informati" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">contenuto di preparati ed informati</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=188022&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__flotta_2d_tabella_2d_documenti" role="menuitem" data-title="Nuovi flotta-tabella-documenti" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">flotta-tabella-documenti</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=227848&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__meteomont" role="menuitem" data-title="Nuovi meteomont" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">meteomont</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=261972&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__menu_2d_singolo_2d_luogo_2d_header" role="menuitem" data-title="Nuovi menu singolo luogo header" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">menu singolo luogo header</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=895401&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__contenuto_2d_web_2d_base" role="menuitem" data-title="Nuovi Contenuto Web Base" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Contenuto Web Base</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=909509&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__lr72__struttura_2d_informati_2d_preparati" role="menuitem" data-title="Nuovi lr72_struttura-informati-preparati" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">lr72_struttura-informati-preparati</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=930481&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__solo_2d_html" role="menuitem" data-title="Nuovi Solo Html" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Solo Html</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=946967&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__header_2d_pagineeditoriali" role="menuitem" data-title="Nuovi Header-PagineEditoriali" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Header-PagineEditoriali</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	

		












































	

		

		






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=maximized&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_ddmStructureId=1039730&amp;p_p_auth=XfO6O7wV&amp;refererPlid=55203" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_kldx__column1__1__menu__pagine_2d_statiche" role="menuitem" data-title="Nuovi Pagine Statiche" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Pagine Statiche</span>
	
	
					</a>
				
				
		</li>
	
	


	


		

	













		</ul>
	
</div>

					</menu>

					<menu class="portlet-topper-toolbar" id="portlet-topper-toolbar_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC" type="toolbar">














<div class="dropdown lfr-icon-menu portlet-options">
	
		
			<a class="direction-right dropdown-toggle icon-monospaced icon-monospaced" href="javascript:;" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_tiym_column1_1_menu" title="Opzioni">
				<span id="jbfs__column1__1"><svg class="lexicon-icon lexicon-icon-ellipsis-v" focusable="false" role="presentation" viewBox="0 0 512 512">
<path class="lexicon-icon-outline" d="M319 255.5c0 35.346-28.654 64-64 64s-64-28.654-64-64c0-35.346 28.654-64 64-64s64 28.654 64 64z"></path>
<path class="lexicon-icon-outline" d="M319 448c0 35.346-28.654 64-64 64s-64-28.654-64-64c0-35.346 28.654-64 64-64s64 28.654 64 64z"></path>
<path class="lexicon-icon-outline" d="M319 64c0 35.346-28.654 64-64 64s-64-28.654-64-64c0-35.346 28.654-64 64-64s64 28.654 64 64z"></path>
</svg></span>
			</a>
		
	

	

	
		
			<ul class="dropdown-menu dropdown-menu-right">
		
	






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/web/guest/precipitazioni?p_p_id=com_liferay_portlet_configuration_css_web_portlet_PortletConfigurationCSSPortlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;_com_liferay_portlet_configuration_css_web_portlet_PortletConfigurationCSSPortlet_mvcPath=%2Fview.jsp&amp;_com_liferay_portlet_configuration_css_web_portlet_PortletConfigurationCSSPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_tiym__column1__1__menu__impostazioni_2d_look_2d_and_2d_feel" role="menuitem" data-title="Impostazioni Look and Feel" data-senna-off="true">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Impostazioni Look and Feel</span>
	
	
					</a>
				
				
		</li>
	
	


	























	
		<li class="portlet-export-import portlet-export-import-icon" role="presentation">
			
				
					<a href="http://localhost:8080/web/guest/precipitazioni?p_p_id=com_liferay_exportimport_web_portlet_ExportImportPortlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;_com_liferay_exportimport_web_portlet_ExportImportPortlet_mvcRenderCommandName=exportImport&amp;_com_liferay_exportimport_web_portlet_ExportImportPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_exportimport_web_portlet_ExportImportPortlet_returnToFullPageURL=%2Fprecipitazioni&amp;_com_liferay_exportimport_web_portlet_ExportImportPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;p_p_auth=rGNEIfff&amp;_com_liferay_exportimport_web_portlet_ExportImportPortlet_" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_tiym__column1__1__menu__esporta_2d__2f__2d_importa" onclick="Liferay.Portlet.openWindow({bodyCssClass: 'dialog-with-footer', namespace: '_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_', portlet: '#p_p_id_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_', portletId: 'com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC', title: 'Esporta / Importa', uri: 'http\x3a\x2f\x2flocalhost\x3a8080\x2fweb\x2fguest\x2fprecipitazioni\x3fp_p_id\x3dcom_liferay_exportimport_web_portlet_ExportImportPortlet\x26p_p_lifecycle\x3d0\x26p_p_state\x3dpop_up\x26_com_liferay_exportimport_web_portlet_ExportImportPortlet_mvcRenderCommandName\x3dexportImport\x26_com_liferay_exportimport_web_portlet_ExportImportPortlet_redirect\x3d\x252Fprecipitazioni\x26_com_liferay_exportimport_web_portlet_ExportImportPortlet_returnToFullPageURL\x3d\x252Fprecipitazioni\x26_com_liferay_exportimport_web_portlet_ExportImportPortlet_portletResource\x3dcom_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC\x26p_p_auth\x3drGNEIfff\x26_com_liferay_exportimport_web_portlet_ExportImportPortlet_'}); return false;" role="menuitem">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Esporta / Importa</span>
	
	
					</a>
				
				
		</li>
	
	
























	
		<li class="portlet-configuration portlet-configuration-icon" role="presentation">
			
				
					<a href="http://localhost:8080/web/guest/precipitazioni?p_p_id=com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_mvcPath=%2Fedit_configuration.jsp&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_returnToFullPageURL=%2Fprecipitazioni&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletConfiguration=true&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_resourcePrimKey=55203_LAYOUT_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_tiym__column1__1__menu__configurazione" onclick="Liferay.Portlet.openWindow({bodyCssClass: 'dialog-with-footer', destroyOnHide: true, namespace: '_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_', portlet: '#p_p_id_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_', portletId: 'com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC', title: '\u0043\u006f\u006e\u0066\u0069\u0067\u0075\u0072\u0061\u007a\u0069\u006f\u006e\u0065', uri: 'http\x3a\x2f\x2flocalhost\x3a8080\x2fweb\x2fguest\x2fprecipitazioni\x3fp_p_id\x3dcom_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet\x26p_p_lifecycle\x3d0\x26p_p_state\x3dpop_up\x26_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_mvcPath\x3d\x252Fedit_configuration\x2ejsp\x26_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_redirect\x3d\x252Fprecipitazioni\x26_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_returnToFullPageURL\x3d\x252Fprecipitazioni\x26_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletConfiguration\x3dtrue\x26_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletResource\x3dcom_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC\x26_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_resourcePrimKey\x3d55203_LAYOUT_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC'}); return false;" role="menuitem">
						


	
		
			
				
					<i class="cog"></i>
				
			
		
	



	
		<span class="taglib-text-icon">Configurazione</span>
	
	
					</a>
				
				
		</li>
	
	
























	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/web/guest/precipitazioni?p_p_id=com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_mvcPath=%2Fedit_permissions.jsp&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_returnToFullPageURL=&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletConfiguration=true&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_resourcePrimKey=55203_LAYOUT_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_tiym__column1__1__menu__permessi" role="menuitem" data-title="Permessi" data-senna-off="true">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Permessi</span>
	
	
					</a>
				
				
		</li>
	
	


	























	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/web/guest/precipitazioni?p_p_id=com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_mvcPath=%2Fedit_configuration_templates.jsp&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletConfiguration=true&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_tiym__column1__1__menu__modelli_2d_di_2d_configurazione" role="menuitem" data-title="Modelli di Configurazione" data-senna-off="true">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Modelli di Configurazione</span>
	
	
					</a>
				
				
		</li>
	
	


	























	
		<li class="item-remove portlet-close portlet-close-icon" role="presentation">
			
				
					<a href="/c/portal/update_layout?p_auth=3Mv8OpWF&amp;p_l_id=55203&amp;p_p_id=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;p_v_l_s_g_id=20181&amp;cmd=delete&amp;referer=%2Fc%2Fportal%2Flayout%3Fp_l_id%3D55203&amp;refresh=1" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_tiym__column1__1__menu__rimuovi" onclick="Liferay.Portlet.close('#p_p_id_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_'); return false;" role="menuitem">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Rimuovi</span>
	
	
					</a>
				
				
		</li>
	
	













		</ul>
	
</div>

					</menu>
			</header>


	<div class="portlet-content portlet-content-editable">

		<div class="autofit-float autofit-row portlet-header">
			<!-- Portlet Name hidden
			<div class="autofit-col autofit-col-expand">
				<h2 class="portlet-title-text">Strumenti Sezione Previsioni e Dati</h2>
			</div>
			-->
			<div class="autofit-col autofit-col-end">
				<div class="autofit-section">


















<div class="visible-interaction">
	













<div class="dropdown lfr-icon-menu btn btn-monospaced btn-sm">
	
		
			<a class="direction-left-side dropdown-toggle icon-monospaced " href="javascript:;" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_hjzj_column1_1_menu" title="Opzioni Contenuto Web">
				<span id="uvlz__column1__1"><svg class="lexicon-icon lexicon-icon-ellipsis-v" focusable="false" role="presentation" viewBox="0 0 512 512">
<path class="lexicon-icon-outline" d="M319 255.5c0 35.346-28.654 64-64 64s-64-28.654-64-64c0-35.346 28.654-64 64-64s64 28.654 64 64z"></path>
<path class="lexicon-icon-outline" d="M319 448c0 35.346-28.654 64-64 64s-64-28.654-64-64c0-35.346 28.654-64 64-64s64 28.654 64 64z"></path>
<path class="lexicon-icon-outline" d="M319 64c0 35.346-28.654 64-64 64s-64-28.654-64-64c0-35.346 28.654-64 64-64s64 28.654 64 64z"></path>
</svg></span>
			</a>
		
	

	

	
		
			<ul class="dropdown-menu dropdown-menu-left-side">
		
	
		

			

			






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/group/guest/~/control_panel/manage?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=normal&amp;p_p_mode=view&amp;refererPlid=55203&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fedit_article.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_articleId=910527&amp;_com_liferay_journal_web_portlet_JournalPortlet_version=1.0&amp;_com_liferay_journal_web_portlet_JournalPortlet_redirect=%2Fprecipitazioni&amp;_com_liferay_journal_web_portlet_JournalPortlet_referringPortletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;p_p_auth=XfO6O7wV" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editWebContentIcon" role="menuitem" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset" data-title="Strumenti Sezione Previsioni e Dati" data-destroyonhide="true">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Modifica Contenuto Web</span>
	
	
					</a>
				
				
		</li>
	
	


		

		

		
			

			






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/web/guest/precipitazioni?p_p_id=com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_mvcPath=%2Fedit_permissions.jsp&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletConfiguration=true&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_portletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_modelResource=com.liferay.journal.model.JournalArticle&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_modelResourceDescription=Strumenti+Sezione+Previsioni+e+Dati&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_resourceGroupId=20181&amp;_com_liferay_portlet_configuration_web_portlet_PortletConfigurationPortlet_resourcePrimKey=910529" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_hjzj__column1__1__menu__permissions" role="menuitem" data-title="Permessi" data-senna-off="true">
						


	
		
			
				
			
		
	



	
		<span class="taglib-text-icon">Permessi</span>
	
	
					</a>
				
				
		</li>
	
	


	

		

		

			

			






















	
		<li class="" role="presentation">
			
				
					<a href="http://localhost:8080/web/guest/precipitazioni?p_p_id=com_liferay_journal_web_portlet_JournalPortlet&amp;p_p_lifecycle=0&amp;p_p_state=pop_up&amp;_com_liferay_journal_web_portlet_JournalPortlet_mvcPath=%2Fview_article_history.jsp&amp;_com_liferay_journal_web_portlet_JournalPortlet_referringPortletResource=com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC&amp;_com_liferay_journal_web_portlet_JournalPortlet_groupId=20181&amp;_com_liferay_journal_web_portlet_JournalPortlet_articleId=910527&amp;_com_liferay_journal_web_portlet_JournalPortlet_showHeader=true&amp;p_p_auth=rcSj8XPn" target="_self" class=" lfr-icon-item taglib-icon" id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_basicViewHistoryIcon" role="menuitem" data-id="_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_PZXqtaQX5PDC_editAsset" data-title="Strumenti Sezione Previsioni e Dati" data-senna-off="true" data-destroyonhide="true">
						

		<span class="taglib-text-icon">Visualizza Cronologia</span>
	
	
					</a>
				
				
		</li>
	
		</ul>
	
</div>


</div>				</div>
			</div>
		</div>

		
			<div>
				


	<div>
						<div>
					
<div >
	<dl><dd><section class="u-background--cyan py-3 pb-5">
<div class="container">
<div class="row pt-3">
<div class="col-12">
<h2>Tutti gli strumenti della sezione Previsioni e Dati</h2>

<ul class="link-list link-list--row row">
	<li class="link-list-item col-12 col-md-3">
	<div class="link-list-span link-list__sub-link-list__heading"><span class="icon i-previsioni-meteo" title="Icona Previsioni Meteo"></span> Previsioni meteo</div>

	<ul class="link-list flex-column">
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/previsioni-regionali" target=""><span class="link-list__item-label">Previsioni regionali</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/previsioni-a-medio-termine"><span class="link-list__item-label">Previsioni a medio termine</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/animazione-meteo"><span class="link-list__item-label">Animazione meteo</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/animazione-mare"><span class="link-list__item-label">Animazione mare</span> </a></li>
	</ul>
	</li>
	<li class="link-list-item col-12 col-md-6">
	<div class="link-list-span link-list__sub-link-list__heading"><span class="icon i-dati-osservati" title="Icona Dati Osservati"></span> Dati osservati</div>

	<ul class="link-list link-list--md-two-col">
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/precipitazioni"><span class="link-list__item-label">Precipitazioni</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/livello-idrometrico"><span class="link-list__item-label">Livelli idrometrici</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/temperature"><span class="link-list__item-label">Temperature</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/vento"><span class="link-list__item-label">Vento</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/umidita"><span class="link-list__item-label">Umidit&#192; relativa</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/pressione"><span class="link-list__item-label">Pressione</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/cumulativa-6"><span class="link-list__item-label">Pioggia cumulata 6h</span> </a></li>
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/cumulativa-48"><span class="link-list__item-label">Pioggia cumulata 48h</span> </a></li>
	</ul>
	</li>
	<li class="link-list-item col-12 col-md-3">
	<div class="link-list-span link-list__sub-link-list__heading"><span class="icon i-radar-meteo" title="Icona Radar Meteo"></span> Radar meteo</div>

	<ul class="link-list flex-column">
		<li class="link-list-item"><a class="link-list-link " href="/web/guest/radar-meteo"><span class="link-list__item-label">Radar meteo: stima delle piogge</span> </a></li>
	</ul>
	</li>
</ul>
</div>
</div>
</div>
</section></dd></dl>
</div>

							
						</div>
					

	</div>

			</div>
		
	</div>
</section>




	</div>
</main>

<script>
 $(document).ready( function() {
 	console.log('ready');
 	var m =$("meta[property='og:title']").attr("content");
 	console.log(m);
 	$('#pageTitle').html(m);
 	$('#liPageTile').html(m);
 });
 
</script>
           