/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.parer.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.parer.model.DatiSpecificiInvio;
import it.eng.parer.model.DatiSpecificiInvioModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DatiSpecificiInvio service. Represents a row in the &quot;parer_DatiSpecificiInvio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DatiSpecificiInvioModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DatiSpecificiInvioImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see DatiSpecificiInvioImpl
 * @generated
 */
@JSON(strict = true)
public class DatiSpecificiInvioModelImpl
	extends BaseModelImpl<DatiSpecificiInvio>
	implements DatiSpecificiInvioModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dati specifici invio model instance should use the <code>DatiSpecificiInvio</code> interface instead.
	 */
	public static final String TABLE_NAME = "parer_DatiSpecificiInvio";

	public static final Object[][] TABLE_COLUMNS = {
		{"ID_INVIO", Types.BIGINT}, {"AMBIENTE", Types.VARCHAR},
		{"VERSIONE", Types.DOUBLE}, {"VERSATORE_ENTE", Types.VARCHAR},
		{"VERSATORE_USER_ID", Types.VARCHAR},
		{"VERSATORE_STRUTTURA", Types.VARCHAR},
		{"CHIAVE_NUMERO", Types.VARCHAR}, {"CHIAVE_ANNO", Types.BIGINT},
		{"CHIAVE_TIPO_REGISTRO", Types.VARCHAR},
		{"TIPOLOGIA_UNITA_DOCUMENTARIA", Types.VARCHAR},
		{"TIPO_CONSERVAZIONE", Types.VARCHAR},
		{"FORZA_ACCETTAZIONE", Types.VARCHAR},
		{"FORZA_CONSERVAZIONE", Types.VARCHAR},
		{"FORZA_COLLEGAMENTO", Types.VARCHAR},
		{"OGGETTO_UNITA_DOCUMENTARIA", Types.VARCHAR},
		{"DATA_UNITA_DOCUMENTARIA", Types.TIMESTAMP},
		{"VERSIONE_DATI_SPECIFICI", Types.DOUBLE},
		{"IDENTIFICATIVO_DATO_SPECIFICO", Types.VARCHAR},
		{"DATA_GENERAZIONE", Types.TIMESTAMP},
		{"NUM_SMS_GENERATI", Types.INTEGER}, {"NUM_SMS_INVIATI", Types.INTEGER},
		{"NUM_NOTIFICHE_RICEZIONE", Types.INTEGER},
		{"DENOMINAZIONE_APPLICATIVO", Types.VARCHAR},
		{"OGGETTO_MAIL", Types.VARCHAR}, {"TESTO_MAIL", Types.VARCHAR},
		{"COMPILATORE_ARPAE", Types.VARCHAR},
		{"COMPILATORE_PROTEZIONE_CIVILE", Types.VARCHAR},
		{"DATA_INIZIO_VALIDITA", Types.TIMESTAMP},
		{"DATA_FINE_VALIDITA", Types.TIMESTAMP},
		{"APPROVATORE_ARPAE", Types.VARCHAR},
		{"DATA_FIRMA_ARPAE", Types.TIMESTAMP},
		{"APPROVATORE_PROTEZIONE_CIVILE", Types.VARCHAR},
		{"DATA_FIRMA_PROTEZIONE_CIVILE", Types.TIMESTAMP},
		{"INVIO_RESPONSABILE_TERRITORIO", Types.VARCHAR},
		{"ID_DOCUMENTO_PRINCIPALE", Types.BIGINT},
		{"TIPO_DOCUMENTO", Types.VARCHAR}, {"TIPO_STRUTTURA", Types.VARCHAR},
		{"DENOMINAZIONE_SENSORE_RILEVAMENTO", Types.VARCHAR},
		{"REGOLA_ALLARME_ID", Types.VARCHAR},
		{"REGOLA_ALLARME_NOME", Types.VARCHAR},
		{"REGOLA_ALLARME_DESCRIZIONE", Types.VARCHAR},
		{"ESITO_INVIO", Types.VARCHAR}, {"userId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"data_invio", Types.TIMESTAMP}, {"data_risposta", Types.TIMESTAMP},
		{"CODICE_ESITO", Types.VARCHAR}, {"CODICE_ERRORE", Types.VARCHAR},
		{"MESG_ERRORE", Types.VARCHAR}, {"CODICE_TIPO_INVIO", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ID_INVIO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("AMBIENTE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("VERSIONE", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("VERSATORE_ENTE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("VERSATORE_USER_ID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("VERSATORE_STRUTTURA", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CHIAVE_NUMERO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CHIAVE_ANNO", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CHIAVE_TIPO_REGISTRO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TIPOLOGIA_UNITA_DOCUMENTARIA", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TIPO_CONSERVAZIONE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FORZA_ACCETTAZIONE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FORZA_CONSERVAZIONE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FORZA_COLLEGAMENTO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("OGGETTO_UNITA_DOCUMENTARIA", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DATA_UNITA_DOCUMENTARIA", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("VERSIONE_DATI_SPECIFICI", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("IDENTIFICATIVO_DATO_SPECIFICO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DATA_GENERAZIONE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("NUM_SMS_GENERATI", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("NUM_SMS_INVIATI", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("NUM_NOTIFICHE_RICEZIONE", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("DENOMINAZIONE_APPLICATIVO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("OGGETTO_MAIL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TESTO_MAIL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("COMPILATORE_ARPAE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("COMPILATORE_PROTEZIONE_CIVILE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DATA_INIZIO_VALIDITA", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DATA_FINE_VALIDITA", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("APPROVATORE_ARPAE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DATA_FIRMA_ARPAE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("APPROVATORE_PROTEZIONE_CIVILE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DATA_FIRMA_PROTEZIONE_CIVILE", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("INVIO_RESPONSABILE_TERRITORIO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ID_DOCUMENTO_PRINCIPALE", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("TIPO_DOCUMENTO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("TIPO_STRUTTURA", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put(
			"DENOMINAZIONE_SENSORE_RILEVAMENTO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("REGOLA_ALLARME_ID", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("REGOLA_ALLARME_NOME", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("REGOLA_ALLARME_DESCRIZIONE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ESITO_INVIO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("data_invio", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("data_risposta", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("CODICE_ESITO", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CODICE_ERRORE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("MESG_ERRORE", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("CODICE_TIPO_INVIO", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table parer_DatiSpecificiInvio (ID_INVIO LONG not null primary key,AMBIENTE VARCHAR(75) null,VERSIONE DOUBLE,VERSATORE_ENTE VARCHAR(75) null,VERSATORE_USER_ID VARCHAR(75) null,VERSATORE_STRUTTURA VARCHAR(75) null,CHIAVE_NUMERO VARCHAR(75) null,CHIAVE_ANNO LONG,CHIAVE_TIPO_REGISTRO VARCHAR(75) null,TIPOLOGIA_UNITA_DOCUMENTARIA VARCHAR(75) null,TIPO_CONSERVAZIONE VARCHAR(75) null,FORZA_ACCETTAZIONE VARCHAR(75) null,FORZA_CONSERVAZIONE VARCHAR(75) null,FORZA_COLLEGAMENTO VARCHAR(75) null,OGGETTO_UNITA_DOCUMENTARIA VARCHAR(75) null,DATA_UNITA_DOCUMENTARIA DATE null,VERSIONE_DATI_SPECIFICI DOUBLE,IDENTIFICATIVO_DATO_SPECIFICO VARCHAR(75) null,DATA_GENERAZIONE DATE null,NUM_SMS_GENERATI INTEGER,NUM_SMS_INVIATI INTEGER,NUM_NOTIFICHE_RICEZIONE INTEGER,DENOMINAZIONE_APPLICATIVO VARCHAR(75) null,OGGETTO_MAIL VARCHAR(75) null,TESTO_MAIL VARCHAR(75) null,COMPILATORE_ARPAE VARCHAR(75) null,COMPILATORE_PROTEZIONE_CIVILE VARCHAR(75) null,DATA_INIZIO_VALIDITA DATE null,DATA_FINE_VALIDITA DATE null,APPROVATORE_ARPAE VARCHAR(75) null,DATA_FIRMA_ARPAE DATE null,APPROVATORE_PROTEZIONE_CIVILE VARCHAR(75) null,DATA_FIRMA_PROTEZIONE_CIVILE DATE null,INVIO_RESPONSABILE_TERRITORIO VARCHAR(75) null,ID_DOCUMENTO_PRINCIPALE LONG,TIPO_DOCUMENTO VARCHAR(75) null,TIPO_STRUTTURA VARCHAR(75) null,DENOMINAZIONE_SENSORE_RILEVAMENTO VARCHAR(75) null,REGOLA_ALLARME_ID VARCHAR(75) null,REGOLA_ALLARME_NOME VARCHAR(75) null,REGOLA_ALLARME_DESCRIZIONE VARCHAR(75) null,ESITO_INVIO VARCHAR(75) null,userId LONG,companyId LONG,groupId LONG,data_invio DATE null,data_risposta DATE null,CODICE_ESITO VARCHAR(75) null,CODICE_ERRORE VARCHAR(75) null,MESG_ERRORE VARCHAR(75) null,CODICE_TIPO_INVIO VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table parer_DatiSpecificiInvio";

	public static final String ORDER_BY_JPQL =
		" ORDER BY datiSpecificiInvio.ID_INVIO ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY parer_DatiSpecificiInvio.ID_INVIO ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ESITO_INVIO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_INVIO_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public DatiSpecificiInvioModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ID_INVIO;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setID_INVIO(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ID_INVIO;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DatiSpecificiInvio.class;
	}

	@Override
	public String getModelClassName() {
		return DatiSpecificiInvio.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DatiSpecificiInvio, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DatiSpecificiInvio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DatiSpecificiInvio, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DatiSpecificiInvio)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DatiSpecificiInvio, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DatiSpecificiInvio, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DatiSpecificiInvio)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DatiSpecificiInvio, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DatiSpecificiInvio, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<DatiSpecificiInvio, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<DatiSpecificiInvio, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<DatiSpecificiInvio, Object>>();

			attributeGetterFunctions.put(
				"ID_INVIO", DatiSpecificiInvio::getID_INVIO);
			attributeGetterFunctions.put(
				"AMBIENTE", DatiSpecificiInvio::getAMBIENTE);
			attributeGetterFunctions.put(
				"VERSIONE", DatiSpecificiInvio::getVERSIONE);
			attributeGetterFunctions.put(
				"VERSATORE_ENTE", DatiSpecificiInvio::getVERSATORE_ENTE);
			attributeGetterFunctions.put(
				"VERSATORE_USER_ID", DatiSpecificiInvio::getVERSATORE_USER_ID);
			attributeGetterFunctions.put(
				"VERSATORE_STRUTTURA",
				DatiSpecificiInvio::getVERSATORE_STRUTTURA);
			attributeGetterFunctions.put(
				"CHIAVE_NUMERO", DatiSpecificiInvio::getCHIAVE_NUMERO);
			attributeGetterFunctions.put(
				"CHIAVE_ANNO", DatiSpecificiInvio::getCHIAVE_ANNO);
			attributeGetterFunctions.put(
				"CHIAVE_TIPO_REGISTRO",
				DatiSpecificiInvio::getCHIAVE_TIPO_REGISTRO);
			attributeGetterFunctions.put(
				"TIPOLOGIA_UNITA_DOCUMENTARIA",
				DatiSpecificiInvio::getTIPOLOGIA_UNITA_DOCUMENTARIA);
			attributeGetterFunctions.put(
				"TIPO_CONSERVAZIONE",
				DatiSpecificiInvio::getTIPO_CONSERVAZIONE);
			attributeGetterFunctions.put(
				"FORZA_ACCETTAZIONE",
				DatiSpecificiInvio::getFORZA_ACCETTAZIONE);
			attributeGetterFunctions.put(
				"FORZA_CONSERVAZIONE",
				DatiSpecificiInvio::getFORZA_CONSERVAZIONE);
			attributeGetterFunctions.put(
				"FORZA_COLLEGAMENTO",
				DatiSpecificiInvio::getFORZA_COLLEGAMENTO);
			attributeGetterFunctions.put(
				"OGGETTO_UNITA_DOCUMENTARIA",
				DatiSpecificiInvio::getOGGETTO_UNITA_DOCUMENTARIA);
			attributeGetterFunctions.put(
				"DATA_UNITA_DOCUMENTARIA",
				DatiSpecificiInvio::getDATA_UNITA_DOCUMENTARIA);
			attributeGetterFunctions.put(
				"VERSIONE_DATI_SPECIFICI",
				DatiSpecificiInvio::getVERSIONE_DATI_SPECIFICI);
			attributeGetterFunctions.put(
				"IDENTIFICATIVO_DATO_SPECIFICO",
				DatiSpecificiInvio::getIDENTIFICATIVO_DATO_SPECIFICO);
			attributeGetterFunctions.put(
				"DATA_GENERAZIONE", DatiSpecificiInvio::getDATA_GENERAZIONE);
			attributeGetterFunctions.put(
				"NUM_SMS_GENERATI", DatiSpecificiInvio::getNUM_SMS_GENERATI);
			attributeGetterFunctions.put(
				"NUM_SMS_INVIATI", DatiSpecificiInvio::getNUM_SMS_INVIATI);
			attributeGetterFunctions.put(
				"NUM_NOTIFICHE_RICEZIONE",
				DatiSpecificiInvio::getNUM_NOTIFICHE_RICEZIONE);
			attributeGetterFunctions.put(
				"DENOMINAZIONE_APPLICATIVO",
				DatiSpecificiInvio::getDENOMINAZIONE_APPLICATIVO);
			attributeGetterFunctions.put(
				"OGGETTO_MAIL", DatiSpecificiInvio::getOGGETTO_MAIL);
			attributeGetterFunctions.put(
				"TESTO_MAIL", DatiSpecificiInvio::getTESTO_MAIL);
			attributeGetterFunctions.put(
				"COMPILATORE_ARPAE", DatiSpecificiInvio::getCOMPILATORE_ARPAE);
			attributeGetterFunctions.put(
				"COMPILATORE_PROTEZIONE_CIVILE",
				DatiSpecificiInvio::getCOMPILATORE_PROTEZIONE_CIVILE);
			attributeGetterFunctions.put(
				"DATA_INIZIO_VALIDITA",
				DatiSpecificiInvio::getDATA_INIZIO_VALIDITA);
			attributeGetterFunctions.put(
				"DATA_FINE_VALIDITA",
				DatiSpecificiInvio::getDATA_FINE_VALIDITA);
			attributeGetterFunctions.put(
				"APPROVATORE_ARPAE", DatiSpecificiInvio::getAPPROVATORE_ARPAE);
			attributeGetterFunctions.put(
				"DATA_FIRMA_ARPAE", DatiSpecificiInvio::getDATA_FIRMA_ARPAE);
			attributeGetterFunctions.put(
				"APPROVATORE_PROTEZIONE_CIVILE",
				DatiSpecificiInvio::getAPPROVATORE_PROTEZIONE_CIVILE);
			attributeGetterFunctions.put(
				"DATA_FIRMA_PROTEZIONE_CIVILE",
				DatiSpecificiInvio::getDATA_FIRMA_PROTEZIONE_CIVILE);
			attributeGetterFunctions.put(
				"INVIO_RESPONSABILE_TERRITORIO",
				DatiSpecificiInvio::getINVIO_RESPONSABILE_TERRITORIO);
			attributeGetterFunctions.put(
				"ID_DOCUMENTO_PRINCIPALE",
				DatiSpecificiInvio::getID_DOCUMENTO_PRINCIPALE);
			attributeGetterFunctions.put(
				"TIPO_DOCUMENTO", DatiSpecificiInvio::getTIPO_DOCUMENTO);
			attributeGetterFunctions.put(
				"TIPO_STRUTTURA", DatiSpecificiInvio::getTIPO_STRUTTURA);
			attributeGetterFunctions.put(
				"DENOMINAZIONE_SENSORE_RILEVAMENTO",
				DatiSpecificiInvio::getDENOMINAZIONE_SENSORE_RILEVAMENTO);
			attributeGetterFunctions.put(
				"REGOLA_ALLARME_ID", DatiSpecificiInvio::getREGOLA_ALLARME_ID);
			attributeGetterFunctions.put(
				"REGOLA_ALLARME_NOME",
				DatiSpecificiInvio::getREGOLA_ALLARME_NOME);
			attributeGetterFunctions.put(
				"REGOLA_ALLARME_DESCRIZIONE",
				DatiSpecificiInvio::getREGOLA_ALLARME_DESCRIZIONE);
			attributeGetterFunctions.put(
				"ESITO_INVIO", DatiSpecificiInvio::getESITO_INVIO);
			attributeGetterFunctions.put(
				"userId", DatiSpecificiInvio::getUserId);
			attributeGetterFunctions.put(
				"companyId", DatiSpecificiInvio::getCompanyId);
			attributeGetterFunctions.put(
				"groupId", DatiSpecificiInvio::getGroupId);
			attributeGetterFunctions.put(
				"data_invio", DatiSpecificiInvio::getData_invio);
			attributeGetterFunctions.put(
				"data_risposta", DatiSpecificiInvio::getData_risposta);
			attributeGetterFunctions.put(
				"CODICE_ESITO", DatiSpecificiInvio::getCODICE_ESITO);
			attributeGetterFunctions.put(
				"CODICE_ERRORE", DatiSpecificiInvio::getCODICE_ERRORE);
			attributeGetterFunctions.put(
				"MESG_ERRORE", DatiSpecificiInvio::getMESG_ERRORE);
			attributeGetterFunctions.put(
				"CODICE_TIPO_INVIO", DatiSpecificiInvio::getCODICE_TIPO_INVIO);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<DatiSpecificiInvio, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<DatiSpecificiInvio, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<DatiSpecificiInvio, ?>>();

			attributeSetterBiConsumers.put(
				"ID_INVIO",
				(BiConsumer<DatiSpecificiInvio, Long>)
					DatiSpecificiInvio::setID_INVIO);
			attributeSetterBiConsumers.put(
				"AMBIENTE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setAMBIENTE);
			attributeSetterBiConsumers.put(
				"VERSIONE",
				(BiConsumer<DatiSpecificiInvio, Double>)
					DatiSpecificiInvio::setVERSIONE);
			attributeSetterBiConsumers.put(
				"VERSATORE_ENTE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setVERSATORE_ENTE);
			attributeSetterBiConsumers.put(
				"VERSATORE_USER_ID",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setVERSATORE_USER_ID);
			attributeSetterBiConsumers.put(
				"VERSATORE_STRUTTURA",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setVERSATORE_STRUTTURA);
			attributeSetterBiConsumers.put(
				"CHIAVE_NUMERO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setCHIAVE_NUMERO);
			attributeSetterBiConsumers.put(
				"CHIAVE_ANNO",
				(BiConsumer<DatiSpecificiInvio, Long>)
					DatiSpecificiInvio::setCHIAVE_ANNO);
			attributeSetterBiConsumers.put(
				"CHIAVE_TIPO_REGISTRO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setCHIAVE_TIPO_REGISTRO);
			attributeSetterBiConsumers.put(
				"TIPOLOGIA_UNITA_DOCUMENTARIA",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setTIPOLOGIA_UNITA_DOCUMENTARIA);
			attributeSetterBiConsumers.put(
				"TIPO_CONSERVAZIONE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setTIPO_CONSERVAZIONE);
			attributeSetterBiConsumers.put(
				"FORZA_ACCETTAZIONE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setFORZA_ACCETTAZIONE);
			attributeSetterBiConsumers.put(
				"FORZA_CONSERVAZIONE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setFORZA_CONSERVAZIONE);
			attributeSetterBiConsumers.put(
				"FORZA_COLLEGAMENTO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setFORZA_COLLEGAMENTO);
			attributeSetterBiConsumers.put(
				"OGGETTO_UNITA_DOCUMENTARIA",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setOGGETTO_UNITA_DOCUMENTARIA);
			attributeSetterBiConsumers.put(
				"DATA_UNITA_DOCUMENTARIA",
				(BiConsumer<DatiSpecificiInvio, Date>)
					DatiSpecificiInvio::setDATA_UNITA_DOCUMENTARIA);
			attributeSetterBiConsumers.put(
				"VERSIONE_DATI_SPECIFICI",
				(BiConsumer<DatiSpecificiInvio, Double>)
					DatiSpecificiInvio::setVERSIONE_DATI_SPECIFICI);
			attributeSetterBiConsumers.put(
				"IDENTIFICATIVO_DATO_SPECIFICO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setIDENTIFICATIVO_DATO_SPECIFICO);
			attributeSetterBiConsumers.put(
				"DATA_GENERAZIONE",
				(BiConsumer<DatiSpecificiInvio, Date>)
					DatiSpecificiInvio::setDATA_GENERAZIONE);
			attributeSetterBiConsumers.put(
				"NUM_SMS_GENERATI",
				(BiConsumer<DatiSpecificiInvio, Integer>)
					DatiSpecificiInvio::setNUM_SMS_GENERATI);
			attributeSetterBiConsumers.put(
				"NUM_SMS_INVIATI",
				(BiConsumer<DatiSpecificiInvio, Integer>)
					DatiSpecificiInvio::setNUM_SMS_INVIATI);
			attributeSetterBiConsumers.put(
				"NUM_NOTIFICHE_RICEZIONE",
				(BiConsumer<DatiSpecificiInvio, Integer>)
					DatiSpecificiInvio::setNUM_NOTIFICHE_RICEZIONE);
			attributeSetterBiConsumers.put(
				"DENOMINAZIONE_APPLICATIVO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setDENOMINAZIONE_APPLICATIVO);
			attributeSetterBiConsumers.put(
				"OGGETTO_MAIL",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setOGGETTO_MAIL);
			attributeSetterBiConsumers.put(
				"TESTO_MAIL",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setTESTO_MAIL);
			attributeSetterBiConsumers.put(
				"COMPILATORE_ARPAE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setCOMPILATORE_ARPAE);
			attributeSetterBiConsumers.put(
				"COMPILATORE_PROTEZIONE_CIVILE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setCOMPILATORE_PROTEZIONE_CIVILE);
			attributeSetterBiConsumers.put(
				"DATA_INIZIO_VALIDITA",
				(BiConsumer<DatiSpecificiInvio, Date>)
					DatiSpecificiInvio::setDATA_INIZIO_VALIDITA);
			attributeSetterBiConsumers.put(
				"DATA_FINE_VALIDITA",
				(BiConsumer<DatiSpecificiInvio, Date>)
					DatiSpecificiInvio::setDATA_FINE_VALIDITA);
			attributeSetterBiConsumers.put(
				"APPROVATORE_ARPAE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setAPPROVATORE_ARPAE);
			attributeSetterBiConsumers.put(
				"DATA_FIRMA_ARPAE",
				(BiConsumer<DatiSpecificiInvio, Date>)
					DatiSpecificiInvio::setDATA_FIRMA_ARPAE);
			attributeSetterBiConsumers.put(
				"APPROVATORE_PROTEZIONE_CIVILE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setAPPROVATORE_PROTEZIONE_CIVILE);
			attributeSetterBiConsumers.put(
				"DATA_FIRMA_PROTEZIONE_CIVILE",
				(BiConsumer<DatiSpecificiInvio, Date>)
					DatiSpecificiInvio::setDATA_FIRMA_PROTEZIONE_CIVILE);
			attributeSetterBiConsumers.put(
				"INVIO_RESPONSABILE_TERRITORIO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setINVIO_RESPONSABILE_TERRITORIO);
			attributeSetterBiConsumers.put(
				"ID_DOCUMENTO_PRINCIPALE",
				(BiConsumer<DatiSpecificiInvio, Long>)
					DatiSpecificiInvio::setID_DOCUMENTO_PRINCIPALE);
			attributeSetterBiConsumers.put(
				"TIPO_DOCUMENTO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setTIPO_DOCUMENTO);
			attributeSetterBiConsumers.put(
				"TIPO_STRUTTURA",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setTIPO_STRUTTURA);
			attributeSetterBiConsumers.put(
				"DENOMINAZIONE_SENSORE_RILEVAMENTO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setDENOMINAZIONE_SENSORE_RILEVAMENTO);
			attributeSetterBiConsumers.put(
				"REGOLA_ALLARME_ID",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setREGOLA_ALLARME_ID);
			attributeSetterBiConsumers.put(
				"REGOLA_ALLARME_NOME",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setREGOLA_ALLARME_NOME);
			attributeSetterBiConsumers.put(
				"REGOLA_ALLARME_DESCRIZIONE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setREGOLA_ALLARME_DESCRIZIONE);
			attributeSetterBiConsumers.put(
				"ESITO_INVIO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setESITO_INVIO);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<DatiSpecificiInvio, Long>)
					DatiSpecificiInvio::setUserId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<DatiSpecificiInvio, Long>)
					DatiSpecificiInvio::setCompanyId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<DatiSpecificiInvio, Long>)
					DatiSpecificiInvio::setGroupId);
			attributeSetterBiConsumers.put(
				"data_invio",
				(BiConsumer<DatiSpecificiInvio, Date>)
					DatiSpecificiInvio::setData_invio);
			attributeSetterBiConsumers.put(
				"data_risposta",
				(BiConsumer<DatiSpecificiInvio, Date>)
					DatiSpecificiInvio::setData_risposta);
			attributeSetterBiConsumers.put(
				"CODICE_ESITO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setCODICE_ESITO);
			attributeSetterBiConsumers.put(
				"CODICE_ERRORE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setCODICE_ERRORE);
			attributeSetterBiConsumers.put(
				"MESG_ERRORE",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setMESG_ERRORE);
			attributeSetterBiConsumers.put(
				"CODICE_TIPO_INVIO",
				(BiConsumer<DatiSpecificiInvio, String>)
					DatiSpecificiInvio::setCODICE_TIPO_INVIO);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getID_INVIO() {
		return _ID_INVIO;
	}

	@Override
	public void setID_INVIO(long ID_INVIO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ID_INVIO = ID_INVIO;
	}

	@JSON
	@Override
	public String getAMBIENTE() {
		if (_AMBIENTE == null) {
			return "";
		}
		else {
			return _AMBIENTE;
		}
	}

	@Override
	public void setAMBIENTE(String AMBIENTE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_AMBIENTE = AMBIENTE;
	}

	@JSON
	@Override
	public double getVERSIONE() {
		return _VERSIONE;
	}

	@Override
	public void setVERSIONE(double VERSIONE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_VERSIONE = VERSIONE;
	}

	@JSON
	@Override
	public String getVERSATORE_ENTE() {
		if (_VERSATORE_ENTE == null) {
			return "";
		}
		else {
			return _VERSATORE_ENTE;
		}
	}

	@Override
	public void setVERSATORE_ENTE(String VERSATORE_ENTE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_VERSATORE_ENTE = VERSATORE_ENTE;
	}

	@JSON
	@Override
	public String getVERSATORE_USER_ID() {
		if (_VERSATORE_USER_ID == null) {
			return "";
		}
		else {
			return _VERSATORE_USER_ID;
		}
	}

	@Override
	public void setVERSATORE_USER_ID(String VERSATORE_USER_ID) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_VERSATORE_USER_ID = VERSATORE_USER_ID;
	}

	@JSON
	@Override
	public String getVERSATORE_STRUTTURA() {
		if (_VERSATORE_STRUTTURA == null) {
			return "";
		}
		else {
			return _VERSATORE_STRUTTURA;
		}
	}

	@Override
	public void setVERSATORE_STRUTTURA(String VERSATORE_STRUTTURA) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_VERSATORE_STRUTTURA = VERSATORE_STRUTTURA;
	}

	@JSON
	@Override
	public String getCHIAVE_NUMERO() {
		if (_CHIAVE_NUMERO == null) {
			return "";
		}
		else {
			return _CHIAVE_NUMERO;
		}
	}

	@Override
	public void setCHIAVE_NUMERO(String CHIAVE_NUMERO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CHIAVE_NUMERO = CHIAVE_NUMERO;
	}

	@JSON
	@Override
	public long getCHIAVE_ANNO() {
		return _CHIAVE_ANNO;
	}

	@Override
	public void setCHIAVE_ANNO(long CHIAVE_ANNO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CHIAVE_ANNO = CHIAVE_ANNO;
	}

	@JSON
	@Override
	public String getCHIAVE_TIPO_REGISTRO() {
		if (_CHIAVE_TIPO_REGISTRO == null) {
			return "";
		}
		else {
			return _CHIAVE_TIPO_REGISTRO;
		}
	}

	@Override
	public void setCHIAVE_TIPO_REGISTRO(String CHIAVE_TIPO_REGISTRO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CHIAVE_TIPO_REGISTRO = CHIAVE_TIPO_REGISTRO;
	}

	@JSON
	@Override
	public String getTIPOLOGIA_UNITA_DOCUMENTARIA() {
		if (_TIPOLOGIA_UNITA_DOCUMENTARIA == null) {
			return "";
		}
		else {
			return _TIPOLOGIA_UNITA_DOCUMENTARIA;
		}
	}

	@Override
	public void setTIPOLOGIA_UNITA_DOCUMENTARIA(
		String TIPOLOGIA_UNITA_DOCUMENTARIA) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TIPOLOGIA_UNITA_DOCUMENTARIA = TIPOLOGIA_UNITA_DOCUMENTARIA;
	}

	@JSON
	@Override
	public String getTIPO_CONSERVAZIONE() {
		if (_TIPO_CONSERVAZIONE == null) {
			return "";
		}
		else {
			return _TIPO_CONSERVAZIONE;
		}
	}

	@Override
	public void setTIPO_CONSERVAZIONE(String TIPO_CONSERVAZIONE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TIPO_CONSERVAZIONE = TIPO_CONSERVAZIONE;
	}

	@JSON
	@Override
	public String getFORZA_ACCETTAZIONE() {
		if (_FORZA_ACCETTAZIONE == null) {
			return "";
		}
		else {
			return _FORZA_ACCETTAZIONE;
		}
	}

	@Override
	public void setFORZA_ACCETTAZIONE(String FORZA_ACCETTAZIONE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FORZA_ACCETTAZIONE = FORZA_ACCETTAZIONE;
	}

	@JSON
	@Override
	public String getFORZA_CONSERVAZIONE() {
		if (_FORZA_CONSERVAZIONE == null) {
			return "";
		}
		else {
			return _FORZA_CONSERVAZIONE;
		}
	}

	@Override
	public void setFORZA_CONSERVAZIONE(String FORZA_CONSERVAZIONE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FORZA_CONSERVAZIONE = FORZA_CONSERVAZIONE;
	}

	@JSON
	@Override
	public String getFORZA_COLLEGAMENTO() {
		if (_FORZA_COLLEGAMENTO == null) {
			return "";
		}
		else {
			return _FORZA_COLLEGAMENTO;
		}
	}

	@Override
	public void setFORZA_COLLEGAMENTO(String FORZA_COLLEGAMENTO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FORZA_COLLEGAMENTO = FORZA_COLLEGAMENTO;
	}

	@JSON
	@Override
	public String getOGGETTO_UNITA_DOCUMENTARIA() {
		if (_OGGETTO_UNITA_DOCUMENTARIA == null) {
			return "";
		}
		else {
			return _OGGETTO_UNITA_DOCUMENTARIA;
		}
	}

	@Override
	public void setOGGETTO_UNITA_DOCUMENTARIA(
		String OGGETTO_UNITA_DOCUMENTARIA) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_OGGETTO_UNITA_DOCUMENTARIA = OGGETTO_UNITA_DOCUMENTARIA;
	}

	@JSON
	@Override
	public Date getDATA_UNITA_DOCUMENTARIA() {
		return _DATA_UNITA_DOCUMENTARIA;
	}

	@Override
	public void setDATA_UNITA_DOCUMENTARIA(Date DATA_UNITA_DOCUMENTARIA) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DATA_UNITA_DOCUMENTARIA = DATA_UNITA_DOCUMENTARIA;
	}

	@JSON
	@Override
	public double getVERSIONE_DATI_SPECIFICI() {
		return _VERSIONE_DATI_SPECIFICI;
	}

	@Override
	public void setVERSIONE_DATI_SPECIFICI(double VERSIONE_DATI_SPECIFICI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_VERSIONE_DATI_SPECIFICI = VERSIONE_DATI_SPECIFICI;
	}

	@JSON
	@Override
	public String getIDENTIFICATIVO_DATO_SPECIFICO() {
		if (_IDENTIFICATIVO_DATO_SPECIFICO == null) {
			return "";
		}
		else {
			return _IDENTIFICATIVO_DATO_SPECIFICO;
		}
	}

	@Override
	public void setIDENTIFICATIVO_DATO_SPECIFICO(
		String IDENTIFICATIVO_DATO_SPECIFICO) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_IDENTIFICATIVO_DATO_SPECIFICO = IDENTIFICATIVO_DATO_SPECIFICO;
	}

	@JSON
	@Override
	public Date getDATA_GENERAZIONE() {
		return _DATA_GENERAZIONE;
	}

	@Override
	public void setDATA_GENERAZIONE(Date DATA_GENERAZIONE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DATA_GENERAZIONE = DATA_GENERAZIONE;
	}

	@JSON
	@Override
	public int getNUM_SMS_GENERATI() {
		return _NUM_SMS_GENERATI;
	}

	@Override
	public void setNUM_SMS_GENERATI(int NUM_SMS_GENERATI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NUM_SMS_GENERATI = NUM_SMS_GENERATI;
	}

	@JSON
	@Override
	public int getNUM_SMS_INVIATI() {
		return _NUM_SMS_INVIATI;
	}

	@Override
	public void setNUM_SMS_INVIATI(int NUM_SMS_INVIATI) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NUM_SMS_INVIATI = NUM_SMS_INVIATI;
	}

	@JSON
	@Override
	public int getNUM_NOTIFICHE_RICEZIONE() {
		return _NUM_NOTIFICHE_RICEZIONE;
	}

	@Override
	public void setNUM_NOTIFICHE_RICEZIONE(int NUM_NOTIFICHE_RICEZIONE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_NUM_NOTIFICHE_RICEZIONE = NUM_NOTIFICHE_RICEZIONE;
	}

	@JSON
	@Override
	public String getDENOMINAZIONE_APPLICATIVO() {
		if (_DENOMINAZIONE_APPLICATIVO == null) {
			return "";
		}
		else {
			return _DENOMINAZIONE_APPLICATIVO;
		}
	}

	@Override
	public void setDENOMINAZIONE_APPLICATIVO(String DENOMINAZIONE_APPLICATIVO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DENOMINAZIONE_APPLICATIVO = DENOMINAZIONE_APPLICATIVO;
	}

	@JSON
	@Override
	public String getOGGETTO_MAIL() {
		if (_OGGETTO_MAIL == null) {
			return "";
		}
		else {
			return _OGGETTO_MAIL;
		}
	}

	@Override
	public void setOGGETTO_MAIL(String OGGETTO_MAIL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_OGGETTO_MAIL = OGGETTO_MAIL;
	}

	@JSON
	@Override
	public String getTESTO_MAIL() {
		if (_TESTO_MAIL == null) {
			return "";
		}
		else {
			return _TESTO_MAIL;
		}
	}

	@Override
	public void setTESTO_MAIL(String TESTO_MAIL) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TESTO_MAIL = TESTO_MAIL;
	}

	@JSON
	@Override
	public String getCOMPILATORE_ARPAE() {
		if (_COMPILATORE_ARPAE == null) {
			return "";
		}
		else {
			return _COMPILATORE_ARPAE;
		}
	}

	@Override
	public void setCOMPILATORE_ARPAE(String COMPILATORE_ARPAE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_COMPILATORE_ARPAE = COMPILATORE_ARPAE;
	}

	@JSON
	@Override
	public String getCOMPILATORE_PROTEZIONE_CIVILE() {
		if (_COMPILATORE_PROTEZIONE_CIVILE == null) {
			return "";
		}
		else {
			return _COMPILATORE_PROTEZIONE_CIVILE;
		}
	}

	@Override
	public void setCOMPILATORE_PROTEZIONE_CIVILE(
		String COMPILATORE_PROTEZIONE_CIVILE) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_COMPILATORE_PROTEZIONE_CIVILE = COMPILATORE_PROTEZIONE_CIVILE;
	}

	@JSON
	@Override
	public Date getDATA_INIZIO_VALIDITA() {
		return _DATA_INIZIO_VALIDITA;
	}

	@Override
	public void setDATA_INIZIO_VALIDITA(Date DATA_INIZIO_VALIDITA) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DATA_INIZIO_VALIDITA = DATA_INIZIO_VALIDITA;
	}

	@JSON
	@Override
	public Date getDATA_FINE_VALIDITA() {
		return _DATA_FINE_VALIDITA;
	}

	@Override
	public void setDATA_FINE_VALIDITA(Date DATA_FINE_VALIDITA) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DATA_FINE_VALIDITA = DATA_FINE_VALIDITA;
	}

	@JSON
	@Override
	public String getAPPROVATORE_ARPAE() {
		if (_APPROVATORE_ARPAE == null) {
			return "";
		}
		else {
			return _APPROVATORE_ARPAE;
		}
	}

	@Override
	public void setAPPROVATORE_ARPAE(String APPROVATORE_ARPAE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_APPROVATORE_ARPAE = APPROVATORE_ARPAE;
	}

	@JSON
	@Override
	public Date getDATA_FIRMA_ARPAE() {
		return _DATA_FIRMA_ARPAE;
	}

	@Override
	public void setDATA_FIRMA_ARPAE(Date DATA_FIRMA_ARPAE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DATA_FIRMA_ARPAE = DATA_FIRMA_ARPAE;
	}

	@JSON
	@Override
	public String getAPPROVATORE_PROTEZIONE_CIVILE() {
		if (_APPROVATORE_PROTEZIONE_CIVILE == null) {
			return "";
		}
		else {
			return _APPROVATORE_PROTEZIONE_CIVILE;
		}
	}

	@Override
	public void setAPPROVATORE_PROTEZIONE_CIVILE(
		String APPROVATORE_PROTEZIONE_CIVILE) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_APPROVATORE_PROTEZIONE_CIVILE = APPROVATORE_PROTEZIONE_CIVILE;
	}

	@JSON
	@Override
	public Date getDATA_FIRMA_PROTEZIONE_CIVILE() {
		return _DATA_FIRMA_PROTEZIONE_CIVILE;
	}

	@Override
	public void setDATA_FIRMA_PROTEZIONE_CIVILE(
		Date DATA_FIRMA_PROTEZIONE_CIVILE) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DATA_FIRMA_PROTEZIONE_CIVILE = DATA_FIRMA_PROTEZIONE_CIVILE;
	}

	@JSON
	@Override
	public String getINVIO_RESPONSABILE_TERRITORIO() {
		if (_INVIO_RESPONSABILE_TERRITORIO == null) {
			return "";
		}
		else {
			return _INVIO_RESPONSABILE_TERRITORIO;
		}
	}

	@Override
	public void setINVIO_RESPONSABILE_TERRITORIO(
		String INVIO_RESPONSABILE_TERRITORIO) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_INVIO_RESPONSABILE_TERRITORIO = INVIO_RESPONSABILE_TERRITORIO;
	}

	@JSON
	@Override
	public long getID_DOCUMENTO_PRINCIPALE() {
		return _ID_DOCUMENTO_PRINCIPALE;
	}

	@Override
	public void setID_DOCUMENTO_PRINCIPALE(long ID_DOCUMENTO_PRINCIPALE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ID_DOCUMENTO_PRINCIPALE = ID_DOCUMENTO_PRINCIPALE;
	}

	@JSON
	@Override
	public String getTIPO_DOCUMENTO() {
		if (_TIPO_DOCUMENTO == null) {
			return "";
		}
		else {
			return _TIPO_DOCUMENTO;
		}
	}

	@Override
	public void setTIPO_DOCUMENTO(String TIPO_DOCUMENTO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TIPO_DOCUMENTO = TIPO_DOCUMENTO;
	}

	@JSON
	@Override
	public String getTIPO_STRUTTURA() {
		if (_TIPO_STRUTTURA == null) {
			return "";
		}
		else {
			return _TIPO_STRUTTURA;
		}
	}

	@Override
	public void setTIPO_STRUTTURA(String TIPO_STRUTTURA) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_TIPO_STRUTTURA = TIPO_STRUTTURA;
	}

	@JSON
	@Override
	public String getDENOMINAZIONE_SENSORE_RILEVAMENTO() {
		if (_DENOMINAZIONE_SENSORE_RILEVAMENTO == null) {
			return "";
		}
		else {
			return _DENOMINAZIONE_SENSORE_RILEVAMENTO;
		}
	}

	@Override
	public void setDENOMINAZIONE_SENSORE_RILEVAMENTO(
		String DENOMINAZIONE_SENSORE_RILEVAMENTO) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DENOMINAZIONE_SENSORE_RILEVAMENTO = DENOMINAZIONE_SENSORE_RILEVAMENTO;
	}

	@JSON
	@Override
	public String getREGOLA_ALLARME_ID() {
		if (_REGOLA_ALLARME_ID == null) {
			return "";
		}
		else {
			return _REGOLA_ALLARME_ID;
		}
	}

	@Override
	public void setREGOLA_ALLARME_ID(String REGOLA_ALLARME_ID) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_REGOLA_ALLARME_ID = REGOLA_ALLARME_ID;
	}

	@JSON
	@Override
	public String getREGOLA_ALLARME_NOME() {
		if (_REGOLA_ALLARME_NOME == null) {
			return "";
		}
		else {
			return _REGOLA_ALLARME_NOME;
		}
	}

	@Override
	public void setREGOLA_ALLARME_NOME(String REGOLA_ALLARME_NOME) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_REGOLA_ALLARME_NOME = REGOLA_ALLARME_NOME;
	}

	@JSON
	@Override
	public String getREGOLA_ALLARME_DESCRIZIONE() {
		if (_REGOLA_ALLARME_DESCRIZIONE == null) {
			return "";
		}
		else {
			return _REGOLA_ALLARME_DESCRIZIONE;
		}
	}

	@Override
	public void setREGOLA_ALLARME_DESCRIZIONE(
		String REGOLA_ALLARME_DESCRIZIONE) {

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_REGOLA_ALLARME_DESCRIZIONE = REGOLA_ALLARME_DESCRIZIONE;
	}

	@JSON
	@Override
	public String getESITO_INVIO() {
		if (_ESITO_INVIO == null) {
			return "";
		}
		else {
			return _ESITO_INVIO;
		}
	}

	@Override
	public void setESITO_INVIO(String ESITO_INVIO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ESITO_INVIO = ESITO_INVIO;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalESITO_INVIO() {
		return getColumnOriginalValue("ESITO_INVIO");
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public Date getData_invio() {
		return _data_invio;
	}

	@Override
	public void setData_invio(Date data_invio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_data_invio = data_invio;
	}

	@JSON
	@Override
	public Date getData_risposta() {
		return _data_risposta;
	}

	@Override
	public void setData_risposta(Date data_risposta) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_data_risposta = data_risposta;
	}

	@JSON
	@Override
	public String getCODICE_ESITO() {
		if (_CODICE_ESITO == null) {
			return "";
		}
		else {
			return _CODICE_ESITO;
		}
	}

	@Override
	public void setCODICE_ESITO(String CODICE_ESITO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CODICE_ESITO = CODICE_ESITO;
	}

	@JSON
	@Override
	public String getCODICE_ERRORE() {
		if (_CODICE_ERRORE == null) {
			return "";
		}
		else {
			return _CODICE_ERRORE;
		}
	}

	@Override
	public void setCODICE_ERRORE(String CODICE_ERRORE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CODICE_ERRORE = CODICE_ERRORE;
	}

	@JSON
	@Override
	public String getMESG_ERRORE() {
		if (_MESG_ERRORE == null) {
			return "";
		}
		else {
			return _MESG_ERRORE;
		}
	}

	@Override
	public void setMESG_ERRORE(String MESG_ERRORE) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_MESG_ERRORE = MESG_ERRORE;
	}

	@JSON
	@Override
	public String getCODICE_TIPO_INVIO() {
		if (_CODICE_TIPO_INVIO == null) {
			return "";
		}
		else {
			return _CODICE_TIPO_INVIO;
		}
	}

	@Override
	public void setCODICE_TIPO_INVIO(String CODICE_TIPO_INVIO) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CODICE_TIPO_INVIO = CODICE_TIPO_INVIO;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DatiSpecificiInvio.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DatiSpecificiInvio toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DatiSpecificiInvio>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DatiSpecificiInvioImpl datiSpecificiInvioImpl =
			new DatiSpecificiInvioImpl();

		datiSpecificiInvioImpl.setID_INVIO(getID_INVIO());
		datiSpecificiInvioImpl.setAMBIENTE(getAMBIENTE());
		datiSpecificiInvioImpl.setVERSIONE(getVERSIONE());
		datiSpecificiInvioImpl.setVERSATORE_ENTE(getVERSATORE_ENTE());
		datiSpecificiInvioImpl.setVERSATORE_USER_ID(getVERSATORE_USER_ID());
		datiSpecificiInvioImpl.setVERSATORE_STRUTTURA(getVERSATORE_STRUTTURA());
		datiSpecificiInvioImpl.setCHIAVE_NUMERO(getCHIAVE_NUMERO());
		datiSpecificiInvioImpl.setCHIAVE_ANNO(getCHIAVE_ANNO());
		datiSpecificiInvioImpl.setCHIAVE_TIPO_REGISTRO(
			getCHIAVE_TIPO_REGISTRO());
		datiSpecificiInvioImpl.setTIPOLOGIA_UNITA_DOCUMENTARIA(
			getTIPOLOGIA_UNITA_DOCUMENTARIA());
		datiSpecificiInvioImpl.setTIPO_CONSERVAZIONE(getTIPO_CONSERVAZIONE());
		datiSpecificiInvioImpl.setFORZA_ACCETTAZIONE(getFORZA_ACCETTAZIONE());
		datiSpecificiInvioImpl.setFORZA_CONSERVAZIONE(getFORZA_CONSERVAZIONE());
		datiSpecificiInvioImpl.setFORZA_COLLEGAMENTO(getFORZA_COLLEGAMENTO());
		datiSpecificiInvioImpl.setOGGETTO_UNITA_DOCUMENTARIA(
			getOGGETTO_UNITA_DOCUMENTARIA());
		datiSpecificiInvioImpl.setDATA_UNITA_DOCUMENTARIA(
			getDATA_UNITA_DOCUMENTARIA());
		datiSpecificiInvioImpl.setVERSIONE_DATI_SPECIFICI(
			getVERSIONE_DATI_SPECIFICI());
		datiSpecificiInvioImpl.setIDENTIFICATIVO_DATO_SPECIFICO(
			getIDENTIFICATIVO_DATO_SPECIFICO());
		datiSpecificiInvioImpl.setDATA_GENERAZIONE(getDATA_GENERAZIONE());
		datiSpecificiInvioImpl.setNUM_SMS_GENERATI(getNUM_SMS_GENERATI());
		datiSpecificiInvioImpl.setNUM_SMS_INVIATI(getNUM_SMS_INVIATI());
		datiSpecificiInvioImpl.setNUM_NOTIFICHE_RICEZIONE(
			getNUM_NOTIFICHE_RICEZIONE());
		datiSpecificiInvioImpl.setDENOMINAZIONE_APPLICATIVO(
			getDENOMINAZIONE_APPLICATIVO());
		datiSpecificiInvioImpl.setOGGETTO_MAIL(getOGGETTO_MAIL());
		datiSpecificiInvioImpl.setTESTO_MAIL(getTESTO_MAIL());
		datiSpecificiInvioImpl.setCOMPILATORE_ARPAE(getCOMPILATORE_ARPAE());
		datiSpecificiInvioImpl.setCOMPILATORE_PROTEZIONE_CIVILE(
			getCOMPILATORE_PROTEZIONE_CIVILE());
		datiSpecificiInvioImpl.setDATA_INIZIO_VALIDITA(
			getDATA_INIZIO_VALIDITA());
		datiSpecificiInvioImpl.setDATA_FINE_VALIDITA(getDATA_FINE_VALIDITA());
		datiSpecificiInvioImpl.setAPPROVATORE_ARPAE(getAPPROVATORE_ARPAE());
		datiSpecificiInvioImpl.setDATA_FIRMA_ARPAE(getDATA_FIRMA_ARPAE());
		datiSpecificiInvioImpl.setAPPROVATORE_PROTEZIONE_CIVILE(
			getAPPROVATORE_PROTEZIONE_CIVILE());
		datiSpecificiInvioImpl.setDATA_FIRMA_PROTEZIONE_CIVILE(
			getDATA_FIRMA_PROTEZIONE_CIVILE());
		datiSpecificiInvioImpl.setINVIO_RESPONSABILE_TERRITORIO(
			getINVIO_RESPONSABILE_TERRITORIO());
		datiSpecificiInvioImpl.setID_DOCUMENTO_PRINCIPALE(
			getID_DOCUMENTO_PRINCIPALE());
		datiSpecificiInvioImpl.setTIPO_DOCUMENTO(getTIPO_DOCUMENTO());
		datiSpecificiInvioImpl.setTIPO_STRUTTURA(getTIPO_STRUTTURA());
		datiSpecificiInvioImpl.setDENOMINAZIONE_SENSORE_RILEVAMENTO(
			getDENOMINAZIONE_SENSORE_RILEVAMENTO());
		datiSpecificiInvioImpl.setREGOLA_ALLARME_ID(getREGOLA_ALLARME_ID());
		datiSpecificiInvioImpl.setREGOLA_ALLARME_NOME(getREGOLA_ALLARME_NOME());
		datiSpecificiInvioImpl.setREGOLA_ALLARME_DESCRIZIONE(
			getREGOLA_ALLARME_DESCRIZIONE());
		datiSpecificiInvioImpl.setESITO_INVIO(getESITO_INVIO());
		datiSpecificiInvioImpl.setUserId(getUserId());
		datiSpecificiInvioImpl.setCompanyId(getCompanyId());
		datiSpecificiInvioImpl.setGroupId(getGroupId());
		datiSpecificiInvioImpl.setData_invio(getData_invio());
		datiSpecificiInvioImpl.setData_risposta(getData_risposta());
		datiSpecificiInvioImpl.setCODICE_ESITO(getCODICE_ESITO());
		datiSpecificiInvioImpl.setCODICE_ERRORE(getCODICE_ERRORE());
		datiSpecificiInvioImpl.setMESG_ERRORE(getMESG_ERRORE());
		datiSpecificiInvioImpl.setCODICE_TIPO_INVIO(getCODICE_TIPO_INVIO());

		datiSpecificiInvioImpl.resetOriginalValues();

		return datiSpecificiInvioImpl;
	}

	@Override
	public DatiSpecificiInvio cloneWithOriginalValues() {
		DatiSpecificiInvioImpl datiSpecificiInvioImpl =
			new DatiSpecificiInvioImpl();

		datiSpecificiInvioImpl.setID_INVIO(
			this.<Long>getColumnOriginalValue("ID_INVIO"));
		datiSpecificiInvioImpl.setAMBIENTE(
			this.<String>getColumnOriginalValue("AMBIENTE"));
		datiSpecificiInvioImpl.setVERSIONE(
			this.<Double>getColumnOriginalValue("VERSIONE"));
		datiSpecificiInvioImpl.setVERSATORE_ENTE(
			this.<String>getColumnOriginalValue("VERSATORE_ENTE"));
		datiSpecificiInvioImpl.setVERSATORE_USER_ID(
			this.<String>getColumnOriginalValue("VERSATORE_USER_ID"));
		datiSpecificiInvioImpl.setVERSATORE_STRUTTURA(
			this.<String>getColumnOriginalValue("VERSATORE_STRUTTURA"));
		datiSpecificiInvioImpl.setCHIAVE_NUMERO(
			this.<String>getColumnOriginalValue("CHIAVE_NUMERO"));
		datiSpecificiInvioImpl.setCHIAVE_ANNO(
			this.<Long>getColumnOriginalValue("CHIAVE_ANNO"));
		datiSpecificiInvioImpl.setCHIAVE_TIPO_REGISTRO(
			this.<String>getColumnOriginalValue("CHIAVE_TIPO_REGISTRO"));
		datiSpecificiInvioImpl.setTIPOLOGIA_UNITA_DOCUMENTARIA(
			this.<String>getColumnOriginalValue(
				"TIPOLOGIA_UNITA_DOCUMENTARIA"));
		datiSpecificiInvioImpl.setTIPO_CONSERVAZIONE(
			this.<String>getColumnOriginalValue("TIPO_CONSERVAZIONE"));
		datiSpecificiInvioImpl.setFORZA_ACCETTAZIONE(
			this.<String>getColumnOriginalValue("FORZA_ACCETTAZIONE"));
		datiSpecificiInvioImpl.setFORZA_CONSERVAZIONE(
			this.<String>getColumnOriginalValue("FORZA_CONSERVAZIONE"));
		datiSpecificiInvioImpl.setFORZA_COLLEGAMENTO(
			this.<String>getColumnOriginalValue("FORZA_COLLEGAMENTO"));
		datiSpecificiInvioImpl.setOGGETTO_UNITA_DOCUMENTARIA(
			this.<String>getColumnOriginalValue("OGGETTO_UNITA_DOCUMENTARIA"));
		datiSpecificiInvioImpl.setDATA_UNITA_DOCUMENTARIA(
			this.<Date>getColumnOriginalValue("DATA_UNITA_DOCUMENTARIA"));
		datiSpecificiInvioImpl.setVERSIONE_DATI_SPECIFICI(
			this.<Double>getColumnOriginalValue("VERSIONE_DATI_SPECIFICI"));
		datiSpecificiInvioImpl.setIDENTIFICATIVO_DATO_SPECIFICO(
			this.<String>getColumnOriginalValue(
				"IDENTIFICATIVO_DATO_SPECIFICO"));
		datiSpecificiInvioImpl.setDATA_GENERAZIONE(
			this.<Date>getColumnOriginalValue("DATA_GENERAZIONE"));
		datiSpecificiInvioImpl.setNUM_SMS_GENERATI(
			this.<Integer>getColumnOriginalValue("NUM_SMS_GENERATI"));
		datiSpecificiInvioImpl.setNUM_SMS_INVIATI(
			this.<Integer>getColumnOriginalValue("NUM_SMS_INVIATI"));
		datiSpecificiInvioImpl.setNUM_NOTIFICHE_RICEZIONE(
			this.<Integer>getColumnOriginalValue("NUM_NOTIFICHE_RICEZIONE"));
		datiSpecificiInvioImpl.setDENOMINAZIONE_APPLICATIVO(
			this.<String>getColumnOriginalValue("DENOMINAZIONE_APPLICATIVO"));
		datiSpecificiInvioImpl.setOGGETTO_MAIL(
			this.<String>getColumnOriginalValue("OGGETTO_MAIL"));
		datiSpecificiInvioImpl.setTESTO_MAIL(
			this.<String>getColumnOriginalValue("TESTO_MAIL"));
		datiSpecificiInvioImpl.setCOMPILATORE_ARPAE(
			this.<String>getColumnOriginalValue("COMPILATORE_ARPAE"));
		datiSpecificiInvioImpl.setCOMPILATORE_PROTEZIONE_CIVILE(
			this.<String>getColumnOriginalValue(
				"COMPILATORE_PROTEZIONE_CIVILE"));
		datiSpecificiInvioImpl.setDATA_INIZIO_VALIDITA(
			this.<Date>getColumnOriginalValue("DATA_INIZIO_VALIDITA"));
		datiSpecificiInvioImpl.setDATA_FINE_VALIDITA(
			this.<Date>getColumnOriginalValue("DATA_FINE_VALIDITA"));
		datiSpecificiInvioImpl.setAPPROVATORE_ARPAE(
			this.<String>getColumnOriginalValue("APPROVATORE_ARPAE"));
		datiSpecificiInvioImpl.setDATA_FIRMA_ARPAE(
			this.<Date>getColumnOriginalValue("DATA_FIRMA_ARPAE"));
		datiSpecificiInvioImpl.setAPPROVATORE_PROTEZIONE_CIVILE(
			this.<String>getColumnOriginalValue(
				"APPROVATORE_PROTEZIONE_CIVILE"));
		datiSpecificiInvioImpl.setDATA_FIRMA_PROTEZIONE_CIVILE(
			this.<Date>getColumnOriginalValue("DATA_FIRMA_PROTEZIONE_CIVILE"));
		datiSpecificiInvioImpl.setINVIO_RESPONSABILE_TERRITORIO(
			this.<String>getColumnOriginalValue(
				"INVIO_RESPONSABILE_TERRITORIO"));
		datiSpecificiInvioImpl.setID_DOCUMENTO_PRINCIPALE(
			this.<Long>getColumnOriginalValue("ID_DOCUMENTO_PRINCIPALE"));
		datiSpecificiInvioImpl.setTIPO_DOCUMENTO(
			this.<String>getColumnOriginalValue("TIPO_DOCUMENTO"));
		datiSpecificiInvioImpl.setTIPO_STRUTTURA(
			this.<String>getColumnOriginalValue("TIPO_STRUTTURA"));
		datiSpecificiInvioImpl.setDENOMINAZIONE_SENSORE_RILEVAMENTO(
			this.<String>getColumnOriginalValue(
				"DENOMINAZIONE_SENSORE_RILEVAMENTO"));
		datiSpecificiInvioImpl.setREGOLA_ALLARME_ID(
			this.<String>getColumnOriginalValue("REGOLA_ALLARME_ID"));
		datiSpecificiInvioImpl.setREGOLA_ALLARME_NOME(
			this.<String>getColumnOriginalValue("REGOLA_ALLARME_NOME"));
		datiSpecificiInvioImpl.setREGOLA_ALLARME_DESCRIZIONE(
			this.<String>getColumnOriginalValue("REGOLA_ALLARME_DESCRIZIONE"));
		datiSpecificiInvioImpl.setESITO_INVIO(
			this.<String>getColumnOriginalValue("ESITO_INVIO"));
		datiSpecificiInvioImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		datiSpecificiInvioImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		datiSpecificiInvioImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		datiSpecificiInvioImpl.setData_invio(
			this.<Date>getColumnOriginalValue("data_invio"));
		datiSpecificiInvioImpl.setData_risposta(
			this.<Date>getColumnOriginalValue("data_risposta"));
		datiSpecificiInvioImpl.setCODICE_ESITO(
			this.<String>getColumnOriginalValue("CODICE_ESITO"));
		datiSpecificiInvioImpl.setCODICE_ERRORE(
			this.<String>getColumnOriginalValue("CODICE_ERRORE"));
		datiSpecificiInvioImpl.setMESG_ERRORE(
			this.<String>getColumnOriginalValue("MESG_ERRORE"));
		datiSpecificiInvioImpl.setCODICE_TIPO_INVIO(
			this.<String>getColumnOriginalValue("CODICE_TIPO_INVIO"));

		return datiSpecificiInvioImpl;
	}

	@Override
	public int compareTo(DatiSpecificiInvio datiSpecificiInvio) {
		long primaryKey = datiSpecificiInvio.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DatiSpecificiInvio)) {
			return false;
		}

		DatiSpecificiInvio datiSpecificiInvio = (DatiSpecificiInvio)object;

		long primaryKey = datiSpecificiInvio.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DatiSpecificiInvio> toCacheModel() {
		DatiSpecificiInvioCacheModel datiSpecificiInvioCacheModel =
			new DatiSpecificiInvioCacheModel();

		datiSpecificiInvioCacheModel.ID_INVIO = getID_INVIO();

		datiSpecificiInvioCacheModel.AMBIENTE = getAMBIENTE();

		String AMBIENTE = datiSpecificiInvioCacheModel.AMBIENTE;

		if ((AMBIENTE != null) && (AMBIENTE.length() == 0)) {
			datiSpecificiInvioCacheModel.AMBIENTE = null;
		}

		datiSpecificiInvioCacheModel.VERSIONE = getVERSIONE();

		datiSpecificiInvioCacheModel.VERSATORE_ENTE = getVERSATORE_ENTE();

		String VERSATORE_ENTE = datiSpecificiInvioCacheModel.VERSATORE_ENTE;

		if ((VERSATORE_ENTE != null) && (VERSATORE_ENTE.length() == 0)) {
			datiSpecificiInvioCacheModel.VERSATORE_ENTE = null;
		}

		datiSpecificiInvioCacheModel.VERSATORE_USER_ID = getVERSATORE_USER_ID();

		String VERSATORE_USER_ID =
			datiSpecificiInvioCacheModel.VERSATORE_USER_ID;

		if ((VERSATORE_USER_ID != null) && (VERSATORE_USER_ID.length() == 0)) {
			datiSpecificiInvioCacheModel.VERSATORE_USER_ID = null;
		}

		datiSpecificiInvioCacheModel.VERSATORE_STRUTTURA =
			getVERSATORE_STRUTTURA();

		String VERSATORE_STRUTTURA =
			datiSpecificiInvioCacheModel.VERSATORE_STRUTTURA;

		if ((VERSATORE_STRUTTURA != null) &&
			(VERSATORE_STRUTTURA.length() == 0)) {

			datiSpecificiInvioCacheModel.VERSATORE_STRUTTURA = null;
		}

		datiSpecificiInvioCacheModel.CHIAVE_NUMERO = getCHIAVE_NUMERO();

		String CHIAVE_NUMERO = datiSpecificiInvioCacheModel.CHIAVE_NUMERO;

		if ((CHIAVE_NUMERO != null) && (CHIAVE_NUMERO.length() == 0)) {
			datiSpecificiInvioCacheModel.CHIAVE_NUMERO = null;
		}

		datiSpecificiInvioCacheModel.CHIAVE_ANNO = getCHIAVE_ANNO();

		datiSpecificiInvioCacheModel.CHIAVE_TIPO_REGISTRO =
			getCHIAVE_TIPO_REGISTRO();

		String CHIAVE_TIPO_REGISTRO =
			datiSpecificiInvioCacheModel.CHIAVE_TIPO_REGISTRO;

		if ((CHIAVE_TIPO_REGISTRO != null) &&
			(CHIAVE_TIPO_REGISTRO.length() == 0)) {

			datiSpecificiInvioCacheModel.CHIAVE_TIPO_REGISTRO = null;
		}

		datiSpecificiInvioCacheModel.TIPOLOGIA_UNITA_DOCUMENTARIA =
			getTIPOLOGIA_UNITA_DOCUMENTARIA();

		String TIPOLOGIA_UNITA_DOCUMENTARIA =
			datiSpecificiInvioCacheModel.TIPOLOGIA_UNITA_DOCUMENTARIA;

		if ((TIPOLOGIA_UNITA_DOCUMENTARIA != null) &&
			(TIPOLOGIA_UNITA_DOCUMENTARIA.length() == 0)) {

			datiSpecificiInvioCacheModel.TIPOLOGIA_UNITA_DOCUMENTARIA = null;
		}

		datiSpecificiInvioCacheModel.TIPO_CONSERVAZIONE =
			getTIPO_CONSERVAZIONE();

		String TIPO_CONSERVAZIONE =
			datiSpecificiInvioCacheModel.TIPO_CONSERVAZIONE;

		if ((TIPO_CONSERVAZIONE != null) &&
			(TIPO_CONSERVAZIONE.length() == 0)) {

			datiSpecificiInvioCacheModel.TIPO_CONSERVAZIONE = null;
		}

		datiSpecificiInvioCacheModel.FORZA_ACCETTAZIONE =
			getFORZA_ACCETTAZIONE();

		String FORZA_ACCETTAZIONE =
			datiSpecificiInvioCacheModel.FORZA_ACCETTAZIONE;

		if ((FORZA_ACCETTAZIONE != null) &&
			(FORZA_ACCETTAZIONE.length() == 0)) {

			datiSpecificiInvioCacheModel.FORZA_ACCETTAZIONE = null;
		}

		datiSpecificiInvioCacheModel.FORZA_CONSERVAZIONE =
			getFORZA_CONSERVAZIONE();

		String FORZA_CONSERVAZIONE =
			datiSpecificiInvioCacheModel.FORZA_CONSERVAZIONE;

		if ((FORZA_CONSERVAZIONE != null) &&
			(FORZA_CONSERVAZIONE.length() == 0)) {

			datiSpecificiInvioCacheModel.FORZA_CONSERVAZIONE = null;
		}

		datiSpecificiInvioCacheModel.FORZA_COLLEGAMENTO =
			getFORZA_COLLEGAMENTO();

		String FORZA_COLLEGAMENTO =
			datiSpecificiInvioCacheModel.FORZA_COLLEGAMENTO;

		if ((FORZA_COLLEGAMENTO != null) &&
			(FORZA_COLLEGAMENTO.length() == 0)) {

			datiSpecificiInvioCacheModel.FORZA_COLLEGAMENTO = null;
		}

		datiSpecificiInvioCacheModel.OGGETTO_UNITA_DOCUMENTARIA =
			getOGGETTO_UNITA_DOCUMENTARIA();

		String OGGETTO_UNITA_DOCUMENTARIA =
			datiSpecificiInvioCacheModel.OGGETTO_UNITA_DOCUMENTARIA;

		if ((OGGETTO_UNITA_DOCUMENTARIA != null) &&
			(OGGETTO_UNITA_DOCUMENTARIA.length() == 0)) {

			datiSpecificiInvioCacheModel.OGGETTO_UNITA_DOCUMENTARIA = null;
		}

		Date DATA_UNITA_DOCUMENTARIA = getDATA_UNITA_DOCUMENTARIA();

		if (DATA_UNITA_DOCUMENTARIA != null) {
			datiSpecificiInvioCacheModel.DATA_UNITA_DOCUMENTARIA =
				DATA_UNITA_DOCUMENTARIA.getTime();
		}
		else {
			datiSpecificiInvioCacheModel.DATA_UNITA_DOCUMENTARIA =
				Long.MIN_VALUE;
		}

		datiSpecificiInvioCacheModel.VERSIONE_DATI_SPECIFICI =
			getVERSIONE_DATI_SPECIFICI();

		datiSpecificiInvioCacheModel.IDENTIFICATIVO_DATO_SPECIFICO =
			getIDENTIFICATIVO_DATO_SPECIFICO();

		String IDENTIFICATIVO_DATO_SPECIFICO =
			datiSpecificiInvioCacheModel.IDENTIFICATIVO_DATO_SPECIFICO;

		if ((IDENTIFICATIVO_DATO_SPECIFICO != null) &&
			(IDENTIFICATIVO_DATO_SPECIFICO.length() == 0)) {

			datiSpecificiInvioCacheModel.IDENTIFICATIVO_DATO_SPECIFICO = null;
		}

		Date DATA_GENERAZIONE = getDATA_GENERAZIONE();

		if (DATA_GENERAZIONE != null) {
			datiSpecificiInvioCacheModel.DATA_GENERAZIONE =
				DATA_GENERAZIONE.getTime();
		}
		else {
			datiSpecificiInvioCacheModel.DATA_GENERAZIONE = Long.MIN_VALUE;
		}

		datiSpecificiInvioCacheModel.NUM_SMS_GENERATI = getNUM_SMS_GENERATI();

		datiSpecificiInvioCacheModel.NUM_SMS_INVIATI = getNUM_SMS_INVIATI();

		datiSpecificiInvioCacheModel.NUM_NOTIFICHE_RICEZIONE =
			getNUM_NOTIFICHE_RICEZIONE();

		datiSpecificiInvioCacheModel.DENOMINAZIONE_APPLICATIVO =
			getDENOMINAZIONE_APPLICATIVO();

		String DENOMINAZIONE_APPLICATIVO =
			datiSpecificiInvioCacheModel.DENOMINAZIONE_APPLICATIVO;

		if ((DENOMINAZIONE_APPLICATIVO != null) &&
			(DENOMINAZIONE_APPLICATIVO.length() == 0)) {

			datiSpecificiInvioCacheModel.DENOMINAZIONE_APPLICATIVO = null;
		}

		datiSpecificiInvioCacheModel.OGGETTO_MAIL = getOGGETTO_MAIL();

		String OGGETTO_MAIL = datiSpecificiInvioCacheModel.OGGETTO_MAIL;

		if ((OGGETTO_MAIL != null) && (OGGETTO_MAIL.length() == 0)) {
			datiSpecificiInvioCacheModel.OGGETTO_MAIL = null;
		}

		datiSpecificiInvioCacheModel.TESTO_MAIL = getTESTO_MAIL();

		String TESTO_MAIL = datiSpecificiInvioCacheModel.TESTO_MAIL;

		if ((TESTO_MAIL != null) && (TESTO_MAIL.length() == 0)) {
			datiSpecificiInvioCacheModel.TESTO_MAIL = null;
		}

		datiSpecificiInvioCacheModel.COMPILATORE_ARPAE = getCOMPILATORE_ARPAE();

		String COMPILATORE_ARPAE =
			datiSpecificiInvioCacheModel.COMPILATORE_ARPAE;

		if ((COMPILATORE_ARPAE != null) && (COMPILATORE_ARPAE.length() == 0)) {
			datiSpecificiInvioCacheModel.COMPILATORE_ARPAE = null;
		}

		datiSpecificiInvioCacheModel.COMPILATORE_PROTEZIONE_CIVILE =
			getCOMPILATORE_PROTEZIONE_CIVILE();

		String COMPILATORE_PROTEZIONE_CIVILE =
			datiSpecificiInvioCacheModel.COMPILATORE_PROTEZIONE_CIVILE;

		if ((COMPILATORE_PROTEZIONE_CIVILE != null) &&
			(COMPILATORE_PROTEZIONE_CIVILE.length() == 0)) {

			datiSpecificiInvioCacheModel.COMPILATORE_PROTEZIONE_CIVILE = null;
		}

		Date DATA_INIZIO_VALIDITA = getDATA_INIZIO_VALIDITA();

		if (DATA_INIZIO_VALIDITA != null) {
			datiSpecificiInvioCacheModel.DATA_INIZIO_VALIDITA =
				DATA_INIZIO_VALIDITA.getTime();
		}
		else {
			datiSpecificiInvioCacheModel.DATA_INIZIO_VALIDITA = Long.MIN_VALUE;
		}

		Date DATA_FINE_VALIDITA = getDATA_FINE_VALIDITA();

		if (DATA_FINE_VALIDITA != null) {
			datiSpecificiInvioCacheModel.DATA_FINE_VALIDITA =
				DATA_FINE_VALIDITA.getTime();
		}
		else {
			datiSpecificiInvioCacheModel.DATA_FINE_VALIDITA = Long.MIN_VALUE;
		}

		datiSpecificiInvioCacheModel.APPROVATORE_ARPAE = getAPPROVATORE_ARPAE();

		String APPROVATORE_ARPAE =
			datiSpecificiInvioCacheModel.APPROVATORE_ARPAE;

		if ((APPROVATORE_ARPAE != null) && (APPROVATORE_ARPAE.length() == 0)) {
			datiSpecificiInvioCacheModel.APPROVATORE_ARPAE = null;
		}

		Date DATA_FIRMA_ARPAE = getDATA_FIRMA_ARPAE();

		if (DATA_FIRMA_ARPAE != null) {
			datiSpecificiInvioCacheModel.DATA_FIRMA_ARPAE =
				DATA_FIRMA_ARPAE.getTime();
		}
		else {
			datiSpecificiInvioCacheModel.DATA_FIRMA_ARPAE = Long.MIN_VALUE;
		}

		datiSpecificiInvioCacheModel.APPROVATORE_PROTEZIONE_CIVILE =
			getAPPROVATORE_PROTEZIONE_CIVILE();

		String APPROVATORE_PROTEZIONE_CIVILE =
			datiSpecificiInvioCacheModel.APPROVATORE_PROTEZIONE_CIVILE;

		if ((APPROVATORE_PROTEZIONE_CIVILE != null) &&
			(APPROVATORE_PROTEZIONE_CIVILE.length() == 0)) {

			datiSpecificiInvioCacheModel.APPROVATORE_PROTEZIONE_CIVILE = null;
		}

		Date DATA_FIRMA_PROTEZIONE_CIVILE = getDATA_FIRMA_PROTEZIONE_CIVILE();

		if (DATA_FIRMA_PROTEZIONE_CIVILE != null) {
			datiSpecificiInvioCacheModel.DATA_FIRMA_PROTEZIONE_CIVILE =
				DATA_FIRMA_PROTEZIONE_CIVILE.getTime();
		}
		else {
			datiSpecificiInvioCacheModel.DATA_FIRMA_PROTEZIONE_CIVILE =
				Long.MIN_VALUE;
		}

		datiSpecificiInvioCacheModel.INVIO_RESPONSABILE_TERRITORIO =
			getINVIO_RESPONSABILE_TERRITORIO();

		String INVIO_RESPONSABILE_TERRITORIO =
			datiSpecificiInvioCacheModel.INVIO_RESPONSABILE_TERRITORIO;

		if ((INVIO_RESPONSABILE_TERRITORIO != null) &&
			(INVIO_RESPONSABILE_TERRITORIO.length() == 0)) {

			datiSpecificiInvioCacheModel.INVIO_RESPONSABILE_TERRITORIO = null;
		}

		datiSpecificiInvioCacheModel.ID_DOCUMENTO_PRINCIPALE =
			getID_DOCUMENTO_PRINCIPALE();

		datiSpecificiInvioCacheModel.TIPO_DOCUMENTO = getTIPO_DOCUMENTO();

		String TIPO_DOCUMENTO = datiSpecificiInvioCacheModel.TIPO_DOCUMENTO;

		if ((TIPO_DOCUMENTO != null) && (TIPO_DOCUMENTO.length() == 0)) {
			datiSpecificiInvioCacheModel.TIPO_DOCUMENTO = null;
		}

		datiSpecificiInvioCacheModel.TIPO_STRUTTURA = getTIPO_STRUTTURA();

		String TIPO_STRUTTURA = datiSpecificiInvioCacheModel.TIPO_STRUTTURA;

		if ((TIPO_STRUTTURA != null) && (TIPO_STRUTTURA.length() == 0)) {
			datiSpecificiInvioCacheModel.TIPO_STRUTTURA = null;
		}

		datiSpecificiInvioCacheModel.DENOMINAZIONE_SENSORE_RILEVAMENTO =
			getDENOMINAZIONE_SENSORE_RILEVAMENTO();

		String DENOMINAZIONE_SENSORE_RILEVAMENTO =
			datiSpecificiInvioCacheModel.DENOMINAZIONE_SENSORE_RILEVAMENTO;

		if ((DENOMINAZIONE_SENSORE_RILEVAMENTO != null) &&
			(DENOMINAZIONE_SENSORE_RILEVAMENTO.length() == 0)) {

			datiSpecificiInvioCacheModel.DENOMINAZIONE_SENSORE_RILEVAMENTO =
				null;
		}

		datiSpecificiInvioCacheModel.REGOLA_ALLARME_ID = getREGOLA_ALLARME_ID();

		String REGOLA_ALLARME_ID =
			datiSpecificiInvioCacheModel.REGOLA_ALLARME_ID;

		if ((REGOLA_ALLARME_ID != null) && (REGOLA_ALLARME_ID.length() == 0)) {
			datiSpecificiInvioCacheModel.REGOLA_ALLARME_ID = null;
		}

		datiSpecificiInvioCacheModel.REGOLA_ALLARME_NOME =
			getREGOLA_ALLARME_NOME();

		String REGOLA_ALLARME_NOME =
			datiSpecificiInvioCacheModel.REGOLA_ALLARME_NOME;

		if ((REGOLA_ALLARME_NOME != null) &&
			(REGOLA_ALLARME_NOME.length() == 0)) {

			datiSpecificiInvioCacheModel.REGOLA_ALLARME_NOME = null;
		}

		datiSpecificiInvioCacheModel.REGOLA_ALLARME_DESCRIZIONE =
			getREGOLA_ALLARME_DESCRIZIONE();

		String REGOLA_ALLARME_DESCRIZIONE =
			datiSpecificiInvioCacheModel.REGOLA_ALLARME_DESCRIZIONE;

		if ((REGOLA_ALLARME_DESCRIZIONE != null) &&
			(REGOLA_ALLARME_DESCRIZIONE.length() == 0)) {

			datiSpecificiInvioCacheModel.REGOLA_ALLARME_DESCRIZIONE = null;
		}

		datiSpecificiInvioCacheModel.ESITO_INVIO = getESITO_INVIO();

		String ESITO_INVIO = datiSpecificiInvioCacheModel.ESITO_INVIO;

		if ((ESITO_INVIO != null) && (ESITO_INVIO.length() == 0)) {
			datiSpecificiInvioCacheModel.ESITO_INVIO = null;
		}

		datiSpecificiInvioCacheModel.userId = getUserId();

		datiSpecificiInvioCacheModel.companyId = getCompanyId();

		datiSpecificiInvioCacheModel.groupId = getGroupId();

		Date data_invio = getData_invio();

		if (data_invio != null) {
			datiSpecificiInvioCacheModel.data_invio = data_invio.getTime();
		}
		else {
			datiSpecificiInvioCacheModel.data_invio = Long.MIN_VALUE;
		}

		Date data_risposta = getData_risposta();

		if (data_risposta != null) {
			datiSpecificiInvioCacheModel.data_risposta =
				data_risposta.getTime();
		}
		else {
			datiSpecificiInvioCacheModel.data_risposta = Long.MIN_VALUE;
		}

		datiSpecificiInvioCacheModel.CODICE_ESITO = getCODICE_ESITO();

		String CODICE_ESITO = datiSpecificiInvioCacheModel.CODICE_ESITO;

		if ((CODICE_ESITO != null) && (CODICE_ESITO.length() == 0)) {
			datiSpecificiInvioCacheModel.CODICE_ESITO = null;
		}

		datiSpecificiInvioCacheModel.CODICE_ERRORE = getCODICE_ERRORE();

		String CODICE_ERRORE = datiSpecificiInvioCacheModel.CODICE_ERRORE;

		if ((CODICE_ERRORE != null) && (CODICE_ERRORE.length() == 0)) {
			datiSpecificiInvioCacheModel.CODICE_ERRORE = null;
		}

		datiSpecificiInvioCacheModel.MESG_ERRORE = getMESG_ERRORE();

		String MESG_ERRORE = datiSpecificiInvioCacheModel.MESG_ERRORE;

		if ((MESG_ERRORE != null) && (MESG_ERRORE.length() == 0)) {
			datiSpecificiInvioCacheModel.MESG_ERRORE = null;
		}

		datiSpecificiInvioCacheModel.CODICE_TIPO_INVIO = getCODICE_TIPO_INVIO();

		String CODICE_TIPO_INVIO =
			datiSpecificiInvioCacheModel.CODICE_TIPO_INVIO;

		if ((CODICE_TIPO_INVIO != null) && (CODICE_TIPO_INVIO.length() == 0)) {
			datiSpecificiInvioCacheModel.CODICE_TIPO_INVIO = null;
		}

		return datiSpecificiInvioCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DatiSpecificiInvio, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DatiSpecificiInvio, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DatiSpecificiInvio, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(DatiSpecificiInvio)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DatiSpecificiInvio>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					DatiSpecificiInvio.class, ModelWrapper.class);

	}

	private long _ID_INVIO;

	private String _AMBIENTE;

	private double _VERSIONE;

	private String _VERSATORE_ENTE;

	private String _VERSATORE_USER_ID;

	private String _VERSATORE_STRUTTURA;

	private String _CHIAVE_NUMERO;

	private long _CHIAVE_ANNO;

	private String _CHIAVE_TIPO_REGISTRO;

	private String _TIPOLOGIA_UNITA_DOCUMENTARIA;

	private String _TIPO_CONSERVAZIONE;

	private String _FORZA_ACCETTAZIONE;

	private String _FORZA_CONSERVAZIONE;

	private String _FORZA_COLLEGAMENTO;

	private String _OGGETTO_UNITA_DOCUMENTARIA;

	private Date _DATA_UNITA_DOCUMENTARIA;

	private double _VERSIONE_DATI_SPECIFICI;

	private String _IDENTIFICATIVO_DATO_SPECIFICO;

	private Date _DATA_GENERAZIONE;

	private int _NUM_SMS_GENERATI;

	private int _NUM_SMS_INVIATI;

	private int _NUM_NOTIFICHE_RICEZIONE;

	private String _DENOMINAZIONE_APPLICATIVO;

	private String _OGGETTO_MAIL;

	private String _TESTO_MAIL;

	private String _COMPILATORE_ARPAE;

	private String _COMPILATORE_PROTEZIONE_CIVILE;

	private Date _DATA_INIZIO_VALIDITA;

	private Date _DATA_FINE_VALIDITA;

	private String _APPROVATORE_ARPAE;

	private Date _DATA_FIRMA_ARPAE;

	private String _APPROVATORE_PROTEZIONE_CIVILE;

	private Date _DATA_FIRMA_PROTEZIONE_CIVILE;

	private String _INVIO_RESPONSABILE_TERRITORIO;

	private long _ID_DOCUMENTO_PRINCIPALE;

	private String _TIPO_DOCUMENTO;

	private String _TIPO_STRUTTURA;

	private String _DENOMINAZIONE_SENSORE_RILEVAMENTO;

	private String _REGOLA_ALLARME_ID;

	private String _REGOLA_ALLARME_NOME;

	private String _REGOLA_ALLARME_DESCRIZIONE;

	private String _ESITO_INVIO;

	private long _userId;
	private long _companyId;
	private long _groupId;
	private Date _data_invio;
	private Date _data_risposta;

	private String _CODICE_ESITO;

	private String _CODICE_ERRORE;

	private String _MESG_ERRORE;

	private String _CODICE_TIPO_INVIO;

	public <T> T getColumnValue(String columnName) {
		Function<DatiSpecificiInvio, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DatiSpecificiInvio)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ID_INVIO", _ID_INVIO);
		_columnOriginalValues.put("AMBIENTE", _AMBIENTE);
		_columnOriginalValues.put("VERSIONE", _VERSIONE);
		_columnOriginalValues.put("VERSATORE_ENTE", _VERSATORE_ENTE);
		_columnOriginalValues.put("VERSATORE_USER_ID", _VERSATORE_USER_ID);
		_columnOriginalValues.put("VERSATORE_STRUTTURA", _VERSATORE_STRUTTURA);
		_columnOriginalValues.put("CHIAVE_NUMERO", _CHIAVE_NUMERO);
		_columnOriginalValues.put("CHIAVE_ANNO", _CHIAVE_ANNO);
		_columnOriginalValues.put(
			"CHIAVE_TIPO_REGISTRO", _CHIAVE_TIPO_REGISTRO);
		_columnOriginalValues.put(
			"TIPOLOGIA_UNITA_DOCUMENTARIA", _TIPOLOGIA_UNITA_DOCUMENTARIA);
		_columnOriginalValues.put("TIPO_CONSERVAZIONE", _TIPO_CONSERVAZIONE);
		_columnOriginalValues.put("FORZA_ACCETTAZIONE", _FORZA_ACCETTAZIONE);
		_columnOriginalValues.put("FORZA_CONSERVAZIONE", _FORZA_CONSERVAZIONE);
		_columnOriginalValues.put("FORZA_COLLEGAMENTO", _FORZA_COLLEGAMENTO);
		_columnOriginalValues.put(
			"OGGETTO_UNITA_DOCUMENTARIA", _OGGETTO_UNITA_DOCUMENTARIA);
		_columnOriginalValues.put(
			"DATA_UNITA_DOCUMENTARIA", _DATA_UNITA_DOCUMENTARIA);
		_columnOriginalValues.put(
			"VERSIONE_DATI_SPECIFICI", _VERSIONE_DATI_SPECIFICI);
		_columnOriginalValues.put(
			"IDENTIFICATIVO_DATO_SPECIFICO", _IDENTIFICATIVO_DATO_SPECIFICO);
		_columnOriginalValues.put("DATA_GENERAZIONE", _DATA_GENERAZIONE);
		_columnOriginalValues.put("NUM_SMS_GENERATI", _NUM_SMS_GENERATI);
		_columnOriginalValues.put("NUM_SMS_INVIATI", _NUM_SMS_INVIATI);
		_columnOriginalValues.put(
			"NUM_NOTIFICHE_RICEZIONE", _NUM_NOTIFICHE_RICEZIONE);
		_columnOriginalValues.put(
			"DENOMINAZIONE_APPLICATIVO", _DENOMINAZIONE_APPLICATIVO);
		_columnOriginalValues.put("OGGETTO_MAIL", _OGGETTO_MAIL);
		_columnOriginalValues.put("TESTO_MAIL", _TESTO_MAIL);
		_columnOriginalValues.put("COMPILATORE_ARPAE", _COMPILATORE_ARPAE);
		_columnOriginalValues.put(
			"COMPILATORE_PROTEZIONE_CIVILE", _COMPILATORE_PROTEZIONE_CIVILE);
		_columnOriginalValues.put(
			"DATA_INIZIO_VALIDITA", _DATA_INIZIO_VALIDITA);
		_columnOriginalValues.put("DATA_FINE_VALIDITA", _DATA_FINE_VALIDITA);
		_columnOriginalValues.put("APPROVATORE_ARPAE", _APPROVATORE_ARPAE);
		_columnOriginalValues.put("DATA_FIRMA_ARPAE", _DATA_FIRMA_ARPAE);
		_columnOriginalValues.put(
			"APPROVATORE_PROTEZIONE_CIVILE", _APPROVATORE_PROTEZIONE_CIVILE);
		_columnOriginalValues.put(
			"DATA_FIRMA_PROTEZIONE_CIVILE", _DATA_FIRMA_PROTEZIONE_CIVILE);
		_columnOriginalValues.put(
			"INVIO_RESPONSABILE_TERRITORIO", _INVIO_RESPONSABILE_TERRITORIO);
		_columnOriginalValues.put(
			"ID_DOCUMENTO_PRINCIPALE", _ID_DOCUMENTO_PRINCIPALE);
		_columnOriginalValues.put("TIPO_DOCUMENTO", _TIPO_DOCUMENTO);
		_columnOriginalValues.put("TIPO_STRUTTURA", _TIPO_STRUTTURA);
		_columnOriginalValues.put(
			"DENOMINAZIONE_SENSORE_RILEVAMENTO",
			_DENOMINAZIONE_SENSORE_RILEVAMENTO);
		_columnOriginalValues.put("REGOLA_ALLARME_ID", _REGOLA_ALLARME_ID);
		_columnOriginalValues.put("REGOLA_ALLARME_NOME", _REGOLA_ALLARME_NOME);
		_columnOriginalValues.put(
			"REGOLA_ALLARME_DESCRIZIONE", _REGOLA_ALLARME_DESCRIZIONE);
		_columnOriginalValues.put("ESITO_INVIO", _ESITO_INVIO);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("data_invio", _data_invio);
		_columnOriginalValues.put("data_risposta", _data_risposta);
		_columnOriginalValues.put("CODICE_ESITO", _CODICE_ESITO);
		_columnOriginalValues.put("CODICE_ERRORE", _CODICE_ERRORE);
		_columnOriginalValues.put("MESG_ERRORE", _MESG_ERRORE);
		_columnOriginalValues.put("CODICE_TIPO_INVIO", _CODICE_TIPO_INVIO);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ID_INVIO", 1L);

		columnBitmasks.put("AMBIENTE", 2L);

		columnBitmasks.put("VERSIONE", 4L);

		columnBitmasks.put("VERSATORE_ENTE", 8L);

		columnBitmasks.put("VERSATORE_USER_ID", 16L);

		columnBitmasks.put("VERSATORE_STRUTTURA", 32L);

		columnBitmasks.put("CHIAVE_NUMERO", 64L);

		columnBitmasks.put("CHIAVE_ANNO", 128L);

		columnBitmasks.put("CHIAVE_TIPO_REGISTRO", 256L);

		columnBitmasks.put("TIPOLOGIA_UNITA_DOCUMENTARIA", 512L);

		columnBitmasks.put("TIPO_CONSERVAZIONE", 1024L);

		columnBitmasks.put("FORZA_ACCETTAZIONE", 2048L);

		columnBitmasks.put("FORZA_CONSERVAZIONE", 4096L);

		columnBitmasks.put("FORZA_COLLEGAMENTO", 8192L);

		columnBitmasks.put("OGGETTO_UNITA_DOCUMENTARIA", 16384L);

		columnBitmasks.put("DATA_UNITA_DOCUMENTARIA", 32768L);

		columnBitmasks.put("VERSIONE_DATI_SPECIFICI", 65536L);

		columnBitmasks.put("IDENTIFICATIVO_DATO_SPECIFICO", 131072L);

		columnBitmasks.put("DATA_GENERAZIONE", 262144L);

		columnBitmasks.put("NUM_SMS_GENERATI", 524288L);

		columnBitmasks.put("NUM_SMS_INVIATI", 1048576L);

		columnBitmasks.put("NUM_NOTIFICHE_RICEZIONE", 2097152L);

		columnBitmasks.put("DENOMINAZIONE_APPLICATIVO", 4194304L);

		columnBitmasks.put("OGGETTO_MAIL", 8388608L);

		columnBitmasks.put("TESTO_MAIL", 16777216L);

		columnBitmasks.put("COMPILATORE_ARPAE", 33554432L);

		columnBitmasks.put("COMPILATORE_PROTEZIONE_CIVILE", 67108864L);

		columnBitmasks.put("DATA_INIZIO_VALIDITA", 134217728L);

		columnBitmasks.put("DATA_FINE_VALIDITA", 268435456L);

		columnBitmasks.put("APPROVATORE_ARPAE", 536870912L);

		columnBitmasks.put("DATA_FIRMA_ARPAE", 1073741824L);

		columnBitmasks.put("APPROVATORE_PROTEZIONE_CIVILE", 2147483648L);

		columnBitmasks.put("DATA_FIRMA_PROTEZIONE_CIVILE", 4294967296L);

		columnBitmasks.put("INVIO_RESPONSABILE_TERRITORIO", 8589934592L);

		columnBitmasks.put("ID_DOCUMENTO_PRINCIPALE", 17179869184L);

		columnBitmasks.put("TIPO_DOCUMENTO", 34359738368L);

		columnBitmasks.put("TIPO_STRUTTURA", 68719476736L);

		columnBitmasks.put("DENOMINAZIONE_SENSORE_RILEVAMENTO", 137438953472L);

		columnBitmasks.put("REGOLA_ALLARME_ID", 274877906944L);

		columnBitmasks.put("REGOLA_ALLARME_NOME", 549755813888L);

		columnBitmasks.put("REGOLA_ALLARME_DESCRIZIONE", 1099511627776L);

		columnBitmasks.put("ESITO_INVIO", 2199023255552L);

		columnBitmasks.put("userId", 4398046511104L);

		columnBitmasks.put("companyId", 8796093022208L);

		columnBitmasks.put("groupId", 17592186044416L);

		columnBitmasks.put("data_invio", 35184372088832L);

		columnBitmasks.put("data_risposta", 70368744177664L);

		columnBitmasks.put("CODICE_ESITO", 140737488355328L);

		columnBitmasks.put("CODICE_ERRORE", 281474976710656L);

		columnBitmasks.put("MESG_ERRORE", 562949953421312L);

		columnBitmasks.put("CODICE_TIPO_INVIO", 1125899906842624L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DatiSpecificiInvio _escapedModel;

}