/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package it.eng.parer.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import it.eng.parer.model.Parametri;
import it.eng.parer.model.ParametriModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Parametri service. Represents a row in the &quot;parer_Parametri&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ParametriModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParametriImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see ParametriImpl
 * @generated
 */
@ProviderType
public class ParametriModelImpl
	extends BaseModelImpl<Parametri> implements ParametriModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parametri model instance should use the <code>Parametri</code> interface instead.
	 */
	public static final String TABLE_NAME = "parer_Parametri";

	public static final Object[][] TABLE_COLUMNS = {
		{"chiave", Types.VARCHAR}, {"valore", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("chiave", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valore", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table parer_Parametri (chiave VARCHAR(75) not null primary key,valore VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table parer_Parametri";

	public static final String ORDER_BY_JPQL = " ORDER BY parametri.chiave ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY parer_Parametri.chiave ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.allerta.parer.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.it.eng.parer.model.Parametri"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		it.eng.allerta.parer.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.it.eng.parer.model.Parametri"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		it.eng.allerta.parer.service.util.ServiceProps.get(
			"lock.expiration.time.it.eng.parer.model.Parametri"));

	public ParametriModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _chiave;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setChiave(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _chiave;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Parametri.class;
	}

	@Override
	public String getModelClassName() {
		return Parametri.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Parametri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Parametri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parametri, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Parametri)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Parametri, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Parametri, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Parametri)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Parametri, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Parametri, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Parametri, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Parametri, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Parametri, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Parametri, Object>>();
		Map<String, BiConsumer<Parametri, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Parametri, ?>>();

		attributeGetterFunctions.put(
			"chiave",
			new Function<Parametri, Object>() {

				@Override
				public Object apply(Parametri parametri) {
					return parametri.getChiave();
				}

			});
		attributeSetterBiConsumers.put(
			"chiave",
			new BiConsumer<Parametri, Object>() {

				@Override
				public void accept(Parametri parametri, Object chiave) {
					parametri.setChiave((String)chiave);
				}

			});
		attributeGetterFunctions.put(
			"valore",
			new Function<Parametri, Object>() {

				@Override
				public Object apply(Parametri parametri) {
					return parametri.getValore();
				}

			});
		attributeSetterBiConsumers.put(
			"valore",
			new BiConsumer<Parametri, Object>() {

				@Override
				public void accept(Parametri parametri, Object valore) {
					parametri.setValore((String)valore);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getChiave() {
		if (_chiave == null) {
			return "";
		}
		else {
			return _chiave;
		}
	}

	@Override
	public void setChiave(String chiave) {
		_chiave = chiave;
	}

	@Override
	public String getValore() {
		if (_valore == null) {
			return "";
		}
		else {
			return _valore;
		}
	}

	@Override
	public void setValore(String valore) {
		_valore = valore;
	}

	@Override
	public Parametri toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Parametri)ProxyUtil.newProxyInstance(
				_classLoader, _escapedModelInterfaces,
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParametriImpl parametriImpl = new ParametriImpl();

		parametriImpl.setChiave(getChiave());
		parametriImpl.setValore(getValore());

		parametriImpl.resetOriginalValues();

		return parametriImpl;
	}

	@Override
	public int compareTo(Parametri parametri) {
		String primaryKey = parametri.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Parametri)) {
			return false;
		}

		Parametri parametri = (Parametri)obj;

		String primaryKey = parametri.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Parametri> toCacheModel() {
		ParametriCacheModel parametriCacheModel = new ParametriCacheModel();

		parametriCacheModel.chiave = getChiave();

		String chiave = parametriCacheModel.chiave;

		if ((chiave != null) && (chiave.length() == 0)) {
			parametriCacheModel.chiave = null;
		}

		parametriCacheModel.valore = getValore();

		String valore = parametriCacheModel.valore;

		if ((valore != null) && (valore.length() == 0)) {
			parametriCacheModel.valore = null;
		}

		return parametriCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Parametri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Parametri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parametri, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Parametri)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Parametri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Parametri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parametri, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Parametri)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader =
		Parametri.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
		Parametri.class, ModelWrapper.class
	};

	private String _chiave;
	private String _valore;
	private Parametri _escapedModel;

}