/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package it.eng.parer.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import it.eng.parer.model.Parametri;
import it.eng.parer.model.ParametriModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Parametri service. Represents a row in the &quot;parer_Parametri&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ParametriModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ParametriImpl}.
 * </p>
 *
 * @author Pratola_L
 * @see ParametriImpl
 * @generated
 */
public class ParametriModelImpl
	extends BaseModelImpl<Parametri> implements ParametriModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a parametri model instance should use the <code>Parametri</code> interface instead.
	 */
	public static final String TABLE_NAME = "parer_Parametri";

	public static final Object[][] TABLE_COLUMNS = {
		{"chiave", Types.VARCHAR}, {"valore", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("chiave", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valore", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table parer_Parametri (chiave VARCHAR(75) not null primary key,valore VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table parer_Parametri";

	public static final String ORDER_BY_JPQL = " ORDER BY parametri.chiave ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY parer_Parametri.chiave ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CHIAVE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ParametriModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _chiave;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setChiave(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _chiave;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Parametri.class;
	}

	@Override
	public String getModelClassName() {
		return Parametri.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Parametri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Parametri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parametri, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Parametri)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Parametri, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Parametri, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Parametri)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Parametri, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Parametri, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Parametri, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Parametri, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Parametri, Object>>();

			attributeGetterFunctions.put("chiave", Parametri::getChiave);
			attributeGetterFunctions.put("valore", Parametri::getValore);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Parametri, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Parametri, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Parametri, ?>>();

			attributeSetterBiConsumers.put(
				"chiave", (BiConsumer<Parametri, String>)Parametri::setChiave);
			attributeSetterBiConsumers.put(
				"valore", (BiConsumer<Parametri, String>)Parametri::setValore);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getChiave() {
		if (_chiave == null) {
			return "";
		}
		else {
			return _chiave;
		}
	}

	@Override
	public void setChiave(String chiave) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_chiave = chiave;
	}

	@Override
	public String getValore() {
		if (_valore == null) {
			return "";
		}
		else {
			return _valore;
		}
	}

	@Override
	public void setValore(String valore) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valore = valore;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Parametri toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Parametri>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ParametriImpl parametriImpl = new ParametriImpl();

		parametriImpl.setChiave(getChiave());
		parametriImpl.setValore(getValore());

		parametriImpl.resetOriginalValues();

		return parametriImpl;
	}

	@Override
	public Parametri cloneWithOriginalValues() {
		ParametriImpl parametriImpl = new ParametriImpl();

		parametriImpl.setChiave(this.<String>getColumnOriginalValue("chiave"));
		parametriImpl.setValore(this.<String>getColumnOriginalValue("valore"));

		return parametriImpl;
	}

	@Override
	public int compareTo(Parametri parametri) {
		String primaryKey = parametri.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Parametri)) {
			return false;
		}

		Parametri parametri = (Parametri)object;

		String primaryKey = parametri.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Parametri> toCacheModel() {
		ParametriCacheModel parametriCacheModel = new ParametriCacheModel();

		parametriCacheModel.chiave = getChiave();

		String chiave = parametriCacheModel.chiave;

		if ((chiave != null) && (chiave.length() == 0)) {
			parametriCacheModel.chiave = null;
		}

		parametriCacheModel.valore = getValore();

		String valore = parametriCacheModel.valore;

		if ((valore != null) && (valore.length() == 0)) {
			parametriCacheModel.valore = null;
		}

		return parametriCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Parametri, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Parametri, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Parametri, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Parametri)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Parametri>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Parametri.class, ModelWrapper.class);

	}

	private String _chiave;
	private String _valore;

	public <T> T getColumnValue(String columnName) {
		Function<Parametri, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Parametri)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("chiave", _chiave);
		_columnOriginalValues.put("valore", _valore);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("chiave", 1L);

		columnBitmasks.put("valore", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Parametri _escapedModel;

}